### ISSUE TITLE
Issue when Installing, error message says node version is many versions behind the expected version

### ISSUE THREAD

**Issue by nhelterbrand** [scolladon/sfdx-git-delta#100]
Issue verification check :

[] does the current repository is fully deployable at the commit sha given to the from parameter of the command ?

## What is the problem

Issue when Installing, error message says node version is many versions behind the expected version

### What is parameter and their value you used

`sfdx plugins:install sfdx-git-delta`

### What is the expected result

The expected result was to install the plugin

### What is the actual result

error message:

```
error sfdx-git-delta@4.2.0: The engine "node" is incompatible with this module. Expected version ">=14.6.0". Got "12.18.3"
error Found incompatible module.
Installing plugin sfdx-git-delta... failed
    Error: yarn add sfdx-git-delta@latest --non-interactive --mutex=file:/Users/nhelterbrand/.local/share/sfdx/yarn.lock
    --preferred-cache-folder=/Users/nhelterbrand/Library/Caches/sfdx/yarn --check-files exited with code 1
```

## Steps to reproduce

run the install script in README

## Execution context

---

```
Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64
1.22.10
v15.8.0
zsh: command not found: sgd
git version 2.24.3 (Apple Git-128)
```

**Operating System:** … MacOS 11.2.1 (20D74)

**Yarn version:** … 1.22.10

**Node version:** … v15.8.0

**sgd version:** … not installed

**git version:** … 2.24.3

## Optional more information

---

_(Write your answer here.)_

**Comment by kknapp1** [comment]
@nhelterbrand I've had the same issue and was able to resolve by installing the sfdx cli via npm. 

- uninstall your current sfdx cli distro
- update your local node & npm version to latest
- install sfdx via npm as described here: https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_install_cli.htm

hope that helps!

**Comment by nhelterbrand** [comment]
That fixed it @kknapp1 , thank you!
