### ISSUE TITLE
Adding new email alert on a custom object is not captured on diff

### ISSUE THREAD

**Issue by niv-goldenberg** [scolladon/sfdx-git-delta#104]
## What is the problem

Adding new email alert on a custom object is not captured on diff, only the first original one is captured.
I tried changing attributes on both email alerts (<alerts> xml tags) and change the order in the MyCustomObject__c.workflow-meta.xml so it will enforce change, but only the first (original) email alert is captured as changed.

### What is parameter and their value you used

sgd -t HEAD -f HEAD^  -r . -o .
or
sgd -t HEAD -f origin/develop  -r . -o .

### What is the expected result

```
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>MyCustomObject__c.Send_Email_Alert_One</members>
       <members>MyCustomObject__c.Send_Email_Alert_Two</members>
        <name>WorkflowAlert</name>
    </types>
    <version>50.0</version>
</Package>
```

### What is the actual result

```
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>MyCustomObject__c.Send_Email_Alert_One</members>
        <name>WorkflowAlert</name>
    </types>
    <version>50.0</version>
</Package>
```

## OS and Versions

Linux x64 Ubuntu 20.04
node v14.15.4
sgd 4.2.0

**Comment by scolladon** [comment]
Hi @niv-goldenberg !

Thanks for your interest on the plugin !

What should I do in a repository to be able to reproduce the issue ?
Thanks in advance

**Comment by niv-goldenberg** [comment]
Hi @scolladon,

Add a new email alert with a new email template. When pull from the scratch org this will update your MyCustomObject__c.workflow-meta.xml, and you'll get something like this:
```
<?xml version="1.0" encoding="UTF-8" ?>
<Workflow xmlns="http://soap.sforce.com/2006/04/metadata">
  <alerts>
    <fullName>Send_Email_Alert_Two</fullName>
    <description
    >Send Email Alert Two</description>
    <protected>false</protected>
    <recipients>
      <recipient>CEO_Admin</recipient>
      <type>role</type>
    </recipients>
    <senderType>CurrentUser</senderType>
    <template>unfiled$public/Email_Two</template>
  </alerts>
  <alerts>
    <fullName>Send_Email_Alert_One</fullName>
    <description
    >Send Email Alert One</description>
    <protected>false</protected>
    <recipients>
      <recipient>CEO_Admin</recipient>
      <type>role</type>
    </recipients>
    <senderType>CurrentUser</senderType>
    <template>unfiled$public/Email_One</template>
  </alerts>
</Workflow>
```

**Comment by niv-goldenberg** [comment]
@scolladon sorry for the multiple edits, trying to do multiple things in parallel :) 
I just thought about something, I have reduce the email alert api name - the original one was 58 chars, reducing it to 43 chars did the trick and the delta diff now capture it.
I'm not sure if you have characters limit somewhere in the code, but worth checking...

Thanks!

**Comment by scolladon** [comment]
@niv-goldenberg that's actually a good tip !

No limit in the plugin code but maybe there is something making the fullName xml tag multiline.
I'll do some checking to see if it is in the metadata.

Could you check on your side if you have a xml prettier making it multiline after some character number please ?

**Comment by niv-goldenberg** [comment]
Interesting... I have this `"prettier.printWidth": 120,` not sure if this might affect the plugin somehow.

**Comment by scolladon** [comment]
Interesting yes ! 

Could you tell if it is related to this prettier configuration ? Does the fullname xml tag is multiline for the issue to occur ?

**Comment by niv-goldenberg** [comment]
I did some tests, and it seems that a git commit create those lines breaks without taking into consideration my VSCode settings - before the commit the file is without line breaks. So if I'm using a short name I don't have any issue.

I'm still investigating what is doing this, but in the meanwhile can you check on the sfdx-git-delta if line breaks can be ignored somehow ?

Thanks!

**Comment by scolladon** [comment]
Maybe you are using husky with prettier, so it will prettify it for you at the commit, no ?

The current detection algorithm cannot be used without line breaks unfortunately

**Comment by mehdisfdc** [comment]
@scolladon I guess that the new behaviour implemented on workflows (https://github.com/scolladon/sfdx-git-delta/pull/102) should also address this issue, right?

**Comment by niv-goldenberg** [comment]
I have removed all the hooks I had in the .git folder, I think they are coming when you first create a default DX project. That solved the issue.

I have different settings for prettify which all of our developers are using, actually didn't notice until now that git commit is changing the format.

Thanks.
