### ISSUE TITLE
Doubled metadata destructive changes

### ISSUE THREAD

**Issue by MaciekLeks** [scolladon/sfdx-git-delta#111]
Consider situation:

1. We have got the same metadata type in two directories, e..g
```
force-app/common/objects/Account/Account.object-meta.xml
force-app/setup/objects/Account/Account.object-meta.xml
```
2. These metadata complements each other
3. Finally, we decided to join definition into one, e.g.
```
force-app/common/objects/Account/Account.object-meta.xml
```
4. We delete the second one:
```
force-app/setup/objects/Account/Account.object-meta.xml
```
And now what happens?
Destructive changes tries to delete Account object, but it should not do that while we still using Account.

Is there any chance to catch such situation or we need to operate on .forceignore while creating desctructiveChanges xml files?

**Comment by scolladon** [comment]
Hi @MaciekLeks !

Currently you need to use the ignore parameter (either with forceignore or another file of your own for the use case).

What we could do is to make the difference between destructiveChanges.xml and the package.xml (remove every occurence in the destructiveChanges present in the package.xml). I think it would fix the issue and could be implemented very fast.
But it comes with questions : 
- What could be the side effects ?
- In which cases we don't want it to be applied ?

@mehdisfdc do you have any idea about those questions and what do you think about this use case and solution proposed ?

**Comment by MaciekLeks** [comment]
1. What could be the side effects ?
If you only remove the second file and do not touch the first one, then the destructive changes will chatch the deletion.

2. In which cases we don't want it to be applied ?
If you only remove the second file and do not touch the first one, then the destructive changes will chatch the deletion.
