### ISSUE TITLE
Validate Destructive Changes

### ISSUE THREAD

**Issue by jjulicher** [scolladon/sfdx-git-delta#117]
When doing a destructive deploy in a CI/CD setup you continuously do a deployment to a e.g. System Test sandbox. 

As an example currently all our develop branch commits are deployed automatically to a System Test environment  - as such when metadata is removed from developer that is in the main branch it will generate the destructive changes.

In the CI/CD pipeline the work around is to retrieve the destructive changes to a local dir, convert it twice - to/from metadata format to source format which regenerates the package.xml which only contains valid destructive changes.

If you don't do this the destructivepost/pre.xml will cause a deployment failure as a previous deployment would have removed the destructive changes. 

Now that sfdx-git-delta is a sfdx plugin and we have access to the retrieve metadata api or event the list metadata types api e.g. list custom fields etc. could we add a --validate--destructive option to do the above step or do you see this as outside the scope?

**Comment by mehdisfdc** [comment]
@jjulicher If I understood correctly, your have implemented this logic in your pipeline to deal with a situation where the destructive package (generated by SGD) would have already been removed from the target environment, correct?

To deal with this situation, can't you simply run the destructive deployment with the `--ignorewarnings` flag?
Such as in this example: `sfdx force:mdapi:deploy -d destructiveChanges --ignorewarnings` 
Or did come across a situation where the `--ignorewarnings` flag was not enough to ensure that the destructive deployment would succeed even when some of the component have already been deleted?

**Comment by jjulicher** [comment]
I use the destructivePre.xml and destructivePost.xml in my pipeline using the source format deploy which unfortunately doesn't have the --ignorewarnings flag.

This enables me to provide a more or less atomic CI deployment process with pre & post destructive changes.

**Comment by mehdisfdc** [comment]
@jjulicher Thank for the additional details, but I'm still not sure to fully get your request.
Currently, SGD generates a destructive package in a dedicated folder, that you can decide to deploy (using `sfdx force:mdapi:deploy -d destructiveChanges --ignorewarnings`) before or after your main deployment (that likely uses `sfdx force:source:deploy`).
Are you using thate destructive package created by SGD?
Or are you saying that you are currently not using it, because you would to deal with destructive changes in a different manner?

**Comment by jjulicher** [comment]
Ok so I use a sfdx plugin "sfdx-destruction', it allows me to specify a pre & post destructive file in the sfdx force:source:deploy command. 

Ahh wait I don't know why I didn't see the ignore warnings flag on the source:deploy before - I'll try that...
