### ISSUE TITLE
TypeError: Class constructor SfdxCommand cannot be invoked without 'new'

### ISSUE THREAD

**Issue by wappzadmin** [scolladon/sfdx-git-delta#120]
Issue verification check :

- [X] does the current repository is fully deployable at the commit sha given to the from parameter of the command ?

## What is the problem

--- Unable to detect changes and delta command is not executing.
TypeError: Class constructor SfdxCommand cannot be invoked without 'new'

## Steps to reproduce

Run the command with or without argument. Ex
```sh
$ sfdx sgd:source:delta -h
```

---

## Execution context

---

**Operating System:** …

**yarn version:** …

**node version:** …

**git version:** …

**sfdx version:** …7.86.3

**sgd plugin version:** …4.3.0

## Optional more information

---

**Comment by scolladon** [comment]
Hi @wappzadmin !

Thanks for reporting this issue.
It is fixed in the new PR #121.

We will ship this version tonight.

**Comment by wappzadmin** [comment]
great, Thanks for prompt update.
