### ISSUE TITLE
Ignore directories in . folders (e.g. .github)

### ISSUE THREAD

**Issue by 1ktribble** [scolladon/sfdx-git-delta#122]
Issue verification check :

- [ ] is the current repository fully deployable at the commit sha given to the from parameter of the command ?

## What is the problem

---
When an update is made to a folder structure with the same name as a recognized Metadata API type, that change is added to package.xml or destructiveChanges.xml.

An example:
I want to create a new GitHub action. Here is the folder structure:
- .github
  - **workflows**
    - ci-cd-flow.workflow

 ci-cd-flow.workflow is included in the package.xml file

### What is parameter and their value you used

```
sgd --to origin/PR-HEAD --from origin/PR-BASE --repo . --output .
```

### What is the expected result

```
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <version>50.0</version>
</Package>
```

No directory created

### What is the actual result

```
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>ci-cd-flow<members>
        <name>Workflow</name>
    </types>
    <version>50.0</version>
</Package>
```

## Steps to reproduce

---

1. Enable Github actions for a repository
2. Create a new Github Action workflow.
3. Run sgd command: sgd --to origin/PR-HEAD --from origin/PR-BASE --repo . --output . 

## Execution context

---

**Operating System:** macOS Catalina 10.15.7

**yarn version:** yarn version v1.22.10

**node version:** Welcome to Node.js v14.15.4

**git version:** git version 2.30.0

**sfdx version:** npm installation - sfdx-cli/7.94.3

**sgd plugin version:** n/a. npm installation sfdx-git-delta@latest

## Optional more information

---

**Comment by scolladon** [comment]
Hi @1ktribble !

Thanks for your interest in the plugin !
And thanks for this very well describe issue !

This is something you can resolve using the [`--ignore` feature](https://github.com/scolladon/sfdx-git-delta#option-1-recommended---install-as-a-salesforce-cli-plugin-sgdsourcedelta) of the plugin

You could create a `.sgdignore` file with the dot files you don't want to be evaluated by the plugin. Ex : 
```sh
$ echo '.github' > .sgdignore
$ sfdx sgd:source:delta --to HEAD --from HEAD^ -i .sgdignore
```

I hope it helps.

I close the issue as there is a way to deal with it. Feel free to reopen it if there is still a problem following the example given
