### ISSUE TITLE
Cannot read property 'getInstance' of undefined

### ISSUE THREAD

**Issue by jbro-io** [scolladon/sfdx-git-delta#131]
## What is the problem

---

### What is parameter and their value you used

`sfdx sgd:source:delta --to HEAD --from 2b286daae2315def99367a57655d529b8f0b57bf`

### What is the expected result

sgd plugin creates an `output/package/package.xml` file that contains the changed metadata between the commit sha and HEAD.

### What is the actual result

Error is generated from sgd plugin:
```
ERROR running sgd:source:delta:  Cannot read property 'getInstance' of undefined
FAIL
```

## Steps to reproduce

---

## Execution context

---

**Operating System:** MacOS

**yarn version:** 1.22.10

**node version:** v14.16.0

**git version:** 2.19.1

**sfdx version:** sfdx-cli/7.94.3 darwin-x64 node-v14.16.0

**sgd plugin version:** latest

**Comment by scolladon** [comment]
Hi @jbro-io!

Thanks for raising this issue and thanks for your interest and your help to make the plugin better!

I do not reproduce this issue locally. Hence I have a few questions : 

- How sfdx has been installed?
- How sgd has been installed?
- Could you provide steps to reproduce the issue? If you could make sure you reproduce those steps locally and on another laptop it would be great. You can use the [reproduction playground](https://github.com/scolladon/sfdx-git-delta-reproduction-playground)

Thanks in advance

**Comment by jbro-io** [comment]
@scolladon Thanks for the quick reply!

I ended up resolving the issue by re-installing the sfdx-cli and then installing the sgd plugin again. Not sure what was going on there, but its resolved now.
