### ISSUE TITLE
On Windows it does not work all the time it seems

### ISSUE THREAD

**Issue by dkadam77** [scolladon/sfdx-git-delta#134]
Issue verification check :

- [ ] does the current repository is fully deployable at the commit sha given to the from parameter of the command ?

On Windows ..it generates the empty package file (I mean XML without any objects in it) and none of other options works,

---

**Comment by dkadam77** [comment]
I have tested it within Intellij terminal then it does not work ...but when i use VSCode terminal or usual windows terminal then it does work.

**Comment by scolladon** [comment]
Hi @dkadam77 !

Thanks for your interest and for contributing to make this plugin better !

It seems this issue is not related to the plugin itself but it is more related to the environment which execute it.
Is there any difference between the terminal in VSCode, the windows terminal and the terminal in Intellij ?

**Comment by sfdcbruno** [comment]
I'm facing a similar issue - It's creating an empty package in VSCode terminal and windows cmd. However, works when using git bash.

**Comment by dkadam77** [comment]
> Hi @dkadam77 !
> 
> Thanks for your interest and for contributing to make this plugin better !
> 
> It seems this issue is not related to the plugin itself but it is more related to the environment which execute it.
> Is there any difference between the terminal in VSCode, the windows terminal and the terminal in Intellij ?



I am not sure what is the difference between the terminals in intellij, VSCode and Win Command prompts.  But it is strange that it behaves differently in different orgs.

**Comment by scolladon** [comment]
Hi!

Thanks for the reproduction steps.
Could you try by protecting the parameter from being interpreted by the terminal using double quote and tell us the result please ?
```sh
$ sfdx sgd:source:delta --to "HEAD" --from "HEAD^" --output .
$ sfdx sgd:source:delta --to "HEAD" --from "HEAD^" --output changed-sources/ --generate-delta
```

To answer your question:
> I have one other question; say you have checked-in the code and it has identified the diff between last 2 check-ins but deployment is somehow failed for this. Meanwhile another check-in happened and if I run the command again then it will identify the diff between last 2 check-ins. Is there any way to identify the diff between the last successful deployment check-in (it may have multiple check-ins in between) to the latest check-in so that I should be able to deploy the code from last deploy failure and not just last check-in diff?? Appreciate your response.

The parameters `--to` and `--from` takes any [git commit sha pointer](https://github.com/scolladon/sfdx-git-delta#diff-between-branches) (commit sha, short commit sha, branch name, tag, git expression like HEAD, etc). So you can design a tag creation to apply to a commit when it is successfully deployed and base the deployments from that tag (using `--from` parameter)

**Comment by PawelWozniak** [comment]
I have the same issue. PowerShell 7.1.3, CMD, Terminal in VSCode. In all of them, I am getting an empty package.xml

**Comment by dkadam77** [comment]
> Hi!
> 
> Thanks for the reproduction steps.
> Could you try by protecting the parameter from being interpreted by the terminal using double quote and tell us the result please ?
> 
> ```shell
> $ sfdx sgd:source:delta --to "HEAD" --from "HEAD^" --output .
> $ sfdx sgd:source:delta --to "HEAD" --from "HEAD^" --output changed-sources/ --generate-delta
> ```
> 
> To answer your question:
> 
> > I have one other question; say you have checked-in the code and it has identified the diff between last 2 check-ins but deployment is somehow failed for this. Meanwhile another check-in happened and if I run the command again then it will identify the diff between last 2 check-ins. Is there any way to identify the diff between the last successful deployment check-in (it may have multiple check-ins in between) to the latest check-in so that I should be able to deploy the code from last deploy failure and not just last check-in diff?? Appreciate your response.
> 
> The parameters `--to` and `--from` takes any [git commit sha pointer](https://github.com/scolladon/sfdx-git-delta#diff-between-branches) (commit sha, short commit sha, branch name, tag, git expression like HEAD, etc). So you can design a tag creation to apply to a commit when it is successfully deployed and base the deployments from that tag (using `--from` parameter)




Hello,

I tried below and it worked for me. By protecting the parameter from being interpreted by the terminal using double quote it seems to be working in intellij terminal as well. Now I can do it from Windows CMD, VSCode Terminal as well as IntelliJ terminal as well. Thanks. 

$ sfdx sgd:source:delta --to "HEAD" --from "HEAD^" --output .
$ sfdx sgd:source:delta --to "HEAD" --from "HEAD^" --output changed-sources/ --generate-delta

**Comment by PawelWozniak** [comment]
For me this still is not working but this one is working:
sfdx sgd:source:delta --to "HEAD" --from "HEAD~1" --output delta

use HEAD~1 instead of HEAD^
It might be due to merging. As my flow is that I merge feature to develop branch and then doing delta on develop. Then deploying package.xml to PROD.
It seems that there is a difference between ~ and ^. Done some reading but still, it isn't clear for me.
