### ISSUE TITLE
The package.xml generated automatically appends the file extension in Document metadata type. 

### ISSUE THREAD

**Issue by kimvwatanabe1** [scolladon/sfdx-git-delta#135]
The Document type in the package.xml that was generated has its file extension appended. Since it has a different structure, the documents in the package won't be deployed.

### What is parameter and their value you used

$LatestTag = '' (_Any latest commit or tag. Just make sure that the diff between two commits contains a document metadata_)
sfdx sgd:source:delta --from $LatestTag --output delta/ -d -a 51.0

### What is the expected result

```
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>Test_Folder</members>
        <members>Test_Folder/TestIcon</members>
        <members>Test_Folder/TestIcon2</members>
        <name>Document</name>
    </types>
    <version>51.0</version>
</Package>
```

### What is the actual result

```
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>Test_Folder</members>
        <members>Test_Folder/TestIcon.document</members>
        <members>Test_Folder/TestIcon.png</members>
        <members>Test_Folder/TestIcon2.document</members>
        <members>Test_Folder/TestIcon2.png</members>
        <name>Document</name>
    </types>
    <version>51.0</version>
</Package>
```

## Steps to reproduce

Run in local machine or in vscode:
```
$LatestTag = 'TAG-1'
sfdx sgd:source:delta --from $LatestTag --output delta/ -d -a 51.0
```
(_LatestTag = Any latest commit or tag. Just make sure that the diff between two commits contains a document metadata. And make sure to create a delta folder first._)

**Operating System:** Win10

**yarn version:** …

**node version:** node-v15.14.0

**git version:** 2.31.0

**sfdx version:** sfdx-cli/7.97.0

**sgd plugin version:** latest

**Comment by DougMidgley** [comment]
@kimvwatanabe1 thanks for submitting!

**Comment by scolladon** [comment]
Hi @kimvwatanabe1!

Thanks for this issue and thanks for your help making this plugin better!

The PR #136 purposes is to fix this issue. Could you give us some help and beta test it on your side ?

**Comment by PawelWozniak** [comment]
For me this still is not working but this one is working:
`sfdx sgd:source:delta --to "HEAD" --from "HEAD~1" --output delta`

use HEAD~1 instead of HEAD^

**Comment by scolladon** [comment]
hi @PawelWozniak !
What do you mean ?
You still reproduce the issue with the file extension in Document metadata type with the v4.5.0 ?
If so, could you give us your steps to reproduce the issue ?

**Comment by PawelWozniak** [comment]
Apologies for posting here it was for a different bug.
