### ISSUE TITLE
Ability to Run Specified Tests while comparing branches

### ISSUE THREAD

**Issue by ravaliyerrabelly** [scolladon/sfdx-git-delta#140]
### Is your proposal related to a problem?

Currently when diff one branch to another, we need the ability to automatically recognize test classes which are added as part of the diff to package.xml.

### Describe the solution you'd like

When doing a diff from feature branch to DEV branch, if we could recognize test classes which have been changed and just 
run those test classes it will save a lot of time rather than running all test classes

**Comment by scolladon** [comment]
Hi @ravaliyerrabelly!

Thanks for your interest on making this plugin better!

This topic has already been discussed in another [issue](https://github.com/scolladon/sfdx-git-delta/issues/126).
We came up with a solution using [yq](https://github.com/scolladon/sfdx-git-delta#generate-a-comma-separated-list-of-the-added-and-modified-apex-classes) to show all the apex class listed in the package.xml.

You could reuse this approach and add a filter on the yq command to extract the apex class containing tests following your naming convention:
`... select(.name=="ApexClass") | <filter members here> | .members | join(",")'`

I hope it helps

**Comment by ravaliyerrabelly** [comment]
Hi could you provide me an example of the the two command which I can add
to butbucket pipeline ?

**Comment by scolladon** [comment]
Yes of course:

`xq . < package/package.xml | jq '.Package.types | if type=="array" then .[] else . end | select(.name=="ApexClass") | <filter members here> | .members | join(",")'`

**Comment by scolladon** [comment]
We close this issue as this is [covered in the README](https://github.com/scolladon/sfdx-git-delta#explicitly-including-specific-files-for-inclusion-or-destruction-regardless-of-diff)

**Comment by rpawar655** [comment]
Can you please let me now the entire command which we have to use at the time for run : 
sfdx force:source:deploy    ...?
@scolladon  
i want to validate the syntax to generate the delta test class and run ...

**Comment by scolladon** [comment]
Hi @rpawar655 !

Not sure to understand what you want.
Either the `sfdx deploy` command ?
Or the [list of the test class](https://github.com/scolladon/sfdx-git-delta#generate-a-comma-separated-list-of-the-added-and-modified-apex-classes) to add to the deploy command, based on the content of the `package.xml`, and how to pass them to the deploy command ?

**Comment by rpawar655** [comment]
Hi @scolladon ,
I am looking for how i can pass to sfdx force:source:deploy cmd. It would be great if you suggest with one testclass example.

**Comment by scolladon** [comment]
Okay,

So, let's imagine we have this package.xml
```xml
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>Service</members>
        <members>ServiceTest</members>
        <name>ApexClass</name>
    </types>
    <version>55.0</version>
</Package>
```

The file contains a `ServiceTest` member.
All the test class contains `Test` at the end of their name.
Then this [xq | jq](https://github.com/kislyuk/yq) query will list all test class and separate them by ",":
```sh
$ xq . < output/package/package.xml | jq '.Package.types | [.] | flatten | map(select(.name=="ApexClass")) | .[] | .members | [.] | flatten | `map(select(. | index("*") | not)) | unique | map(select(. | index("Test")))  | join(",")'
> "ServiceTest"
```

Then I use it in the command line directly (I use zsh, it may be different based on your shell):
```sh
$ sfdx force:source:deploy --testlevel RunSpecifiedTests --runtests $(xq . < output/package/package.xml | jq '.Package.types | [.] | flatten | map(select(.name=="ApexClass")) | .[] | .members | [.] | flatten | map(select(. | index("*") | not)) | unique | map(select(. | index("Test")))  | join(",")')
```

You may want to extract it in a variable before (it may be different based on your shell):
```sh
$ SPECIFIED_TEST=$(xq . < output/package/package.xml | jq '.Package.types | [.] | flatten | map(select(.name=="ApexClass")) | .[] | .members | [.] | flatten | map(select(. | index("*") | not)) | unique | map(select(. | index("Test")))  | join(",")')
$ sfdx force:source:deploy --testlevel RunSpecifiedTests --runtests ${SPECIFIED_TEST}
```

I hope it helps!

**Comment by rpawar655** [comment]
Hey @scolladon That is what i am looking for thanks a ton 👍 
Let me try out this in my CI/CD

**Comment by rpawar655** [comment]
Hi @scolladon - Query - If i dont have any class in my package via SGD git delta then above command won't work. As we are using RunSpecifiedTest. How we can tackle this situation? How we can put condition over here.
