### ISSUE TITLE
Generating delta between two commits on same branch?

### ISSUE THREAD

**Issue by tdahle-conga** [scolladon/sfdx-git-delta#142]
How we want to use this is: We open a PR, approve, merge it into master. Master then runs a github action to determine the differences between how it was (previous commit) and the new commit from the merge, generate the package.xml, and then deploy that.

My step trying to do this is:
```
- name: Generate SFDX Delta Package
  run: |
    mkdir deploy
    echo ${{ env.BRANCH_NAME }}
    git fetch origin ${{ env.BRANCH_NAME }}
    sfdx sgd:source:delta --to ${{ github.event.after }} --from ${{ github.event.before }} --repo . --output deploy/
    echo "--- package.xml generated with added and modified metadata since ${{ github.event.before }} ---"
    cat deploy/package/package.xml
    echo ""
    echo "--- destructiveChanges.xml generated with deleted metadata since ${{ github.event.before }} ---"
    cat deploy/destructiveChanges/destructiveChanges.xml
    echo ""
```

Where BRANCH_NAME is the name of the current branch (master). This only ever produces an empty package.xml with no changes recorded. Now, if I directly compare branches like:
```
sfdx sgd:source:delta --to dev --from master --repo . --output deploy/
```

I get changes in my package.xml. But as far as I know, I don't have the name of the branch that just merged into master, so this won't actually be viable. How can you compare one branch's commits? Or achieve this scenario?

Oh, and I've never gotten HEAD and HEAD^ to work. Anything on the same branch just spits out an empty package.xml. I've only gotten results comparing different branches.

**Comment by tdahle-conga** [comment]
An update from playing around with this more:
I finally got this to work on windows to give me a package.xml with differences between two commits on the same branch when I ran this in my console
```
sfdx sgd:source:delta --to HEAD --from "a021bf09cbd42287d41676428e907467f52239c6" --output .
```

However, running the SAME line in github action with ${{ github.event.before }} to get that previous commit instead of the hardcoded commit SHA still gives an empty package.xml. I even put quotes around it and it didn't help. 

I am pretty much out of ideas on how to make this work in github actions.

**Comment by mehdisfdc** [comment]
Hi @tdahle-conga ! Thank you for logging this issue. This seems to be an issue with your github action rather than SGD.

Did you make sure that the previous commit is accessible in this context? Have you tried using a different [fetch-depth](https://github.com/marketplace/actions/checkout) value (such as `fetch-depth: 0` for example)?
