### ISSUE TITLE
Dont recognize classes delta

### ISSUE THREAD

**Issue by dianaerb** [scolladon/sfdx-git-delta#145]
Hi, 

Thank you for this plugin is very useful for me. But currently, I have an issue related with the package.xml generated. It does not include the tag <apexclass> and I know that there is a difference because I created a new class. I'm really sure that the class does not exist in origin/devCol branch and exists in my current branch. Do you have any idea about why might be my problem?

I am running this command for getting the package, it works but doesn't include apex class.

`sfdx sgd:source:delta --to "origin/devCol" --from $CI_COMMIT_SHA  --output .`

![image](https://user-images.githubusercontent.com/3708942/121092850-ce58d880-c7b1-11eb-8c5a-aa5f81e12ed7.png)

**Comment by mehdisfdc** [comment]
Hi @dianaerb! Thank you for using SGD, and thank you for taking the time to log your issue!

My understanding of your situation is that your latest commit is in the `$CI_COMMIT_SHA` variable, and that the reference branch (against which the diff is to be performed) is `origin/devCol`. 
Is that correct?

In that situation, you would have to use `$CI_COMMIT_SHA` as the `--to`, and the `origin/devCol` as the `--from`. 
This means that a working command in your situation should probably look like this:
`sfdx sgd:source:delta --to $CI_COMMIT_SHA --from "origin/devCol" --output .`

Could you give it a try and let us know how it goes?
Thank you!

**Comment by dianaerb** [comment]
Thank you very much to answer my message @mehdisfdc. You are right. I tested it and worked fine. 

Best regards!
