### ISSUE TITLE
Support Bot, BotVersion, and CorsWhitelist metadata types

### ISSUE THREAD

**Issue by bobbywhitesfdc** [scolladon/sfdx-git-delta#146]
running sgd against a project that contains some metadata types that should be included in the package.xml that is generated but these are skipped.

Bot
BotVersion

### Describe the solution you'd like

sgd should detect these metadata types and include them in the package.xml :-) 

### Describe alternatives you've considered

Alternative is hand editing of the generated package.xml :-( 

### Additional context
Here's the structure on the filesystem that I've seen:
force-app/main/default/bots/<Botname>
<Botname>.bot-meta.xml
<BotVersion>.botVersion-meta.xml
---
force-app/mainWhitelistOrigins
<item1>.corsWhitelistOrigin-meta.xml
<item2>.corsWhitelistOrigin-meta.xml

Package.xml
```
    <types>
        <members>Virtual_Assistant</members>
        <members>Virtual_Assistant2</members>
        <name>Bot</name>
    </types>
    <types>
        <members>Virtual_Assistant.v1</members>
        <members>Virtual_Assistant2.v1</members>
        <name>BotVersion</name>
    </types>
```

**Comment by bobbywhitesfdc** [comment]
@scolladon Thank you in advance!

**Comment by bobbywhitesfdc** [comment]
Please disregard the corsWhitelist item, I see that it's actually in there and working now!

**Comment by scolladon** [comment]
@bobbywhitesfdc please look the new version 4.6.0 🥳
