### ISSUE TITLE
--generate-delta param returns "Source and destination must not be the same." in Warnings

### ISSUE THREAD

**Issue by hectorgb** [scolladon/sfdx-git-delta#147]
Issue verification check :

- [X] does the current repository is fully deployable at the commit sha given to the from parameter of the command ?

## What is the problem
I'm trying to generate de delta with --generate-delta param with no success. It creates the package/package.xml file with correct metadata, but is returnin a warning: "Source and destination must not be the same." when i use the mentioned param(--generate-delta). Is not generating the files in the diff, just creates the package. Is happening in my local and also in a GitLab repo.

### What is parameter and their value you used
sfdx sgd:source:delta --from HEAD^ --to HEAD --output . --generate-delta

### What is the expected result
I expect a package folder within the files contained in the diff. That was the behaviour when i used this wonderful plugin before, but now i'm not getting it works as expected, and not sure if it's on my side (could be, probably, sure...)

### What is the actual result
It is creating fine the pckagae/package.xml, but it doesn't ceate a folder with just the changes, and provides the following warning in the output.

```
{
  "error": null,
  "output": ".",
  "success": true,
  "warnings": [
    "force-app/main/default/classes/ApexClass3.cls: Source and destination must not be the same.",
    "force-app/main/default/classes/ApexClass3.cls: Source and destination must not be the same."
  ]
}
```

## Steps to reproduce
1. Create a feature branch from develop. E.g: feature/apexclass-test
2. Create an ApexClass. E.g: ApexClass3
3. Commit your new class
4. Perform the mentioned command (sfdx sgd:source:delta --from HEAD^ --to HEAD --output . --generate-delta)

## Execution context
Localy and remotely. It is also happening in GitLAb repo created in my local.

**Operating System:** Ubuntu 20.04.1

**yarn version:** 1.22.10

**node version:** v15.14.0

**git version:** 2.25.1

**sfdx version:** sfdx-cli/7.94.3-a4e7c7955b linux-x64 node-v14.15.4

**sgd plugin version:** sfdx-git-delta 4.5.0

## Optional more information

---

**Comment by scolladon** [comment]
Hi @hectorgb !

Thanks for your interest in the plugin.

What is described here is not a bug, it is how the plugin works.
It is not possible to set as output the same folder as the target repository.
The command need to have a dedicated folder to generate its output (and avoid override the repository content).

You could create an "output" folder in your repository prior to run the command and then execute the command :
```sh
# go to the repo
cd /repo/path
# create output folder
mkdir output
# run sgd
sfdx sgd:source:delta --from "HEAD^" --to "HEAD" --output "output" --generate-delta
# do your stuff with the result
...
# then dispose the output folder
rm -rf output
```

Let me know if it helped

Seb

**Comment by hectorgb** [comment]
Hi @scolladon 

So sorry to bother you with this stupid thing, i'll read twice next time...

Apologies

Thanks!
Hector.

**Comment by scolladon** [comment]
No problem at all !

Your issue is very well defined ! Thank you for that.
You earned the "good first issue" label ! :D
