### ISSUE TITLE
ERROR running sgd:source:delta:  Unexpected arguments: --ignore-destructive, destructiveignore[BUG NAME]

### ISSUE THREAD

**Issue by AnantSahTeli** [scolladon/sfdx-git-delta#149]
Issue verification check :

- [x] does the current repository is fully deployable at the commit sha given to the from parameter of the command ?

## What is the problem

---

## Steps to reproduce

---

## Execution context

---

**Operating System:**  linux-x64

**yarn version:** …

**node version:**node-v14.14.0

**git version:** …

**sfdx version:** sfdx-cli/7.82.1-0 

**sgd plugin version:** …

## Optional more information

---

**Comment by mehdisfdc** [comment]
Hi @AnantSahTeli , thank you for creating this issue!
Could you provide us with a little more information on how you got this error and how to reproduce it? Thank you!

**Comment by AnantSahTeli** [comment]
@mehdisfdc Thanks for the quick response, I am able to fix this error by updating the new version of sfdx and delta plugins.
