### ISSUE TITLE
[Workflow retrieved from Diff is EMPTY]

### ISSUE THREAD

**Issue by deepakandeli** [scolladon/sfdx-git-delta#152]
Issue verification check :

- [ ] does the current repository is fully deployable at the commit sha given to the from parameter of the command ?

## What is the problem
The extracted Workflow files are empty with just the header.
---

### What is parameter and their value you used

`sfdx sgd:source:delta --to HEAD --from "12a2229e4811d24aef3b464794f26b2b5246b41a" --output ./.unpackaged/delta/output --generate-delta`

### What is the expected result
Expected to retrieve all the changed files including Workflow files with the Workflow rules and alert inside the individual file.
But it seems each of the workflow file copied over from Git to the local folder is NULL without any entries related to Workflow rules or Alert details

**Expected File**
`<?xml version="1.0" encoding="UTF-8"?>
<Workflow xmlns="http://soap.sforce.com/2006/04/metadata">
    <alerts>
        <fullName>Test_Email</fullName>
        <description>Test Email.</description>
        <protected>false</protected>
        <recipients>
            <type>creator</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>SVMXC__ServiceMaxEmailTemplates/SMAX_PS_SAP_Error_HTML</template>
    </alerts>
    <fieldUpdates>
        <fullName>Set_Parent_ID</fullName>
        <field>SMAX_PS_Parent_ID__c</field>
        <formula>IF(NOT(ISBLANK(SMAX_PS_Parts_Order__c)),SMAX_PS_Parts_Order__r.Id,IF(NOT(ISBLANK(SMAX_PS_Work_Order__c)),SMAX_PS_Work_Order__r.Id,&apos;&apos;))</formula>
        <name>Set Parent ID</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Formula</operation>
        <protected>false</protected>
        <reevaluateOnChange>false</reevaluateOnChange>
    </fieldUpdates>
    <outboundMessages>
        <fullName>JitterBitOutboundMessage</fullName>
        <apiVersion>51.0</apiVersion>
        <description>Outbound message send to JitterBit everytime a Interface Log record is created.</description>
        <endpointUrl>https://envbmnfyjz8pq.x.pipedream.net/</endpointUrl>
        <fields>CreatedById</fields>
        <fields>CreatedDate</fields>
        <fields>Id</fields>
        <fields>SMAX_PS_Interface_Name__c</fields>
        <fields>SMAX_PS_Interface_Status__c</fields>
        <fields>SMAX_PS_Object_API_name__c</fields>
        <fields>SMAX_PS_Parent_ID__c</fields>
        <includeSessionId>true</includeSessionId>
        <integrationUser>deepak.andeli@servicemax.com.hts</integrationUser>
        <name>JitterBitOutboundMessage</name>
        <protected>false</protected>
        <useDeadLetterQueue>false</useDeadLetterQueue>
    </outboundMessages>
    <rules>
        <fullName>Integration Outbound Message</fullName>
        <actions>
            <name>Set_Parent_ID</name>
            <type>FieldUpdate</type>
        </actions>
        <actions>
            <name>JitterBitOutboundMessage</name>
            <type>OutboundMessage</type>
        </actions>
        <active>true</active>
        <formula>AND(
	ISPICKVAL( SMAX_PS_Interface_Status__c,&apos;In Progress&apos;),
	NOT(OR(CONTAINS(&apos;SVMXC__Installed_Product__c&apos;,SMAX_PS_Object_API_name__c),CONTAINS(&apos;Product2&apos;,SMAX_PS_Object_API_name__c),CONTAINS(&apos;Account&apos;,SMAX_PS_Object_API_name__c),CONTAINS(&apos;PricebookEntry&apos;,SMAX_PS_Object_API_name__c),CONTAINS(&apos;OracleWorkOrder&apos;,SMAX_PS_Object_API_name__c),CONTAINS(&apos;OracleCase&apos;,SMAX_PS_Object_API_name__c)))
)</formula>
        <triggerType>onCreateOnly</triggerType>
    </rules>
    <rules>
        <fullName>SMAX PS Send Email on Integration Error</fullName>
        <actions>
            <name>Test_Email</name>
            <type>Alert</type>
        </actions>
        <active>true</active>
        <criteriaItems>
            <field>SMAX_PS_Interface_Log__c.SMAX_PS_Interface_Status__c</field>
            <operation>equals</operation>
            <value>Failed</value>
        </criteriaItems>
        <description>Send email to the Interface log record creator when there is a failure with the integration</description>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
    </rules>
    <rules>
        <fullName>Set Parent ID</fullName>
        <actions>
            <name>Set_Parent_ID</name>
            <type>FieldUpdate</type>
        </actions>
        <active>false</active>
        <formula>OR(NOT(ISNULL(SMAX_PS_Parts_Order__c)),NOT(ISNULL(SMAX_PS_Work_Order__c)))</formula>
        <triggerType>onCreateOnly</triggerType>
    </rules>
</Workflow>
`

### What is the actual result
**Actual file retrieved**
`<?xml version="1.0" encoding="utf-8"?>
<Workflow xmlns="http://soap.sforce.com/2006/04/metadata"></Workflow>`

## Steps to reproduce

- Retrieve the workflow file from Salesforce Org
- Commit the workflow file to the repository
- Run the sgd command to retrieve the files and package.xml from Source to a local folder
- Locate the Workflow folder and navigate to the .workflow file that was committed in Step 2
- We would see that the file is EMPTY without Alert and Rule information

---

Playground Git Repo: https://github.com/deepakandeli/sfdx-git-delta-reproduction-playground-master

`sfdx sgd:source:delta --to HEAD --from "ff4983e8e033c4967dce5d4f0586cca8704c9b0b" --output ../output --generate-delta`

Content of **sgd/reproduction/playground/workflows/SMAX_PS_Interface_Log__c.workflow**
`<?xml version="1.0" encoding="utf-8"?>
<Workflow xmlns="http://soap.sforce.com/2006/04/metadata"></Workflow>`

## Execution context

---

**Operating System:**Windows 10 running in VSC bash terminal

**yarn version:** …

**node version:**v13.11.0

**git version:**2.31.1.windows.1

**sfdx version:** sfdx-cli/7.105.0 win32-x64 node-v14.17.0

**sgd plugin version:** sfdx-git-delta 4.6.0

## Optional more information

---

`A       force-app/main/default/email/SVMXC__ServiceMaxEmailTemplates/SMAX_PS_SAP_Error_HTML.email
A       force-app/main/default/email/SVMXC__ServiceMaxEmailTemplates/SMAX_PS_SAP_Error_HTML.email-meta.xml
M       force-app/main/default/email/SVMXC__ServiceMaxEmailTemplates/SMAX_PS_SAP_Integration_Error.email
A       force-app/main/default/flexipages/Installed_Product_Record_Page.flexipage
M       force-app/main/default/flexipages/SMAX_PS_Account_Record_Page.flexipage
M       force-app/main/default/flexipages/SMAX_PS_Case.flexipage
M       force-app/main/default/flexipages/SMAX_PS_Contact_Record_Page.flexipage
A       force-app/main/default/flexipages/SMAX_PS_Installed_Product_Component.flexipage
M       force-app/main/default/flexipages/SMAX_PS_Installed_Product_Page.flexipage
M       force-app/main/default/flexipages/SMAX_PS_Location_Record_Page.flexipage
M       force-app/main/default/flexipages/SMAX_PS_Product_Record_Page.flexipage
M       force-app/main/default/flexipages/SMAX_PS_Service_Quote_Record_Page.flexipage
M       force-app/main/default/layouts/Case-SMAX PS Case Layout.layout
M       force-app/main/default/objects/Case.object
M       force-app/main/default/objects/SVMXC__Quote__c.object
M       force-app/main/default/objects/SVMXC__Service_Order__c.object
M       force-app/main/default/workflows/SMAX_PS_Interface_Log__c.workflow
D       force-app/main/default/workflows/SMAX_PS_Interface_Log__c.workflow-meta.xml`

**Comment by mehdisfdc** [comment]
Thank you for logging your issue @deepakandeli , and thank you for providing such a detailed description!

@scolladon I tested the reproduction steps on macOs, and was not able to reproduce this issue (the SMAX_PS_Interface_Log__c.workflow file was properly populated during my test).
So I suspect that this might an issue specific to Windows. I've noticed that the workflow description is in japanese in the repo (承認者へのメール通知), so maybe it's an encoding issue on Windows? (note: this is just an hypothesis, I haven't tried to reproduce on Windows so far).

**Comment by scolladon** [comment]
Hi @deepakandeli !

Thanks very much for this issue.
It is related to interoperability and sanitizing !
I think this issue has been here since the beginning for inFile metadata type, nice catch !

We have created a PR for that : #153 
The fix makes the reproduction playground works on my side (with a Windows VM).

Would you like to test it on your side also ?
If you don't know how I can guide you on [gitter](https://gitter.im/scolladon) !

**Comment by scolladon** [comment]
New [Release](https://github.com/scolladon/sfdx-git-delta/releases/tag/v4.6.1) closing this issue!
