### ISSUE TITLE
CustomLabels fiel - new labels not detected

### ISSUE THREAD

**Issue by welhorr** [scolladon/sfdx-git-delta#162]
We are still facing the custom label issue, but only when adding new custom labels (not editing existing ones) to the file CustomLabels.labels-meta.xml.

This is working fine:

1. Create a new branch from Master. Let's call it develop.
2. Checkout branch develop.
3. Edit the sfdx/main/default/labels/CustomLabels.labels-meta.xml file **by only editing the description of an existing customer label named LABEL1**
4. Commit changes.
5. In Jenskins run: sfdx sgd:source:delta -t LASTCOMMITIDINDEVELOPER -f PREVIOUSSUCCESSCOMMITID creates the below package.xml and deployment happens without any issue.

```
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>LABEL1</members>
        <name>CustomLabel</name>
    </types>
    <version>52.0</version>
</Package>
```

Now, if we add **a new custom label** to the file sfdx/main/default/labels/CustomLabels.labels-meta.xml, for example:

```
<labels>
        <fullName>WALTEST</fullName>
        <language>en_US</language>
        <protected>false</protected>
        <shortDescription>WALTEST</shortDescription>
        <value>WALTEST</value>
</labels>
```

And then we do the exact same step above, we get an empty package.xml file and the deployment fails.

```
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <version>52.0</version>
</Package>
```

When we edit an existing label called EXISTINGLABEL AND add a new one called TESTLABEL, we get this package.xml file:
```
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>EXISTINGLABEL</members>
        <name>CustomLabel</name>
    </types>
    <version>52.0</version>
</Package>
```

The main difference is that editing an existing label (by editing its description for example) is detected, but adding a NEW label to the file is not detected. This was also the behavior prior to this new 4.7 version. 

Note that the customLabels file has more than 40k lines.

We are using the latest 4.7 version. 

Thanks.

**Comment by scolladon** [comment]
Hi @welhorr !

Thanks for raising it.
I thought this use case was covered by the tests...

I'll have a look at it very soon reusing the data you sent

**Comment by scolladon** [comment]
I tested using the [reproduction playground](https://github.com/scolladon/sfdx-git-delta-reproduction-playground/tree/issue/47-again) and I did not manage to reproduce the issue...

Do you manage to reproduce on your machine by making sure you are using the last version of sgd ?
If so, then could you fork the [branch](https://github.com/scolladon/sfdx-git-delta-reproduction-playground/tree/issue/47-again) of the reproduction playground and commit your analysis @welhorr ? It will greatly helped us as we do not reproduce it for now

> **Tips**
> Here is how I work with the reproduction playground:
> 1. I create a branch (but here you can use issue/47-again)
> 2. I put the init data (in this case it is the big CustomLabel file, which is already present)
> 3. I make the changes in the files (in this case it is a random change of the description + the > addition of a CustomLabel. I tried to add it at the start and the end of the file with the same result)) and I commit it
> 4. I run sgd and commit the result with a commit message explaining the result

**Comment by welhorr** [comment]
Thanks @scolladon , let me check and I will get back to you about this one.

**Comment by welhorr** [comment]
Hi @scolladon , it seems this is fixed now after further testing it. Thanks for the great support here!

**Comment by joelswiss** [comment]
Hi @scolladon , is the issue appearing again, as the deployment failed as delta failed to find/track the change in the custom-label file. If you kindly look into it.
![Screenshot 2023-12-19 164840](https://github.com/scolladon/sfdx-git-delta/assets/118887509/4955cb6c-ac4e-48c5-a082-28fb74089965)

**Comment by scolladon** [comment]
Hi @joelswiss, sorry to read that.

Could you please give us detailed instructions to reproduce it locally ?

**Comment by joelswiss** [comment]
> Hi @joelswiss, sorry to read that.
> 
> Could you please give us detailed instructions to reproduce it locally ? And also your execution context please ? `$ uname -v ; yarn -v ; node -v ; git --version ; sfdx --version ; sfdx plugins`
> 
> I am using this [reproduction instructions](https://github.com/scolladon/sfdx-git-delta/issues/162#issuecomment-876732840) on my mac and I cannot reproduce


1.) Create a new label in source org
2.) Retrieve it in vs code and partial commit that label to source branch 
3.) Create a pull request to target branch
4.) On Create our pull request pipeline will be triggered.
5.) Package validation is failing due to no source backed component found 

Code utilized in pipeline to find delta:
             pwd
             mkdir toDeploy 
             SFDX_DISABLE_DNS_CHECK=true sfdx sgd:source:delta --to "HEAD" --from "HEAD~1" --output ./toDeploy/ --generate-delta --source force-app              
              ls ./toDeploy 
However, there is no delta value getting created for custom label and the pipeline failed.

**Comment by scolladon** [comment]
Just to be sure @joelswiss, does it works locally ? And what is the is running ? Sfdx version, got version, node version, sgd version ?

On my side it works just fine (Mac)

**Comment by joelswiss** [comment]
> Just to be sure @joelswiss, does it works locally ? And what is the is running ? Sfdx version, got version, node version, sgd version ?
> 
> On my side it works just fine (Mac)

Hi @scolladon , if you may kindly review the required info:
sfdx-cli/7.200.7 linux-x64 node-v18.16.0

**Comment by scolladon** [comment]
Could you give me access to the repository please @joelswiss ?

Or could you provide the git log of that PR please ?

**Comment by joelswiss** [comment]
> Could you give me access to the repository please @joelswiss ?
> 
> Or could you provide the git log of that PR please ?
This is our Organization repo, can we setup a call to demonstrate the issue.

**Comment by scolladon** [comment]
Hi @joelswiss, sure let's schedule something.
My email is on my github profile
