### ISSUE TITLE
New PathAssistant Not detected

### ISSUE THREAD

**Issue by robertoamd90** [scolladon/sfdx-git-delta#167]
When you add new PathAssistant, in 'force-app/main/default/pathAssistant/' folder, the changes is not detected from the delta tool.

Step to reproduce:

1. create the fodler 'force-app/main/default/pathAssistant/' if not exist
2. create a file named 'Test.pathAssistant-meta.xml'
```<?xml version="1.0" encoding="UTF-8"?>
<PathAssistant xmlns="http://soap.sforce.com/2006/04/metadata">
    <active>true</active>
    <entityName>Order</entityName>
    <fieldName>Status</fieldName>
    <masterLabel>Test</masterLabel>
    <recordTypeName>__MASTER__</recordTypeName>
</PathAssistant>
```
3. Commit the new file 'Test.pathAssistant-meta.xml'
4. Run the command 'sfdx sgd:source:delta --to HEAD --from HEAD^ --output delta'
5. check the empty Package.xml in the delta folder:
```
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <version>52.0</version>
</Package>
```

**Comment by scolladon** [comment]
Hi @robertoamd90 !

Thanks for your interest in the plugin and thanks for your contribution to make it better !

I tried to reproduce on my side using the [reproduction playground](https://github.com/scolladon/sfdx-git-delta-reproduction-playground/tree/issue/167).

It seems to be working on my side when using the `pathAssistants` (in plural) [folder](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_pathassistant.htm).

Could you confirm on your side that it fixes the issue ?

**Comment by robertoamd90** [comment]
Hi @scolladon ,
Thanks for your fast feedback,
We have checked your suggest and fixed the folder name (created from Scratch Org Pull) with the suggested name (confirmed by developer guide), and this fixed the problem.

Thanks a lot for your work,

Roberto

**Comment by scolladon** [comment]
Thanks! 

That is weird that `sfdx force:source:pull` creates a bad folder name...
Have you seen a related issue on the sfdx repo ?
Maybe you should create one !

**Comment by robertoamd90** [comment]
We did some tests, 
push and pull work correctly with both folder, but we don't know why CLI have created singular folder. Maybe ti was created on old CLI version.

Thanks again!
