### ISSUE TITLE
Package.xml without messageChannel

### ISSUE THREAD

**Issue by devair** [scolladon/sfdx-git-delta#170]
Issue verification check :

- [ ] does the current repository is fully deployable at the commit sha given to the from parameter of the command ?

## What is the problem

When I commit a messageChannel metadata into repo, the command below does not identify it.

sfdx sgd:source:delta --to "HEAD" --from "HEAD^" --output "."

---

### What is the expected result

\<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
\<Package xmlns="http://soap.sforce.com/2006/04/metadata">
	\<types>
		\<members>*</members>
		\<name>LightningMessageChannel</name>
	\</types>
	\<version>52.0</version>
\</Package>

### What is the actual result

\<?xml version="1.0" encoding="UTF-8"?>
\<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    \<version>52.0</version>
\</Package>

## Steps to reproduce

---

## Execution context

---

**Operating System:** Windows 10

**yarn version:** …

**node version:**  v15.14.0

**git version:** git version 2.32.0.windows.1

**sfdx version:**  sfdx-cli/7.105.0 win32-x64 node-v15.14.0

**sgd plugin version:** sfdx-git-delta 4.7.1

## Optional more information

---

  Provide the output of those command line :
  $ git diff --name-status --no-renames <from> <to>

D       force-app/main/default/lwc/sapPartidasFilter/sapPartidasFilter.html
D       force-app/main/default/lwc/sapPartidasFilter/sapPartidasFilter.js
D       force-app/main/default/lwc/sapPartidasFilter/sapPartidasFilter.js-meta.xml
M       force-app/main/default/lwc/sapPartidasList/sapPartidasList.html
M       force-app/main/default/lwc/sapPartidasList/sapPartidasList.js
D       force-app/main/default/messageChannel/PartidasFinanceirasFiltered.messageChannel-meta.xml

**Comment by scolladon** [comment]
Hi @devair !

Thanks for this very detailed issue !

I think the issue comes from the folder where is located the `messageChannel` component.
According to the [documentation](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_lightningmessagechannel.htm) it should be named `messageChannels` whereas it is named `messageChannel` in the sample provided.

Could you try using the folder named `messageChannels` and let us know if it solved the issue ?

**Comment by devair** [comment]
@scolladon 

Thanks for the answer.
I fixed the directory name then it solved.
