### ISSUE TITLE
Apex subfolder can generate wrong package.xml

### ISSUE THREAD

**Issue by pfrandsen** [scolladon/sfdx-git-delta#171]
Issue verification check :

- [ ] does the current repository is fully deployable at the commit sha given to the from parameter of the command ?

## What is the problem

If I have Apex class(es) in a subfolder called "settings" then an erroneous package.xml file will be generated (same is likely the case with destructive changes). Example:

force-app/main/default/classes/settings/MarketingCloudSettings.cls

Generates:

`<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>MarketingCloudSettings.cls</members>
        <name>Settings</name>
    </types>
    <version>52.0</version>
</Package>`

Instead of:

`<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>MarketingCloudSettings.cls</members>
        <name>ApexClass</name>
    </types>
    <version>52.0</version>
</Package>`

---

### What is parameter and their value you used

sfdx sgd:source:delta --to feature/TTR-420-update-subscriber --from master --output changes

### What is the expected result
`<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>MarketingCloudSettings.cls</members>
        <name>ApexClass</name>
    </types>
    <version>52.0</version>
</Package>`

### What is the actual result
`<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>MarketingCloudSettings.cls</members>
        <name>Settings</name>
    </types>
    <version>52.0</version>
</Package>`

## Steps to reproduce

Create folder: force-app/main/default/classes/settings
Create Apex class in folder
git add and commit
run sgd to generate package.xml

---

## Execution context

---

**Operating System:** …
Windows 10

**yarn version:** …
1.12.1

**node version:** …
14.17.3

**git version:** …
2.17.1.windows.2

**sfdx version:** …
sfdx-cli/7.110.0 win32-x64 node-v14.17.3

**sgd plugin version:** …
sfdx-git-delta 4.7.1

@salesforce/sfdx-diff 0.0.6

## Optional more information

Thanx for a GREAT tool!
---

**Comment by scolladon** [comment]
Hi @pfrandsen !

Thanks for your interest in the plugin and for contributing to make it better.

This issue is very interesting! Thanks for raising it.
I'll come with a fix in the next days, stay tuned!

**Comment by pfrandsen** [comment]
Thanx @scolladon.
I really appreciate what you are doing.

**Comment by scolladon** [comment]
New version including a fix just released (4.7.2)
FYI @pfrandsen
