### ISSUE TITLE
Question - Deploy FieldTranslation with SFDX

### ISSUE THREAD

**Issue by barouchk** [scolladon/sfdx-git-delta#182]
when pulling from sandbox object translation with package:

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
	<types>
        <members>Expert_Consulting__c</members>
        <name>CustomObject</name>
    </types>
	<types>
        <members>Expert_Consulting__c-iw</members>
        <name>CustomObjectTranslation</name>
    </types>
	<version>52.0</version>
</Package>
```
It retrieve all fieldTranslation as well

But when performing deploy with the same package.xml, the field translation not deployed.

This issue happened with version: sfdx-cli/7.112.1

Someone have a solution to deploy fieldTranslation with sfdx?

**Comment by scolladon** [comment]
Hi @barouchk !

Thanks for your interest in the plugin and for your help to make it better !

Translation ! That is a big topics using the metadata. Behavior depends on the API version, the content of the package.xml the action (retrieve or deploy)... 🤯 

Have you tried to explicitly list in the managed package the CustomField and the CustomFieldTranslation wanted ?
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
	<types>
        <members>Expert_Consulting__c</members>
        <name>CustomObject</name>
    </types>
	<types>
        <members>Expert_Consulting__c.ExampleCustomField__c</members>
        <name>CustomField</name>
    </types>
	<types>
        <members>Expert_Consulting__c-iw</members>
        <name>CustomObjectTranslation</name>
    </types>
	<types>
        <members>Expert_Consulting__c.ExampleCustomField__c-iw</members>
        <name>CustomFieldTranslation</name>
    </types>
	<version>52.0</version>
</Package>
```

**Comment by barouchk** [comment]
Hi Scolladon,

I also asked this question in salesforce-cli GitHub and found that the new version has an issue with deploying FieldTranslation.

The deployment for fieldTranslation last worked on version: **7.110.0**
I have tested it and it's worked, Hope they will fix it in the next version.

The solution, for now, is to install version: 7.110.0 (one month ago):
`sfdx plugins:install sfdx-cli@7.110.0`
