### ISSUE TITLE
Bitbucket pipeline configuration issue

### ISSUE THREAD

**Issue by joao-carvalho-bnt** [scolladon/sfdx-git-delta#183]
Issue verification check :

- [ ] does the current repository is fully deployable at the commit sha given to the from parameter of the command ?

## What is the problem
I'm unable to configure a bitbucket pipeline to work with SGD.

 ### Provide a clear and concise description of what the problem is.
Upon verifing the changes, I try to run the SGD command to output them into a folder, but an error message is outputed.

### What is parameter and their value you used
sgd --to some-pr-branch  --from origin/QA --repo . --output .

### What is the expected result
Expect the file to be outputed into the standard "package" folder

### What is the actual result
An error message is throw:
`sgd --to some-pr-branch  --from origin/QA --repo . --output .

/root/.nvm/versions/node/v8.9.4/lib/node_modules/sfdx-git-delta/bin/cli:48
  output.warnings = jobResult?.warnings?.map(warning => warning.message)
                              ^
SyntaxError: Unexpected token .
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:607:28)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3`

## Steps to reproduce
1. Create a pipeline in bitbucket
2. Install sgd - legacy version
3. try to run the command to check changes

---

<!--
  Isolate the issue and create a branch in the playground repository
  to help reproducing the actual result
  Provide the repository url to access the reproducible state
  Provide the sgd command to execute to reproduce
  Ex :
  https://github.com/scolladon/sfdx-git-delta-reproduction-playground
  sgd -d -r . -f HEAD^
  sfdx sgd:source:delta -d -f HEAD^

**Comment by scolladon** [comment]
Hi @joao-carvalho-bnt !

Thanks for your interest on the plugin and for your help making it better.

Base and the logs I see, it seems the node version used is v8.9.4.
The minimum node version required to run the plugin is v14.6.0.

I also see it is using the sgd cli instead of the sfdx plugin, I'm interested on why you chose to use it this way ?
