### ISSUE TITLE
[permissivediff] Allow to use permissive git diff to ignore diffs related to indentation

### ISSUE THREAD

**Issue by nvuillam** [scolladon/sfdx-git-delta#184]
### Is your proposal related to a problem?

sfdx plugin [sfdx-hardis](https://www.npmjs.com/package/sfdx-hardis) uses sfdx-git-delta to:
- update local package.xml after a force:source:pull
- manage a file packageDeployOnChange.xml , to avoid deploying items whose state have not changed since last deploy

### Describe the solution you'd like

Manage a new argument `--permissivediff` to add the following parameters to **git diff** call 
```javascript
[
    '--ignore-all-space',
    '--ignore-blank-lines',
    '--ignore-cr-at-eol',
    '--word-diff-regex',
]
```

It allows to avoid detecting as a difference the indentation/spaces stuff

### Describe alternatives you've considered

None

### Additional context

I almost completed the dev in my fork of sfdx-git-delta, a PR will come soon

**Comment by scolladon** [comment]
Hi @nvuillam !

Thanks for your interest in the plugin and for contributing in making it better !

I like this suggestion!

I have questions:

- Why this should not be the standard behaviour? => What will be the added value to that and why both use cases should exists?
- why using `--word-diff-regex` parameter? With which value?

Suggestion: the parameter name must follow the [cli parameter apache convention](https://commons.apache.org/proper/commons-cli/index.html). I suggest the following `--permissive-diff -P` if we keep this wording

Please add me to your fork so I can contribute and help you solve CI/CD issues you may encounter

**Comment by nvuillam** [comment]
> Thanks for your interest in the plugin and for contributing in making it better !

You're welcome, thanks for your great plugin that allowed me to create a command on [sfdx-hardis](https://marketplace.visualstudio.com/items?itemName=NicolasVuillamy.vscode-sfdx-hardis) that completes automatically package.xml after a force:source:retrieve, so now at Hardis Group even consultants can use SFDX, without having to be trained to git ❤️ 

> Why this should not be the standard behaviour? => What will be the added value to that and why both use cases should exists?

Let's say that someone updated a label to add empty lines ... if permissive-diff was by default, such update would not be considered as a detected difference

> Suggestion: the parameter name must follow the cli parameter apache convention. I suggest the following --permissive-diff -P if we keep this wording

The problem with cli parameter apache convention is that [OCLIF flags convention](https://oclif.io/docs/flags) does not agree: `-` are not allowed within parameter names :/ ( or maybe it's sfdx-cli flags, I don't remember but i'm sure I already had errors when using a `-` in a flag name )

> why using --word-diff-regex parameter? With which value?

`'--ignore-all-space',    '--ignore-blank-lines',    '--ignore-cr-at-eol'` were not enough for some of my use cases, and using `--word-diff-regex` solved them :) But as I'm far from being a git expert, I can't really explain why :/ 

> Please add me to your fork so I can contribute and help you solve CI/CD issues you may encounter

Done !
