### ISSUE TITLE
[BUG NAME] not identifying the delta if we use multiple src folders. example src, src-a

### ISSUE THREAD

**Issue by RohitGagan16** [scolladon/sfdx-git-delta#189]
Issue verification check :

- [ ] does the current repository is fully deployable at the commit sha given to the from parameter of the command ?

## What is the problem
The repo contain multiple src folders. example src and src-a. I changed the file in src-a folder and commit it. When i try to run the following command to find the delta between the last two commit hash, this doesnot list the difference.
Here is the command

sudo sfdx sgd:source:delta --to $TOCOMMIT_HASH --from $FROM_COMMIT_HASH  --ignore-destructive destructiveignore --output sfdx-delta --generate-delta
---

However, if i run simple git diff, this gives the correct diff with following command
git diff $FROM_COMMIT_HASH $TOCOMMIT_HAS

### What is the expected result

Expected result is this should fetch the delta between the two commits, rather than depending on the source folders. For the above example, it should show the difference between src-a folder as well

### What is the actual result
sudo sfdx sgd:source:delta --to $TOCOMMIT_HASH --from $FROM_COMMIT_HASH  --ignore-destructive destructiveignore --output sfdx-delta --generate-delta

The above command didnt provide any differnce

## Steps to reproduce

---

## Execution context

---

**Operating System:** …

**yarn version:** …

**node version:** …

**git version:** …

**sfdx version:** …

**sgd plugin version:** …

## Optional more information

---

**Comment by mehdisfdc** [comment]
Hi @RohitGagan16 , and thank you for taking the time to log your issue!

I've tried to reproduce it, but was not able to :-(
Would you be able to share with us the detailed steps to reproduce the issue on a public repro (such as a fork of https://github.com/scolladon/sfdx-git-delta-reproduction-playground)?

Also, just to make sure we explored all possible causes: you are mentioning "src" as the name of one of your folder, which is often the default folder name when metadata is the (old) mdapi format. However, SGD works only when the metadata is in the (new) [Source format](https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_source_file_format.htm). Could you confirm that you are using this Source format?

**Comment by RohitGagan16** [comment]
Hi,
Thanks a lot for taking the time to look into the issue.
I confirm that the sources are in source format and not in the mdapi format. Here is the detailed description.
We are implementing the modular structure for the repo. Single repo is shared by multiple teams and we are giving separate source folder to the separate teams(src,src-a,src-b,src-c etc).

Folder structure for all is (src/main/default....,src-a/main/default/...  etc

Now when i try to use the delta between two commits, it only gives for the src folder. Not for the src-a or src-b or any folder.
Let me know if you need more details. I am ok with discussing on zoom call or so as well

Regards
Rohit Gagan.
________________________________

**Comment by mehdisfdc** [comment]
Thank you for the additional information @RohitGagan16 !
@scolladon I believe I was now able to reproduce the issue, let's discuss it together next time we speak.

**Comment by mehdisfdc** [comment]
Thank you for the additional information @RohitGagan16 !

Unlike stated in my previous (deleted) comment, I did not manage to reproduce your issue, sorry.

Here is what I checked on this sample repo https://github.com/mehdisfdc/sfdx-git-delta-reproduction-playground

1) the `sfdx sgd:source:delta --to "HEAD" --from "HEAD^" --output sfdx-delta --generate-delta` command outputs only the "ApexClass2" (that is under the "src-a" folder)

2) 1) the `sfdx sgd:source:delta --to "HEAD" --from "d93f81e" --output sfdx-delta --generate-delta` command outputs both "ApexClass2" (under the "src-a" folder) and  "ApexClass1" (under the "force-app" folder).

So something must be different in your case...

Could you please first check with the `sfdx plugins` that you are using version 4.8.1 of SGD?

If so, could you please share with me the steps to reproduce the issue on a public GitHub folder (you can fork https://github.com/mehdisfdc/sfdx-git-delta-reproduction-playground for example)?

Thank you!

**Comment by mehdisfdc** [comment]
@RohitGagan16 Do you still face this problem? If so, could you share the reproduction steps in a public repo?
Otherwise I'll close this issue.

**Comment by RohitGagan16** [comment]
Hi,
Please close this issue. It was an mistake from my side.

Thanks a lot for looking into the issue

Regards
Rohir

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
