### ISSUE TITLE
Renaming field name - not destroying the old one - git status R100 and R065

### ISSUE THREAD

**Issue by MaciekLeks** [scolladon/sfdx-git-delta#193]
Let me be concise:

S01E01 - commit FROM: stay calm
S01E02 - commit TO: Renamed field  from IsFullyReserved to IsFullyReservedOld

Who loves who between two episodes:
The tool does not fetch the the git change:

git diff:
```
git diff --name-status ${FROM} ${TO}
```
```
 R100    force-app/common/objectTranslations/Order-pl/IsFullyReserved__c.fieldTranslation-meta.xml       force-app/common/objectTranslations/Reservation__c-pl/IsFullyReserved__c.fieldTranslation-meta.xml
R065    force-app/common/objects/Order/fields/IsFullyReserved__c.field-meta.xml force-app/common/objects/Order/fields/IsFullyReservedOld__c.field-meta.xml
```

the tool:
destructive changes package.xml:
```
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <version>52.0</version>
</Package>
```
package.xml parts
```
...
 <types>
        <members>Contract.HasWatermark__c</members>
        <members>Order.IsFullyReservedOld__c</members>
        <members>Reservation__c.IsFullyReserved__c</members>
        <name>CustomField</name>
    </types>
...
```
```

**Comment by scolladon** [comment]
Hi @MaciekLeks !

Thanks for logging this issue.

Could you put it in the reproduction playground ?
And make sure it is reproducible in there ?

Then we will be able to reproduce locally and debug
Thanks a lot

**Comment by MaciekLeks** [comment]
OK, I will ping you  when it's ready.

**Comment by MaciekLeks** [comment]
Dear Sebastien, 

I cannot replicate the problem. I've tried using the playground project (very good idea). Due to our corpo policy we cannot share the repo so we have dissused it and I propose to show you this during the very short meeting (10-15mins). If you agree, write to me at maciej.leks@gmail.com. I will adapt to your schedule. 

Maciek

**Comment by scolladon** [comment]
Hi,

Thanks @MaciekLeks for our meeting of today.
I think I understand better what is the context of the issue here.

I will try in the next few days to isolate this behaviour in the sgd-playground and then to fix the issue :)

I'll keep you posted here!
