### ISSUE TITLE
How to execute sgd:source:delta for multiple root folders specific to enviroment

### ISSUE THREAD

**Issue by nikhileshmishra** [scolladon/sfdx-git-delta#194]
## What is the problem

Unable to execute sgd:source:delta command since root level of repo has multiple folders specific to environment.

 My project structure in root git hub repo  is like below (attached)
![project structure](https://user-images.githubusercontent.com/89146067/136189597-7fcea0c6-09c6-4382-8be9-55f15ba20300.png)
1.	force-app/main/default
2.	src-devops
3.	src-envspecific/nonprod,
4.	i) src-envspecific/qa
        ii) src-envspecific/pqa
        iii) src-envspecific/training

We generally deploy the mentioned folders specific to environment .(**in this case its QA**)
 sfdx force:source:deploy -p force-app/main/default,src-devops,src-envspecific/nonprod,src-envspecific/qa,src-profiles/applications/Customer_Care.app-meta.xml --testlevel RunLocalTests --targetusername qa

Now when we use the plugin to deploy in QA, how to ignore the folder specified to other environment (folders like src-envspecific/pqa or src-envspecific/training )
Please suggest the best way to use plugin for multiple src folders & specified to each environment

**Comment by nikhileshmishra** [comment]
Hi,
Thanks a lot for taking the time to look into the issue.
I tried executing the 1st option by using below command for QA environment ignoring the other folders

sfdx sgd:source:delta --to HEAD --from AARP-2021-PI-4.5.0.1101.QA -i src-envspecific/pqa -i src-envspecific/training -i src-envspecific/prod --output .
Since its QA ,so i have ignored other folders 
I got below error
{
  "error": "EISDIR: illegal operation on a directory, read",
  "output": ".",
  "success": false,
  "warnings": []
}

Is the --ignore option only for files or we can mention only the folders  ?
since mentioning each file wont be feasible against each folder

**Comment by nikhileshmishra** [comment]
sfdx sgd:source:delta -i .pqa-deployignore -i .nonprod-deployignore --output changedsources/ --generate-delta --to HEAD --from AARP-2021-PI-5.2.0.212.TEST

I want 2 ignore 2 files , but its ignoring only 1 file. How can we use the command to ignore both files?

**Comment by nikhileshmishra** [comment]
Thanks for all support so far

**Comment by scolladon** [comment]
Hi @nikhileshmishra !

You're welcome, it is our pleasure to help you having the most of the plug-in, plus it helps other too !

The `-i` parameter can take only one file

In this situation I would concatenate all the ignore file I want to use into one file (`cat file1 file2 fileN > concatFile`) and then use this new file with the plugin command

**Comment by nikhileshmishra** [comment]
Thanks  a lot again for quick solution.
