### ISSUE TITLE
Getting error while deploying

### ISSUE THREAD

**Issue by nikhileshmishra** [scolladon/sfdx-git-delta#201]
I am using below script & its able to generate the package file
but my deploying I m getting error

Below is my script
=====================================
stage('Authorize SalesforceOrgs')
	{
          sh """ 	      
   sfdx force:auth:jwt:grant --instanceurl "${SF_INSTANCE_URL}" --clientid "${clientid}" --username "${username}"  --jwtkeyfile "${server_key_file}" --setdefaultdevhubusername --setalias "${alias}"
      """                     
    }	
 stage('deploy')
  {
	  tag = sh(returnStdout:  true, script: "git describe --tags --abbrev=0 --match AARP-*.PQA HEAD")
          echo tag
    sh """
                                   mkdir changed-sources
                                   sfdx sgd:source:delta --to HEAD --from "${tag}" --output changed-sources/ --generate-delta
                                   cat changed-sources/package/package.xml
                                   sfdx force:source:deploy -x package/package.xml -u "${username}"
	"""
=================================================
I am getting below error 
![image](https://user-images.githubusercontent.com/89146067/140066276-16d08413-f4c7-4490-b192-bd0e91b9cacf.png)
	
	My doubt is same username & approach works when we do full deployments   
	So while deploying package xml for git delta deployments ,do we need to approach diff way to authorize sandbox 1st

**Comment by mehdisfdc** [comment]
Hi @nikhileshmishra 
Thank you for logging your issue. However, this issue does not look related to SGD: the error message you shared indicates that the org configuration missing for the target username.

I suggest you first built a working pipeline without SGD, and then add SGD only when all steps are properly working in your scripts.
