### ISSUE TITLE
PlatformEventSubscriberConfigs not included in package.xml

### ISSUE THREAD

**Issue by pfrandsen** [scolladon/sfdx-git-delta#202]
Issue verification check :

- [ ] does the current repository is fully deployable at the commit sha given to the from parameter of the command ?

## What is the problem

PlatformEventSubscriberConfig is not included in diff.

---

### What is the expected result

A package.xml file with the platformEventSubscriberConfig should be generated.

### What is the actual result

The package.xml file is empty (does not include platformEventSubscriberConfig).

## Steps to reproduce
Create new configuration in force-app/main/default/PlatformEventSubscriberConfigs/, e.g. WorkItemBatch.platformEventSubscriberConfig-meta.xml

```
<?xml version="1.0" encoding="UTF-8"?>
<PlatformEventSubscriberConfig xmlns="http://soap.sforce.com/2006/04/metadata">
    <batchSize>200</batchSize>
    <masterLabel>WorkItemBatchTriggerConfig</masterLabel>
    <platformEventConsumer>WorkItemBatchTrigger</platformEventConsumer>
    <user>user@somedomain.com</user>
</PlatformEventSubscriberConfig>
```

Run sgd and verify that package.xml is empty.

---

## Execution context

---

**Operating System:** Windows 10

**yarn version:** 1.12.1

**node version:** v14.17.3

**git version:** 2.29.1.windows.1

**sfdx version:** sfdx-cli/7.124.0 win32-x64 node-v14.18.1

**sgd plugin version:** 4.9.1

## Optional more information

---

**Comment by scolladon** [comment]
Hi @pfrandsen !

Thanks for this enhancement request and for you help making this plugin better !

We will take care of it in the coming days.

Stay tuned !

**Comment by scolladon** [comment]
Hi @pfrandsen !

Could you test locally the [feature](https://github.com/scolladon/sfdx-git-delta/pull/203) for this ?
You can follow the step from our [CONTRIBUTING.md](https://github.com/scolladon/sfdx-git-delta/blob/master/CONTRIBUTING.md#testing-the-plugin-from-a-pull-request) file to know how to do it !

Thanks in advance !

**Comment by pfrandsen** [comment]
Hi @scolladon - thanx for working on this and apologies for not seeing the comments in this thread sooner. I will check this as soon as possible (need to get to my work computer).

**Comment by pfrandsen** [comment]
Hi @scolladon - I have now built the branch locally and tested the updated plugin - it works perfectly - thanx a lot for your great :-)

**Comment by scolladon** [comment]
New version is published !!
Enjoy

**Comment by pfrandsen** [comment]
Thanx @scolladon :-)
