### ISSUE TITLE
Compare the Branch Issue . It only work with Master to Developer. But when compare from Developer to Feature branch it creating empty package.xml

### ISSUE THREAD

**Issue by rupeshku320** [scolladon/sfdx-git-delta#205]
Issue verification check :

- [Yes ] does the current repository is fully deployable at the commit sha given to the from parameter of the command ?

## What is the problem

Comparing branches is not giving any out put in the package.xml 

### What is parameter and their value you used
sfdx sgd:source:delta --to "Feature_Release" --from "Developer" --output . --loglevel TRACE

### What is the actual result
Package.xml and destructiveChanges.xml has no value of the Classes which has been removed 

## Steps to reproduce

---

## Execution context

---

**Operating System:** …

**yarn version:** …

**node version:** …

**git version:** …

**sfdx version:** …

**sgd plugin version:** …

## Optional more information

---

**Comment by scolladon** [comment]
Hi @rupeshku320 !

Thanks for your help making this plugin better !

Could you provide guidance on how to reproduce this bug please ?
You can fork the [reproduction playground](https://github.com/scolladon/sfdx-git-delta-reproduction-playground) and create a branch to do so !

Thanks

**Comment by rupeshku320** [comment]
Please close the case I need to pull the developer brach again after creating the feature branch and it work

On Nov 15, 2021 2:31 AM, Sebastien ***@***.***> wrote:
CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe. If you are unsure, please forward this email to ***@***.*** for further scrutiny.


Hi @rupeshku320<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Frupeshku320&data=04%7C01%7Cragrawal%40cmcenergy.com%7C79ffbc51c718446a62fa08d9a8125ace%7Cf7fd4f4ab9b240d4b3301f4436c1415e%7C0%7C0%7C637725619072255851%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=vNxd%2Be99vayQxIWoPCVcIXYaPGSKjKoMJc6nCFAqF3A%3D&reserved=0> !

Thanks for your help making this plugin better !

Could you provide guidance on how to reproduce this bug please ?
You can fork the reproduction playground<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fscolladon%2Fsfdx-git-delta-reproduction-playground&data=04%7C01%7Cragrawal%40cmcenergy.com%7C79ffbc51c718446a62fa08d9a8125ace%7Cf7fd4f4ab9b240d4b3301f4436c1415e%7C0%7C0%7C637725619072255851%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=LZfkY1dhnEuJzsHp1o%2Bt31dzdGGM6fuZXWhePaoYWjc%3D&reserved=0> and create a branch to do so !

Thanks

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fscolladon%2Fsfdx-git-delta%2Fissues%2F205%23issuecomment-968649458&data=04%7C01%7Cragrawal%40cmcenergy.com%7C79ffbc51c718446a62fa08d9a8125ace%7Cf7fd4f4ab9b240d4b3301f4436c1415e%7C0%7C0%7C637725619072265808%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=SrJRKtXjZWbiWH8QLP1KGFEHGoi%2BpJaLsQYse95qHQk%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FATJ3RFPNBUFVN4NF4KKR3JDUMDAO5ANCNFSM5IAJFC2A&data=04%7C01%7Cragrawal%40cmcenergy.com%7C79ffbc51c718446a62fa08d9a8125ace%7Cf7fd4f4ab9b240d4b3301f4436c1415e%7C0%7C0%7C637725619072275765%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=IWsGztWtmZ2ugbNc6zYZfUz22niz0b7aLPNPSoOvWeU%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cragrawal%40cmcenergy.com%7C79ffbc51c718446a62fa08d9a8125ace%7Cf7fd4f4ab9b240d4b3301f4436c1415e%7C0%7C0%7C637725619072275765%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=GrYEJXUqqZZqvJsI64IwV8fN7qprCROslVzmedMqb%2F0%3D&reserved=0> or Android<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cragrawal%40cmcenergy.com%7C79ffbc51c718446a62fa08d9a8125ace%7Cf7fd4f4ab9b240d4b3301f4436c1415e%7C0%7C0%7C637725619072285719%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=eeWjwUzghzZXJi%2B3NpZaeOxaUdwVYhIhjCK3bLHgwB0%3D&reserved=0>.

**Comment by scolladon** [comment]
Ok ! good to hear that.

Feel free to raise any issue with the plugin, we will help you !
