### ISSUE TITLE
sfdx sgd:source:delta not able to generate package.xml for Territory2Rule

### ISSUE THREAD

**Issue by AnantSahTeli** [scolladon/sfdx-git-delta#206]
Issue verification check :

- [x] does the current repository is fully deployable at the commit sha given to the from parameter of the command ?

## What is the problem

---
Not able to generate delta package.xml with Territory2Rule  and Territory2Model 

### What is parameter and their value you used

      <types>
        <members>CRM_CP_Global_Sales_Model.DE_CP_Homecare_TM_71111_Region_Nord_Care_01</members>
        <members>CRM_CP_Global_Sales_Model.DE_CP_Homecare_TM_71111_Region_Nord_Care_01_Nutrition</members>
        <name>Territory2Rule</name>
    </types>

### What is the actual result

-->

## Steps to reproduce

---

## Execution context

---

**Operating System:** …Linux

**yarn version:** …

**node version:** … 14,14,0

**git version:** …2.30.0

**sfdx version:** …7.126

**sgd plugin version:** …

## Optional more information

---

**Comment by AnantSahTeli** [comment]
![delta_package_with_territory2Rule](https://user-images.githubusercontent.com/17002256/141792306-b730db89-818f-4771-9f8a-4e35122055dc.png)

**Comment by scolladon** [comment]
Hi @AnantSahTeli !

Thanks for raising this issue !

Could you help us reproduce it?
Using the [reproduction playground](https://github.com/scolladon/sfdx-git-delta-reproduction-playground) please.

**Comment by AnantSahTeli** [comment]
Hi Sebastian,

I tried uploading files, but it seems the upload is disabled and not able
to share any file.

[image: image.png]

Best regards,

Anant Sah Teli
Mobile: +45 9168 1612

**Comment by scolladon** [comment]
What did you want to upload @AnantSahTeli ?

**Comment by AnantSahTeli** [comment]
my repository which contains the structure and files which I am using.

**Comment by scolladon** [comment]
Could you reproduce it in the [reproduction playground](https://github.com/scolladon/sfdx-git-delta-reproduction-playground) ?

**Comment by AnantSahTeli** [comment]
managed to put all cmponent(*) in the package.xml to solve this issue.

**Comment by scolladon** [comment]
Hi @JohanJohanson !

Thanks for commenting here, that the right place if it is related to Territory.
Thanks for providing this context, I'll dig it soon and let you know my findings here !

**Comment by zokito** [comment]
@scolladon I've been working with @JohanJohanson on this and have made a fix for which I will prepare a pull request for if you are interested

**Comment by scolladon** [comment]
@zokito and @JohanJohanson that would be great ! Please be my guest, I'll participate in the review
PS: Just in case you missed it, we have a [CONTRIBUTING](https://github.com/scolladon/sfdx-git-delta/blob/main/CONTRIBUTING.md) guide to help you in the process

**Comment by scolladon** [comment]
Release [5.1.2](https://github.com/scolladon/sfdx-git-delta/releases/tag/v5.1.2) just shipped with the fix for this issue !
