### ISSUE TITLE
SGD is not installed globally causing issue with GitHub Actions through Docker

### ISSUE THREAD

**Issue by TomSesselmann** [scolladon/sfdx-git-delta#208]
Issue verification check :

- [x] does the current repository is fully deployable at the commit sha given to the from parameter of the command ?

## What is the problem

---

SGD plugin is not available in Github Actions through Docker

### What is the actual result

`Warning: sgd:source:delta is not a sfdx command.`

## Steps to reproduce

---

See this issue https://github.com/actions/runner/issues/1474
The workaround is to run
`export HOME=/root && sfdx sgd:source:delta ...`

**Comment by TomSesselmann** [comment]
I'm not too sure, but based on the comments on the other thread it seems to be an issue with the way it is installed compared to other sfdx plugins.

> this runner alters your HOME env-variable from /root to a shared docker mount point /github/home and you have installed sfdx-git-delta to /root/.local/share and not globally.
https://github.com/actions/runner/issues/1474#issuecomment-965749362

**Comment by scolladon** [comment]
I wonder if this issue is showing for any sfdx plugins...
If this is the case then maybe we should notify the sfdx plugin team 🤔 

Have you tried with another plugin ? Same result ?

**Comment by scolladon** [comment]
@TomSesselmann do you still have the issue ?
Does the #211 helps you in this case ?

**Comment by scolladon** [comment]
Closing this issue has it does not seems to be an issue anymore.
Feel free to reopen with more content to investigate
