### ISSUE TITLE
Not able to generate manifest files when running in Github-hosted Runners

### ISSUE THREAD

**Issue by jietan-awareservices** [scolladon/sfdx-git-delta#211]
Issue verification check :

- [X] does the current repository is fully deployable at the commit sha given to the from parameter of the command ?

## What is the problem

When running the sgd command in Github-hosted Runner, the manifest files are not generated.

---

I have created empty package.xml files as placeholders in the repo but they are not updated after the sgd command is executed. It almost seems that the command doesn't pick up the heads. It works in my local machine.

The setup before executing sgd in Github-hosted Runner includes:

- actions/checkout@v2
- actions/setup-node@v1
- sudo apt-get install git
- npm install sfdx-cli
- sfdx plugins:install sfdx-git-delta

I wonder if there are other setups needed for sgd to pick up the commits in Github Actions.

---

### What is parameter and their value you used

$ node_modules/sfdx-cli/bin/run sgd:source:delta --to "HEAD" --from "HEAD^" --output "deploy/"

Other to/from parameters have been tested as well but didn't work

---

### What is the expected result

package.xml file that has list of components

---

### What is the actual result

package.xml file remains unchanged and has no components

---

## Execution context

Github-hosted Runner, uses macOS / Linux, without Docker.

**Comment by scolladon** [comment]
Hi @jietan-awareservices !

Thanks for raising this issue !
I wonder if it is somehow related to #208 ?

What I can see is that the parameter given to sgd assume the repository is located in the current folder.
Is it the case ? Where checkoutv2 clone the repository ?

**Comment by jietan-awareservices** [comment]
@scolladon When I refer to other folders in the repo, it doesn't throw any errors so I assume
`export HOME=/root`
is not required.

I used the docker and the same approach in #208 and it worked. Happy to close the issue unless you'd like me to investigate more.

**Comment by scolladon** [comment]
@jietan-awareservices we can close this issue if you have found a way to make it works

Feel free to investigate more and to provide an elegant way to use the plugin in docker ! Be our guest to create a PR to explain it in the README 😃
