### ISSUE TITLE
v4.11 fail while 4.10 works fine

### ISSUE THREAD

**Issue by niv-goldenberg** [scolladon/sfdx-git-delta#213]
Issue verification check :

- [ ] does the current repository is fully deployable at the commit sha given to the from parameter of the command ? yes

## What is the problem

New delta version 4.11 just crush with the following error:
`{
  "status": 1,
  "result": null
}`

If I revert back to a specific version (4.10) that works again:
`sfdx plugins:install sfdx-git-delta@4.10.0`

We are using this command:
`sfdx sgd:source:delta -t HEAD -f ${{ inputs.previous_commit_sha_alias }} -r . -o . --ignore --json --loglevel debug`

Fedora 34
Node v14.18.1

Thanks

**Comment by scolladon** [comment]
Hi @niv-goldenberg !

Thanks for raising this issue and sorry for this inconvenience.
I tried the commands with version 4.11.0 locally and it worked on my side.

What I can see is that the command used in your case is using `--ignore` parameter without passing any value (which failed on my side). Maybe it is a clue.

Could you send us the minimal context of execution to reproduce the issue in isolation please ?

**Comment by scolladon** [comment]
New version ([4.12.0](https://www.npmjs.com/package/sfdx-git-delta)) available !
