### ISSUE TITLE
SGD Not Adding All Changed Tableau Components to Package.xml

### ISSUE THREAD

**Issue by ninja-momma** [scolladon/sfdx-git-delta#218]
Issue verification check :

- [x] does the current repository is fully deployable at the commit sha given to the from parameter of the command ?

## What is the problem

SGD is not adding all of the changed Tableau components to the package.xml file.  Below is the log from our Jenkins build:

```
+ ls -R changed_sources/force-app
changed_sources/force-app/main/default:
wave

changed_sources/force-app/main/default/wave:
EM_Utilization_comp.wcomp
EM_Utilization_comp.wcomp-meta.xml
Utilization_Dashboard.wdash
Utilization_Dashboard.wdash-meta.xml
Utilization_component.wcomp
Utilization_component.wcomp-meta.xml

reviewing deployment package.xml
[Pipeline] sh
+ cat changed_sources/package/package.xml
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>Utilization_Dashboard</members>
        <name>WaveDashboard</name>
    </types>
    <version>52.0</version>
</Package>
```

### What is parameter and their value you used

`sfdx sgd:source:delta --to HEAD --from d6f7937b68cc90c3b182c3c008601e1abcaa0e9c --output changed_sources --generate-delta --ignore .forceignore_deployment`

### What is the expected result

```
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>Utilization_Dashboard</members>
        <name>WaveDashboard</name>
    </types>
    <types>
       <members>EM_Utilization_comp</members>
       <members>Utilization_comp</members>
       <name>WaveComponent</name>
    </types>
    <version>52.0</version>
</Package>
```

### What is the actual result

```
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>Utilization_Dashboard</members>
        <name>WaveDashboard</name>
    </types>
    <version>52.0</version>
</Package>
```

Only the Utilization_Dashboard was deployed.

## Steps to reproduce

linux-x64

node-v17.1.0

git version 2.11.0

sfdx-cli/7.112.1

sgd plugin version: 4.8.1

**Comment by scolladon** [comment]
Hi @ninja-momma !

Thanks for raising this issue and for helping this plugin to be better !

This metadata is not added in our internal metadata repository, this is why it is not treated.

I had a quick look at the [metadata api documentation](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_wavedashboard.htm) and I have not been able to find it there (I looked from 53.0 to 40.0...) !

Do you know where I can find it so I can include it ?
Or do you know how it behave:
- In which folder it is located ?
- What is the suffix of the file ?
- Does it comes with a `-meta.xml` related file ?

Thanks !

**Comment by scolladon** [comment]
Awesome, that's a great contribution, thank you very much.

I think there are couple of other metadata types that we should also include based on the content of the blog (DiscoveryAIModel and DiscoveryGoal)

We will create a new version integrating this very soon

Stay tuned

**Comment by ninja-momma** [comment]
Thank you so much!  This plugin is a fantastic tool!

**Comment by scolladon** [comment]
New version ([4.12.0](https://www.npmjs.com/package/sfdx-git-delta)) available !
