### ISSUE TITLE
Type Error Class extends value undefined is not a constructor or null

### ISSUE THREAD

**Issue by Kamilsz** [scolladon/sfdx-git-delta#224]
Hi,

Having recently updated the sfdx CLI to version 7.131.0 linux-x64 node-v16.13.1 I started getting the error "Type Error Class extends value undefined is not a constructor or null". The plugin is version 4.11 and is running in a docker image.
![image](https://user-images.githubusercontent.com/3039025/145506201-689741ce-f472-4e5f-8ead-ef458f9eea7e.png)

**Comment by scolladon** [comment]
Hi @Kamilsz !

Thanks for raising this issue.
I can see the sfdx cli is using node v16.
Could you try with node v14 and see if you have the same result ?

**Comment by Kamilsz** [comment]
Hi @scolladon ,

I had problems with installing sf cli on node v14, but running node v17 seemed to help. There was no issue with sgd in that version. Thanks.
