### ISSUE TITLE
package.xml not generating anything in GitHub actions VM 

### ISSUE THREAD

**Issue by jayayy** [scolladon/sfdx-git-delta#225]
Issue verification check :

- [X] does the current repository is fully deployable at the commit sha given to the from parameter of the command ?

## What is the problem

on running  the command sfdx sgd:source:delta --to HEAD --from HEAD^ --output ./output --source ./force-app -d, the package.xml that is generated is empty, that is none of the elements appear. I have changed an apex class, an account field and an email template but none of them are visible in the generated package. Using the -d parameter also does not generate any files in the output folder. 

### What is parameter and their value you used

sfdx sgd:source:delta --to HEAD --from HEAD^ --output ./output --source ./force-app -d

### What is the expected result

<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>DataManager_Activity</members>
        <name>ApexClass</name>
    </types>
    <version>52.0</version>
</Package>

### What is the actual result

<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <version>52.0</version>
</Package>

## Steps to reproduce

Please access this following link to visit the git repo, feel free to make a new .yml there to test the build. https://github.com/jayayy/GitActions/tree/sfdxformat

## Execution context

#23~20.04.1-Ubuntu SMP Fri Nov 19 10:20:52 UTC 2021
1.22.17
v14.18.2
git version 2.34.1
sfdx-cli/7.130.1 linux-x64 node-v14.18.2
sfdx-git-delta 4.11.0

## Optional more information

  Provide the output of those command line :
  $ git diff --name-status --no-renames HEAD^ HEAD
//The command I am trying to run here is throwing an error, as show in the Screenshot below, let me know if there is some issue
![image](https://user-images.githubusercontent.com/87470487/145834916-bc7048a6-cc83-40df-97b9-e824d6aaf9e3.png)

**Comment by scolladon** [comment]
Hi @jayayy !

Thanks for logging this issue !

I think this issue could be fixed on your side by [protecting argument using quote](https://github.com/scolladon/sfdx-git-delta/issues/134).

Could you try this ? Exemple: 
```sh
$ sfdx sgd:source:delta --to "HEAD" --from "HEAD^" --output "./output "--source "./force-app" -d
```

**Comment by jayayy** [comment]
Thanks for the quick response! 
![image](https://user-images.githubusercontent.com/87470487/145842948-7356faa2-b689-494a-b97e-76c67a6687d5.png)
Sadly still no luck, changed an apex class file; can refer the log for the run here[https://github.com/jayayy/GitActions/runs/4508434849?check_suite_focus=true](url)

**Comment by scolladon** [comment]
Maybe it is because you install it using node 16.

Could you try by running node 14 instead ?

**Comment by jayayy** [comment]
Still the same seb! https://github.com/jayayy/GitActions/runs/4508598133?check_suite_focus=true

**Comment by scolladon** [comment]
Ok, then maybe it is an [issue](https://github.com/scolladon/sfdx-git-delta/issues/142) with the `fetch-depth` parameter of the `checkout` github action.

Documentation [here](https://github.com/actions/checkout#:~:text=and%20tags.%0A%20%20%20%20%23%20Default%3A%201-,fetch%2Ddepth%3A%20%27%27,-%23%20Whether%20to%20download)

**Comment by jayayy** [comment]
I'm afraid still an empty package [here](https://github.com/jayayy/GitActions/runs/4508942501?check_suite_focus=true)

**Comment by scolladon** [comment]
I think there is an issue with the current github action implementation:
![Screenshot 2021-12-13 at 17 30 13](https://user-images.githubusercontent.com/522422/145851024-9b3e1d9e-3bb4-4bea-83f0-80fe198f55b6.png)

It seems that the `fetch-depth` parameter is not set for the checkout action in the rbd.yml file
![2021-12-13_17-31-01](https://user-images.githubusercontent.com/522422/145851130-ced75d13-5ccd-49fd-88c6-b29190b1e85e.png)

**Comment by jayayy** [comment]
Hurray! Finally got it working thanks a lot Sebastian for your prompt and quick responses. I’m new to gitactions and hence, the glitch-up. Thanks a lot!
