### ISSUE TITLE
diff between commits not tracked in CI, works locally

### ISSUE THREAD

**Issue by pgonzaleznetwork** [scolladon/sfdx-git-delta#233]
Hi there,

Here's my CI job which uses the sfdx-git-delta plugin

https://github.com/pgonzaleznetwork/salesforce-org/blob/master/.github/workflows/commit-feature-branch.yml

The specific command is

```
- name: 'Create delta packages for new, modified or deleted metadata'
              run: | 
                  mkdir changed-sources
                  sfdx sgd:source:delta --to "HEAD" --from "HEAD^" --output changed-sources/ --generate-delta --source force-app/ 
                  echo "Show changed-sources directory"
                  ls changed-sources
                  cat changed-sources/package/package.xml 
```

The output of this is that the changed-sources folder does NOT have the source-app folder (i.e the actual delta) and the package.xml is empty, as if nothing had changed between commits

![Screenshot 2022-01-02 at 22 43 16](https://user-images.githubusercontent.com/8467087/147891474-194b4a98-f106-4be7-8d1b-80b5c8a1dd04.png)

This is the commit that was done on the branch

https://github.com/pgonzaleznetwork/salesforce-org/commit/5c3dfd28528b8c6771025c80e4d2a48aea7b7819

And here's the action that failed

https://github.com/pgonzaleznetwork/salesforce-org/runs/4686351362?check_suite_focus=true

When I do this locally (i.e changing the apex class and committing locally), the output directory has the delta as expected

![Screenshot 2022-01-02 at 22 51 01](https://user-images.githubusercontent.com/8467087/147891513-b45c21c8-63a4-473e-a414-59fc40e9a938.png)

The branch on the remote repo already existed before I pushed the change. So the push should definitely count as a commit.

Thoughts?

**Comment by scolladon** [comment]
Hi !

Thanks for raising this issue !

Maybe it comes from the `actions/checkout@v2` step parameters in the github action definition used here.
This action only fetch the last commit of the branch, so it cannot evaluate a difference with previous commit.
The [action needs to be told](https://github.com/actions/checkout#fetch-all-history-for-all-tags-and-branches) to have more than the last commit.

Let us know if it helped

**Comment by pgonzaleznetwork** [comment]
That did it, thank you so much! This plugin is pretty amazing, thank you for your contribution!

**Comment by scolladon** [comment]
Thanks a lot ! Happy to provide value
