### ISSUE TITLE
destructive deployment 

### ISSUE THREAD

**Issue by nikhileshmishra** [scolladon/sfdx-git-delta#238]
When there is change in destructiveChanges/destructiveChanges.xml file 
the deployment log shows 0/0  .Is it correct ? Even in sandbox we could see it shows 0/0
How can we check if its doing its destructive change

MDAPI PROGRESS | ������������������������������������������������������������������������������������������������������������������������ | 0/0 Components
MDAPI PROGRESS | ������������������������������������������������������������������������������������������������������������������������ | 0/0 Components

**Comment by nikhileshmishra** [comment]
We are using below command
sfdx force:mdapi:deploy -d changedsources/destructiveChanges --ignorewarnings --targetusername QA

**Comment by mehdisfdc** [comment]
Hi @nikhileshmishra 
Could you elaborate a bit more on your issue?
Do you have an issue with the content of the destructiveChanges.xml created by SGD?
Or does the file content look OK, and you have a general issue/question with the deployment of a destructive change through sfdx force:mdapi:deploy?

**Comment by nikhileshmishra** [comment]
The file destructiveChanges.xml created by SGD looks good & its shows the components deleted .

My question is , when we deploy the destructive components
what can we expect to see in logs & sandbox ?


In my logs , i could see below 0/0 . Is it correct ? 
or it should show the actual number of components deleted. Even in my sandbox ,i see 0/0 components .

![image](https://user-images.githubusercontent.com/89146067/149952976-b2f3f9c0-05d0-4e9f-9bdd-fc7882993a52.png)

**Comment by mehdisfdc** [comment]
@nikhileshmishra The progress bar and the values displayed in the output of the `sfdx force:mdapi:deploy` command are entirely controlled by the Salesforce CLI, so I would suggest logging an issue [there](https://github.com/forcedotcom/cli/issues) (including the detailed step to reproduce the issue) if it shows an incorrect number of deleted components.
