### ISSUE TITLE
Validate pull-request

### ISSUE THREAD

**Issue by Strenget** [scolladon/sfdx-git-delta#240]
Hello!

Thank you for your tool. It's very useful. 
Can I ask for an example of validation pull-request? 
For now I just validate deploy by package.xml, but also I would like to know how I can validate by desctructivePackage.xml that will be related on previous deployment. Does exist some best practice for this?
I use this command to validate deploy with package.xml
"sfdx force:source:deploy --manifest git_delta/package/package.xml --checkonly --targetusername Hub --testLevel RunLocalTest"
And I would like use this one without running all tests again. (We have a very big project)
"sfdx force:mdapi:deploy --manifest git_delta/destructiveChanges/destructiveChanges.xml --checkonly --targetusername Hub"
Is it possible?

Thanks for you advice!

**Comment by mehdisfdc** [comment]
Hi @Strenget. Thank you for your question, it's very relevant!

Until recently there was no easy solution to this problem, but I see that now the `sfdx force:source:deploy` command [now supports](https://developer.salesforce.com/docs/atlas.en-us.sfdx_cli_reference.meta/sfdx_cli_reference/cli_reference_force_source.htm) the following arguments: `--predestructivechanges <filepath> --postdestructivechanges <filepath>`

This is [a recent addition](https://github.com/forcedotcom/cli/issues/188#issuecomment-1019530409) to the CLI, and we haven't tested it yet with SGD.

But in theory it would mean that you could execute both the additive and destructive change in a single deployment, with
`sfdx force:source:deploy --manifest git_delta/package/package.xml --postdestructivechanges git_delta/destructiveChanges/destructiveChanges.xml --checkonly --targetusername Hub --testLevel RunLocalTest`

Could check that solution and let us know if works for your use-case? As always, please test it in a developer sandbox first  :-)

**Comment by Strenget** [comment]
Hi @mehdisfdc it works!!
Thanks a lot :)

**Comment by mehdisfdc** [comment]
Thank you for your feedback @Strenget !
Glad to read this solved your issue, and I think we will soon update the readme with that solution :)
