### ISSUE TITLE
Destructive change deployment failed in sandbox ,but didn't fail the pipeline with error.

### ISSUE THREAD

**Issue by nikhileshmishra** [scolladon/sfdx-git-delta#242]
We had 3 destructive changes in destructiveChanges.xml

In jenkins pipeline , deployment ran with this command
sfdx force:mdapi:deploy -d changedsources/destructiveChanges --ignorewarnings --targetusername PRODSTAGE
deployment passed & went to deploy package,xml

When we checked in sandbox , we saw the destructive deployment failed under deployment status
![image](https://user-images.githubusercontent.com/89146067/152212397-1bf50371-adeb-4688-a718-233ffb29bfa7.png)

My question is ,what needs to be added in script, so that it shd have failed the pipeline as well when it failed in the sandbox.

**Comment by mehdisfdc** [comment]
@nikhileshmishra Could you explain a bit more what are the issue you faced and why you believe this is an issue in the SGD plugin? 

A destructive deployment could fail for many reasons unrelated to SGD (the most likely being that some dependencies with the deleted metadata may still exist in the sources and/or from the target org).

Did you have noticed that the content the destructiveChanges folder what not as expected?

**Comment by nikhileshmishra** [comment]
Content inside destructivechanges were expected
even there was some reason for the failure ,we could identify seeing the error in sandbox.

whats concerning is , if destructive deployment failed at sandbox , it shd have failed the jenkins pipeline job throwing the same error . But it went as success nd went to next stage. I am not sure if it has something to with plugin or need to mention something in script to fail the job.

 We see that, whenever apex class test fails or package.xml deployment fails ,it fails the stage & job.This works as expected 
 But we dont see this in destructive deployments .

 If you have come across to such situations, please share the solution

Thanks a lot for your quick reply.

**Comment by mehdisfdc** [comment]
@nikhileshmishra There are several reasons why a destructive deployment could fail.
IMHO the simplest way to deal with that in your CI/CD pipeline is to make the destructive deployment optional (controlled by a pipeline variable), so that you could disable it and with this specific destructive deployment manually if needed.
Since this is not directly related to SGD I'm closing this issue. But feel free to share the specific scenario that is causing you trouble if are stuck with it.

**Comment by nikhileshmishra** [comment]
Can you please help with syntax for destructive deployment , 
If deployment is failure/unsuccessful  in sandbox , It should not pass that stage and fail the CI/CD PIPELINE

currently ,whether its pass or fail, its passing the stage

we are using this command...its working when success ... plz suggest how to fail the pipelien when it has component error in sandbox

sfdx force:mdapi:deploy -d changedsources/destructiveChanges --ignorewarnings --targetusername QA

**Comment by mehdisfdc** [comment]
@nikhileshmishra I'm not 100% to understand your question and what you are trying to achieve.
If your issue is that the `sfdx force:mdapi:deploy` command returns a success in spite of failing to delete some components, I would suggest to remove the `--ignorewarnings` flag.

**Comment by nikhileshmishra** [comment]
Yes u understood it right, it returns success in spite of failing to delete these components
