### ISSUE TITLE
Can't generate delta from NPM script in Windows "--from was unexpected at this time"

### ISSUE THREAD

**Issue by jonny-harte** [scolladon/sfdx-git-delta#255]
When I try to generate a delta from an NPM script in windows I get the below error message. The same script works fine on Mac.
"--from was unexpected at this time"

### What is parameter and their value you used

`"manifest:generate": "sfdx sgd:source:delta --loglevel trace --to $(git rev-parse HEAD) --from $(git rev-list --max-parents=0 HEAD) --output manifest/changed-sources --source force-app --ignore .forceignore",`

### What is the expected result

Generate a complete manifest off all files in the local project

### What is the actual result

```
--from was unexpected at this time.
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! salesforce-app@1.0.0 manifest:generate: `sfdx sgd:source:delta --loglevel trace --to $(git rev-parse HEAD) --from $(git rev-list --max-parents=0 HEAD) --output manifest/changed-sources --source force-app --ignore .forceignore`
npm ERR! Exit status 255
npm ERR!
npm ERR! Failed at the salesforce-app@1.0.0 manifest:generate script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jonat\AppData\Roaming\npm-cache\_logs\2022-02-28T22_21_50_816Z-debug.log
The terminal process "C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -Command npm run manifest:generate" terminated with exit code: 1.
```

**Comment by jonny-harte** [comment]
I think its because of the `$()` but I don't know how to make it working in windows?

**Comment by scolladon** [comment]
Hi @jonny-harte 

Thanks for this issue !

I think your question is "how to use `$()` linux command substitution in windows ? Right ?

I'm not a windows user, so I tried to google this: "[windows $()](https://www.google.com/search?q=windows+%24()&oq=windows+%24())"
And I found this [link](https://superuser.com/questions/1137190/equivalent-of-bashs-on-windows) which explains how to do it depending which command you have.

Let me know if it helps you.
Tell us if you find an elegant way to do it we should also add it in the README.md

**Comment by scolladon** [comment]
Thanks for coming back to us @jonny-harte !

I think we can close this issue, if you think otherwise feel free to reopen it !
