### ISSUE TITLE
Fail to deploy Experience bundle

### ISSUE THREAD

**Issue by alex9138** [scolladon/sfdx-git-delta#26]
Hello @scolladon,

**Reproduction step :**

Run sgd -d -t HEAD -f $COMMIT_SHA1 -r . -o output with a diff in the experience bundle meta

**Result:**

![image](https://user-images.githubusercontent.com/13768869/83609086-0cf3fb80-a57e-11ea-8be8-3a6499f44409.png)
force-app/main/default/experiences/Employee1.site-meta.xml seems not to be there in output

**Expected Result :**
No error 
file force-app/main/default/experiences/Employee1.site-meta.xml is present in output

**Versions:**
Linux Ubuntu Latest
Node version :
v12.16.3
Npm version :
6.14.5
sfdx-git-delta@3.0.6
3.0.6

**Comment by scolladon** [comment]
Hello,

Thanks for raising this issue.
I think the issue is related to the metadata json file for the version 48.
The API did not replied the Experience Bundle (maybe because it is beta).

I think a fix would be to add it.
I will try this way and update here.

Cheers

**Comment by alex9138** [comment]
Hello, 

Thanks :)

In the spring 20 release note (v 48) : https://releasenotes.docs.salesforce.com/en-us/spring20/release-notes/rn_networks_developers_exp.htm they said experience bundle is now GA (and was in pilot in v 47)

**Comment by scolladon** [comment]
@alex9138 could you test on your side using this version of the app : #27

**Comment by alex9138** [comment]
@scolladon I'm on a windows host ☠️ 
Do you mean that I should npm install on feature/experience-bundle locally & give it a try?

**Comment by scolladon** [comment]
You could clone the repository, do a npm install inside it and then try to use the command line from the repository cloned : 
`
$ node bin/cli <parameters>
`

**Comment by alex9138** [comment]
@scolladon here results with a diff with only one experience bundle file changed (test purpose only) on a ubuntu linux VM.

**Input:**
<pre>
commit 58a4ff438263cd36fc218898678d6d47a50ddd1f (HEAD -> develop)
Author: Alexis Rafesthain <alexis.rafesthain@modis.com>
Date:   Thu Jun 4 02:05:01 2020 -0700

    test sgd

diff --git a/force-app/main/default/experiences/Employee1/views/accountManagement.json b/force-app/main/default/experiences/Employee1/views/accountManagement.json
index 100c1895..6b32784b 100644
--- a/force-app/main/default/experiences/Employee1/views/accountManagement.json
+++ b/force-app/main/default/experiences/Employee1/views/accountManagement.json
@@ -86,7 +86,7 @@
         "renditionMap" : { },
         "type" : "region"
       } ],
-      "renderPriority" : "NEUTRAL",
+      "renderPriority" : "",
       "renditionMap" : { },
       "type" : "component"
     } ],
@@ -116,4 +116,4 @@
   "themeLayoutType" : "Inner",
   "type" : "view",
   "viewType" : "account-management"
-}
\ No newline at end of file
+}
</pre>
**Command:**
<pre>node ../sgd/bin/cli -d -t HEAD -f HEAD^1 -r . -o output 
Error terminating the process during sfdx-git-delta : object null is not iterable (cannot read property Symbol(Symbol.iterator))
(node:37196) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, stat 'force-app/main/default/experiences/Employee1/views/accountManagement.json-meta.xml'
(node:37196) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:37196) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
</pre>

**Versions:**
$ node -v
v12.18.0
npm -v
6.14.4

cat /etc/os-release 
NAME="Ubuntu"
VERSION="20.04 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04 LTS"
VERSION_ID="20.04"

**Comment by scolladon** [comment]
Hi @alex9138 ,

I have reproduced it locally.
Thanks for having tried on your side.

A new version of the branch is ready, you can review the PR #27 and retry locally with this new version of the PR.

Let me know if it is ok on your side !

**Comment by alex9138** [comment]
Hi @scolladon alright from there with given diff. :)

**Comment by scolladon** [comment]
New release [v3.1.0](https://github.com/scolladon/sfdx-git-delta/releases/tag/v3.1.0) !
