### ISSUE TITLE
getting sgd: command not found error ( same pipeline was working fine 13days ago and no change since then )

### ISSUE THREAD

**Issue by alokste** [scolladon/sfdx-git-delta#260]
sudo npm install sfdx-git-delta@latest -g
  git config remote.origin.fetch '+refs/heads/*:refs/remotes/origin/*'
  git fetch --all
  git checkout -b pr
  git --no-pager diff --name-status pr origin/develop
  sgd --to pr --from origin/develop --repo . --output .
  cat package/package.xml     
  shell: /usr/bin/bash -e {0}
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@[3](https://github.com/alokste/ctaprepmockscenario1/runs/5525635324?check_suite_focus=true#step:6:3).[4](https://github.com/alokste/ctaprepmockscenario1/runs/5525635324?check_suite_focus=true#step:6:4).0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated cli-ux@4.9.3: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.

added 327 packages, and audited 328 packages in 1[5](https://github.com/alokste/ctaprepmockscenario1/runs/5525635324?check_suite_focus=true#step:6:5)s

20 packages are looking for funding
  run `npm fund` for details

10 vulnerabilities (7 moderate, 3 high)

npm notice 
To address issues that do not require attention, run:
npm notice New minor version of npm available! 8.3.1 -> 8.5.4
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v8.5.4>
npm notice Run `npm install -g npm@8.5.4` to update!
npm notice 
Fetching origin
From https://github.com/alokste/ctaprepmockscenario1
 * [new branch]      develop       -> origin/develop
 * [new branch]      feature-todel -> origin/feature-todel
 * [new branch]      hofix         -> origin/hofix
 * [new branch]      main          -> origin/main
 * [new branch]      release       -> origin/release
Switched to a new branch 'pr'
D	force-app/main/default/classes/GeocodingService.cls
D	force-app/main/default/classes/GeocodingService.cls-meta.xml
/home/runner/work/_temp/ccd511c3-cc4f-4a97-90bc-89be45cdf14b.sh: line [6](https://github.com/alokste/ctaprepmockscenario1/runs/5525635324?check_suite_focus=true#step:6:6): sgd: command not found
Error: Process completed with exit code 12[7](https://github.com/alokste/ctaprepmockscenario1/runs/5525635324?check_suite_focus=true#step:6:7).

**Comment by scolladon** [comment]
Hi @alokste 

Thanks for raising this.
This situation is expected, the command sgd has been declared obsolete since version [4.2.0](https://github.com/scolladon/sfdx-git-delta/blob/main/CHANGELOG.md#changelog-1) and has been deprecated since version [5.0.0](https://github.com/scolladon/sfdx-git-delta/blob/main/CHANGELOG.md#500-2022-03-11).

It means you have two choices here:

1. Migrate to the sfdx plugin [installation](https://github.com/scolladon/sfdx-git-delta#install-as-a-salesforce-cli-plugin-sgdsourcedelta) and [usage](https://github.com/scolladon/sfdx-git-delta#how-to-use-it). All the parameters and behaviour are the same it should not change you at all
2. Keep using the latest version 4: `$ npm install sfdx-git-delta@^4.x.x`

Let us know if you still have an issue.
I hope you will move to the version 5 and benefit from all its benefits 😃

**Comment by alokste** [comment]
Thanks @scolladon , looks like version 5 needs nodejs verion > 14 ,hence I am getting below error . Is there any github actions which installs nodejs version 14 or above. Looks like sfdx-actions/setup-sfdx@v1 installs version 12 of nodejs.

7s
Run sfdx-actions/setup-sfdx@v[1](https://github.com/alokste/ctaprepmockscenario1/runs/5528743865?check_suite_focus=true#step:3:1)
8s
Run echo 'y' | sfdx plugins:install sfdx-git-delta
Finished digital signature check.
This plugin is not digitally signed and its authenticity cannot be verified. Continue installation y/n?: Installing plugin sfdx-git-delta... yarn add v[1](https://github.com/alokste/ctaprepmockscenario1/runs/5528743865?check_suite_focus=true#step:4:1).22.10
Installing plugin sfdx-git-delta... info No lockfile found.Installing plugin sfdx-git-delta... [1/4] Resolving packages...Installing plugin sfdx-git-delta... [2/4] Fetching packages...Installing plugin sfdx-git-delta... info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.Installing plugin sfdx-git-delta... failed
warning sfdx-git-delta > @salesforce/command > cli-ux@4.9.3: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
warning sfdx-git-delta > @salesforce/core > jsforce > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning sfdx-git-delta > @salesforce/core > jsforce > request > har-validator@5.1.5: this library is no longer supported
warning sfdx-git-delta > @salesforce/core > jsforce > request > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
error sfdx-git-delta@5.0.0: The engine "node" is incompatible with this module. Expected version ">=14.6.0". Got "12.[18](https://github.com/alokste/ctaprepmockscenario1/runs/5528743865?check_suite_focus=true#step:4:18).3"
error Found incompatible module.
    Error: yarn add sfdx-git-delta@latest --non-interactive 
    --mutex=file:/home/runner/.local/share/sfdx/yarn.lock 
    --preferred-cache-folder=/home/runner/.cache/sfdx/yarn --check-files 
    exited with code 1
Error: Process completed with exit code 1.

**Comment by scolladon** [comment]
Yes, @alokste !

Here is an extract of what we do in our CI/CD:

```yaml
	# Step definition before this line
    runs-on: ubuntu-latest
    steps:
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Install SFDX CLI
        run: npm install -g sfdx-cli

      - name: Install SGD
        run: sfdx plugins:install sfdx-git-delta

	  # Then you can do your checks ...
	  - name: Checkout sources
        uses: actions/checkout@v2
```

**Comment by alokste** [comment]
closed

**Comment by scolladon** [comment]
You're welcome !

Glad it helped you
