### ISSUE TITLE
How to avoid SGD from interpreting github workflows files ?

### ISSUE THREAD

**Issue by alokste** [scolladon/sfdx-git-delta#261]
The deployment fails with error : Error  PROD_DEPLOY_Pipeline.yml  An object 'PROD_DEPLOY_Pipeline.yml' of type Workflow was named in package.xml, but was not found in zipped directory

The package from the SGD command : sfdx sgd:source:delta --to "HEAD" --from "$prev_commit_sha" --repo . --output . 

It was working fine with older version of sgd 4.x 

Generated Package.xml 

<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>Assignment__c.Description__c</members>
        <members>Assignment__c.Gap__c</members>
        <members>Assignment__c.Planned_End_Date__c</members>
        <members>Assignment__c.Planned_Start_Date__c</members>
        <name>CustomField</name>
    </types>
    <types>
        <members>Assignment__c</members>
        <name>CustomObject</name>
    </types>
    <types>
        <members>Assignment__c.All</members>
        <name>ListView</name>
    </types>
    <types>
        <members>PROD_DEPLOY_Pipeline.yml</members>
        <name>Workflow</name>
    </types>
    <version>54.0</version>
</Package>--- destructiveChanges.xml generated with deleted metadata ---
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <version>54.0</version>
</Package>

**Comment by scolladon** [comment]
Hi @alokste !

Thanks for raising this issue.
It is interesting, could you provide use the minimal data context to be able to reproduce please ?

**Comment by scolladon** [comment]
I think I know what happened here @alokste 

The `PROD_DEPLOY_Pipeline.yml` is in a `workflow` folder.
Hence it has been interpreted by sgd because it is part of the diff.

One way to avoid this behaviour is to use [`--source (-s)` parameter](https://github.com/scolladon/sfdx-git-delta#scoping-delta-generation-to-a-specific-folder). It will tell sgd what is the folder in the repo to focus on for sources.

**Comment by alokste** [comment]
1. Added an object to the sfdx project
2. Modified the yml file inside the .github>workflow folder - PROD_DEPLOY_Pipeline.yml
3. push both the above changes to the git repo branch > Main
4. The deployment on PROD_DEPLOY_Pipeline.yml got triggered

Expected : the yml files being inside the .github > workflow folder should not have been picked up for packaging and deployment
Actual : the PROD_DEPLOY_Pipeline.yml was also included the package.xml as a Workflow and hence the deployment failed.

The failed run can be referred here : https://github.com/alokste/ctaprepmockscenario1/actions/runs/1979883763
Also attaching the snapshot of the .github folder structure
[.github.zip](https://github.com/scolladon/sfdx-git-delta/files/8244089/default.github.zip)
![ymlfiles](https://user-images.githubusercontent.com/6496615/158158228-8e52f6a9-9c66-43cc-b555-26fa7aa5203b.JPG)

**Comment by alokste** [comment]
thank you .. resolved with the --source

**Comment by Julian88Tex** [comment]
@scolladon  Can multiple folders be specified in source parameter? I ran into this issue and our repo needs to look for changes in two different folder locations.

**Comment by scolladon** [comment]
It is not possible to specify multiple path in the `source` parameter yet.
It takes only one path
![Screen Shot 2022-10-26 at 18 19 01](https://user-images.githubusercontent.com/522422/198080337-660e6183-d5a6-4def-9a3c-ac23ecc56fc3.png)

**Comment by scolladon** [comment]
Yes, you can exclude folder using [--ignore or --ignore-destructive](https://github.com/scolladon/sfdx-git-delta#exclude-some-metadata-only-from-destructivechangesxml)

**Comment by Julian88Tex** [comment]
@scolladon thanks, can that be multiple paths?

**Comment by Julian88Tex** [comment]
Got it thanks <3
