### ISSUE TITLE
When custom object metadata changes, master detail field is not copied to output

### ISSUE THREAD

**Issue by denisab85** [scolladon/sfdx-git-delta#263]
Issue verification check :

- [x] is the current repository fully deployable at the commit sha given to the from parameter of the command ?

## What is the problem
When custom object metadata changes, master detail field is not copied to output.
The use case and the issue it causes is described in this KB article: ['Cannot set sharingModel to ControlledByParent on a CustomObject without a MasterDetail relationship field' error](https://help.salesforce.com/s/articleView?id=000334872&type=1)

### What is parameter and their value you used

`sfdx  sgd:source:delta -t 3ff46f9fa87a17a1e704f903f2f38a6805aaf6c0 -f 12acf61ce1b78587a1b424c079aa77f69836c98d -d`

In a sample org, an MC_Email_Notification__c object has a custom field Case__c of type MasterDetail.
```
<?xml version="1.0" encoding="UTF-8"?>
<CustomObject xmlns="http://soap.sforce.com/2006/04/metadata">
    ...
    <allowInChatterGroups>true</allowInChatterGroups>
    <compactLayoutAssignment>SYSTEM</compactLayoutAssignment>
    <deploymentStatus>Deployed</deploymentStatus>
    <description>Used for email notification to client thru MC</description>
    <enableActivities>true</enableActivities>
    <enableBulkApi>true</enableBulkApi>
    <enableFeeds>false</enableFeeds>
    <enableHistory>true</enableHistory>
    <enableLicensing>false</enableLicensing>
    <enableReports>true</enableReports>
    <enableSearch>true</enableSearch>
    <enableSharing>true</enableSharing>
    <enableStreamingApi>true</enableStreamingApi>
    <externalSharingModel>ControlledByParent</externalSharingModel>
    <label>MC Email Notification</label>
    <nameField>
        <displayFormat>EmailNotification {0000}</displayFormat>
        <label>MC Email Notification Name</label>
        <trackHistory>false</trackHistory>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MC Email Notifications</pluralLabel>
    <searchLayouts></searchLayouts>
    <sharingModel>ControlledByParent</sharingModel>
    <visibility>Public</visibility>
</CustomObject>
```

```
<?xml version="1.0" encoding="UTF-8"?>
<CustomField xmlns="http://soap.sforce.com/2006/04/metadata">
    <fullName>Case__c</fullName>
    <externalId>false</externalId>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>MC Email Notifications</relationshipLabel>
    <relationshipName>MC_Email_Notifications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <trackHistory>false</trackHistory>
    <trackTrending>false</trackTrending>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>false</writeRequiresMasterRead>
</CustomField> 
```

The only change in the 'to' commit is a space character added in the MC_Email_Notification__c.object-meta.xml file.

### What is the expected result

File ./fields/Case__c.field-meta.xml should be copied to the output folder.

### What is the actual result

Only the MC_Email_Notification__c.object-meta.xml file itself is copied to the output folder.

## Steps to reproduce

---

1. Identify any custom object that has a filed of type MasterDetail.
2. Make any change to that custom object metadata XML.
3. Make a commit with that change.
4. Run the plugin for the commit.

## Execution context

---

**Operating System:** Windows 10

**yarn version:** 1.22.17

**node version:** v16.13.2

**git version:** 2.34.1.windows.1

**sfdx version:** 7.138.1

**sgd plugin version:** 5.0.0

## Optional more information

---

```
PS C:\Projects\Salesforce\advisorportal-sfdx> git diff --name-status --no-renames 12acf61ce1b78587a1b424c079aa77f69836c98d 3ff46f9fa87a17a1e704f903f2f38a6805aaf6c0 
M       force-app/main/default/objects/MC_Email_Notification__c/MC_Email_Notification__c.object-meta.xml
```

**Comment by scolladon** [comment]
Hi @denisab85 !

Thanks for raising this issue.
It looks like a regression from the performance refactoring because we included this "feature" [previously](https://github.com/scolladon/sfdx-git-delta/commit/929608085daaace1cc8416e3a9982f29342ef151).

I'll do some test this week to:
- try to reproduce it / isolate it
- detect when this regression has been inserted
- fix it
- add robust tests case to detect future regression

**Comment by scolladon** [comment]
Hi @denisab85 the release 5.0.2 contains the fix for this bug! 
Enjoy and thanks for raising it !
