### ISSUE TITLE
5.0.3 version introduced bug on document metadata

### ISSUE THREAD

**Issue by arafesthain** [scolladon/sfdx-git-delta#270]
Issue verification check :

- [x] does the current repository is fully deployable at the commit sha given to the from parameter of the command ?

## What is the problem
Only document xml metadata is present inside a document folder in version 5.0.3
![image](https://user-images.githubusercontent.com/13768869/159345220-90565f3c-a50d-4f61-9f12-f5b0dcfa2de1.png)

![image](https://user-images.githubusercontent.com/13768869/159345592-490a86d8-a34a-4883-99e1-e31aa8e6896d.png)

## Expected Results (like in version 5.0.2)

![image](https://user-images.githubusercontent.com/13768869/159345352-999b3a35-39b9-4a44-9550-25f8937d36be.png)

Command used:
` sfdx sgd:source:delta -d -t HEAD -f 2022_GR2.1_MARKETING -r /home/vsts/work/1/salesforce_repo -i /home/vsts/work/1/salesforce_repo/.forceignore -o output`

**Comment by scolladon** [comment]
Hi @arafesthain 

Thanks for raising this issue.
It is an issue with the new way to get diff from git not explicitly parsing binary file.

We will ship a new version very soon to fix this.

**Comment by scolladon** [comment]
Quick question here.

Imagine you just change the png file.
Per exemple just `Action_Required.png`

What do you expect to be able to deploy a delta generated sources from the plugin: 

1. Just the png file _(the actual behaviour of the plugin)_
2. The png file and the associated `document-meta.xml` file _(My local tests make me think it should be this)_
3. The whole folder _(I don't think so)_

**Comment by arafesthain** [comment]
> Quick question here.
> 
> Imagine you just change the png file.
> Per exemple just `Action_Required.png`
> 
> What do you expect to be able to deploy a delta generated sources from the plugin: 
> 
> 1. Just the png file _(the actual behaviour of the plugin)_
> 2. The png file and the associated `document-meta.xml` file _(My local tests make me think it should be this)_
> 3. The whole folder _(I don't think so)_
> 
> PR #271 ready for review/testing @arafesthain if you have time

Hi there, Thanks for the quick reply, point 2 for me :)
Don't remember if you put the steps somewhere to compile the package locally?

**Comment by scolladon** [comment]
Yes, we did add steps to run the plugin from sources [here](https://github.com/scolladon/sfdx-git-delta/blob/main/CONTRIBUTING.md#testing-the-plugin-from-a-pull-request)

**Comment by arafesthain** [comment]
@scolladon unable to use sgd command after following these steps.
I ran all commands listed in your doc from my sgd local repo (and all commands ran well)
Then going back into my source repo (not sgd one) and running `sfdx sgd:source:delta....`, I got " Warning: sgd is not a sfdx command."

**Comment by arafesthain** [comment]
same error after running yarn install sucessfully.

**Comment by scolladon** [comment]
I think there maybe an issue with the globally installed version of prettier in your environment and the way we are prettifying the README.md

To unblock you just remove `; prettier --write README.md` part of the `postpack` script in the `package.json` file

**Comment by arafesthain** [comment]
@scolladon GO for the pull request :) working fine from here
