### ISSUE TITLE
bug: Malformed CustomLabels.labels-meta.xml generated

### ISSUE THREAD

**Issue by denisab85** [scolladon/sfdx-git-delta#273]
Issue verification check :

- [ ] does the current repository is fully deployable at the commit sha given to the from parameter of the command ?
No. It's a minimalistic set of files sufficient to reproduce the issue.

## What is the problem

---

When running delta with a `-d` argument, the `CustomLabels.labels-meta.xml` file is generated, but its content is malformed.

### What is parameter and their value you used

`sfdx sgd:source:delta -t 64b2d48d67178ffbd41e0acb85f7e56f05045ab9 -f 43044842b1ca1ae77a52d9ae358f10cb2d26f3c7 -d`

### What is the expected result

```
<?xml version="1.0" encoding="UTF-8"?>
<CustomLabels xmlns="http://soap.sforce.com/2006/04/metadata">
    <labels>
        <fullName>Full Name</fullName>
        <language>en_US</language>
        <protected>false</protected>
        <shortDescription>Short Description</shortDescription>
        <value>Value</value>
    </labels>
</CustomLabels>
```

### What is the actual result

```
<?xml version="1.0" encoding="utf-8"?>
<0>&lt;</0>
<1>?</1>
<2>x</2>
<3>m</3>
<4>l</4>
<5> </5>
<6>v</6>
<7>e</7>
<8>r</8>
<9>s</9>
<10>i</10>
<11>o</11>
<12>n</12>
<13>=</13>
<14>&quot;</14>
<15>1</15>
<16>.</16>
<17>0</17>
<18>&quot;</18>
<19> </19>
<20>e</20>
<21>n</21>
<22>c</22>
<23>o</23>
<24>d</24>
<25>i</25>
<26>n</26>
<27>g</27>
<28>=</28>
<29>&quot;</29>
<30>u</30>
<31>t</31>
<32>f</32>
<33>-</33>
<34>8</34>
<35>&quot;</35>
<36>?</36>
<37>&gt;</37>
<38>
</38>
<39>[</39>
<40>o</40>
<41>b</41>
<42>j</42>
<43>e</43>
<44>c</44>
<45>t</45>
<46> </46>
<47>O</47>
<48>b</48>
<49>j</49>
<50>e</50>
<51>c</51>
<52>t</52>
<53>]</53>
```

## Steps to reproduce

---

1. Unzip the attached file
2. `cd` to the unzipped folder
3. Run `sfdx sgd:source:delta -t 64b2d48d67178ffbd41e0acb85f7e56f05045ab9 -f 43044842b1ca1ae77a52d9ae358f10cb2d26f3c7 -d`

## Execution context

---

**Operating System:** Windows 10

**yarn version:** 1.22.17

**node version:** v16.13.2

**git version:** 2.34.1.windows.1

**sfdx version:** 7.138.1

**sgd plugin version:** 5.0.2

## Optional more information

---

  Provide the output of those command line :
  $ git diff --name-status --no-renames <from> <to>
```
PS C:\Projects\Salesforce\sample> git diff --name-status --no-renames 43044842b1ca1ae77a52d9ae358f10cb2d26f3c7 64b2d48d67178ffbd41e0acb85f7e56f05045ab9
A       force-app/main/default/labels/CustomLabels.labels-meta.xml
```
  And for each SharingRule, WorkflowRule and CustomLabel files :
  $ git diff --no-prefix <from> <to> -- <file-path>

```
PS C:\Projects\Salesforce\sample> git diff --no-prefix 43044842b1ca1ae77a52d9ae358f10cb2d26f3c7 64b2d48d67178ffbd41e0acb85f7e56f05045ab9 ./force-app/main/default/labels/CustomLabels.labels-meta.xml   
diff --git force-app/main/default/labels/CustomLabels.labels-meta.xml force-app/main/default/labels/CustomLabels.labels-meta.xml
new file mode 100644
index 0000000..0294b1e
--- /dev/null
+++ force-app/main/default/labels/CustomLabels.labels-meta.xml
@@ -0,0 +1,10 @@
+<?xml version="1.0" encoding="UTF-8"?>
+<CustomLabels xmlns="http://soap.sforce.com/2006/04/metadata">
+    <labels>
+        <fullName>Full Name</fullName>
+        <language>en_US</language>
+        <protected>false</protected>
+        <shortDescription>Short description</shortDescription>
+        <value>Value</value>
+    </labels>
+</CustomLabels>
\ No newline at end of file
``
[sample.zip](https://github.com/scolladon/sfdx-git-delta/files/8326974/sample.zip)
`

**Comment by scolladon** [comment]
Hi @denisab85 !

Thanks for raising this issue.

Could you try with the last version of the plugin (version 5.0.4) and see if you still have the issue ?
I think it has been solved with the version 5.0.3, feel free to reopen this issue if you still have it.

In the mean time I will push a fix for the Custom Label xml header generation

**Comment by denisab85** [comment]
Tested @v5.0.5, the file looks good now.
However, I noticed that the formatting of the `CustomLabels.labels-meta.xml` file is changed during the operation, which leads to removed space characters inside text tags' content. E.g.:

![image](https://user-images.githubusercontent.com/16647044/159776416-7c951c0f-873a-409c-808e-d26dcc2874a2.png)

This might represent an issue if those strings are to be concatenated.

**Comment by scolladon** [comment]
I think this is ok because it mimics the behaviour of the metadata API (thankfully !!)

I tried on a fresh environment and it is not possible to add white char in front and at the end of a Custom Label 
* When creating a custom label from the setup
* When pushing a custom label from sources (retrieve it right after pushing it and the value will be trimmed)

IMHO it seems possible to have trailing whitespace in sources only when creating the value of the custom label from the sources and never retrieve/pull it after having pushed them.

**Comment by denisab85** [comment]
Makes sense. Thanks for checking.
