### ISSUE TITLE
package.xml ordering different between Mac & Windows

### ISSUE THREAD

**Issue by jonny-harte** [scolladon/sfdx-git-delta#278]
Issue verification check:

- [x] is the current repository fully deployable at the commit SHA provided with the 'from' parameter of the command?

## What is the problem?

We are trying to use the package.xml from the delta to keep the manifest package up to date as well as deployments. However, 
the order of the package.xml file appears to be different depending on whether you run the command on Windows or Mac. This is making it hard to spot genuine updates in PR's.

![Screenshot 2022-03-28 at 3 34 30 pm](https://user-images.githubusercontent.com/6071669/160422111-042cbdd6-ee88-451d-bd67-f240c27984c9.png)

### What is the parameter and the value you used with it?

`mkdir \"manifest/changed-sources\" ; sfdx sgd:source:delta --api-version=54 --loglevel trace --to \"HEAD\" --from $(git rev-list --max-parents=0 HEAD) --output \"manifest/changed-sources\" --source force-app --ignore .forceignore ; rm \"manifest/package.xml\" ; mv \"manifest/changed-sources/package/package.xml\" \"manifest/package.xml\" ; rm -R \"manifest/changed-sources\" ; prettier --write \"manifest/package.xml\"`

### What is the expected result?

Consistent package.xml order regardless of where it has been run.

### What is the actual result?

Types & Members are in a different order creating large diff's between commits.

**Operating System:** …
Windows 11, macOS Monterey

**node version:** …
v17.8.0

**git version:** …
git version 2.32.0 (Apple Git-132)

**sfdx version:** …
sfdx-cli/7.142.1 darwin-x64 node-v16.14.0

**sgd plugin version:** 
5.0.3

**Comment by scolladon** [comment]
Hi @jonny-harte !

Thanks for raising this issue and for your interest in the plugin !
I totally get your point, it should behave the same whatever environment in runs into

I am not able to reproduce it locally easily (no vm at hand neither windows environment)

I have a clue for the reasons of this behaviour discrepancy between windows and linux so I have created a PR #279 .
Could you [test](https://github.com/scolladon/sfdx-git-delta/blob/main/CONTRIBUTING.md#testing-the-plugin-from-a-pull-request) it and let us know if it fixed the issue?

**Comment by jonny-harte** [comment]
Thanks @scolladon just done a test using v5.0.6 on the same Mac & Windows machines and the package.xml is now consistent.

**Comment by scolladon** [comment]
Hum that's weird
We have not released the fix yet...
You tested with the PR #279 content ? (following those [steps](https://github.com/scolladon/sfdx-git-delta/blob/main/CONTRIBUTING.md?rgh-link-date=2022-03-28T17%3A42%3A27Z#testing-the-plugin-from-a-pull-request))

**Comment by jonny-harte** [comment]
Sorry thought 5.0.6 was the version in the PR, but updating both to that seems to have fixed it. Is there a way to test the PR without installing yarn?

**Comment by scolladon** [comment]
I think it is possible to test the PR without `yarn`, just replace `yarn` command with `npm run`, though I've never tried and I'm not sure at all it would work (all the tooling for sfdx plugin use yarn, maybe there is a reason behind that)
