### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'prototype')

### ISSUE THREAD

**Issue by JSaterdalen** [scolladon/sfdx-git-delta#285]
Issue verification check:

- [ ] is the current repository fully deployable at the commit SHA provided with the 'from' parameter of the command?

## What is the problem?

Running any sgd command fails with the following error: 

`TypeError: Cannot read properties of undefined (reading 'prototype')`

### What is the parameter and the value you used with it?

`sfdx sgd:source:delta -f a12892586e1ebbb32e54b234ee451dd19596249a -o _output`

### What is the expected result?

Would expect to have a package.xml created in the _output directory.

### What is the actual result?

Error message from above. 

## Steps to reproduce

---

## Execution context

**Operating System:** Darwin Kernel Version 21.4.0: Fri Mar 18 00:47:26 PDT 2022; root:xnu-8020.101.4~15/RELEASE_ARM64_T8101

**yarn version:** 1.22.18

**node version:** v16.13.0

**git version:** 2.35.1

**sfdx version:** sfdx-cli/7.144.2 darwin-x64 node-v16.14.2

**sgd plugin version:** 5.1.2

**Comment by JSaterdalen** [comment]
Uninstalling and reinstalling the plugin seems to have resolved my issue.

**Comment by scolladon** [comment]
Hi @JSaterdalen !

Glad to see you managed it by yourself.

Thanks for updating the issue on your own, really appreciated!

Safe incremental sfdx deployment!
