### ISSUE TITLE
Packages containing territory only changes do not get to Salesforce

### ISSUE THREAD

**Issue by shkalantaryCL** [scolladon/sfdx-git-delta#290]
Issue verification check:

- [ ] is the current repository fully deployable at the commit SHA provided with the 'from' parameter of the command?

## What is the problem?

---
We have observed that the deployment on packages with only changes to territory do not get along to Salesforce , even though the build status is successful in Jenkins but the request is not sent to SF. However , if we have changes to other components in addition to the territories in the same build , then only the build reflects on SF UI. But even in the second scenario the  changes to territory component do not get deployed/ reflected on the target org.

### What is the parameter and the value you used with it?

mkdir sfdx-delta
 sudo sfdx sgd:source:delta --to 'commit id' --from 'previous commit id' --output sfdx-delta --generate-delta

### What is the expected result?
sample of a delta package containing both territory & other changes :
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>Account-PMGS-WLS-IC-Advisor Accounts</members>
        <members>Account-WLS-IC-Advisor Accounts</members>
        <name>Layout</name>
    </types>
    <types>
        <members>Advanced_Advisor_Practices.territory2</members>
        <name>Territory2Model</name>
    </types>
    <version>53.0</version>
</Package>

### What is the actual result?

actual and expected delta package generated on the Jenkins output log are same & look good.

## Steps to reproduce

1. make a change to territory component on feature branch
2. create a PR from the feature branch to the main branch and merge
3. trigger the Jenkins job
4. Watch the output log

**Operating System:** Windows 10

**yarn version:** …

**node version:** …

**git version:** 2.24.4

**sfdx version:** 7.108.0

**sgd plugin version:** …

**Comment by scolladon** [comment]
Hi @shkalantaryCL 

Thanks for raising this issue, thanks for your interest in the plugin and for your help to improve it.

Per the description of this issue, the plugin seems to be do its job fine (generating xml files and delta files).
I found one fixed issue related to what you described in the [sfdx-cli](https://github.com/forcedotcom/cli/issues/1147)

I have couple questions:
* What is the command and the parameters you use to deploy territory metadata?
* Do you have this issue using this command even from the whole sources of you repository? (without using incremental generation with the plugin)

**Comment by scolladon** [comment]
@shkalantaryCL closing this issue as it may be related to a solved known issue and it has been open for a very long time
Feel free to reopen it with more information
