### ISSUE TITLE
Copy object definition with "--generate-delta" or add ann option

### ISSUE THREAD

**Issue by JorneVL** [scolladon/sfdx-git-delta#294]
### Is your proposal related to a problem?
Partially, I have the issue when uploading the difference to Gearset.
I use the --generate-delta option for creating a new folder that I upload with Gearset.
Gearset needs the "object-meta.xml" files in the Object folder so they know that they need to compare that object.

For example I have added a field to Opportunity in a comparison, SGD creates an empty folder Opportunity with a subfolder fields with one file.

### Describe a solution you propose
Is it possible to copy the object-meta.xml from the 'source' folder so this issue won't occur?
Maybe with adding an extra command line option.

### Describe alternatives you've considered
I don't found any automatic alternative.

**Comment by scolladon** [comment]
Hi @JorneVL 

I don't think we want to manage this situation in the plugin, for multiple reasons:
- Not adding the `object-meta.xml` file is ok from a pure incremental deployment standpoint
- Adding a parameter would be working just for people using gearset to deploy, which will couple the plugin to gearset
- It is possible to handle it via post processing using a script

I have question though! 
Why gearset needs this `object-meta.xml` file in this case?
If considerable, have you tried to ask them to remove this requirement?

Here is a bash script I would use in your situation (may be adapted to your environment)
```sh
#!/usr/bin/env bash

# object folder path
objectsPath=$1 
# sgd output
output=$2

OBJECT_META_XML="object-meta.xml"

for folder in $output/$objectsPath/*/; do
    objectName=$(basename "$folder")
    if [ -d "$folder" ] && [ "$(ls -A  $folder)" ] && [ -f "$objectsPath/$objectName/$objectName.$OBJECT_META_XML" ]; then 
        cp -v "$objectsPath/$objectName/$objectName.$OBJECT_META_XML" "$output/$objectsPath/$objectName/"
    fi
done
```

You can use it this way (assuming it is called `script.sh`and is has been turned into an executable using `chmod u+x script.sh`):
```sh
# first parameter is the path to the object folder
# second parameter is the output folder of sgd
$ ./script.sh force-app/main/default/object output
```

**Comment by JorneVL** [comment]
Hi @scolladon,

That is clear. I have communicated with Gearset.
But I understand you don't want this in this plugin.

Thank you for the script!
I will indeed solve this outside both systems.

Kind regards,
Jorne

**Comment by scolladon** [comment]
Thanks for your understanding and thanks for your interest in the plug-in !

If you don't mind @JorneVL, could you explain us your workflow with gearset please ? I'm curious 😁

**Comment by JorneVL** [comment]
@scolladon I tried some ways to improve the comparisons, but the workflow is not working. Gearset has other requirements.
