### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'prototype')

### ISSUE THREAD

**Issue by deckblad** [scolladon/sfdx-git-delta#296]
Running the following command:
`sfdx sgd:source:delta`

Results in the following error:
`TypeError: Cannot read properties of undefined (reading 'prototype')`

This happens regardless of arguments. I had just updated all plugins to latest. I am using your latest version.

`
$ sfdx plugins
sfdmu 4.13.4
sfdx-essentials 2.12.0
sfdx-git-delta 5.2.0
sfdx-hardis 2.85.1
sfpowerkit 4.2.5
shane-sfdx-plugins 4.43.0
├─ @mshanemc/plugin-streaming 1.1.7
└─ @mshanemc/sfdx-sosl 1.1.0
texei-sfdx-plugin 1.14.4
`
Windows 10

**yarn version:** 1.22.18

**node version:** v16.15.0

**git version:** git version 2.20.1.windows.1

**sfdx version:** sfdx-cli/7.147.1 win32-x64 node-v16.14.2

**sgd plugin version:** 5.2.0

**Comment by scolladon** [comment]
Thanks for letting us know !
I hope it helped with this [issue](https://github.com/hardisgroupcom/sfdx-hardis/issues/230)

Happy sfdx incremental deployment !
