### ISSUE TITLE
Error Installing the SGD Delta Plugin

### ISSUE THREAD

**Issue by anandsecured** [scolladon/sfdx-git-delta#298]
Apologies for not following the given template to raise issues. As I feel I don't have all information needed as per template and issue got resolved now and I need to know how it got resolved. Appreciate your help and amazing work you did with this plugin

We use SGD plugin in our Jenkins CICD pipline and today for some reasons delta plugin was not working and while installing we were getting error and some time back mysteriously this error disappeared. Can you please shed some light on why this error occurred and how it got resolved. It would he helpful for our RCA. 
I referred earlier issue reported for same problem and we were trying to implement the solution provided in the ticket but somehow this issue got resolved.

Below is the error we got during the plugin installation
  
Installing plugin sfdx-git-delta... info There appears to be trouble with your network connection. Retrying...Installing plugin sfdx-git-delta... info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.Installing plugin sfdx-git-delta... failed
error An unexpected error occurred: "https://registry.yarnpkg.com/sfdx-git-delta: unable to verify the first certificate".
    Error: yarn add sfdx-git-delta@latest --non-interactive 
    --mutex=file:/root/.local/share/sfdx/yarn.lock 
    --preferred-cache-folder=/root/.cache/sfdx/yarn --check-files exited with 
    code 1.

**Comment by scolladon** [comment]
Hi @anandsecured !

Thanks for your interest in the plugin and thanks for raising your hand on this particular behaviour.

From what I can read, it seems to be 2 issues 

1. Network issue during the installation 

> Installing plugin sfdx-git-delta... info There appears to be trouble with your network connection. Retrying...Installing plugin
We (plugin developer) can't do much for this

2. First certificate verification

> Seems to be related to the Network issue. My guess is, as yarn cannot access the registry because of network access, it cannot check the certificate
We (plugin developer) can't do much for this either

Do you have network issue with this Jenkins instance ? Where is it located, cloud or on premise ?
What is the current architecture ? Do you have a private npm registry ?

**Comment by anandsecured** [comment]
Hi @scolladon,

Thanks much for the responses. 
We had network issues in our morning and it got solved before we started encountering this issue and our Jenkins instance is hosted in cloud and we don't have private registry. If it's nothing from your side I believe some residual network problems from our side might have caused this issue.
