### ISSUE TITLE
Reports and Report Folders should be different types

### ISSUE THREAD

**Issue by pbunygin** [scolladon/sfdx-git-delta#299]
Issue verification check:

- [x] is the current repository fully deployable at the commit SHA provided with the 'from' parameter of the command?

## What is the problem?

---
When package.xml is generated both report folders and reports are listed in as the 'Report' type. 

```
<types>
    <members>ReportFolder</members>
    <members>ReportFolder/ReportName</members>
    <name>Report</name>
</types>

```
That leads to the error "An object 'ReportFolder/ReportName' of type Report was named in package.xml, but was not found in zipped directory"

### What is the parameter and the value you used with it?

"sfdx sgd:source:delta --to HEAD --from SHA --output ."

### What is the expected result?

```
<types>
    <members>ReportFolder</members>
    <name>ReportFolder</name>
</types>
<types>
    <members>ReportFolder/ReportName</members>
    <name>Report</name>
</types>
```
No deployment errors

### What is the actual result?

```
<types>
    <members>ReportFolder</members>
    <members>ReportFolder/ReportName</members>
    <name>Report</name>
</types>
```
The error "An object 'ReportFolder/ReportName' of type Report was named in package.xml, but was not found in zipped directory"

## Steps to reproduce

---

1. Commit report folder
2. Commit report in the folder

## Execution context

---

$ uname -v ; yarn -v ; node -v ; git --version ; sfdx --version ; sfdx plugins
2021-03-26 22:17 UTC
bash: yarn: command not found
v14.18.1
git version 2.33.0.windows.2
 »   Warning: sfdx-cli update available from 7.118.1 to 7.143.0.
sfdx-cli/7.118.1 win32-x64 node-v14.17.6
 »   Warning: sfdx-cli update available from 7.118.1 to 7.143.0.
sfdx-git-delta 5.2.0

## More information (optional)

---

**Comment by scolladon** [comment]
Hi @pbunygin!

Thanks for raising this issue and thanks for your helping improving the plugin!

I think I understand the issue.
I need to spike a little bit on that in order to be sure it should behave the same for every [in folder](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_folder.htm) metadata type, and find an elegant and easy to implement solution.

Does it work with a slash at the end of the folder ?
```xml
<types>
    <members>ReportFolder/</members>
    <members>ReportFolder/ReportName</members>
    <name>Report</name>
</types>
```

**Comment by pbunygin** [comment]
Hi @scolladon,
Thank you for the plugin and the support!

**Comment by scolladon** [comment]
Hi @pbunygin

I tried locally to deploy report and reportFolder using package xml and `sfdx force:source:deploy` command.
My test scenario is deployed in the [playground](https://github.com/scolladon/sfdx-git-delta-reproduction-playground/tree/issue/299)

I tried two different scenario: 

## Report Folder metadata declared separatly

In this case the folder is declared in the ReportFolder type section of the package.xml
```xml
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>Sample/Test</members>
        <name>Report</name>
    </types>
    <types>
        <members>Sample</members>
        <name>ReportFolder</name>
    </types>
    <version>54.0</version>
</Package>
```
Result of the execution `sfdx force:source:deploy -x package.xml/path`: It works, even if the [documentation does not say it could](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_folder.htm#:~:text=The%20following%20is%20the%20package%20manifest%20definition%20of%20a%20document%20folder%20that%20contains%20a%20document%3A)
![Screenshot 2022-05-09 at 19 47 35](https://user-images.githubusercontent.com/522422/167467577-943b1255-6528-4ed0-948d-6ca0569b5882.png)

## Report Folder metadata declared with Report

In this case the folder is declared in the Report type section of the package.xml, as described in the [documentation](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_folder.htm#:~:text=The%20following%20is%20the%20package%20manifest%20definition%20of%20a%20document%20folder%20that%20contains%20a%20document%3A)
```xml
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>Sample</members>
        <members>Sample/Test</members>
        <name>Report</name>
    </types>
    <version>54.0</version>
</Package>
```
Result of the execution `sfdx force:source:deploy -x package.xml/path`: Work As Design
![Screenshot 2022-05-09 at 19 49 00](https://user-images.githubusercontent.com/522422/167468206-a2bb27fc-e984-4345-9364-90055f144082.png)

@pbunygin could you help us isolate the issue with the package.xml declaration at the same level of the type (as stated in the documentation)? As you can see I'm unable to reproduce the behavior you describe

**Comment by scolladon** [comment]
I agree, it looks like either a `sfdx-cli` or gov cloud...
@pbunygin Could you raise this issue in `sfdx-cli`please and past the link in a comment here ?
We will be able to track it from here also then
