### ISSUE TITLE
Add RestrictionRule Metadata to package.xml

### ISSUE THREAD

**Issue by mark10281996** [scolladon/sfdx-git-delta#308]
### Is your proposal related to a problem?
Yes
---

sfdx-git-delta plugin does not include RestrictionRule metadata in package.xml. This metadata was added in API version 54.0. https://developer.salesforce.com/docs/atlas.en-us.236.0.api_meta.meta/api_meta/meta_restrictionrule.htm

### Describe a solution you propose
Include RestrictionRule Metadata in sfdx-git-delta plugin. 
This can be added to the v54.json file.

---

### Describe alternatives you've considered
Currently have to add it manually to the package.xml to deploy.

---

**Comment by scolladon** [comment]
Hi @mark10281996 

Thank you very much for this suggestion.
I'll do a PR very soon and a new version will be shipped right after that with this enhancement.

**Comment by mark10281996** [comment]
Thank you @scolladon!
