### ISSUE TITLE
Purpose of package.xml file in destructiveChanges folder

### ISSUE THREAD

**Issue by alex9138** [scolladon/sfdx-git-delta#31]
Hello @scolladon,

Can you elaborate here or in README on the purpose of package.xml file in destructiveChanges folder?

Thanks
Alex

**Comment by scolladon** [comment]
Hello @alex9138 

It is explained a little bit in the [how to use it section](https://github.com/scolladon/sfdx-git-delta#how-to-use-it).

Deploying destructive changes requires also a package.xml (even an empty one) in the payload

force:source:deploy method do not handle destructiveChanges.xml [yet](https://github.com/forcedotcom/cli/issues/188), so destructive deployment need to be sequenced in two phases (deploy changes and addition, then deploy destruction)

If you do delta sources deployment using mdapi:deploy you could add the destructiveChanges.xml file to the folder deployment folder after having done a convert on the output sources.

So 3 usages here :
1. deploy sources from repo using package.xml
`
$ sfdx force:source:deploy -x output/package/package.xml
$ sfdx force:mdapi:deploy -d output/destructiveChanges
`
2. deploy delta sources from output
`
$ sfdx force:source:deploy -p output/sourceFolder
$ sfdx force:mdapi:deploy -d output/destructiveChanges
`
3. deploy metadata from output
`
$ sfdx force:source:convert -x output/package/package.xml -d output/dir
# or
$ sfdx force:source:convert -p output/sourceFolder -d output/dir
$ cp output/destructiveChanges/destructiveChanges.xml output/dir
$ sfdx force:mdapi:deploy -d output/dir
`

Does that answer your question ?

Would you like to emphasize those aspect in the readme ? (if you want to create a PR, please be my guest!)

**Comment by alex9138** [comment]
:) #32
