### ISSUE TITLE
Missing modified files in package.xml

### ISSUE THREAD

**Issue by docv266** [scolladon/sfdx-git-delta#310]
Issue verification check:

- [ ] is the current repository fully deployable at the commit SHA provided with the 'from' parameter of the command?

## What is the problem?

---

I have modified 5 files over 4 commits.
Here is the git diff between the first and the last commit:

`git diff --name-only a53b4ab67083215a2face5d65ed32f1a7842d18c..3a9b57feadadc450aa6695a11e40f1b50aec08d6`

Gives:
```
.gitlab-ci.yml
src/B2B_Core/utilities/generic/classes/B2B_Debug.cls
src/B2B_Core/utilities/generic/classes/B2B_Debug_Test.cls
src/B2B_Telesales_Feature/services/B2B_Stock/B2B_StockService.cls
src/B2B_Telesales_Feature/services/B2B_Stock/B2B_StockService_Test.cls
```

### What is the parameter and the value you used with it?

I perform this delta:
`sfdx sgd:source:delta --from=a53b4ab67083215a2face5d65ed32f1a7842d18c --to=3a9b57feadadc450aa6695a11e40f1b50aec08d6 --source=src --output=temp`

### What is the expected result?

It should gives the following package.xml file:
```
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>B2B_StockService</members>
        <members>B2B_StockService_Test</members>
        <members>B2B_Debug</members>
        <members>B2B_Debug_Test</members>
        <name>ApexClass</name>
    </types>
    <version>54.0</version>
```

### What is the actual result?

It gives the following package.xml file instead:
```
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>B2B_Debug</members>
        <members>B2B_Debug_Test</members>
        <name>ApexClass</name>
    </types>
    <version>54.0</version>
```

## Execution context

---

**Operating System:** Ubuntu

**node version:** v16.15.0

**git version:** 2.17.1

**sfdx version:** sfdx-cli/7.154.0 linux-x64 node-v16.15.0

**sgd plugin version:** v5.2.0

**Comment by docv266** [comment]
I understand what happened.

Our files are stored with a custom tree structure.
And some of our Apex class file were not in a subfolder named "classes".

Since the plugin is looking for that in the metadata file, those files were ignored.

**Comment by mehdisfdc** [comment]
Anyway, thank you for having investigated further your issue and for taking the time to close your issue!
