### ISSUE TITLE
sfdx sgd:source:delta not producing a package.xml with changes in GITLAB pipeline

### ISSUE THREAD

**Issue by willianpaulop** [scolladon/sfdx-git-delta#313]
Issue verification check:

- [ ] is the current repository fully deployable at the commit SHA provided with the 'from' parameter of the command?

## What is the problem?

---I'm running sfdx sgd:source:delta in GitLab pipeline and it its generating an empty package file when comparing head with the destination MR branch, but when running the same command locally, the package.xml is created with the correct changed files

### What is the parameter and the value you used with it?

running this in Gitlab pipeline doesn't work ( $CI_MERGE_REQUEST_TARGET_BRANCH_NAME is develop):
sfdx sgd:source:delta --to HEAD --from origin/$CI_MERGE_REQUEST_TARGET_BRANCH_NAME --output delta-folder/ --generate-delta

but running this locally works:
sfdx sgd:source:delta --from origin/develop --output delta-folder/ --generate-delta

### What is the expected result?

<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>OpportunityFieldUpdate</members>
        <members>OpportunityFieldUpdate_Test</members>
        <name>ApexClass</name>
    </types>
    <version>53.0</version>
</Package>

### What is the actual result?

<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <version>53.0</version>
</Package>

## Steps to reproduce

`mkdir -p delta-folder
    rm -fr delta-folder/*
    echo "merge location $CI_MERGE_REQUEST_TARGET_BRANCH_NAME $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME"  
    sfdx sgd:source:delta --to HEAD --from origin/$CI_MERGE_REQUEST_TARGET_BRANCH_NAME --output delta-folder/ --generate-delta
    ls delta-folder/
    echo "package content $(<delta-folder/package/package.xml)"`

## Execution context

---

**Operating System:** …

**yarn version:** …

**node version:** …

**git version:** …

**sfdx version:**  latest

**sgd plugin version:** 4.12.1

## More information (optional)

Using sgd version 4.12.1 as latest version fails with --from is not a valid sha pointer: \"origin/develop\"

**Comment by mehdisfdc** [comment]
Hi @willianpaulop.
Thank you for logging this issue!

Are you sure that your `from` parameter can be accessed from your pipeline?
Could you please run `git diff --name-status --no-renames origin/$CI_MERGE_REQUEST_TARGET_BRANCH_NAME HEAD` to verify that you `from` parameter is valid?

If you can't access this remote branch from you pipeline, you may need to add a command such as `git fetch origin "+refs/heads/*:refs/remotes/origin/*"`

**Comment by willianpaulop** [comment]
@mehdisfdc adding git fetch solved the issue, thanks a lot :)
