### ISSUE TITLE
Node version issue

### ISSUE THREAD

**Issue by lavanyagun** [scolladon/sfdx-git-delta#314]
Issue verification check:

- [ ] is the current repository fully deployable at the commit SHA provided with the 'from' parameter of the command?

## What is the problem?
---

echo y | sfdx plugins:install sfdx-git-delta
  sfdx plugins 
  shell: /usr/bin/bash -e {0}
Finished digital signature check.
This plugin is not digitally signed and its authenticity cannot be verified. Continue installation y/n?: Installing plugin sfdx-git-delta... yarn add v1.22.10
Installing plugin sfdx-git-delta... info No lockfile found.Installing plugin sfdx-git-delta... [1/4] Resolving packages...Installing plugin sfdx-git-delta... [2/4] Fetching packages...Installing plugin sfdx-git-delta... info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.Installing plugin sfdx-git-delta... failed
warning sfdx-git-delta > @salesforce/core > jsforce > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/[3](https://github.com/fq-bizsystems/FLoQastSFDCProduction/runs/6984239950?check_suite_focus=true#step:5:3)1[4](https://github.com/fq-bizsystems/FLoQastSFDCProduction/runs/6984239950?check_suite_focus=true#step:5:4)2
warning sfdx-git-delta > @salesforce/core > jsforce > request > har-validator@[5](https://github.com/fq-bizsystems/FLoQastSFDCProduction/runs/6984239950?check_suite_focus=true#step:5:6).1.5: this library is no longer supported
warning sfdx-git-delta > @salesforce/core > jsforce > request > uuid@3.4.0: Please upgrade  to version [7](https://github.com/fq-bizsystems/FLoQastSFDCProduction/runs/6984239950?check_suite_focus=true#step:5:8) or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v[8](https://github.com/fq-bizsystems/FLoQastSFDCProduction/runs/6984239950?check_suite_focus=true#step:5:9).dev/blog/math-random for details.
error @salesforce/command@5.2.0: The engine "node" is incompatible with this module. Expected version ">=14.0.0". Got "12.18.3"
error Found incompatible module.
    Error: yarn add sfdx-git-delta@latest --non-interactive 
    --mutex=file:/home/runner/.local/share/sfdx/yarn.lock 
    --preferred-cache-folder=/home/runner/.cache/sfdx/yarn --check-files 
    exited with code 1

## Steps to reproduce

---

## Execution context

---

**Operating System:** …

**yarn version:** …

**node version:** …

**git version:** …

**sfdx version:** …

**sgd plugin version:** …

## More information (optional)

---

**Comment by scolladon** [comment]
Hi @lavanyagun !

Thanks for raising this issue.

Looking at the log provided, it seems the plugin is executed with node version 12.18.3 where it needs v14 at least.

Could you use node v14 and retry ?

**Comment by lavanyagun** [comment]
Hi @scolladon 

I have been using v14 version. Here is the code 
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Setup Node
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '14'
      
    
    # Runs a single command using the runners shell
    - name: 'Build and Deploy'
      run: |
        wget https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
        mkdir sfdx-cli
        tar xJf sfdx-linux-amd64.tar.xz -C sfdx-cli --strip-components 1
        ./sfdx-cli/install

**Comment by scolladon** [comment]
Thanks for those information

I think the sfdx-cli version you are installing comes with an embedded node version (12).
Maybe the link is very old. New link is the following: https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable/sfdx-linux-x64.tar.xz

You can try with the new url (I have never tested that)
```yaml
# Runs a single command using the runners shell
- name: 'Build and Deploy'
  run: |
    wget https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable/sfdx-linux-x64.tar.xz
    mkdir sfdx-cli
    tar xJf sfdx-linux-amd64.tar.xz -C sfdx-cli --strip-components 1
    ./sfdx-cli/install
```

Or you can try installing sfdx-cli using npm instead (this is what we do in our CI)

```yaml
# Runs a single command using the runners shell
- name: 'Build and Deploy'
  run: npm install -g sfdx-cli
```

============

Other things: setup-node has a new v3 available 😉 
```yaml
# Setup Node
- name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 14
```

**Comment by lavanyagun** [comment]
Hi,

I have tried both options you mentioned. Here is the code

# This is a basic workflow to help you get started with Actions
name: CI job on Lavanya Branch
# Controls when the action will run. Triggers the workflow on push or pull
request
# events but only for the master branch
on:
push:
branches: [ lavanya ]
pull_request:
branches: [ lavanya ]
# A workflow run is made up of one or more jobs that can run sequentially
or in parallel
jobs:
# This workflow contains a single job called "build"
build:
# The type of runner that the job will run on
runs-on: ubuntu-latest
# Steps represent a sequence of tasks that will be executed as part of the
job
steps:
# Checks-out your repository under $GITHUB_WORKSPACE, so your job can
access it
- uses: ***@***.***
# Setup Node
- name: Setup Node
uses: ***@***.***
# Runs a single command using the runners shell
- name: 'Build and Deploy'
run: |
wget
https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
mkdir sfdx-cli
tar xJf sfdx-linux-amd64.tar.xz -C sfdx-cli --strip-components 1
./sfdx-cli/install
# Authorize SF Org
- name: Authorize SF Org
env:
CLIENT_ID: ${{ secrets.SALESFORCEDEVCLIENTID }}
USERNAME: ${{ secrets.SALESFORCEDEVUSERNAME }}
INSTANCE_URL: ${{ secrets.SALESFORCEDEVINSTANCEURL }}
run: sfdx force:auth:jwt:grant --clientid $CLIENT_ID --jwtkeyfile
./buildfiles/server.key --username $USERNAME --instanceurl $INSTANCE_URL -a
dev
# Runs a set of commands using the runners shell
- name: 'Convert Metadata'
run: sfdx force:source:convert --rootdir=force-app --outputdir=convert
- name: 'Deploy Metadata'
run: sfdx force:mdapi:deploy --deploydir=convert -u dev -w 50
- name: 'Deployment Report'
run: sfdx force:mdapi:deploy:report -u dev
Please find the attached log and let me know.

Thanks,
Lavanya.

**Comment by lavanyagun** [comment]
Hi,

Sorry, I accidentally sent my older version of code to you. Here is my
updated version

jobs:
build:
# The type of runner that the job will run on
runs-on: ubuntu-latest
# Steps represent a sequence of tasks that will be executed as part of the
job
steps:
# Checks-out your repository under $GITHUB_WORKSPACE, so your job can
access it
- uses: ***@***.***
# Setup Node
- name: Setup Node
uses: ***@***.***
with:
node-version: 14
# Runs a single command using the runners shell
- name: 'Build and Deploy'
run: |
wget
https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable/sfdx-linux-x64.tar.xz
mkdir sfdx-cli
tar xJf sfdx-linux-x64.tar.xz -C sfdx-cli --strip-components 1
./sfdx-cli/install
# Authorize SF Org
- name: Authorize SF Org
env:
CLIENT_ID: ${{ secrets.SALESFORCEDEVCLIENTID }}
USERNAME: ${{ secrets.SALESFORCEDEVUSERNAME }}
INSTANCE_URL: ${{ secrets.SALESFORCEDEVINSTANCEURL }}
run: sfdx force:auth:jwt:grant --clientid $CLIENT_ID --jwtkeyfile
./buildfiles/server.key --username $USERNAME --instanceurl $INSTANCE_URL -a
dev
- name: "Install App and Create Delta"
run: |
npm install ***@***.*** --global
git config remote.origin.fetch '+refs/heads/*:refs/remotes/origin/*'
git fetch --all
git checkout -b pr
git --no-pager diff --name-status pr origin/lavanya
sgd --to pr --from origin/staging --repo . --output .
cat package/package.xml
- name: 'Convert Metadata'
run: sfdx force:source:convert --manifest=package/package.xml
--outputdir=convert
- name: 'Run Test on Metadata'
run: sfdx force:mdapi:deploy --deploydir=convert --testlevel=RunLocalTests
--checkonly -w30
Here is the error i'm getting

2022-06-22 16:26:40 (136 MB/s) - ‘sfdx-linux-x64.tar.xz’ saved
[57702268/57702268]


/home/runner/work/_temp/64c45643-eb05-4d0e-97a4-3ea1032ecb60.sh: line 4:
./sfdx-cli/install: No such file or directory


*Error: *Process completed with exit code 127.


Please suggest where I should install sgd and any changes to code are
really appreciable. Thank you!

Thanks,
Lavanya.

**Comment by scolladon** [comment]
@lavanyagun it seems sfdx-cli installation did not go well in this case.

You should try installing sfdx-cli with npm instead of downloading it:

```yaml
- name: 'Build and Deploy'
  run: npm install -g sfdx-cli
```

You also need to [specifiy](https://github.com/scolladon/sfdx-git-delta#cicd-specificity) the [fetch-depth](https://github.com/actions/checkout#checkout-v3) in the CI to be able to use SGD

**Comment by scolladon** [comment]
@lavanyagun any progress so far ?

**Comment by scolladon** [comment]
Hi @lavanyagun

Thanks for sharing your workflow definition.
From what I see, the `sgd` command does not seem to be installed before being executed.
So the workflow need to install prior using it.

And, it seems this version is using the `sgd` command line which has been decomissionated.
Now you need to use the sfdx plugin instead.
I recommend adding a step to install the plugin just after installing `sfdx cli` using this command
```sh
echo y | sfdx plugins:install sfdx-git-delta
```

Then you will have to use sgd **via** sfdx: 
```sh
$ sfdx sgd:source:delta --to pr --from origin/staging --repo . --output .
# instead of sgd --to pr --from origin/staging --repo . --output .
```

**Comment by scolladon** [comment]
Closing this issue
Feel free to reopen it with more information @lavanyagun
