### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by ofarras** [scolladon/sfdx-git-delta#319]
Issue verification check:

- [ ] is the current repository fully deployable at the commit SHA provided with the 'from' parameter of the command?

## What is the problem?

---

After executing  on output only shows: TypeError: Cannot read properties of undefined (reading 'prototype')

### What is the parameter and the value you used with it?

sfdx sgd:source:delta --to "HEAD" --from "HEAD^" --output "scripts/deploy/"

### What is the expected result?

Generate package

### What is the actual result?

Not working

## Steps to reproduce

---

## Execution context

---

**Operating System:** …
Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64
**yarn version:** …
1.17.3
**node version:** …
v16.15.0
**git version:** …
git version 2.21.0 (Apple Git-122)
**sfdx version:** …
sfdx-cli/7.158.1 darwin-x64 node-v16.15.1
**sgd plugin version:** …
sfdx-git-delta 5.3.0

## More information (optional)

---

**Comment by ofarras** [comment]
@mehdisfdc yes it works.

Thanks again!!!

**Comment by JaniszewskiMarcin** [comment]
Hello @mehdisfdc,
I have similar problem but the command is running on Azure job where we install everything from scratch at every iteration of the job, so the plugin is reinstalling all the time and still getting this error TypeError: Cannot read properties of undefined (reading 'prototype') with the command sfdx sgd:source:delta. So the re-installation do not help us in this case :/ Is there any other fix?

**Comment by scolladon** [comment]
Hi @JaniszewskiMarcin !

I see that you have open a new bug [here](https://github.com/scolladon/sfdx-git-delta/issues/326).
Thanks for doing that.

Let's look at that there
