### ISSUE TITLE
Delta package on detached head contains extra components from the target branch

### ISSUE THREAD

**Issue by sfdcbruno** [scolladon/sfdx-git-delta#320]
Issue verification check:

- [ ] is the current repository fully deployable at the commit SHA provided with the 'from' parameter of the command?

## What is the problem?

---

Running SGD on a docker container in gitlab, the pipeline is triggered on a Merge Request from feature branches to validate the components getting merged into develop branch. The delta is being calculated from lastTag on develop, to HEAD (detached).
If the develop branch has new commits (and tags), and its ahead of feature branch, running the delta causes the output to contain components from the develop branch that have not been modified on the feature branch.
I'm not sure if this is an issue or if it should behave like this - any help is appreciated.

### What is the parameter and the value you used with it?

sfdx sgd:source:delta -a $SF_API_VERSION --from $latestTag --to HEAD --output $CI_PROJECT_DIR/build-files/ --generate-delta -i .dx-delta-ignore

### What is the expected result?

Only files that have been modified should be added to the delta package.

### What is the actual result?

Delta package contains files modified in source branch AND target branch, if target is ahead of source.

## Steps to reproduce

---

- develop branch HEAD with tag T1
- feature-test branches out of develop 
- commits happen in both feature and develop branches (separate developments, different files modified) - new develop tag T2
- on merge request, run delta from HEAD (feature) to T2
- delta contains files that were modified on develop branch

## Execution context

---

**Operating System:** …
#1 SMP PREEMPT Thu Mar 17 17:05:54 UTC 2022

**yarn version:** …
1.22.19

**node version:** …
v18.6.0

**git version:** …
git version 2.30.2

**sfdx version:** …
sfdx-cli/7.159.0 linux-x64 node-v18.6.0

**sgd plugin version:** …
sfdx-git-delta 5.3.0

## More information (optional)

---

**Comment by scolladon** [comment]
Hi @sfdcbruno,

Thanks for raising this question !

I think what you want is to get the content of your branch compared to its ancestor point (without containing what has been merged into your base branch) after you branch has been create.

There was a previous question with the same requirement [here](https://github.com/scolladon/sfdx-git-delta/issues/101) that made us update the [README to explain how to do this using git](https://github.com/scolladon/sfdx-git-delta#:~:text=Comparing%20branches%20(from%20a%20common%20ancestor)

**Comment by sfdcbruno** [comment]
Thank you @scolladon! This is exactly what I needed, works like a charm!

**Comment by scolladon** [comment]
Glad to help!

Enjoy incremental deployment!

I can see you are using a docker container to host sfdx-cli and sgd I guess.
I know some other people in our community are having [trouble to run sgd inside docker](https://github.com/scolladon/sfdx-git-delta/issues/315).
They mainly have a successful installation of the plugin (or a silent failure), but when they list the installed plugin sgd does not appear.

Could you [open a discussion](https://github.com/scolladon/sfdx-git-delta/discussions/new?category=show-and-tell) in this repo and explain how you use sgd inside docker please ? I think it could be very helpful to everyone
