### ISSUE TITLE
Big object Deployment Issue as it is causing build failures 

### ISSUE THREAD

**Issue by saileshkhadka** [scolladon/sfdx-git-delta#327]
While deploying, the metadata operation is failed due to big object is not included in package.xml
For metadata v53.json,
https://github.com/scolladon/sfdx-git-delta/blob/main/src/metadata/v53.json
here, big object field is not included as separate directory as indexes like others CustomField,businessProcesses
![MicrosoftTeams-image](https://user-images.githubusercontent.com/26744853/184657093-3dc548a7-9823-45f7-aa4a-c9ba910d1805.png)

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/26744853/184656642-309b1f96-5df9-4a7f-8901-2effa7d9a001.png)

**Comment by scolladon** [comment]
Hi @saileshkhadka!

Thank you very much for raising this issue.
Thanks for your interest on the plugin and for your help to make it better.

I see the issue, I'm going to create a PR.

I'll notify you here when it is patched and released, stay tuned!

**Comment by scolladon** [comment]
Hi @saileshkhadka 

A new PR (#330) is on its way.

This PR assume the `Index` metadata is in a specific file (`.index-meta.xml`) under the `indexes` folder of the big object it is related to:
![Screenshot 2022-08-18 at 19 41 28](https://user-images.githubusercontent.com/522422/185459998-c457f75d-ebc5-46f8-823a-38f5b0555526.png)

**Comment by scolladon** [comment]
Thank you very much @saileshkhadka 

New version [5.4.0](https://github.com/scolladon/sfdx-git-delta/releases/tag/v5.4.0) is just released with this bug fix !
Thanks for helping improving the plugin

Happy incremental deployment !!
