### ISSUE TITLE
ENOENT no such file or directory *.undefined

### ISSUE THREAD

**Issue by alex9138** [scolladon/sfdx-git-delta#33]
Hello @scolladon 

A new one, unable to find a file that is not in my repo.

I have checked, the whole object ContractedPrice deployment is ok  with sfdx force:source:deploy so no error in it I guess.

Reproduction step : 
```
$  sgd -d -t HEAD -f origin/master -r . -o output
Error terminating the process during sfdx-git-delta : Error: ENOENT: no such file or directory, stat 'force-app\main\default\objects\DWIN2_ContractedPrice__c\DWIN2_ContractedPrice__c.undefined'

$ git diff HEAD^..origin/master --stat | grep Contract
 .../DWIN2_ContractedPrice__c.object-meta.xml       |    2 +-
 .../fields/DWIN2_Contract__c.field-meta.xml        |    2 +-
```

**Comment by scolladon** [comment]
Hi @alex9138 !

Thanks again for helping making this product better.

Could you provide instruction on how reproduce (build the repository state and the command to reproduce) ?
Also, what is the content of package/package.xml and destructiveChanges/destructiveChanges.xml ?

**Comment by alex9138** [comment]
:) 

First there is no package/destructiveChanges folder

$ ls -la output/
total 8
drwxr-xr-x 1 alexis.rafesthain 1049089 0 juin  25 12:39 .
drwxr-xr-x 1 alexis.rafesthain 1049089 0 juin  25 12:31 ..
drwxr-xr-x 1 alexis.rafesthain 1049089 0 juin  25 12:39 force-app

**Comment by alex9138** [comment]
Hi @scolladon,

A new one this afternoon 

`Error terminating the process during sfdx-git-delta : Error: ENOENT: no such file or directory, stat 'force-app/main/default/email/DWIN2_Lead_Folder.emailFolder'`

If it helps --> Real file is : DWIN2_Lead_Folder.emailFolder-meta.xml

**Comment by scolladon** [comment]
@alex9138 could you test the #34 fix to see if it fixes this issue and if there is not another underlying issue.

I tested it on my side with the dataset you provided and it seems technically ok now, but maybe functionnally it misses something.
Your eyes would be greatly appreciated here :)

**Comment by alex9138** [comment]
@scolladon alright from there.

Nice to see the error handling in this one, will be helpful in pipe :)

**Comment by alex9138** [comment]
Hello @scolladon, 

Just to let you know that missing output directory is not cristal clear anymore with the new error handling.

```
$ ../../sgd/bin/cli -d -t HEAD -f 69acf4915e94c58bb061a0e06fc139635ef16836 -r . -o output
{
  "error": {},
  "output": "output",
  "success": false,
  "warnings": null
}
```

**Comment by scolladon** [comment]
New version 3.1.2 available !

**Comment by alex9138** [comment]
Thanks :)
