### ISSUE TITLE
Include Omni Studio Metadata components in SGD-git-delta

### ISSUE THREAD

**Issue by krushithAnde** [scolladon/sfdx-git-delta#331]
sgd-git-delta for Omni studio metadata components

We are trying to implement Omnistudio deployments with CI/CD integrations but couldnt generate git delta i believe its directories are not included in the metadata directory.
Eg: 
OmniInteractionConfig
OmniScript
OmniIntegrationProcedure
OmniUiCard

### Describe a solution you propose
 
 Include omnistudio metadata components in src metadata json structure might resolve omnistudio metadata git delta generation.

### Describe alternatives you've considered

---

### Additional context

---

**Comment by scolladon** [comment]
Hi @krushithAnde !

Thanks for this enhancement request!

I tried to look at the [documentation](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_intro.htm) for those metadata type definition so I can add them in our list.
But I could only find a definition for `OmniInteractionConfig`.
Could you give us the link to the documentation for all the element you wish to add please?

**Comment by krushithAnde** [comment]
Hi,
I haven't got any documentation link, however used the following to retrive and deploy omnistudio metadata 

`<?xml version="1.0" encoding="UTF-8"?>`
`<Package xmlns="[http://soap.sforce.com/2021/10/metadata"](http://soap.sforce.com/2021/10/metadata%22)>`
    `<types>`
        `<members>*</members>`
        `<name>OmniInteractionConfig</name>`
    `</types>`
    `<types>`
       ` <members>*</members>`
        `<name>OmniScript</name>`
    `</types>`
    `<types>`
        `<members>*</members>`
        `<name>OmniIntegrationProcedure</name>`
    `</types>`
    `<types>`
       ` <members>*</members>`
        `<name>OmniUiCard</name>`
   ` </types>`
    `<version>54.0</version>`
`</Package>`

**Comment by scolladon** [comment]
Great!

Please give the folder structure: (file name with extensions and folder in which they are located)

**Comment by krushithAnde** [comment]
please find the folder structure and extensions in screenshot for reference 

![image](https://user-images.githubusercontent.com/54552513/186397814-3d8d6d1c-48ac-4e97-b7d8-0dd7a377b363.png)

**Comment by krushithAnde** [comment]
hi @scolladon,
can you please include omni dataraptor too 
![image](https://user-images.githubusercontent.com/54552513/186572508-edd4c438-3ba3-41c8-8223-ce4b0caabe79.png)
for reference used the following command 
`sfdx force:source:retrieve -m 'OmniDataTransform'` to retrive the dataraptors

**Comment by scolladon** [comment]
Done @krushithAnde !

Could you help us with the functional testing please ?
The [PR](https://github.com/scolladon/sfdx-git-delta/pull/333) is here with all the content asked.
You need to follow those [steps](https://github.com/scolladon/sfdx-git-delta/blob/main/CONTRIBUTING.md#testing-the-plugin-from-a-pull-request) in order to test the PR locally.

Please ensure, the metadata are added in the package.xml and they are deployable after that (meaning the package.xml is properly build)

That would be greatly appreciated.

**Comment by krushithAnde** [comment]
Hi,

I did functional testing locally.. and It worked!!!! 

Thank you @scolladon 

Generated package.xml and successfully validated too. 

For reference :

![image](https://user-images.githubusercontent.com/54552513/186784058-e8476acf-7073-4656-874e-69876cf87689.png)

`sfdx force:source:deploy -c -x package/package.xml  --postdestructivechanges destructiveChanges/destructiveChanges.xml --verbose
`
![image](https://user-images.githubusercontent.com/54552513/186784306-0f3e13a7-c217-4345-8a83-a68ecafc8d6c.png)


Thanks
Krushitha

**Comment by scolladon** [comment]
Thank you very much @krushithAnde 

New version [5.4.0](https://github.com/scolladon/sfdx-git-delta/releases/tag/v5.4.0) is just released with this enhancement !
Thanks for helping improving the plugin

Happy incremental deployment !!
