### ISSUE TITLE
Unable to install plugin after 5.4.0 release

### ISSUE THREAD

**Issue by mostafascoober** [scolladon/sfdx-git-delta#334]
Issue verification check:

- [ ] is the current repository fully deployable at the commit SHA provided with the 'from' parameter of the command?

## What is the problem?
When installing the latest release v5.4.0 via the command `sfdx plugins:install sfdx-git-delta`, the installation fails for failure to install the husky dependency. This was tested on Linux and Mac. Attempting to install the previous version v5.3.1 via the command `sfdx plugins:install sfdx-git-delta@5.3.1` works without an issue.

## Steps to reproduce
install plugin via command `sfdx plugins:install sfdx-git-delta`
---

## Execution context
System Admin
---

**Comment by reszkaj** [comment]
It is so annoying. I also noticed it on my side.

**Comment by jonny-harte** [comment]
Yep just started happening with our CI

**Comment by scolladon-sfdc** [comment]
Hi !

I'm on it !
It looks to be an issue with the [environment variable](https://github.com/typicode/husky/issues/945) set during plugin installation.

I'm fixing it now.

**Comment by scolladon** [comment]
Hi !

I'm on it !
It looks to be an issue with the https://github.com/typicode/husky/issues/945 set during plugin installation.

I'm fixing it now.

**Comment by gaelCangy** [comment]
Hello Having the same issue here

`+ echo "y" | sfdx plugins:install sfdx-git-delta
Installing plugin sfdx-git-delta... yarn add v1.22.19
Installing plugin sfdx-git-delta... info No lockfile found.Installing plugin sfdx-git-delta... [1/4] Resolving packages...Installing plugin sfdx-git-delta... [2/4] Fetching packages...Installing plugin sfdx-git-delta... [3/4] Linking dependencies...Installing plugin sfdx-git-delta... [4/4] Building fresh packages...Installing plugin sfdx-git-delta... info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.Installing plugin sfdx-git-delta... failed
warning sfdx-git-delta > @salesforce/core > jsforce > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning sfdx-git-delta > @salesforce/core > jsforce > request > har-validator@5.1.5: this library is no longer supported
warning sfdx-git-delta > @salesforce/core > jsforce > request > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
error /root/.local/share/sfdx/node_modules/sfdx-git-delta: Command failed.
Exit code: 127
Command: husky install
Arguments: 
Directory: /root/.local/share/sfdx/node_modules/sfdx-git-delta
Output:
/bin/sh: 1: husky: not found
    Error: yarn add sfdx-git-delta@latest --non-interactive 
    --mutex=file:/root/.local/share/sfdx/yarn.lock 
    --preferred-cache-folder=/root/.cache/sfdx/yarn --check-files exited with 
    code 127`

I

**Comment by scolladon** [comment]
New [release 5.4.1](https://github.com/scolladon/sfdx-git-delta/releases/tag/v5.4.1) have a fix for this issue.

Let me know if you still have this issue
And really sorry for the inconvenience, I did not see that coming...
