### ISSUE TITLE
Deletion not working using destructiveChanges.xml

### ISSUE THREAD

**Issue by Vaibhasrivastava** [scolladon/sfdx-git-delta#337]
I've used SGD command to retrieve the deleted changes and deployed the xml but the metadata is not getting deleted from the destination org.

I've used sfdx force:mdapi:deploy -d destructiveChanges --ignorewarnings this command for deletion but it seems to be not working.
Please help , 
if anyone has also worked on deletion of metadata.

**Comment by scolladon** [comment]
Hi @Vaibhasrivastava !

Do you have any warnings or errors ?
What happen if you execute `sfdx force:mdapi:deploy -d destructiveChanges` (without ignore warnings flag) ?

**Comment by scolladon** [comment]
Hi @Vaibhasrivastava !

Any update here ?

**Comment by scolladon** [comment]
No update for a long time
We close this issue then
@Vaibhasrivastava feel free to reopen it with more information so we can help here
