### ISSUE TITLE
translationJSON?.Translations?.flowDefinitions?.forEach is not a function

### ISSUE THREAD

**Issue by briank73** [scolladon/sfdx-git-delta#341]
In version 5.4.1. we get the error below - in version 5.3.1 it works fine. And sorry for not being able to provide more info :-(

{
  "error": "translationJSON?.Translations?.flowDefinitions?.forEach is not a function",
  "output": "changes",
  "success": false,
  "warnings": []
}

**Comment by scolladon** [comment]
Duplicate of #342
