### ISSUE TITLE
Git Delta not working

### ISSUE THREAD

**Issue by anupam081** [scolladon/sfdx-git-delta#348]
Issue verification check:

- [ ] is the current repository fully deployable at the commit SHA provided with the 'from' parameter of the command? No

## What is the problem?
The below git delta command does not work. It executes successfully but always generates the empty package xml
sfdx sgd:source:delta --to "HEAD" --from "HEAD^" --output ./manifest --generate-delta --source force-app

when i run git diff it give me below result:
$ git diff HEAD^..HEAD
diff --git a/force-app/main/default/triggers/AccountTriggerPOC.trigger b/force-app/main/default/triggers/AccountTriggerPOC.trigger
index 1ad70606..f4708987 100644
--- a/force-app/main/default/triggers/AccountTriggerPOC.trigger
+++ b/force-app/main/default/triggers/AccountTriggerPOC.trigger
@@ -7,7 +7,7 @@ trigger AccountTriggerPOC on SOBJECT (before insert, before update) {
         Account acct = Trigger.new[0]; // first record
         List<contact> contacts = [select id, salutation, firstname, lastname, email
                    from Contact where accountId = :acct.Id];
-        Decimal yy = 1;
+        Decimal yy = 2;

---

### What is the parameter and the value you used with it?
sfdx sgd:source:delta --to "HEAD" --from "HEAD^" --output ./manifest --generate-delta --source force-app

### What is the expected result?
The command generates the package.xml with the apex trigger

### What is the actual result?
The command always generates the empty package.xml
![image](https://user-images.githubusercontent.com/30425172/188615030-10c2bbcd-4e9c-4d17-a8fc-a4c354a3799e.png)
![image](https://user-images.githubusercontent.com/30425172/188615198-ce76a4be-6aa8-488e-8a4a-17d05652554d.png)
![image](https://user-images.githubusercontent.com/30425172/188615277-04a10407-ba0d-4724-9fab-894cda553d84.png)

## Steps to reproduce
Change any component and commit it locally in VSCODE
Run this command : sfdx sgd:source:delta --to "HEAD" --from "HEAD^" --output ./manifest --generate-delta --source force-app
The command runs successfully but generate an empty package.xml

---

## Execution context

---

**Operating System:** … windows 10

**yarn version:** …

**node version:** …

**git version:** … git version 2.37.2.windows.2

**sfdx version:** … sfdx-cli/7.158.1 win32-x64 node-v16.15.1

**sgd plugin version:** … @salesforce/sfdx-scanner 2.13.7
sfdx-git-delta 5.4.2

## More information (optional)

---

git diff --name-status --no-renames "HEAD" "HEAD^"
M       force-app/main/default/triggers/AccountTriggerPOC.trigger

**Comment by scolladon** [comment]
Hi @anupam081 !

Thanks for raising this issue and thanks for your help making the plugin better.

I have tried to reproduce locally and everything works fine on my end.
I'm using Mac terminal, maybe this is what differs from you.
What kind of terminal are you using ?

I put a zip I used to try to reproduce the issue (without success).
[sgd-issue-348.zip](https://github.com/scolladon/sfdx-git-delta/files/9496617/sgd-issue-348.zip)
You can unzip it and look at the manifest, it is correctly generated (on my side).
What you can do then is to delete the content of the manifest folder and reexecute the plugin.
Let us know the result then, we will be able to look at the differences.
```sh
$ rm -rf ./manifest/*
$ sfdx sgd:source:delta -t "HEAD" -f "HEAD^" -o ./manifest -d -s force-app
```

**Comment by anupam081** [comment]
Hi @scolladon 

I am using bash terminal in VSCODE installed on windows 10. 
I tried the same suggestion but am having the same results.

Further I tried on PowerShell terminal in VSCODE - Having the same result

Lastly I tried in Windows Command prompt terminal - **And it worked this time** 
Clearly seems to be the issue with the terminal, where this command is not working on bash and powershell terminal.
see the results below:
![image](https://user-images.githubusercontent.com/30425172/188817473-2b31da4b-79a5-4958-b491-4ce81beaf5ef.png)

**Comment by scolladon** [comment]
That's very helpful!

Glad to hear you have been able to isolate the issue and also you found a workaround.

What is the Linux bash you are using with Windows 10 ? Git bash ? Cygwin ? Linux bash shell ?
I wonder which one of these works and which doesn't 😁

**Comment by anupam081** [comment]
Hello @scolladon 
I am using Git bash on windows 10.

It only working on windows command prompt.

Thanks !

**Comment by anupam081** [comment]
Hi @scolladon 
One update the command runs successfully on Git Bash on windows when I first fetch the SHA1 hashes for "HEAD" and "HEAD^"and use it directly in the delta command like below:
sfdx sgd:source:delta -t "a3f3da4146b5f84a350a9bea599b05ef84071608" -f "9ce6926d7db06431c080de359793e3db5e64b96c" -o ./manifest -d -s force-app

Any update on this issue or workaround to run this?

![image](https://user-images.githubusercontent.com/30425172/189105334-a9ff5679-105b-465f-bff3-1f6885dff5c8.png)

**Comment by scolladon** [comment]
I think I know the issue then...
"^" character in windows is the escape wild card. Like "\" is for Linux.

It should not be used when using the plug-in and this is why we removed its usage from our readme file.

I will update the windows usage section to explain about this "^" special character

Thank you very much for enlightening this !
