### ISSUE TITLE
Apex classes outside of force-app/main/default/classes not being added to package.xml

### ISSUE THREAD

**Issue by fedegiust** [scolladon/sfdx-git-delta#350]
Issue verification check:

- [x] is the current repository fully deployable at the commit SHA provided with the 'from' parameter of the command?

## What is the problem?

Currently we moved the Test Apex Classes to force-app/tests and have all other classes in the standard force-app/main/default/classes

If we run a git diff command, I can see apex classes and test classes in the modified files

![image](https://user-images.githubusercontent.com/1804862/190156236-a108d12a-c642-45d5-80fa-64f47b5bb7d7.png)

This is while sitting in pre-master branch to get the diff between pre-master and master to be able to run validation before merging into master

I tried the following commands
`sfdx sgd:source:delta --from $(git merge-base pre-master origin/master)  --output "./temp/" -s . -n .includeFolders`
`sfdx sgd:source:delta --from pre-master  --output "./temp/" -s . -n .includeFolders`
`sfdx sgd:source:delta --from origin/master  --output "./temp/" -s . -n .includeFolders`

The test classes never get added

### What is the parameter and the value you used with it?

`sfdx sgd:source:delta --from $(git merge-base pre-master origin/master)  --output "./temp/" -s . -n .includeFolders`
`sfdx sgd:source:delta --from pre-master  --output "./temp/" -s . -n .includeFolders`
`sfdx sgd:source:delta --from origin/master  --output "./temp/" -s . -n .includeFolders`

This is the content of my .includeFolders

```
force-app/main/default/
force-app/tests/
```

### What is the expected result?

```
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>LeadsService</members>
        <members>LeadTriggerHandler</members>
        <members>LeadTriggerHandlerTest</members>
        <members>TestDataFactory</members>
        <name>ApexClass</name>
    </types>
    <types>
        <members>OpportunityRenewalsNew</members>
        <name>ApexPage</name>
    </types>
    <types>
        <members>Contact.Person_Source__c</members>
        <members>Lead.Person_Source__c</members>
        <members>Lead.TeamWhoCreated__c</members>
        <name>CustomField</name>
    </types>
    <types>
        <members>Account-Project Manager</members>
        <members>Contact-Channel Sales</members>
        <members>Contact-Internal Sales</members>
        <members>Contact-Sales</members>
        <members>Lead-Internal Sales Lead Layout</members>
        <members>Lead-Marketing Lead Layout</members>
        <members>Lead-Operations</members>
        <members>Lead-Sales Lead Layout</members>
        <name>Layout</name>
    </types>
    <types>
        <members>LeadSource</members>
        <name>StandardValueSet</name>
    </types>
    <types>
        <members>Lead.Lead_source_cannot_change</members>
        <members>Lead.Lead_Source_manual_creation</members>
        <members>Lead.Mandatory_Website</members>
        <members>Lead.Original_Person_source_cannot_change</members>
        <members>Lead.Original_Person_Source_manual_creation</members>
        <members>Lead.Return_Reason_and_Follow_Up_Date_mandato</members>
        <members>Opportunity.QP_Main_Contact</members>
        <name>ValidationRule</name>
    </types>
    <version>55.0</version>
</Package>
```

### What is the actual result?

With the test classes missing
```
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>LeadsService</members>
        <members>LeadTriggerHandler</members>
        <name>ApexClass</name>
    </types>
    <types>
        <members>OpportunityRenewalsNew</members>
        <name>ApexPage</name>
    </types>
    <types>
        <members>Contact.Person_Source__c</members>
        <members>Lead.Person_Source__c</members>
        <members>Lead.TeamWhoCreated__c</members>
        <name>CustomField</name>
    </types>
    <types>
        <members>Account-Project Manager</members>
        <members>Contact-Channel Sales</members>
        <members>Contact-Internal Sales</members>
        <members>Contact-Sales</members>
        <members>Lead-Internal Sales Lead Layout</members>
        <members>Lead-Marketing Lead Layout</members>
        <members>Lead-Operations</members>
        <members>Lead-Sales Lead Layout</members>
        <name>Layout</name>
    </types>
    <types>
        <members>LeadSource</members>
        <name>StandardValueSet</name>
    </types>
    <types>
        <members>Lead.Lead_source_cannot_change</members>
        <members>Lead.Lead_Source_manual_creation</members>
        <members>Lead.Mandatory_Website</members>
        <members>Lead.Original_Person_source_cannot_change</members>
        <members>Lead.Original_Person_Source_manual_creation</members>
        <members>Lead.Return_Reason_and_Follow_Up_Date_mandato</members>
        <members>Opportunity.QP_Main_Contact</members>
        <name>ValidationRule</name>
    </types>
    <version>55.0</version>
</Package>
```

## Steps to reproduce

Move test classes to force-app/tests and try to find the diff

## Execution context

```
2020-10-23 13:08 UTC
1.22.11
v14.16.0
git version 2.29.2.windows.3
sfdx-cli/7.167.2 win32-x64 node-v16.17.0
@salesforce/lwc-dev-server 2.11.0
@salesforce/sfdx-diff 0.0.6    
@salesforce/sfdx-scanner 2.13.8
sfdmu 4.15.1
sfdx-git-delta 5.4.2
spm-plugin 1.0.7
```

**Operating System:** Windows 10

**Comment by scolladon** [comment]
Hi @fedegiust !

Thanks for raising this issue and for helping us to make the plugin better.

The issue here comes from the **folder** containing the classes.
Apex classes are meant to be under a `classes` folder.
It works even if the `classes` folder is a grand parent or above.
cf [apex class metadata documentation](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_classes.htm#:~:text=Apex%20classes%20are%20stored%20in%20the%20classes%20folder%20in%20the%20corresponding%20package%20directory).

Example:
`force-app/path/to/classes/MyClass.cls` ✅
`force-app/path/to/classes/subfolder/MyClass.cls` ✅
`force-app/path/to/domain/MyClass.cls` ❌

In your case:
`force-app/tests/TestDataFactory.cls` ❌
`force-app/tests/classes/TestDataFactory.cls` ✅
`force-app/classes/tests/TestDataFactory.cls` ✅

I hope it helps

**Comment by fedegiust** [comment]
So it doesn't support a different folder structure, like the one in ApexRecipes then?
https://github.com/trailheadapps/apex-recipes/tree/main/force-app

In there you have classes in `force-app/main/default/classes/Async Apex Recipes/` and the corresponding tests in `force-app/tests/Async Apex Recipes/`

**Comment by scolladon** [comment]
In this situation, the `classes` folder is where the apex classes are stored (directly under this folder or in a subfolder)

The way the plugin works requires to follow the the folder structure described in the metadata API.
Internally it parses the path to map a specific handler depending the folder.

Metadata are quite complicated and heterogenous, they are meant to be stored in a dedicated folder (this is the behavior when retrieving metadata).
Per example wave types are distinguished by their file extension, but static resources can only be distinguished by the folder they are contained into.

We decided to deal with that aspect using folders to detect how to handle metadata types, we have multiple different handlers.

I think it could be dealt with differently if the plugin only consider the extension of the file to determined which handler it needs.
But this is a big refactoring and I anticipate hard time to identify edge cases (like static resources per exemple).

What I propose: 

1. Use the folder classes to store your test classes and continue using sgd (like this per exemple: `force-app/tests/classes/TestDataFactory.cls`)
2. I'm going to spike a bit on how to support metadata type detection using file extension when possible and fallback to previous detection when not possible to use file extension.

If it is okay for you, then I'll create an enhancement request linked to this issue and we can close it.

**Comment by fedegiust** [comment]
That's ok
