### ISSUE TITLE
Not generating files in specified folder

### ISSUE THREAD

**Issue by willianpaulop** [scolladon/sfdx-git-delta#351]
Issue verification check:

- [ ] is the current repository fully deployable at the commit SHA provided with the 'from' parameter of the command?

## What is the problem?
I'm trying to generate a delta folder in Gitlab Pipelines using this sfdx sgd:source:delta --to HEAD --from origin/$CI_MERGE_REQUEST_TARGET_BRANCH_NAME --output delta-folder/ --generate-delta but no files are being generated at the destination folder

### What is the parameter and the value you used with it?

sfdx sgd:source:delta --to HEAD --from origin/$CI_MERGE_REQUEST_TARGET_BRANCH_NAME --output delta-folder/ --generate-delta

### What is the expected result?

Have modified files saved on delta-folder

### What is the actual result?

folder is empty

## Steps to reproduce

---

## Execution context

---

**Operating System:** …

**yarn version:** …

**node version:** …

**git version:** …

**sfdx version:** …

**sgd plugin version:** …

## More information (optional)

---

**Comment by scolladon** [comment]
Hi @willianpaulop !

Thanks for raising this issue and helping plugin to get better.

Could you help us reproduce the issue please ?
Provide your pipeline yaml file and also what kind of changes were not catched by the plugin in this context (`git diff --name-status --no-renames $CI_MERGE_REQUEST_TARGET_BRANCH_NAME HEAD`

Something you could try very fast is to make sure the whole repository is cloned (and not only the last commit) in the CI context. This is usually not the case automatically

**Comment by mehdisfdc** [comment]
Did you properly fetch origin in your pipeline?
`git fetch origin "+refs/heads/*:refs/remotes/origin/*"`

**Comment by willianpaulop** [comment]
Hi @scolladon 
Here's my yaml file
[gitlab.docx](https://github.com/scolladon/sfdx-git-delta/files/9583312/gitlab.docx)

and here is a highlight of where the issue should be, btw I'm running it in gitlab pipeline:
`function deploy_metadata() {

    local org_username=$1
    local check_only=" "

    if [ ! $org_username ]; then
      echo "ERROR No org username provided to 'deploy_metadata' function" >&2
      exit 1;
    fi
    if [ $DELTA_DEPLOY == "true" ]; then
      calculateDelta
      if [ ! $source_folder ]; then
        source_folder=$(cat sfdx-project.json | jq -r '.packageDirectories[] | select(.path=="delta-folder") | .path') //the folder is empty here
        echo "setting source folder as delta folder " $source_folder
      fi
    fi

    # Check for default package directory in sfdx-project.json
    if [ ! $source_folder ]; then
      source_folder=$(cat sfdx-project.json | jq -r '.packageDirectories[] | select(.default==true) | .path')
      echo "setting source folder as default folder " $source_folder
    fi
    if [ ! $source_folder ]; then
      echo "no default package directory found, defaulting to first package directory listed in sfdx-project.json" >&2
      cat sfdx-project.json >&2
    fi
    echo "sfdx-project content $(<sfdx-project.xml)"
    # Check for any package directory in sfdx-project.json
    if [ ! $source_folder ]; then
      echo "no default package directory found, defaulting to first package directory listed in sfdx-project.json" >&2
      cat sfdx-project.json >&2
      source_folder=$(cat sfdx-project.json | jq -r '.packageDirectories | .[0] | .path')
    fi

    # Giving up
    if [ ! $source_folder ]; then
      echo "ERROR Default package directory not specified. Specify a default package directory in sfdx-project.json." >&2
      exit 1
    fi
    echo "source folder " $source_folder
    #Run checkonly in merge requests to develop branch
    if [[ $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_JOB_NAME != 'deploy-sit-metadata' ]]; then
      check_only='--checkonly'
    fi

    local cmd="sfdx force:source:deploy --targetusername $org_username --sourcepath $source_folder --wait 120 -l RunLocalTests $check_only --json" && (echo $cmd >&2)

    local output=$($cmd)
    local return_message="$(jq -r '.result.success' <<< $output)"
    echo "test " $return_message
    if [ $return_message == "false" ]; then
      echo "ERROR Deploying metadata, check Salesforce for more info" >&2
      exit 1
    fi
  ```
}

  function install_delta_tool() {
    echo y | sfdx plugins:install sfdx-git-delta@5.3.1
  }

  function calculateDelta() {  
    local check_only=" "
    echo "Calculate changes with sfdx-git-delta..."
    git fetch origin "+refs/heads/*:refs/remotes/origin/*"
    mkdir -p delta-folder
    rm -fr delta-folder/*
    if [ $CI_PIPELINE_SOURCE == "merge_request_event" ]; then
      echo "setting delta on merge request created"
      sfdx sgd:source:delta --to HEAD --from origin/$CI_MERGE_REQUEST_TARGET_BRANCH_NAME --output delta-folder/ --generate-delta
    else  
      echo "setting delta on merge request approved"
      sfdx sgd:source:delta --to HEAD --from HEAD^ --output delta-folder/ --generate-delta
    fi
    #sfdx sgd:source:delta --to HEAD --from origin/$CI_MERGE_REQUEST_TARGET_BRANCH_NAME --output delta-folder/ --generate-delta
    ls
    ls delta-folder/force-app/main/*/*
    echo "current folder $PWD"
    echo "package content $(<delta-folder/package/package.xml)"

  }`
```

Diff:

`A	.gitlab-ci.yml
M	force-app/.DS_Store
D	force-app/Apex-Test-Tracker/force-app/main/default/classes/CI_ConfigWrapper.cls
D	force-app/Apex-Test-Tracker/force-app/main/default/classes/CI_ConfigWrapper.cls-meta.xml
D	force-app/Apex-Test-Tracker/force-app/main/default/classes/CI_NotTestClass.cls
D	force-app/Apex-Test-Tracker/force-app/main/default/classes/CI_NotTestClass.cls-meta.xml
D	force-app/Apex-Test-Tracker/force-app/main/default/classes/CI_ScheduledDispatcher.cls
D	force-app/Apex-Test-Tracker/force-app/main/default/classes/CI_ScheduledDispatcher.cls-meta.xml
D	force-app/Apex-Test-Tracker/force-app/main/default/classes/CI_Support.cls
D	force-app/Apex-Test-Tracker/force-app/main/default/classes/CI_Support.cls-meta.xml
D	force-app/Apex-Test-Tracker/force-app/main/default/classes/CI_TestCIOperations.cls
D	force-app/Apex-Test-Tracker/force-app/main/default/classes/CI_TestCIOperations.cls-meta.xml
D	force-app/Apex-Test-Tracker/force-app/main/default/classes/CI_TestCIOperations2.cls
D	force-app/Apex-Test-Tracker/force-app/main/default/classes/CI_TestCIOperations2.cls-meta.xml
D	force-app/Apex-Test-Tracker/force-app/main/default/email/Apex_Test_Tracker.emailFolder-meta.xml
D	force-app/Apex-Test-Tracker/force-app/main/default/email/Apex_Test_Tracker/Default_TestTracker_Notification.email
D	force-app/Apex-Test-Tracker/force-app/main/default/email/Apex_Test_Tracker/Default_TestTracker_Notification.email-meta.xml
D	force-app/Apex-Test-Tracker/force-app/main/default/layouts/CI_TestResult__c-CI_TestResult Layout.layout-meta.xml
D	force-app/Apex-Test-Tracker/force-app/main/default/objects/CI_Configuration__c/CI_Configuration__c.object-meta.xml
D	force-app/Apex-Test-Tracker/force-app/main/default/objects/CI_Configuration__c/fields/Archive_Days__c.field-meta.xml
D	force-app/Apex-Test-Tracker/force-app/main/default/objects/CI_Configuration__c/fields/Last_Test_Request__c.field-meta.xml
D	force-app/Apex-Test-Tracker/force-app/main/default/objects/CI_Configuration__c/fields/Notification_Email__c.field-meta.xml
D	force-app/Apex-Test-Tracker/force-app/main/default/objects/CI_Configuration__c/fields/Test_Delay__c.field-meta.xml
D	force-app/Apex-Test-Tracker/force-app/main/default/objects/CI_TestResult__c/CI_TestResult__c.object-meta.xml
D	force-app/Apex-Test-Tracker/force-app/main/default/objects/CI_TestResult__c/fields/ClassID__c.field-meta.xml
D	force-app/Apex-Test-Tracker/force-app/main/default/objects/CI_TestResult__c/fields/Message__c.field-meta.xml
D	force-app/Apex-Test-Tracker/force-app/main/default/objects/CI_TestResult__c/fields/Namespace__c.field-meta.xml
D	force-app/Apex-Test-Tracker/force-app/main/default/objects/CI_TestResult__c/fields/Pass__c.field-meta.xml
D	force-app/Apex-Test-Tracker/force-app/main/default/objects/CI_TestResult__c/fields/Summary_Record__c.field-meta.xml
D	force-app/Apex-Test-Tracker/force-app/main/default/objects/CI_TestResult__c/fields/Test_Name__c.field-meta.xml
D	force-app/Apex-Test-Tracker/force-app/main/default/objects/CI_TestResult__c/listViews/All.listView-meta.xml
D	force-app/Apex-Test-Tracker/force-app/main/default/workflows/CI_TestResult__c.workflow-meta.xml
M	force-app/main/.DS_Store
A	force-app/main/APEX_TEST_TRACKER/force-app/main/default/classes/CI_ConfigWrapper.cls
A	force-app/main/APEX_TEST_TRACKER/force-app/main/default/classes/CI_ConfigWrapper.cls-meta.xml
A	force-app/main/APEX_TEST_TRACKER/force-app/main/default/classes/CI_NotTestClass.cls
A	force-app/main/APEX_TEST_TRACKER/force-app/main/default/classes/CI_NotTestClass.cls-meta.xml
A	force-app/main/APEX_TEST_TRACKER/force-app/main/default/classes/CI_ScheduledDispatcher.cls
A	force-app/main/APEX_TEST_TRACKER/force-app/main/default/classes/CI_ScheduledDispatcher.cls-meta.xml
A	force-app/main/APEX_TEST_TRACKER/force-app/main/default/classes/CI_Support.cls
A	force-app/main/APEX_TEST_TRACKER/force-app/main/default/classes/CI_Support.cls-meta.xml
A	force-app/main/APEX_TEST_TRACKER/force-app/main/default/classes/CI_TestCIOperations.cls
A	force-app/main/APEX_TEST_TRACKER/force-app/main/default/classes/CI_TestCIOperations.cls-meta.xml
A	force-app/main/APEX_TEST_TRACKER/force-app/main/default/classes/CI_TestCIOperations2.cls
A	force-app/main/APEX_TEST_TRACKER/force-app/main/default/classes/CI_TestCIOperations2.cls-meta.xml
A	force-app/main/APEX_TEST_TRACKER/force-app/main/default/email/Apex_Test_Tracker.emailFolder-meta.xml
A	force-app/main/APEX_TEST_TRACKER/force-app/main/default/email/Apex_Test_Tracker/Default_TestTracker_Notification.email
A	force-app/main/APEX_TEST_TRACKER/force-app/main/default/email/Apex_Test_Tracker/Default_TestTracker_Notification.email-meta.xml
A	force-app/main/APEX_TEST_TRACKER/force-app/main/default/layouts/CI_TestResult__c-CI_TestResult Layout.layout-meta.xml
A	force-app/main/APEX_TEST_TRACKER/force-app/main/default/objects/CI_Configuration__c/CI_Configuration__c.object-meta.xml
A	force-app/main/APEX_TEST_TRACKER/force-app/main/default/objects/CI_Configuration__c/fields/Archive_Days__c.field-meta.xml
A	force-app/main/APEX_TEST_TRACKER/force-app/main/default/objects/CI_Configuration__c/fields/Last_Test_Request__c.field-meta.xml
A	force-app/main/APEX_TEST_TRACKER/force-app/main/default/objects/CI_Configuration__c/fields/Notification_Email__c.field-meta.xml
A	force-app/main/APEX_TEST_TRACKER/force-app/main/default/objects/CI_Configuration__c/fields/Test_Delay__c.field-meta.xml
A	force-app/main/APEX_TEST_TRACKER/force-app/main/default/objects/CI_TestResult__c/CI_TestResult__c.object-meta.xml
A	force-app/main/APEX_TEST_TRACKER/force-app/main/default/objects/CI_TestResult__c/fields/ClassID__c.field-meta.xml
A	force-app/main/APEX_TEST_TRACKER/force-app/main/default/objects/CI_TestResult__c/fields/Message__c.field-meta.xml
A	force-app/main/APEX_TEST_TRACKER/force-app/main/default/objects/CI_TestResult__c/fields/Namespace__c.field-meta.xml
A	force-app/main/APEX_TEST_TRACKER/force-app/main/default/objects/CI_TestResult__c/fields/Pass__c.field-meta.xml
A	force-app/main/APEX_TEST_TRACKER/force-app/main/default/objects/CI_TestResult__c/fields/Summary_Record__c.field-meta.xml
A	force-app/main/APEX_TEST_TRACKER/force-app/main/default/objects/CI_TestResult__c/fields/Test_Name__c.field-meta.xml
A	force-app/main/APEX_TEST_TRACKER/force-app/main/default/objects/CI_TestResult__c/listViews/All.listView-meta.xml
A	force-app/main/APEX_TEST_TRACKER/force-app/main/default/workflows/CI_TestResult__c.workflow-meta.xml`

**Comment by willianpaulop** [comment]
> Did you properly fetch origin in your pipeline? `git fetch origin "+refs/heads/*:refs/remotes/origin/*"`

yes, I did

**Comment by scolladon** [comment]
@willianpaulop 

The git diff result displayed comes from the CI execution ? Or from your local ? (We need the one in the CI)
The sgd version used is 5.3.1, could you move it to the current latest (5.4.2) please ? (I don't think it will fix the issue but it will be easier to debug)
I cannot see how the repository is cloned in the pipeline description. Could you show us how it is done? (sgd needs the full repository to be cloned in order to be able to run the comparison, often CIs fetch only the commit they need for optimization sake. We really need to make sure this step is checked before going any further)
Could it be an issue with the user rights here? (cf this [discussion](https://github.com/scolladon/sfdx-git-delta/issues/315) for jenkins and github action with docker image)

**Comment by willianpaulop** [comment]
Hi @scolladon there was a typo in my yml file 😬  thanks for the help
