### ISSUE TITLE
sgd --to "HEAD" --from SHA not generating delta files

### ISSUE THREAD

**Issue by Renan-Mastropaolo** [scolladon/sfdx-git-delta#356]
Issue verification check:

- [x] is the current repository fully deployable at the commit SHA provided with the 'from' parameter of the command?

## What is the problem?

---

Currently on our CI/CD process, every time we have a commit a new pipeline is started with deployment to DEV and UAT environments. During our deployment jobs, we run the command sgd --to "HEAD" --from "$BranchTag" --output builds/incremental --generate-delta where $BranchTag is the commit SHA of the first commit of current branch.
The problem is, when developers start to commit a lot of files (100+ commits with multiple files modified in each commit), the sgd command start to fail (the command runs, but no delta files are returned), but on the output there is no error. 

### What is the parameter and the value you used with it?

sgd --to "HEAD" --from $BranchTag  --output builds/incremental --generate-delta ($BranchTag -----> first command of current branch)

### What is the expected result?

All files modified between $BranchTag and HEAD

### What is the actual result?

Nothing is generated at patch builds/incremental

## Steps to reproduce

---

  Sorry, I can not provide the repo, since it is private.
  Create a branch, make a initial commit and save it's SHA.
  Modify some files and create a commit for each file, revert some commits in the process.
  Run sgd --to "HEAD" --from $initCommitSHA --output builds/incremental --generate-delta
  sgd should fail, but no error message on output.

## Execution context

---

Operating System: Linux

yarn version: N/A

node version: v16.16.0

git version: 2.17.1

sfdx version: sfdx-cli/7.163.0 linux-x64 node-v16.16.0

sgd plugin version: 4.7.0 (npm install sfdx-git-delta@4.7.0 --global)

## More information (optional)

---

git diff --name-status --no-renames "$BranchTag":
fatal: ambiguous argument '9ad707a7': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

**Comment by scolladon** [comment]
Hi @Renan-Mastropaolo !

Thanks for raising this issue, thanks for you help making the plugin better.

I have a couple of questions:

- Is it reproducible on your local machine ? Does sgd output is empty as well ?
- What is the CI/CD here ? Can you show its configuration ?
- Are you aware of [this](https://github.com/scolladon/sfdx-git-delta#cicd-specificity) CI/CD specificity ? Does the CI/CD configuration enforce it ?
- Usually, CI/CD clone the repository without history, they clone only the last commit (for performance). It is up to the script to tell how much history (depth) it needs. For [exemple for github action](https://github.com/actions/checkout#fetch-all-history-for-all-tags-and-branches). If this depth check is not done, sgd does not have material to do the comparison. How do you handle that aspect ?

**Comment by Renan-Mastropaolo** [comment]
Hello @scolladon
Thank you for your help, your last suggestion was the point that we were missing, our CI/CD only fetched about 50 past commits, after the 50th commit, sgd and git diff failed. We configured our deployment jobs to fetch more commits and it is now working as expected. Thanks a lot for your help and quick response.
