### ISSUE TITLE
dynamic api version

### ISSUE THREAD

**Issue by danielperrella** [scolladon/sfdx-git-delta#362]
### Is your proposal related to a problem?

The plug-in api is currently set at 52, currently flows have implemented new tags that are impossible to deploy with this version.

### Describe a solution you propose

---

Get the current api version dynamically from the sfdx-project.json project file in the 'sourceApiVersion' field and implement an additional parameter to the plug-in

**Comment by scolladon** [comment]
Hi @danielperrella!

Thanks for this very nice suggestion!

I understand that you want the api version used by the plugin to be driven by the `sourceApiVersion` in the file `sfdx-project.json` in the repository, using a new parameter. Great idea.

## Here is how I see that in term of feature:

### Solution 1
When `--api-version` is set then use this version
Else try to find the sourceApiVersion from the `sfdx-project.json`
If the API version found is not handled by the plugin then use the default and log a warning in the result

### Solution 2
When `--api-version` is set then use this version it is the main override
If not handled by the plugin then throw an error

Add a new parameter to tell the plugin to get the sourceApiVersion from the `sfdx-project.json`
If not possible or not handled by the plugin then throw an error

If both parameter are used, `--api-version` takes over

## Questions
It is weird that you cannot get version above 52, we are proposing until 55.
What is the sgd version you are using?

**Comment by mehdisfdc** [comment]
Thank you @danielperrella for proposing this enhancement. 
It's indeed a great idea not to have the API version harcoded in the plugin.

@scolladon I like you solution 1. As a developer that's the way I would expect the plugin to behave (i.e. "it just works").

**Comment by scolladon** [comment]
@danielperrella a [new release](https://github.com/scolladon/sfdx-git-delta/releases/tag/v5.6.0) is ready with this feature!

You can install it by installing the `latest-rc` tag.

```sh
$ sfdx plugins:install sfdx-git-delta@latest-rc 
```

We use the `release candidate` tag for new features before make it latest to make sure it is really stable.
