### ISSUE TITLE
Add BatchProcessJobDefinition metadata

### ISSUE THREAD

**Issue by domimpact** [scolladon/sfdx-git-delta#363]
### Is your proposal related to a problem?

When I do delta for a project which contains BatchProcessJobDefinition metadata it doesn't generate section for this type in package.xml.

### Describe a solution you propose

Update plugin so it supports BatchProcessJobDefinition metadata https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_batchprocessjobdefinition.htm

Thanks!

**Comment by scolladon** [comment]
Hi @domimpact 

Thanks for this enhancement!

We will integrate it soon, stay tuned.

**Comment by scolladon** [comment]
We just released the version 5.5.1 @domimpact 
You can install it using the `latest-rc` tag:
```sh
$ sfdx plugins:install sfdx-git-delta@latest-rc
```

Let us know if everything is working following the expectations, we will make it the `latest`

**Comment by domimpact** [comment]
Hi @scolladon . It works well now, thank you!
