### ISSUE TITLE
Deployment fails when deleting a flow

### ISSUE THREAD

**Issue by jdgirald** [scolladon/sfdx-git-delta#366]
Issue verification check:

- [x] is the current repository fully deployable at the commit SHA provided with the 'from' parameter of the command?

## What is the problem?

I deleted a flow from our repo (Account_ACU_Update) and then we ran the command `sfdx sgd:source:delta -f $MERGE_BASE -s src --output output` and it created a destructiveChanges.xml with a flow element. 

```
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>Account_ACU_Update</members>
        <name>Flow</name>
    </types>
    <version>54.0</version>
</Package>
```

If I try to deploy it with `sfdx force:source:deploy --checkonly -x output/package/package.xml --postdestructivechanges=output/destructiveChanges/destructiveChanges.xml ` I get the following error:

Error   Account_ACU_Update insufficient access rights on cross-reference id

### What is the expected result?

Flow deleted from org or not added to destructiveChanges.xml

### What is the actual result?

Error   Account_ACU_Update insufficient access rights on cross-reference id

**Comment by scolladon** [comment]
Hi @jdgirald 

Thanks for raising this issue!

I think it is related to this [Salesforce issue](https://trailblazer.salesforce.com/issues_view?id=a1p4V000002KI7bQAG&title=support-deletion-of-flow-metadata-through-destructive-changes)

The solution/workaround they are suggesting is to add the flow version in the `destructiveChanges.xml` instead
Is it possible in your workflow/repo to have the version in the flow file name when adding them in your repository ?

**Comment by jdgirald** [comment]
Thanks @scolladon, looks like is a salesforce limitation.

Since we use the destructiveChanges.xml in automatic deployments, I don't think is possible to add the flow version to the file manually. We could somehow query the version number, but still, I guess the flow version might be different between environments.

For now, I think the workaround is to add flows to the ignore-destructive file, so they are not added to the `destructiveChanges.xml`.

**Comment by scolladon** [comment]
I see it is [not possible anymore](https://docs.copado.com/articles/#!copado-ci-cd-publication/how-to-deploy-flows-using-salesforce-api-version-v-44-0) to retrieve flow file with their version number.

I was using this trick in a previous project: retrieving flow with their version number and deploying them with their version.
I solved our problem at that time which was to know which version is enabled.
But it had also some downside: 

- number of flow version limitation => requires to delete them, in all environment (or having a refresh strategy)
- development workflow need to commit only the next one (if I had to create n version of flow during dev, I need to change the flow version I commit to be the next number compared to the code base so everyone is aligned)

Anyway, it seems to not be possible anymore...
Lets watch this [issue](https://trailblazer.salesforce.com/issues_view?id=a1p4V000002KI7bQAG&title=support-deletion-of-flow-metadata-through-destructive-changes) closely and adapt depending on the fix

**Comment by aheber** [comment]
There is some light at the end of the tunnel but I don't think you can do it in isolation.

To Delete a Flow you have to...
1. Find all the versions in the org: `SELECT Id, Definition.DeveloperName, VersionNumber, Status FROM Flow WHERE Definition.DeveloperName IN ('${queryString}')` where `queryString` is the name extracted from the deleted file names.
2. For each discovered version, add it to the `destructiveChanges[Post].xml` as a `Flow` type with a member name similar to `<members>${version.Definition.DeveloperName}-${version.VersionNumber}</members>`

If the change is just deactivating a Flow, you should be able to do that in isolation. 
Just add a "FlowDefinition" to the resulting package that has something like this
```
<?xml version="1.0" encoding="UTF-8"?>
<FlowDefinition xmlns="http://soap.sforce.com/2006/04/metadata">
    <activeVersionNumber>0</activeVersionNumber>
</FlowDefinition>
```
(I realize that is adding metadata to the file system which isn't really what SGD does)

We have these actions scripted as companions to the generated metadata produced by SGD and that is working well enough for us.

Not sure what to do with that information as I feel like both of those actions have new behavior impacts for SGD, though I'd be perfectly happy not to have a custom script on top to handle these.

**Comment by scolladon** [comment]
Thanks @aheber for this very nice solution and details about it.

SGD purpose is to deal with the metadata in the repo, and it does not query the content of the orgs. Getting all the flow version would require a significant change in the role of this plugin and its architecture (the sgd plugin does not require connection to the org).
So at this point if you want to automate flow deletion this would have to be achieved through another plugin (this [one](https://hardisgroupcom.github.io/sfdx-hardis/hardis/org/purge/flow/) per exemple) or a custom script (at least until [Known Issue](https://trailblazer.salesforce.com/issues_view?id=a1p4V000002KI7bQAG&title=support-deletion-of-flow-metadata-through-destructive-changes) is here).

From my experience, there are multiple ways to deal with this situation and I have seen it differently implemented in different project with different outcome in term of result, developer experience and release experience.
The main question is where the team want to put the burden...

**Comment by aheber** [comment]
Completely understand and support the direction.
