### ISSUE TITLE
TypeError: Invalid Version: 3.31.04 [app version 5.5.0]

### ISSUE THREAD

**Issue by jfaderanga** [scolladon/sfdx-git-delta#368]
## What is the problem?

---

Executed the command to generate a simple delta request right after installation and get the error "TypeError: Invalid Version: 3.31.04"

### What is the parameter and the value you used with it?

sfdx sgd:source:delta --to "HEAD" --from "HEAD^" --output delta/ --generate-delta

### What is the expected result?

It should generate delta components in the delta folder

### What is the actual result?

throws and error "TypeError: Invalid Version: 3.31.04"

## Steps to reproduce

---
1. Install the plugin,  echo y | sfdx plugins:install sfdx-git-delta
2. Create a dir, mkdir delta
3. Generate delta, sfdx sgd:source:delta --to "HEAD" --from "HEAD^" --output delta/ --generate-delta
4. Error thrown

**Operating System:** windows

**node version:** v14.18.1

**git version:** 2.32.0

**sfdx version:**  7.152.0

**sgd plugin version:** 5.5.0

**Comment by chrispangg** [comment]
We have also encountered the same bug

**Comment by TonyWhiteSMS** [comment]
Having the same issue, interestingly 
sgd plugin version: 5.5.0
was working yesterday...

But we did note a bunch of version warnings...

**Comment by guan-tay** [comment]
i encountered that too
![image](https://user-images.githubusercontent.com/84484937/195462889-b547a35e-a50b-4ae4-bb20-32d7a6992ebb.png)

**Comment by brytonpilling** [comment]
Possibly related to this sfdx change? The package.json version jumped from 3.30.14 to 3.31.04 strangely.

https://github.com/forcedotcom/sfdx-core/commit/7bb86ff6209ccc5749f3ac9d774baa1693158246

**Comment by jvitorinoj** [comment]
The same problem here, even installing an older version

`echo y |sfdx plugins:install sfdx-git-delta@v5.4.2`

<img width="518" alt="image" src="https://user-images.githubusercontent.com/31418573/195465792-019250cf-0cad-4030-a8e1-6214800a8899.png">

**Comment by stadisina** [comment]
All our projects have same issue, so the pipeline deployments all blocked. But Deploying from vscode works fine

**Comment by stadisina** [comment]
may be issue with the version number is referenced wrong 3.31.04 instead of 3.31.4. 

Just a thought since npm website version is different here 
https://www.npmjs.com/package/@salesforce/core/v/3.31.4

**Comment by stadisina** [comment]
> it was working on my local machine until I tried re-installing it which upgrades it to 5.5.0 - now even if I tried to downgrade to 5.2.0 it still not working..

in my local it still works fine with this command, it generating the delta.
 **_sfdx sgd:source:delta --to origin/UAT --from origin/master --output delta-package_**

**Comment by brytonpilling** [comment]
Okay, so I was able to do a successful pipeline run if I changed my docker image being used from latest ( which uses the sfdx version 1.172.0 which was released this morning ) to a specific version a week old or so. So I am pretty sure this is related to the sfdx version update and htis plugin not being able to handle the version change.

https://github.com/forcedotcom/cli/blob/main/releasenotes/sfdx/README.md

**Comment by brytonpilling** [comment]
Sorry, my explanation probably wasn't very clear. We run a docker image from sfdx, and that was updated to no longer reference latest. Then we have a line in our bitbucket pipeline to install this plugin... so because the sfdx cli was older, the version is 3.30.12, which of course doesn't cause any problems.

**Comment by cromwellryan** [comment]
Thank you to @jfaderanga for reporting this issue and for @brytonpilling for his comments on [the offending commit in @salesforce/core](https://github.com/forcedotcom/sfdx-core/commit/7bb86ff6209ccc5749f3ac9d774baa1693158246).

We have resolved he underlying issue. Please see [this message](https://github.com/forcedotcom/sfdx-core/issues/677#issuecomment-1276940798) on the canonical sfdx issue for more details.

**Comment by mehdisfdc** [comment]
Thank you @jfaderanga and @brytonpilling for your identifying the issue and contributing to the resolution!

And thank you so much @cromwellryan for having resolved it so fast, and shared the updates here!

**Comment by scolladon** [comment]
+100 for what @mehdisfdc says
Amazing community here ❤️
