### ISSUE TITLE
  TypeError: Invalid Version: 3.31.04

### ISSUE THREAD

**Issue by pgonzaleznetwork** [scolladon/sfdx-git-delta#371]
Issue verification check:

- [ ] is the current repository fully deployable at the commit SHA provided with the 'from' parameter of the command?

## What is the problem?

---

I have multiple users using a pre-defined YAML file that uses the following syntax

https://github.com/pgonzaleznetwork/dreamforce22-org/blob/main/.github/workflows/validate-deployment-on-pull-request-development.yml

### What is the parameter and the value you used with it?

 sfdx sgd:source:delta --to "HEAD" --from "HEAD^" --output changed-sources/ --generate-delta --source force-app/

### What is the expected result?

Should produced output file

### What is the actual result?

Throws this error

TypeError: Invalid Version: 3.31.04

**Comment by mehdisfdc** [comment]
Hi @pgonzaleznetwork.
Have you tried updating the Salesforce CLI to the latest version?
There was an issue with a specific version of the Salesforce CLI, that has been been fixed yesterday evening. 
See https://github.com/scolladon/sfdx-git-delta/issues/368

**Comment by pgonzaleznetwork** [comment]
Thank you @mehdisfdc , if you look at the YAML file I provided, I'm already downloading the stable release of the CLI. Can you confirm this is what you would expect to see? 

        ```
 wget https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable/sfdx-linux-x64.tar.xz
          mkdir ~/sfdx
          tar xJf sfdx-linux-x64.tar.xz -C ~/sfdx --strip-components 1
          echo "$HOME/sfdx/bin" >> $GITHUB_PATH
          ~/sfdx/bin/sfdx version
```

**Comment by vaibhavdangar-woolies** [comment]
Just for information:
Works fine with earlier sfdx version in Docker image: **salesforce/salesforcedx:7.159.0-full**
 sfdx-cli/7.159.0 linux-x64 node-v16.13.2
 @salesforce/cli/1.36.0 linux-x64 node-v16.13.2

**Comment by mehdisfdc** [comment]
@pgonzaleznetwork Could you check which version you are actually running?
`sfdx --version`

**Comment by pgonzaleznetwork** [comment]
The person who reported the issue to me (I wasn't able to reproduce it) told me they fixed this by upgrading this to actions from v2 to v3

![Screenshot 2022-10-17 at 09 45 11](https://user-images.githubusercontent.com/8467087/196132350-f26bf344-f820-4d19-b1af-846c1631ea7f.png)

Any idea why that would fix it?

**Comment by mehdisfdc** [comment]
@pgonzaleznetwork No idea, sorry, but I'm not well versed into Github Actions.
