### ISSUE TITLE
Github action fails and returns - "error": "--to is not a valid sha pointer: \"HEAD\", --from is not a valid sha pointer: \"origin/develop\""

### ISSUE THREAD

**Issue by peter-caitens** [scolladon/sfdx-git-delta#373]
When I run the command to compare the changes in my repository the command is returning the following error:
```
force-app/ --ignore build-settings/deployIgnore --ignore-destructive build-settings/destructiveIgnore
{
  "error": "--to is not a valid sha pointer: \"HEAD\", --from is not a valid sha pointer: \"origin/develop\"",
  "output": "deployFolder",
  "success": false,
  "warnings": []
}
```
Can anyone please help in getting my pipeline working again?

### What is the parameter and the value you used with it?
**export HOME=/root && sfdx sgd:source:delta --from origin/develop --to HEAD --output deployFolder --generate-delta --source** 

When I run the command to get the git diff I get the following result:
**git diff --name-status --no-renames origin/develop HEAD**

error: Could not access 'origin/develop'

### What is the expected result?
It was previously working where it would output the changes between the branches into the folder deployFolder.

## Steps to reproduce
This is the contents of my docker file used to build the image to run on. The docker image is run from a github action.
```
FROM node:lts-alpine

ENV PATH="${PATH}:/sbin"

RUN apk add --update --no-cache  git findutils bash unzip curl wget npm openjdk8-jre openssh-client perl jq sed tree

RUN npm install sfdx-cli --global
RUN sfdx --version

ENV XDG_DATA_HOME=/sfdx_plugins/.local/share
ENV XDG_CONFIG_HOME=/sfdx_plugins/.config
ENV XDG_CACHE_HOME=/sfdx_plugins/.cache

RUN echo y | sfdx plugins:install sfdx-git-delta
RUN sfdx plugins
RUN env
```
---

## Execution context
**Operating System:** …
github action

**git --version**
git version 2.36.2

**sfdx version**
sfdx-cli/7.172.0 linux-x64 node-v16.18.0

**sfdx plugins**
sfdx-git-delta 5.5.0

**env**
GITHUB_WORKSPACE=/__w/salesforce-core/salesforce-core
HOSTNAME=2c7e5792faeb
GITHUB_PATH=/__w/_temp/_runner_file_commands/add_path_4b1cd2[6](https://github.com/verteva/salesforce-core/actions/runs/3261908722/jobs/5357834820#step:5:6)6-9307-4ff5-9406-74b1cf766b01
GITHUB_ACTION=__run
YELLOW_TEXT=\033[1;33m
GITHUB_RUN_NUMBER=2763
RUNNER_NAME=Hosted Agent
XDG_DATA_HOME=/sfdx_plugins/.local/share
SLACK_BOT_TOKEN=***
XDG_CONFIG_HOME=/sfdx_plugins/.config
GITHUB_TRIGGERING_ACTOR=peter-caitens
GITHUB_REF_TYPE=branch
**YARN_VERSION=1.22.19**
***
RED_TEXT=\033[0;31m
GITHUB_ACTIONS=true
GITHUB_SHA=44fd2f56118e663e11a3599a98ef7109be663e10
GITHUB_REF=refs/pull/864/merge
RUNNER_OS=Linux
GITHUB_REF_PROTECTED=false
HOME=/github/home
GITHUB_API_URL=https://api.github.com
RUNNER_ARCH=X64
RUNNER_TEMP=/__w/_temp
GREEN_TEXT=\033[0;32m
GITHUB_STATE=/__w/_temp/_runner_file_commands/save_state_4b1cd266-9307-4ff5-9406-74b1cf766b01
GITHUB_ENV=/__w/_temp/_runner_file_commands/set_env_4b1cd266-9307-4ff5-9406-74b1cf766b01
GITHUB_EVENT_PATH=/github/workflow/event.json
GITHUB_EVENT_NAME=pull_request
GITHUB_RUN_ID=3261908722
GITHUB_STEP_SUMMARY=/__w/_temp/_runner_file_commands/step_summary_4b1cd266-9307-4ff5-9406-74b1cf766b01
FORCE_APP_FOLDER=force-app
XDG_CACHE_HOME=/sfdx_plugins/.cache
GITHUB_ACTOR=***
GITHUB_RUN_ATTEMPT=1
GITHUB_GRAPHQL_URL=https://api.github.com/graphql
DEPLOY_FOLDER=deployFolder
GITHUB_SERVER_URL=https://github.com
RESET_TEXT=\033[0m
SHLVL=1
RUNNER_TOOL_CACHE=/__t
GITHUB_REF_NAME=864/merge
GITHUB_JOB=cicd
GITHUB_REPOSITORY=verteva/salesforce-core
GITHUB_RETENTION_DAYS=90
RUNNER_WORKSPACE=/__w/salesforce-core
GITHUB_ACTION_REPOSITORY=
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/sbin
GITHUB_BASE_REF=develop
BLUE_TEXT=\033[0;34m
CI=true
GITHUB_REPOSITORY_OWNER=verteva
GITHUB_HEAD_REF=feature/BP-508-Tech-Debt-convert-Lead-apex-classes-to-fflib-standard
GITHUB_ACTION_REF=
**NODE_VERSION=16.18.0**
GITHUB_WORKFLOW=1. Feature Pipeline
GITHUB_OUTPUT=/__w/_temp/_runner_file_commands/set_output_4b1cd266-9307-4ff5-9406-74b1cf7666b01

## More information (optional)

I have just had to update my docker image base image from node:14 to node 16 as the sfdx install was failing due to missing package "node:os"

---

**Comment by scolladon** [comment]
Hi @peter-caitens 

Thanks for raising this very detailed issue.

I tried locally using node 16 and I do not reproduce.

What looks interesting to me is: "error: Could not access 'origin/develop'"
It looks like the folder where the command is run is not a git repository.
What reinforce this thinking is that even "HEAD" is not recognize as a git sha pointer, which is not possible to be the case if the folder is a git repository.

Maybe the command is not executed in the repository folder (which is weird as only the node version has changed on your side) ? Or the repository checkout is not done ? Or done after ?

**Comment by peter-caitens** [comment]
I run the `tree` command from the same location and I get a list of all the file in the repo including the .git folder and all it's contents.
I think it has something to do with being run from the github action and I can run the image locallly and the command works fine.

**Comment by peter-caitens** [comment]
Do you have any recommended docker files to use that are known to work with github actions?
Also, if I just run the command `sfdx sgd:source:delta ...` it says it can't find the command and asks if I meant `sfdx force:source:delete `(I think that is it from memory)

**Comment by scolladon** [comment]
We have a [discussion](https://github.com/scolladon/sfdx-git-delta/discussions/325) explaining how to deal with that
Can you go through it and let us know if it was useful in your situation?

**Comment by peter-caitens** [comment]
I had seen that discussion and incorporated the fix for Option 1 for Github actions without any success. To make sure I just ran a build. I still received a failed build.

**Docker File**
```
FROM  salesforce/salesforcedx:7.165.0-full

ENV DEBIAN_FRONTEND=noninteractive
ARG SFPOWERSCRIPTS_VERSION=alpha

ARG PMD_VERSION=${PMD_VERSION:-6.48.0}
ARG SFPOWERSCRIPTS_VERSION=alpha
ARG GIT_COMMIT

# update git & common packages
# Note: this installs the necessary libs to make the bundled version of Chromium that Puppeteer
# installs, work.
RUN apt-get update && apt-get install -qq software-properties-common \
    && add-apt-repository ppa:git-core/ppa -y  \
    &&  apt-get install -qq   \
        git \
        curl \
        sudo \
        jq \
        zip \
        unzip \
	    make \
        g++ \
        wget \
        gnupg \
        tree \
	    libxkbcommon-x11-0 libdigest-sha-perl  libxshmfence-dev \
        gconf-service libappindicator1 libasound2 libatk1.0-0 \
        libatk-bridge2.0-0 libcairo-gobject2 libdrm2 libgbm1 libgconf-2-4 \
        libgtk-3-0 libnspr4 libnss3 libx11-xcb1 libxcb-dri3-0 libxcomposite1 libxcursor1 \
        libxdamage1 libxfixes3 libxi6 libxinerama1 libxrandr2 libxshmfence1 libxss1 libxtst6 \
        fonts-liberation fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst fonts-freefont-ttf \
    && apt-get autoremove --assume-yes \
    && apt-get clean --assume-yes  \
    && rm -rf /var/lib/apt/lists/*

# Set XDG environment variables explicitly so that GitHub Actions does not apply
# default paths that do not point to the plugins directory
# https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html
ENV XDG_DATA_HOME=/sfdx_plugins/.local/share \
    XDG_CONFIG_HOME=/sfdx_plugins/.config  \
    XDG_CACHE_HOME=/sfdx_plugins/.cache \
    JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64/

#
# Create symbolic link from sh to bash
# Create isolated plugins directory with rwx permission for all users
# Azure pipelines switches to a container-user which does not have access
# to the root directory where plugins are normally installed
RUN ln -sf bash /bin/sh && \
    mkdir -p $XDG_DATA_HOME && \
    mkdir -p $XDG_CONFIG_HOME && \
    mkdir -p $XDG_CACHE_HOME && \
    chmod -R 777 sfdx_plugins && \
    export JAVA_HOME && \
    export XDG_DATA_HOME && \
    export XDG_CONFIG_HOME && \
    export XDG_CACHE_HOME

RUN git --version
RUN sfdx --version

#Set XDG environment variables explicitly so that GitHub Actions does not apply
#default paths that do not point to the plugins directory
#https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html
ENV XDG_DATA_HOME=/sfdx_plugins/.local/share
ENV XDG_CONFIG_HOME=/sfdx_plugins/.config
ENV XDG_CACHE_HOME=/sfdx_plugins/.cache

RUN echo 'y' | sfdx plugins:install sfdx-git-delta
```

**deploy.yml**
```
    steps:
      - name: Checkout Current Branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Compare changes to [${{ inputs.FROM_BRANCH }}] Branch
        run: |
          mkdir -p ${{ env.DEPLOY_FOLDER }}
          git --version
          sfdx version
          sfdx plugins
          env
          export HOME=/root && sfdx sgd:source:delta --from origin/${{ inputs.FROM_BRANCH }} --to HEAD --output ${{ env.DEPLOY_FOLDER }} --generate-delta --source ${{ env.FORCE_APP_FOLDER}}/ --ignore build-settings/deployIgnore --ignore-destructive build-settings/destructiveIgnore

```

**Results**
```
git version 2.38.0
 ›   Warning: sfdx-cli update available from 7.165.0 to 7.172.0.
sfdx-cli/7.165.0 linux-x64 node-v16.13.2
 ›   Warning: sfdx-cli update available from 7.165.0 to 7.172.0.
sfdx-git-delta 5.5.0
XDG_CONFIG_HOME=/sfdx_plugins/.config
GREEN_TEXT=\033[0;32m
HOSTNAME=7a049cfe745b
GITHUB_REF_NAME=864/merge
GITHUB_API_URL=https://api.github.com
GITHUB_STEP_SUMMARY=/__w/_temp/_runner_file_commands/step_summary_5061780c-1b22-49c2-9984-584ce7f83c60
GITHUB_RUN_ATTEMPT=1
RUNNER_TOOL_CACHE=/__t
JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64/
FORCE_APP_FOLDER=force-app
GITHUB_REPOSITORY_OWNER=verteva
GITHUB_ACTIONS=true
CI=true
GITHUB_HEAD_REF=feature/BP-508-Tech-Debt-convert-Lead-apex-classes-to-fflib-standard
GITHUB_ACTOR=peter-caitens
GITHUB_ACTION_REF=
GITHUB_ACTION=__run
GITHUB_REF_PROTECTED=false
***
HOME=/github/home
GITHUB_STATE=/__w/_temp/_runner_file_commands/save_state_5061780c-1b22-49c2-9984-584ce7f83c60
SFDX_CONTAINER_MODE=true
GITHUB_ACTION_REPOSITORY=
GITHUB_REF_TYPE=branch
RUNNER_TEMP=/__w/_temp
GITHUB_RETENTION_DAYS=90
GITHUB_ENV=/__w/_temp/_runner_file_commands/set_env_5061780c-1b22-49c2-9984-584ce7f83c60
DEBIAN_FRONTEND=noninteractive
BLUE_TEXT=\033[0;34m
RUNNER_WORKSPACE=/__w/salesforce-core
GITHUB_REF=refs/pull/864/merge
GITHUB_SHA=36fb4a5f6d707d653ae37ab244169204f56be2c7
GITHUB_RUN_ID=3264807452
RUNNER_ARCH=X64
YELLOW_TEXT=\033[1;33m
GITHUB_SERVER_URL=https://github.com
GITHUB_EVENT_PATH=/github/workflow/event.json
GITHUB_GRAPHQL_URL=https://api.github.com/graphql
RUNNER_OS=Linux
GITHUB_BASE_REF=develop
SHELL=/bin/bash
GITHUB_PATH=/__w/_temp/_runner_file_commands/add_path_5061780c-1b22-49c2-9984-584ce7f83c60
GITHUB_JOB=cicd
RUNNER_NAME=Hosted Agent
GITHUB_OUTPUT=/__w/_temp/_runner_file_commands/set_output_5061780c-1b22-49c2-9984-584ce7f83c60
SHLVL=1
GITHUB_REPOSITORY=verteva/salesforce-core
GITHUB_EVENT_NAME=pull_request
XDG_CACHE_HOME=/sfdx_plugins/.cache
XDG_DATA_HOME=/sfdx_plugins/.local/share
GITHUB_RUN_NUMBER=2767
RESET_TEXT=\033[0m
GITHUB_WORKFLOW=1. Feature Pipeline
PATH=/usr/local/lib/nodejs/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
GITHUB_WORKSPACE=/__w/salesforce-core/salesforce-core
SLACK_BOT_TOKEN=***
DEPLOY_FOLDER=deployFolder
GITHUB_TRIGGERING_ACTOR=peter-caitens
RED_TEXT=\033[0;31m
_=/usr/bin/env
 ›   Warning: sfdx-cli update available from 7.165.0 to 7.172.0.
{
  "error": "--to is not a valid sha pointer: \"HEAD\", --from is not a valid sha pointer: \"origin/develop\"",
  "output": "deployFolder",
  "success": false,
  "warnings": []
}
Error: Process completed with exit code 1.
```

**Comment by scolladon** [comment]
What I can see with a first reading is a `action/checkout@v2` using v2 instead of v3.
It seems to be the root cause of [another issue](https://github.com/scolladon/sfdx-git-delta/issues/371)

could you run this : `git diff --name-status --no-renames origin/${{ inputs.FROM_BRANCH }} HEAD` inside the `deploy.yml`, just after `env` for example.

Also, why are you using a docker image ? What is your specific need to have it running inside a docker image instead of using github action container ?

**Comment by peter-caitens** [comment]
I am using a docker image so as to avoid the time required to deploy the required software each time I run a build. I have a shell script that runs in order to run some processes on the list of changed elements. If there is another way I am happy to know about it.

I also updated the checkout to v3 and re-ran the build with the git diff command and it failed as before on the git diff command
```
error: Could not access 'origin/develop'
```

Thanks for trying to help out. I appreciate it.

**Comment by scolladon** [comment]
That's strange... what it says is: origin develop not present, even after a full checkout (fetchDepth 0)

How do you declare your docker in the github action yml ? 
Do you pass this option: `options: --user root` ?

**Comment by scolladon** [comment]
Have you tried with `options: --user root` ? 
Does it change anything ?

**Comment by peter-caitens** [comment]
Based on a comment you made I went back to just using the native github container and it all runs fine with everything I need in ubuntu-latest and the speed to install the software each time is comparable.
So I have dropped the idea and effort of trying to get it working in a docker image.

**Comment by scolladon** [comment]
Ok, got it.
Thanks for letting us know.

My POV about github action container vs docker:
- Using github action instead of docker allow to always use the latest version of the tools where docker image has to be updated to have the latest tools.
- Having fixed version inside a docker allow to be sure the tools are going to the way they always worked.
