### ISSUE TITLE
Offline install of sfdx-git-delta plug-in on host without any internet connection

### ISSUE THREAD

**Issue by amreshvijay** [scolladon/sfdx-git-delta#377]
### Discussed in https://github.com/scolladon/sfdx-git-delta/discussions/376

<div type='discussions-op-text'>

<sup>Originally posted by **amreshvijay** October 31, 2022</sup>
I want to install sfdx-git-delta plug-in on a host which doesn't have an internet connection.
Is there a way to download any corresponding package for this plugin and copy over to that particular host and install it?</div>

**Comment by mehdisfdc** [comment]
Closing the issue as it's not a supported use-case and it's being discussed in https://github.com/scolladon/sfdx-git-delta/discussions/376
