### ISSUE TITLE
The ignore option is not taken into account 

### ISSUE THREAD

**Issue by camillerev** [scolladon/sfdx-git-delta#383]
Issue verification check:

- [ ] is the current repository fully deployable at the commit SHA provided with the 'from' parameter of the command?

## What is the problem?

---
We are using sfdx-git-delta plugging for our Continuous Integration. We are using the ignore option. However, when we look at the construct package.xml, we can find files that we wanted to ignore.
(For example : our yml script are inside a folder called .github/workflows that we want to ignore and the package.xml contains the yml files as member of the workflows Salesforce metadata)
<img width="368" alt="image" src="https://user-images.githubusercontent.com/62376486/199776846-7993c006-310f-42d3-8dbe-818548bc47f3.png">

### What is the parameter and the value you used with it?

sfdx plugins:install sfdx-git-delta
sfdx sgd:source:delta -a 55 --to HEAD --from origin/master --output . -i manifest/mdapi/.sgdignore

.sgdignore:
**/audience/*
**/documents/*
**/installedPackage/*
.github/workflows
force-app/main/default/standardValueSets/CasePriority.standardValueSet-meta.xml
force-app/main/default/standardValueSetTranslations/CasePriority-fr.standardValueSetTranslation-meta.xml
force-app/main/default/objectTranslations/Case-fr/case_priority.fieldTranslation-meta.xml

### What is the expected result?

The package.xml doesn't contains the files in the ignore file.

### What is the actual result?

The package.xml contains the files in the ignore file.

## Steps to reproduce

---

1. Use the repo : https://github.com/camillerev/sfdx-delta-error-reproduction
2. Run : `git checkout feature/test`
3. Run : `sfdx plugins:install sfdx-git-delta@v5.6.0`
4. Run : `sfdx sgd:source:delta -a 55 --to HEAD --from origin/main --output . -i manifest/mdapi/.sgdignore`
5. Check the new file: package.xml
6. The file should not contain ci_test_validation.yml
Result:
<img width="431" alt="image" src="https://user-images.githubusercontent.com/62376486/199798111-221c4239-73af-4d3e-b64d-10f4c8e99685.png">

## Execution context

---

**Operating System:** MacOs 12.6.1

**yarn version:** …

**node version:**: v18.7.0

**git version:** : git version 2.30.2

**sfdx version:** : sfdx-cli/7.174.0

**sgd plugin version:** : 5.6.0

**Comment by scolladon** [comment]
Hi @camillerev 

Thanks for this very well defined issue, thanks for your help making the plugin better.

Following this issue we made the `latest` tag point to the `v5.5.0` (stable) so no further issue with the installation.

We are going to ship a fix shortly

Stay tuned

**Comment by scolladon** [comment]
Hi @camillerev 

We just released a new version containing the fix (`v5.7.0`).
It is available in the `latest-rc` release channel for now and will be included in the `latest` channel soon when it will be known as stable enough.

Could you test locally by installing the `latest-rc` version and let us know the result on your side ?
Here is how to install the `latest-rc` release channel : 
```sh
$ sfdx plugins:install sfdx-git-delta@release-rc
```

Happy incremental deployment

**Comment by camillerev** [comment]
Hello @scolladon ! I tried with the command `sfdx plugins:install sfdx-git-delta@latest-rc` (sfdx plugins:install sfdx-git-delta@release-rc didn't work I guess it was a typo), and everything seems to work 🎉 
There is no ignore files in the package.xml!! Thanks a lot for your fix! 🙌

**Comment by scolladon** [comment]
Nice catch for the typo, thanks @camillerev !
I update my comment

Thanks for trying it, we will move `latest` to this release when more confident
