### ISSUE TITLE
Package.xml file is empty when the branch has only 1 layout change

### ISSUE THREAD

**Issue by irfanlai** [scolladon/sfdx-git-delta#392]
Issue verification check:

- [x] is the current repository fully deployable at the commit SHA provided with the 'from' parameter of the command?
- [ ] Yes

## What is the problem?
When the branch consists of only a layout change then the package.xml is generated blank.
The following command in my YAML is generating an empty Package.xml. It will not generate any delta package and my validation will fail.
# Creates delta package using sfdx git delta
      - name: Create delta packages for new, modified or deleted metadata
        run: >
          mkdir changed-sources
          
          sfdx sgd:source:delta --to "HEAD" --from "HEAD^" --output changed-sources/ --generate-delta --source force-app/ 
---

### What is the parameter and the value you used with it?
          mkdir changed-sources
          
          sfdx sgd:source:delta --to "HEAD" --from "HEAD^" --output changed-sources/ --generate-delta --source force-app/

### What is the expected result?
There was 1 layout change and it should have shown that layout change in the XML

### What is the actual result?
55.0
ERROR running force:source:deploy:  The sourcepath "changed-sources/force-app" is not a valid source file path.
Error: Process completed with exit code 1.

## Steps to reproduce
Scenario 1: Only layout change in the PR
The YAML is executed when a PR is raised. 
It would install SFDXgit delta and then create the package which is basically empty.
When the deployment validation occurs that command fails because package.xml is empty.
Command for validation:
sfdx force:source:deploy -p "changed-sources/force-app" --checkonly --testlevel NoTestRun

If I merge the PR which will trigger deployment. The Deployment executes with nothing to deploy and the message is following.
---- No Salesforce Metadata changes to deploy ----
Command for deployment:
sfdx force:source:deploy -p "changed-sources/force-app" --testlevel NoTestRun

Scenario 2:
Commit 1: There is only 1 layout change
Actual Result: Package.XML is empty
Expected Result: Layout should have been added as the delta

Commit 2: Added 1 custom field
Actual Result: Package.XML only contains the new custom field and no layout
Expected Result: Layout and Custom filed should have been added as the delta

Commit 3: Added 1 more layout
Actual Result: Package.XML only contains the new custom field and no layouts
Expected Result:  2 Layout and 1 Custom filed should have been added as the delta

---

## Execution context

---

  Ubuntu
  20.04.5
sfdx-cli/7.178.0 linux-x64 node-v18.12.0
sfdx-git-delta 5.8.0

## More information (optional)

---

**Comment by irfanlai** [comment]
I want to update the issue. The bug is when the branch has only 1 layout change in the pull request. For some reason, the package.xml does not update layout in the delta changes hence the file is empty.

**Comment by mehdisfdc** [comment]
Hi @irfanlai . Thank you for sharing your issue.

I've got 2 questions for you to help us understand the cause:

1) Could you share the output of the following command (executed in the same context as SGD):
`$ git diff --name-status --no-renames <from> <to>
`
2) Are you able to reproduce this issue locally? If that's the case, could you please share with a sample repo to reproduce the issue (for example you could fork [this one](https://github.com/scolladon/sfdx-git-delta-reproduction-playground))?

**Comment by irfanlai** [comment]
We can close this issue. Due to backmerge of code to all branches the commit id got messed up and that is the reason the package.xml was empty.
