### ISSUE TITLE
Missing permission set in package.xml when comparing a two branches

### ISSUE THREAD

**Issue by g1b3r** [scolladon/sfdx-git-delta#394]
Issue verification check:

- [x] is the current repository fully deployable at the commit SHA provided with the 'from' parameter of the command?

## What is the problem?

---
During creation of package xml from 2 branches using sfdx sgd:source:delta --to origin/develop --from origin/main -o . 
there is a permission set missing 
When i use a Git diff permission set is there

### What is the parameter and the value you used with it?
sfdx sgd:source:delta --to origin/develop --from origin/main -o . 

### What is the expected result?

Generate package.xml with permissionset 
### What is the actual result?

Missing permission set in package xml
## Steps to reproduce

---
using sfdx sgd:source:delta --to origin/develop --from origin/main -o . where in branch is any permision set

## Execution context

---

**Operating System:** …
Darwin Kernel Version 21.6.0: Thu Sep 29 20:12:57 PDT 2022; root:xnu-8020.240.7~1/RELEASE_X86_64

**yarn version:** …
1.22.19
**node version:** …
v14.15.4
**git version:** …
git version 2.33.0
**sfdx version:** …
sfdx-cli/7.178.0 darwin-x64 node-v18.12.0
@salesforce/analytics 1.0.9
**sgd plugin version:** …
isvte-sfdx-plugin 1.1.16
sfdx-git-delta 5.2.0

## More information (optional)

---

      .forceignore
      config/project-scratch-def.json
      force-app/main/default/profiles/Admin.profile-meta.xml
      sfdx-project.json

**Comment by scolladon** [comment]
Hi @g1b3r 

Thanks for raising this issue, I'll do my best to help you on that.

I can see the sgd version used here is 5.2.0
=> could you upgrade to latest and see if you have the same behavior ?

If you still have the issue, then I'll need those information:
execute this on the repo folder with a terminal: `git diff --name-status --no-renames origin/main origin/develop`
=> Does the permissionset appear in the output of the command?

I also need the folder structure of the repo
=> I want to know in which folder the permission set is located

Could you tell us the step to isolate it and reproduce it as well (using the [playground](https://github.com/scolladon/sfdx-git-delta-reproduction-playground) could help you)

**Comment by g1b3r** [comment]
Hi 

Thank you for helping. I just updated a plugin and i have same result

git diff --name-status --no-renames origin/main origin/develop results below

A       .forceignore
A       config/project-scratch-def.json
A       force-app/main/default/permissionset/Manager.permissionset-meta.xml
A       force-app/main/default/profiles/Admin.profile-meta.xml

Its a standard sfdx configuration 

After work i try to reproduce in playground

**Comment by scolladon** [comment]
Thank you very much !

I think I have a strong lead here
The folder containing the Permission Set here is `permissionset` without an 's'
The [documentation](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_permissionset.htm) says Permission Set must be in a `permissionsets` with an 's'

The plugin enforce this norm and I think it is the reason why it does not work here.
Could you try moving the Permission Set in a `permissionsets` folder and let us know the result please?

**Comment by g1b3r** [comment]
Yes thats the issue :) 

Thank you :) im overworked ;) ;)
