### ISSUE TITLE
[Enhanced LWR related mdt] Add missing DigitalExperienceBundle and DigitalExperienceConfigs to delta in ApiVersion 56

### ISSUE THREAD

**Issue by pibenett** [scolladon/sfdx-git-delta#396]
### Is your proposal related to a problem?

---

Absolutely, I wanted to create a validate package to deploy my new LWR enhanced community :)

### Describe a solution you propose

---

To simply add LWR enhanced related metadata to the delta output

### Describe alternatives you've considered

---

Validate with Gearset

### Additional context

---

Nope

**Comment by scolladon** [comment]
Hi @pibenett !

Thanks for this enhancement proposition.

After giving it a quick look at it I think it requires a new specific handler for `digitalExperiences` type...
I'll look into it deeper soon and hopefully add it.

Stay tuned

**Comment by scolladon** [comment]
Hi @pibenett !

We have finished a [first draft](https://github.com/scolladon/sfdx-git-delta/pull/397) for the digital experiences new metadata type
Could you have a quick look and do first user acceptance before we release it please?

You can follow [those steps](https://github.com/scolladon/sfdx-git-delta/blob/main/CONTRIBUTING.md#testing-the-plugin-from-a-pull-request) to test locally version under code review

**Comment by pibenett** [comment]
Hey @scolladon !

Just finished testing it and it works like a charm.
Thank you very much for your fast work

**Comment by scolladon** [comment]
Thank you very much for your help and your reactivity here @pibenett 
It is highly appreciated 👍 

We merged the code and we will ship it in the next release (in the coming days probably).

We will notify you in this thread, stay tuned!

**Comment by scolladon** [comment]
Hi @pibenett!

We just released the version `v5.9.0` containing the new metadata.
You can install it using the `latest-rc` channel:
```sh
$ sfdx plugins:install sfdx-git-delta@latest-rc
```

Do not hesitate to create an issue if anything goes wrong using it
Let us know as well if everything goes ok, we will use this feedback to create a `latest` release
