### ISSUE TITLE
npm Installation error in CI/CD

### ISSUE THREAD

**Issue by bishwambharsen** [scolladon/sfdx-git-delta#400]
Issue verification check:

- [x] is the current repository fully deployable at the commit SHA provided with the 'from' parameter of the command?

## What is the problem?
Getting this error while installing the plugin via CI CD pipeline. 
--- Warning: sfdx-cli update available from 7.171.0 to 7.180.0.
    ShellExecError: npm ERR! code UNABLE_TO_GET_ISSUER_CERT_LOCALLY
    npm ERR! errno UNABLE_TO_GET_ISSUER_CERT_LOCALLY
    npm ERR! request to https://registry.npmjs.org/sfdx-git-delta failed, 
    reason: unable to get local issuer certificate
    {
      "error": {
        "code": "UNABLE_TO_GET_ISSUER_CERT_LOCALLY",
        "summary": "request to https://registry.npmjs.org/sfdx-git-delta 
    failed, reason: unable to get local issuer certificate",
        "detail": ""
      }
    }
    npm ERR! A complete log of this run can be found in:
    npm ERR!     /root/.npm/_logs/2022-12-14T07_13_01_413Z-debug-0.log
    Code: ShellExecError
Installing plugin sfdx-git-delta... done

### What is the parameter and the value you used with it?
Unable to install the plugin via CI CD pipeline. Used to work before but now failing. 

### What is the expected result?
Expect result is the plugin will be installed. 

### What is the actual result?
 Warning: sfdx-cli update available from 7.171.0 to 7.180.0.
    ShellExecError: npm ERR! code UNABLE_TO_GET_ISSUER_CERT_LOCALLY
    npm ERR! errno UNABLE_TO_GET_ISSUER_CERT_LOCALLY
    npm ERR! request to https://registry.npmjs.org/sfdx-git-delta failed, 
    reason: unable to get local issuer certificate
    {
      "error": {
        "code": "UNABLE_TO_GET_ISSUER_CERT_LOCALLY",
        "summary": "request to https://registry.npmjs.org/sfdx-git-delta 
    failed, reason: unable to get local issuer certificate",
        "detail": ""
      }
    }
    npm ERR! A complete log of this run can be found in:
    npm ERR!     /root/.npm/_logs/2022-12-14T07_13_01_413Z-debug-0.log
    Code: ShellExecError
Installing plugin sfdx-git-delta... done

## Steps to reproduce
Try to install the plugin via CI CD pipeline
---

## Execution context

---

**Operating System:** …

**yarn version:** …

**node version:** …

**git version:** …

**sfdx version:** …

**sgd plugin version:** …

## More information (optional)

---

**Comment by scolladon** [comment]
Hi @bishwambharsen !

Thanks for raising this issue, thanks for your help making this plugin better.

This issue occurs only in the CI/CD pipeline if I understand properly.
It seems to be an issue accessing npm in the context of the CI/CD.
I need more information to help here:
- git version
- node version
- sfdx-cli version
- npm version
- npm configuration (registry, env variable, proxy, etc)
- CI vendor
- CI location (cloud or on premise)
- Anything that could be valuable in the context of this investigation without divulging private/secret/personal information

**Comment by bishwambharsen** [comment]
Hi @scolladon  it seems the problem is not with the plugin itself but with the proxy as I am behind a corporate firewall. As such I would like to close this bug. Thanks for your quick response.
