### ISSUE TITLE
Generated sources take the .forceignore into consideration

### ISSUE THREAD

**Issue by pibenett** [scolladon/sfdx-git-delta#404]
### Is your proposal related to a problem?

Not related to any problem.

Would be a nice feature if the --generate-delta flag would have an option (or regular behavior) to create the generated sources metadata taking into consideration the .forceignore file to avoid some metadata

### Describe alternatives you've considered

Remove the unwanted source metadatas by hand.

Thank you for this and more globally for your work :)

**Comment by pibenett** [comment]
Hi @scolladon!

Sorry for that I CTRL-F forceignore in the readme and as I did not find anything I tough the feature was not implemented.
That's my bad I should have searched better.

Anyway I tried the command it worked like a charm

Have a good day :)

**Comment by scolladon** [comment]
No problem at all!

The feature could be more displayed in the README
