### ISSUE TITLE
Version 5.10.0 does not create delta

### ISSUE THREAD

**Issue by joernflath** [scolladon/sfdx-git-delta#413]
Issue verification check:

- [x] is the current repository fully deployable at the commit SHA provided with the 'from' parameter of the command?

## What is the problem?

---
During the execution of the following command
`sfdx sgd:source:delta --from <latest tag> --to HEAD --output ./deployment/tmp --generate-delta --source ./force-app`
the Plugin does not create the force-app folder containing the delta.
The correct package.xml is created though.

### What is the expected result?

Expected outcome: force-app/main/default folders containing the generated delta metadata

### What is the actual result?

Actual outcome: the above mentioned folders are not being created and the delta metadata is not present.

### Workaround

Downgrade to version 5.8.0

## Execution context

---

**Operating System:** Darwin Kernel Version 22.2.0: Fri Nov 11 02:04:44 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T8103

**yarn version:** …

**node version:** v18.6.0

**git version:** 2.38.

**sfdx version:** sfdx-cli/7.182.1 darwin-arm64 node-v18.6.0

**sgd plugin version:** 5.10.0

**Comment by scolladon** [comment]
Hi @joernflath !

Thanks for raising this issue and thanks for contributing in making this project better!

Do you have a different behavior with `v5.8.0` (`stable`) ?
What is the result of this command: `git diff --name-status --no-renames <from> HEAD`

**Comment by joernflath** [comment]
Hi @scolladon,
yes, 5.8.0 is working and produces the desired folders and delta metadata.
The results of the command are:
`A       force-app/main/default/customMetadata/adv_Mapping_Id.adv_Quote_Template_ID.md-meta.xml
A       force-app/main/default/objects/Quote/fields/adv_Agreement_Template_Id__c.field-meta.xml
A       force-app/main/default/objects/Quote/webLinks/Send_Agreement.webLink-meta.xml
A       force-app/main/default/objects/echosign_dev1__SIGN_Agreement__c/echosign_dev1__SIGN_Agreement__c.object-meta.xml
A       force-app/main/default/objects/echosign_dev1__SIGN_Agreement__c/fields/adv_Quote__c.field-meta.xml
M       force-app/main/default/permissionsets/adv_Sales_Process_Read_Only.permissionset-meta.xml
M       force-app/main/default/profiles/Admin.profile-meta.xml
`

**Comment by scolladon** [comment]
Ok thank you so far.
I cannot reproduce it locally.

we need your help further to find what is going on.

Could you create a branch in a fork of the [reproduction playground](https://github.com/scolladon/sfdx-git-delta-reproduction-playground) and add here the minimal metadata (obfuscate as needed the content) and commits to reproduce the issue and then give us access to the branch and what command to run to reproduce the issue in the playground.

**Comment by joernflath** [comment]
Hi @scolladon,
I reproduced the steps in the playground and commented on the commits with the full commands to reproduce the issue:
https://github.com/joernflath/sfdx-git-delta-reproduction-playground

**Comment by scolladon** [comment]
Hi @joernflath!

That's great news, thank you very much for your help on this one.
I'll cook a fix in the coming days and let you know.

In the meantime we have rolled back the `latest` version to `v5.8.0` so you should be fine using `latest`

**Comment by scolladon** [comment]
Hi @joernflath !

We just released the version `5.10.1`
You can install it using the `latest-rc` channel:

```sh
$ sfdx plugins:install sfdx-git-delta@latest-rc
````

Do not hesitate to create an issue if anything goes wrong using it.
Let us know as well if everything goes ok.
We will use your feedback to promote this version to the `latest` channel.
