### ISSUE TITLE
With Ver v5.10.0 the deployment validation is failing to start

### ISSUE THREAD

**Issue by irfanlai** [scolladon/sfdx-git-delta#416]
Issue verification check:

- [ ] is the current repository fully deployable at the commit SHA provided with the 'from' parameter of the command?

## What is the problem?
This is Blocker issue for us.
I have GitHub actions that validate the changes when a PR is created. Untill ver: sfdx-git-delta 5.8.0 the deployment pipeline was working fine. Today morning all the PR validation is failing and the only difference I could find out is ver 5.10.0.

---

### What is the expected result?

Validate deployment should trigger without any issues

### What is the actual result?

Getting the following error in the GitHub Actions.
ERROR running force:source:deploy:  The sourcepath "changed-sources/force-app" is not a valid source file path.
Error: Process completed with exit code 1.

### Workaround?
None.
Is there I way I can install the older ver? If Yes then I need the command for installing the older ver?

## Execution context

**Operating System:**   Ubuntu 22.04.1

**yarn version:** …

**node version:** …

**git version:** git version 2.38.2

**sfdx version:** sfdx-cli/7.182.1 linux-x64 node-v18.12.1

**sgd plugin version:** sfdx-git-delta 5.10.0

---

**Comment by whoisemiliano** [comment]
@irfanlai you can install a new version using the following command `echo y | sfdx plugins:install sfdx-git-delta@5.8.0` we are using the `5.8.0` version and looks like its working fine until they fix the `5.10.0` version

**Comment by scolladon** [comment]
Hi @irfanlai !

Thanks for raising this issue and thanks for contributing in making this project better!

Sorry for the inconvenience, we just rollback the `latest` channel to `v5.8.0`.
So you can keep your CI without changing it

Could you send the result of the command : 
```sh
$ git diff --name-status --no-renames <from> <to>
```

**Comment by irfanlai** [comment]
@scolladon Thank you for the rollback. I tested the validation again and it is working without any issues. So 5.10.0 has some issues.

**Comment by scolladon** [comment]
duplicate #413

**Comment by scolladon** [comment]
Hi @irfanlai & @whoisemiliano!

We have a fix cooking [here](https://github.com/scolladon/sfdx-git-delta/pull/419)
I tried it with a [playground](https://github.com/scolladon/sfdx-git-delta-reproduction-playground/tree/issue/414) and it is working.

Could you [try the PR](https://github.com/scolladon/sfdx-git-delta/blob/main/CONTRIBUTING.md#testing-the-plugin-from-a-pull-request) with your real use case and see if it fixes the issue please ?

**Comment by whoisemiliano** [comment]
Thanks for your hard work ! I will try it asap !

**Comment by scolladon** [comment]
Hi @irfanlai @whoisemiliano !

We just released the version `5.10.1`
You can install it using the `latest-rc` channel:

```sh
$ sfdx plugins:install sfdx-git-delta@latest-rc
````

Do not hesitate to create an issue if anything goes wrong using it.
Let us know as well if everything goes ok.
We will use your feedback to promote this version to the `latest` channel.

**Comment by irfanlai** [comment]
Thanks for the support and fixes.
I have two back-to-back production releases this week on Wednesday & Thursday. I will add your changes to my repo on Thursday night so we can test it starting Friday. 
Again thanks for your continued support of this project.

**Comment by scolladon** [comment]
I think you should wait a bit, sorry...
An issue has been returned from #414

We are going to look into it.

Thanks for your support proposition anyway !

Stay tuned

**Comment by irfanlai** [comment]
@scolladon Did you release ver 5.11.0 because I am having the same above issue where deployment is failing?

**Comment by scolladon** [comment]
Hi @irfanlai

Yes we released `v5.11.0` as `latest` channel earlier today.

What version/channel are you using ?
How can I reproduce the issue locally ?

**Comment by irfanlai** [comment]
> Hi @irfanlai
> 
> Yes we released `v5.11.0` as `latest` channel earlier today.
> 
> What version/channel are you using ?
> How can I reproduce the issue locally ?
> 

Let me see if I can give you repo access

**Comment by irfanlai** [comment]
@scolladon I have given you access to my test repo. You can check in Actions that the validation failed after PR was created with ver 5.11.0.
If you change the version in main to 5.8.0. It will work fine.
Let me know if you need anything else to debug this further.

**Comment by scolladon** [comment]
I reproduced locally what was done in the github action
This issue seems to occurs when the `--source` parameter is used.

I reopen this issue and will provide a fix soon

Thanks for this prototype @irfanlai, very helpful

**Comment by scolladon** [comment]
Hi @irfanlai !

We just released the version `v5.11.1` containing the fix for this issue.
You can install it using the `latest` channel:

```sh
$ sfdx plugins:install sfdx-git-delta@latest
````

Do not hesitate to create an issue if anything goes wrong using it.
Let us know as well if everything goes ok.

**Comment by irfanlai** [comment]
@scolladon We have been using v5.11.1 and so far no issues. 
Do you have any specific day you release the latest ver?
Is there any way you put that has an announcement?

This will help us to use a specific ver and implement new ver as per our flexibility. This will make sure our pipeline does not break.

**Comment by scolladon** [comment]
Hi @irfanlai 

The `v5.11.1` is the current `latest` version.
`latest` is the default channel when nothing is specified 
It means if you install `sgd` with this command it will install latest:
```sh
$ sfdx plugins:install sfdx-git-delta
# same as
$ sfdx plugins:install sfdx-git-delta@latest
```

We suggested a way to [variabilize the installation version in CI/CD using environment variable](https://github.com/scolladon/sfdx-git-delta#cicd-specificity).
It avoid having to commit something in order to change the version.

We usually do `major`/`minor` releases at the beginning of the week (from monday to wednesday).
We deploy `patch` releases and channel version pointer rollback any day of the week to make sure no one is stuck.

If you want to be notified about releases you can [subscribe to our notifications](https://docs.github.com/en/account-and-profile/managing-subscriptions-and-notifications-on-github/managing-subscriptions-for-activity-on-github/viewing-your-subscriptions), Github will notify you automatically when we do a release.
