### ISSUE TITLE
Providing diff across the branches

### ISSUE THREAD

**Issue by mohan-chinnappan-n** [scolladon/sfdx-git-delta#426]
Hi Sébastien Colladon

 Let us provide a tool  which compares set of commit-ids in 2 different branches
 
like git:compare -b main,release  -f 14d343a,3d3ddd -t 4dedee3,5ef595d
This compares
     main from 14d343a to 4dedee3  with
     release from 3d3ddd to 5ef595d

**Comment by scolladon** [comment]
Hi @mohan-chinnappan-n !

Thanks for this enhancement request and thanks for contributing in making this project better!

Let's open the discussion here and see how we could open / distribute this part of the plugin

**Comment by scolladon** [comment]
It is possible to use the engine of the plugin [directly from any javascript](https://github.com/scolladon/sfdx-git-delta#use-the-module-in-your-own-node-application) application.
