### ISSUE TITLE
relationshipGraphDefinition as part of the metadata versions

### ISSUE THREAD

**Issue by Tzeimi** [scolladon/sfdx-git-delta#427]
### Is your proposal related to a problem?
When generating the package from the delta, there's a missing metadata type since its not part of the current object in the 56 version.

---
### Describe a solution you propose

---
Add in upcoming version (57) this metadata type or maybe in current version (56)

### Describe alternatives you've considered

Currently I'm pushing manually the files for that metadata type but that generates two deployments, would be better to have a single one.
---

**Comment by scolladon** [comment]
Hi @Tzeimi !

Thanks for raising this enhancement and thanks for contributing in making this project better!

We'll ship this metadata support soon, stay tuned

**Comment by scolladon** [comment]
Hi @Tzeimi !

We just released the version `v5.11.0` containing the new metadata `RelationshipGraphDefinition`.
You can install it using the `latest-rc` channel:

```sh
$ sfdx plugins:install sfdx-git-delta@latest-rc
````

Do not hesitate to create an issue if anything goes wrong using it.
Let us know as well if everything goes ok.
We will use your feedback to promote this version to the `latest` channel.
