### ISSUE TITLE
[`v5.11.1`] incremental file copy issue on windows (still working in `v5.8.0`)

### ISSUE THREAD

**Issue by baslu93** [scolladon/sfdx-git-delta#434]
## What is the problem?

Using "sfdx sgd source delta" with -d option to generate delta files in [--output] folder,
a delta containing some Page Layouts was discovered,
the delta folder was created, but it contained only the basic files (destructiveChanges and packages);
the package was populated correctly but the Page Layout files were missing.

### What is the parameter and the value you used with it?

```
$ echo $FROM
99ffa887697794c60ac508ac648b1b916bf3e895

$ sfdx sgd:source:delta --from $FROM --output delta_folder -d

»   Warning: sfdx-cli update available from 7.173.0 to 7.180.0.
{
  "error": null,
  "output": "delta_folder",
  "success": true,
  "warnings": []
}
```
### What is the actual result?
```
$ find delta_folder
delta_folder
delta_folder/destructiveChanges
delta_folder/destructiveChanges/destructiveChanges.xml
delta_folder/destructiveChanges/package.xml
delta_folder/package
delta_folder/package/package.xml

$ cat delta_folder/package/package.xml
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns=http://soap.sforce.com/2006/04/metadata>
    <types>
        <members>GroundTravelEnrgyUse-Ground Travel Energy Use Layout</members>
        <members>ReportingPeriod__c-Reporting Period Layout</members>
        <members>StnryAssetEnvrSrc-Office Layout</members>
        <name>Layout</name>
    </types>
    <version>54.0</version>
</Package>
```

### What is the expected result?

I was expecting the delta_folder was containg also the following:
**force/app/main/default/layouts/GroundTravelEnrgyUse-Ground Travel Energy Use Layout.layout-meta.xml**
**force/app/main/default/layouts/ReportingPeriod__c-Reporting Period Layout.layout-meta.xml**
**force/app/main/default/layouts/StnryAssetEnvrSrc-Office Layout.layout-meta.xml**

## Execution context

```
$ uname -v
2022-02-23 17:44 UTC
```

**Operating System:** Windows 11

**yarn version:** 1.22.19

**node version:** v16.15.0

**git version:** git version 2.36.0.windows.1

**sfdx version:** sfdx-cli/7.173.0 win32-x64 node-v16.15.0

**sgd plugin version:** sfdx-git-delta 5.11.0

**Comment by scolladon** [comment]
Hi @baslu93 !

Thanks for raising this issue and thanks for contributing in making this project better!

Can you try with the `latest` version ? (v5.11.1)
If you still have the issue with the `latest` version, can you provide the steps to reproduce the issue locally ?

**Comment by baslu93** [comment]
Hi @scolladon !

I've created a lighter repo and I was able to replicate the issue with v5.11.1 (I've checked 5.8.0 is working fine)
Here the steps:
```
git clone https://github.com/baslu93/proof-sfdx-git-delta.git
mkdir delta_folder
sfdx sgd:source:delta --from 153250494adf409c8e922d2734137b4cf5bee1c3 --output delta_folder -d

```
The force-app folder is missing in delta_folder, the package.xml generated is containing the changed layout

**Comment by scolladon** [comment]
Nice !

Thanks for that, I've been able to run it locally.

Here is my result:
![Screenshot 2023-01-25 at 12 06 33](https://user-images.githubusercontent.com/522422/214548242-40b90191-0e38-481b-a1f3-5de96c710010.png)

So it seems to be ok with v5.11.1 on mac, but not on windows

I also tried with the [new version](https://github.com/scolladon/sfdx-git-delta/pull/433) to come and it works also.
Could you test it locally using the next version to come ? You can follow the [steps on this comment](https://github.com/scolladon/sfdx-git-delta/pull/433#issuecomment-1402217390)
I want to know if it is fixing this issue or not

**Comment by baslu93** [comment]
Oh got it, good to know that is working on mac since my pipeline is built on ubuntu-latest.
Here the steps I did on my Windows laptop:
```
$ sfdx plugins:uninstall sfdx-git-delta
$ cd sfdx-git-delta/
$ git checkout fix/relative-repo-value
$ git pull
$ yarn install
$ yarn pack
$ sfdx plugins:link
$ sfdx plugins
@salesforce/lwc-dev-server 2.11.0
@salesforce/sfdx-scanner 2.13.9
sfdx-git-delta 5.11.1 (link) C:\Users\luca.bassani\repos\sfdx-git-delta

$ cd ..
$ cd proof-sfdx-git-delta/
$ rm -rf delta_folder/
$ mkdir delta_folder
$ sfdx sgd:source:delta --from 153250494adf409c8e922d2734137b4cf5bee1c3 --output delta_folder -d
$ find delta_folder/
delta_folder/
delta_folder/destructiveChanges
delta_folder/destructiveChanges/destructiveChanges.xml
delta_folder/destructiveChanges/package.xml
delta_folder/package
delta_folder/package/package.xml
```
I'm still facing the issue even when checking out  the branch fix/relative-repo-value.
Hope the steps are in line with your suggestion and thank your for your answers!

**Comment by scolladon** [comment]
Thank you very much @baslu93 for those information
Really helpful.

I will try to reproduce in windows environment soon and keep you updated in this thread
Sorry for the inconvenience, we are refactoring a bit how we get the data from git and it comes with a bit of trouble despite our best efforts.

I pushed a commit today on the [PR](https://github.com/scolladon/sfdx-git-delta/pull/433) you tested.
Just to be sure, does the commit sha on top of the branch you checked out is: [8f0334d](https://github.com/scolladon/sfdx-git-delta/pull/433/commits/8f0334db14cf3649101c972271463f851f711b04) ?

**Comment by baslu93** [comment]
Yep, I confirm you the sha is the one you mentioned.
I've tried using `git bash` and `cmd.exe` (same output).

**Comment by scolladon** [comment]
Ok thanks,

Then I need to investigate further with a dedicated windows environment

I'll keep you posted here
In the meantime if you can use a linux pipeline it should work there
