### ISSUE TITLE
[5.11.1] Delta execution copying old file content to --output dir

### ISSUE THREAD

**Issue by Renan-Mastropaolo** [scolladon/sfdx-git-delta#435]
Issue verification check:

- [x] is the current repository fully deployable at the commit SHA provided with the 'from' parameter of the command?

## What is the problem?

---

Hello sfdx-git-delta team. I am facing a strange behavior with sgd plugin v5.11.1 (.0 as well), that the plugin is copying the old file content to the output dir.
On our CI/CD we have some pre-deployment Powershell scripts that runs before the sgd plugin command, these scripts replace specific text in some of our files, mostly namedCredentials and customMetadata, this helps us to manage multiple environments with different endpoints without the need to create unnecessary metadata to our sandboxes.
As I said, these scripts run before the sgd plugin. 

So the file content at 
_"/thunder/force-app/main/default/namedCredentials/Name_of_nc.namedCredential-meta.xml"_ is

`<?xml version="1.0" encoding="UTF-8"?>
<NamedCredential xmlns="http://soap.sforce.com/2006/04/metadata">
    <endpoint>*.*</endpoint>
</NamedCredential>`

and after the script the endpoint is replaced with

`<?xml version="1.0" encoding="UTF-8"?>
<NamedCredential xmlns="http://soap.sforce.com/2006/04/metadata">
   <endpoint>https://endpoint.com</endpoint>
</NamedCredential>`

but after the sgd plugin run, the content of the file at 
_"/thunder/builds/incremental/force-app/main/default/namedCredentials/Name_of_nc.namedCredential-meta.xml"_ is the same as pre-script state:

`<?xml version="1.0" encoding="UTF-8"?>
<NamedCredential xmlns="http://soap.sforce.com/2006/04/metadata">
    <endpoint>*.*</endpoint>
</NamedCredential>`

It does work with sgd v5.8.0 and when we deploy the full branch (without running sgd).

### What is the parameter and the value you used with it?

sfdx sgd:source:delta --to "HEAD" --from "$BranchTag" --output builds/incremental --generate-delta

### What is the expected result?

The expected result is the same content file from _"/thunder/force-app/main/default/namedCredentials/Name_of_nc.namedCredential-meta.xml"_ into _"/thunder/builds/incremental/force-app/main/default/namedCredentials/Name_of_nc.namedCredential-meta.xml"_

Expected content:
`<?xml version="1.0" encoding="UTF-8"?>
<NamedCredential xmlns="http://soap.sforce.com/2006/04/metadata">
   <endpoint>https://endpoint.com</endpoint>
</NamedCredential>`

### What is the actual result?
`<?xml version="1.0" encoding="UTF-8"?>
<NamedCredential xmlns="http://soap.sforce.com/2006/04/metadata">
    <endpoint>*.*</endpoint>
</NamedCredential>`
The content of the files previous to the script execution

## Steps to reproduce

---

I can not provide you our repo since it is private.

## Execution context

---

**uname -v:** #100~18.04.1-Ubuntu SMP Mon Oct 17 11:44:30 UTC 2022

**Operating System:** Ubuntu Linux

**yarn version:** 1.22.19

**node version:** v14.21.1

**git version:** git version 2.25.1

**sfdx version:** sfdx-cli/7.171.0 linux-x64 node-v14.21.1

**sgd plugin version:** sfdx-git-delta 5.11.1 (5.11.1)

**Comment by scolladon** [comment]
Hi @Renan-Mastropaolo !

Thanks for raising this issue and thanks for contributing in making this project better!

You are right, we slightly changed the behavior of sgd after `v5.8.0`
Now, the content of the file is taken from git and not on the file system. _More explanation [here](https://github.com/scolladon/sfdx-git-delta/pull/385)_
It means if you change it during the pipeline in the sources before sgd is executing it will not be taken in account.

I'm sorry but we will not change this behaviour...
What I can suggest you is to adapt your script to this new behaviour and move those file in the `output` folder after sgd is executed.

I do not close this issue and would rather let you do it in case
- you would like to discuss further about this (maybe you have an idea we could implement to better suit you)
- or if we can help you migrate your scripts.

**Comment by Renan-Mastropaolo** [comment]
Oh, thanks for the quick response and easy explanation.
Sorry, I think I've missed this change on the Release notes, good to know.
I will be engaging my team to change this script behavior in the future, for now we will stick if v5.8.0.
Again, thank you for your help.

**Comment by scolladon** [comment]
I strongly encourage you to use tags to install sgd, ie `latest` (default) or `stable` channel.
This way you will always benefit from the new Metadata type added.
We do our best to make the plugin as stable as possible, here is [how we](https://github.com/scolladon/sfdx-git-delta/discussions/346#discussioncomment-3763282) do it, and [npm displays](https://www.npmjs.com/package/sfdx-git-delta?activeTab=versions) channel <-> version mapping
We [suggest](https://github.com/scolladon/sfdx-git-delta#:~:text=%2D%2Doutput%20.-,Use%20global%20variable,-when%20you%20need) a way to variabilize the sgd version in pipeline without having to commit in the repo, this way you can swap sgd version easily
