### ISSUE TITLE
add support to more metadata types

### ISSUE THREAD

**Issue by Tzeimi** [scolladon/sfdx-git-delta#443]
### Is your proposal related to a problem?

---

Im working with some features from FSC / omnistudio and some other new features. Would be great if its possible to dynamically 
set the name / members based on the modified / new files inside the project path.

But since that's something more complex, could it be possible to get support for:

ActionPlanTemplate
DocumentType
RecordActionDeployment

Thank you :)

**Comment by scolladon** [comment]
Hi @Tzeimi !

Let's add those metadata!
I'll let you know when it will be released

What is your idea about dynamically set the name ?
What would be your experience as a user ?

**Comment by scolladon** [comment]
Also @Tzeimi 

I found metadata definition for:
- [ActionPlanTemplate](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_actionplantemplate.htm)
- [RecordActionDeployment](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_recordactiondeployment.htm)

But I did not find something for DocumentType.
The closer I could find in the doc is [OcrSampleDocument](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_ocrsampledocument.htm?q=DocumentType) which is related to [OcrTemplate](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_ocrtemplate.htm?q=DocumentType)
I do not have any experience with those metadata.
Can you help here ? Which metadata definition should be added for DocumentType and where to find its definition in the doc ?

**Comment by Tzeimi** [comment]
hmmm since having a dynamic path would be hard due to some names doesnt match the actual metadata type, a good option from the user experience could be something like

sgd:config:set:types where you pass the metdataType and folder in project path to link to that metadata type.

Regarding the metadata definition for DocumentType let me see what can I find, because is something new for me too

**Comment by Tzeimi** [comment]
here's the [link](https://developer.salesforce.com/docs/atlas.en-us.financial_services_cloud_object_reference.meta/financial_services_cloud_object_reference/sforce_api_objects_documenttype.htm?q=documenttype) for documentType definition

**Comment by scolladon** [comment]
Thanks for those information

Looking at what we found in the doc, it seems DocumentType is not a metadata, it is a data so it is not packageable.
Do you have an example of package.xml I could use to fetch DocumentType elements and what kind of files it will generate (file name, file path and file content) ?

**Comment by Tzeimi** [comment]
Yeah, as you mentioned its not something to have in the repo (my bad) this will be something I'll handle as a post install step with data loader.

**Comment by scolladon** [comment]
Ok, then no need to add it ?
Just [ActionPlanTemplate](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_actionplantemplate.htm) and [RecordActionDeployment](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_recordactiondeployment.htm) (and RecommendationStrategy) would be ok for you ?

**Comment by Tzeimi** [comment]
Yes, please.

**Comment by scolladon** [comment]
The PR is merged !
We will ship a new version next week containing those new metadata types
Stay tuned !

**Comment by Tzeimi** [comment]
Thank you!

**Comment by tmassalski** [comment]
Any chance to re-open this issue and add support for "DocumentType"?
This metadata type is listed in metadata coverage report (link seems to be broken) and deployable.

Here's an example manifest:

```
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>Test</members>>
        <name>DocumentType</name>
    </types>
    <version>59.0</version>
</Package>
```
and file path & content:
documentTypes/Test.documentType-meta.xml

```
<?xml version="1.0" encoding="UTF-8"?>
<DocumentType xmlns="http://soap.sforce.com/2006/04/metadata">
    <isActive>true</isActive>
    <masterLabel>Test</masterLabel>
</DocumentType>
```

Thank you!

**Comment by scolladon** [comment]
Hi @tmassalski,

Sure, I reopen this issue.
 
Just to be sure, do you found a link to a documentation ?
And, in order to test that, what should I do in my org to create document type ? (I'll try to `retrieve` and `deploy` them)

**Comment by mehdisfdc** [comment]
@scolladon I didn't find a documentation page on the Metadata API Developer Guide, but there is an entry for DocumentType in the [Metadata Coverage tool](https://developer.salesforce.com/docs/metadata-coverage/59).

**Comment by tmassalski** [comment]
Hi @scolladon,

As @mehdisfdc mentioned, if you click a link from metadata coverage details it leads nowhere https://developer.salesforce.com/docs/metadata-coverage/59/DocumentType/details

But the [link](https://help.salesforce.com/s/articleView?id=sf.admin_define_doctypes.htm&type=5) posted earlier by @Tzeimi  seems correct.

Here's a [link ](https://help.salesforce.com/s/articleView?id=sf.admin_define_doctypes.htm&type=5) with instruction how to create document type. Omnistudio/FSC is required.
