### ISSUE TITLE
Malfunction of the parameter include

### ISSUE THREAD

**Issue by danielperrella** [scolladon/sfdx-git-delta#447]
I am trying to use the include command,
I always want to deploy the Admin profile.
I have prepared an .include file in two versions:

- the first on the branch main with: force-app\main\default\profiles\*
- the second one on the branch feature with: force-app\main\default\profiles\Admin.profile-meta.xml

If I launch the command "sfdx sgd:source:delta -f main -t feature -o . -n .include" on the main branch I have as a response:
{
  "error": null,
  "output": ".",
  "success": true,
  "warnings": []
}

but there is no profile in the generated file.

If I launch the command "sfdx sgd:source:delta -f main -t feature -o . -n .include" on the feature branch I have as a response:
{
  "error": "Cannot read properties of undefined (reading 'metaFile')",
  "output": ".",
  "success": false,
  "warnings": []
}

## Steps to reproduce

I prepared this repository for testing: https://github.com/danielperrella/sfdx-git-delta-issue

first test:
git checkout main
sfdx sgd:source:delta -f main -t feature -o . -n .include

second test:
git checkout feature
sfdx sgd:source:delta -f main -t feature -o . -n .include

## Execution context

---

**Operating System:** Windows 11

**yarn version:** x

**node version:** v18.12.1

**git version:** 2.39.0.windows.2

**sfdx version:** 7.187.1 

**sgd plugin version:** 5.11.4

**Comment by scolladon** [comment]
Hi @danielperrella !

Thanks for raising this issue and thanks for contributing in making this project better!

I'll have a look soon with all the reproduction steps you provided (thanks for that)

**Comment by scolladon** [comment]
We created a fix @danielperrella [here](https://github.com/scolladon/sfdx-git-delta/pull/448)

Could you please follow [those steps](https://github.com/scolladon/sfdx-git-delta/blob/main/CONTRIBUTING.md#testing-the-plugin-from-a-pull-request) to test it locally and let us know the result on your machine please ?

I tested it on a windows virtual machine and it seems to fix the issue with the issue repository you provided

**Comment by danielperrella** [comment]
Hi @scolladon thank you for the zero-time fix.

It works with the .include file present on the 'feature' branch, but still does not work with the .include file present on the 'main' branch (the one with the *)

**Comment by scolladon** [comment]
Nice to hear, thanks for your very fast help on this one

Could you try with this path matcher: `force-app\main\default\profiles\*`

I suspect the first one is not understood well by `minimatch`

**Comment by danielperrella** [comment]
No way, 
I tried with:
- force-app\main\default\profiles\*
- force-app\main\default\profiles\*.profile-meta.xml

It only works:
force-app\main\default\profiles\Admin.profile-meta.xml

**Comment by scolladon** [comment]
I made a few exploratory tests in order to better understand how micromatch works:
```js
// expl-micromatch.js
// npm install --save-dev micromatch
// node expl-micromatch.js
const micromatch = require('micromatch')

const winwin = () => {
    const inc = 'force-app\\main\\default\\profiles\\*'
    const inputs = ['force-app\\main\\default\\profiles\\Admin.profile-meta.xml']
    const result = micromatch(inputs, inc)
    console.log(result)
}
// Failure
winwin() // []

const winlin = () => {
    const inc = 'force-app\\main\\default\\profiles\\*'
    const inputs = ['force-app/main/default/profiles/Admin.profile-meta.xml']
    const result = micromatch(inputs, inc)
    console.log(result)
}
// Failure
winlin() // []

const linwin = () => {
    const inc = 'force-app/main/default/profiles/*'
    const inputs = ['force-app\\main\\default\\profiles\\Admin.profile-meta.xml']
    const result = micromatch(inputs, inc)
    console.log(result)
}
// Success
linwin() // ['force-app/main/default/profiles/Admin.profile-meta.xml']

const linlin = () => {
    const inc = 'force-app/main/default/profiles/*'
    const inputs = ['force-app/main/default/profiles/Admin.profile-meta.xml']
    const result = micromatch(inputs, inc)
    console.log(result)
}
// Success
linlin() // ['force-app/main/default/profiles/Admin.profile-meta.xml']
```

What I understand from the result is the path in the pattern must be unix to work `/`  (it seems to follow the gitignore spec)
It matches windows path correctly when matcher path is defined with the unix format.

Could you try with your sample using `/` path separator ? 

On my side those works fine:
- `force-app/main/default/profiles/*`
- `force-app/main/default/profiles/*.profile-meta.xml`
- `force-app/main/default/profiles/Admin.profile-meta.xml`

This one works as well because it does not match (expected because it means match any file starting by profiles under default folder)
- `force-app/main/default/profiles*`

**Comment by danielperrella** [comment]
Hi @scolladon 
As you said, with Unix separators it works, I have tested it too.
Thanks for your time,
I am waiting for the release 💯

**Comment by scolladon** [comment]
Thanks for your great help on this one.

We'll ship a `latest-rc` soon and let you know when you'll be able to use it
