### ISSUE TITLE
How to generate 47.0 and 49.0 json files

### ISSUE THREAD

**Issue by lokrajahuja** [scolladon/sfdx-git-delta#45]
Hi @scolladon ,

Can you please help me with the process of creating the metadata JSON file of a particular API version such as 49.0 or 47.0?
Also, metadata types related to **Territory2** are not available in your v48.0 JSON file. 

How do we make sure that all supported metadata types are added to the metadata JSON file?

Thank You 
Lok

**Comment by scolladon** [comment]
Hi @lokrajahuja 

Thanks for raising this concern, if you are interested in those API version then they should be available.
It would have been great to create this issue following the enhancement issue type though.

I will create the files for 49.0 and 47.0 and also I will look to create a script for this so next time it will be much more easier.

Seb

**Comment by scolladon** [comment]
@lokrajahuja could you provide the described metadata xmls file related to an org with Territory2 enabled ?
For version 47, 48 and 49 please ?

**Comment by scolladon** [comment]
PR #46 is here to add support for Territory2 metadata object
