### ISSUE TITLE
Missing metadata types

### ISSUE THREAD

**Issue by abendris27** [scolladon/sfdx-git-delta#456]
## What is the problem?
---
The 2 following metadata types are not recognized when doing a diff
DecisionMatrixDefinition
ExpressionSetDefinition

is this related to getting the metadata types ?

### What is the parameter and the value you used with it?

sfdx sgd:source:delta --to HEAD --from $commitId --output $(SGD_DIR)
--> the generated package.xml doesn't contain any added Expression set or decision matrix

### What is the expected result?

<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
	<types>
		<members>InsurancePolicyAsset.Unpaid_months__c</members>
		<name>CustomField</name>
	</types>
	<types>
		<members>AcquisitionLoadingMatrix</members>
		<members>CommutationMatrix</members>
		<members>Parameters</members>
		<name>DecisionMatrixDefinition</name>
	</types>
	<types>
		<members>SurrenderValue_V1</members>
		<name>ExpressionSetDefinitionVersion</name>
	</types>
	<version>57.0</version>
</Package>

### What is the actual result?

all the rest expt this

## Execution context

---

**Operating System:** …

**yarn version:** …

**node version:** …

**git version:** …

**sfdx version:** …

**sgd plugin version:** …

## More information (optional)

---

**Comment by scolladon** [comment]
Hi @abendris27!

Thanks for raising this feature request and thanks for contributing in making this project better!

We are going to add those metadata in the next release.

Here is the metadata definition we are going to add:
- [ExpressionSetDefinition](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_expressionsetdefinition.htm)
- [DecisionMatrixDefinition](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_decisionmatrixdefinition.htm)

**Comment by abendris27** [comment]
Thanks for your reactivity
