### ISSUE TITLE
[Error Message Unclear] Unable to find the file with the error

### ISSUE THREAD

**Issue by arafesthain** [scolladon/sfdx-git-delta#476]
Hello @scolladon any chance we can get the file that caused the error ? 

```
+ sfdx sgd:source:delta -d -t HEAD -f 2022_GR12.0 -r /home/vsts/work/1/salesforce_repo -i /home/vsts/work/1/salesforce_repo/.forceignore -o output
+ SGD_SUCCESS=false
+ SGD_ERROR='Unexpected string in JSON at position 2608'
```

SGD VERSION = 5.8.0 & @latest

**Comment by scolladon** [comment]
Hi @arafesthain!

Thanks for raising this issue and thanks for contributing in making this project better!

I have never experienced this kind of issue.
Could you isolate it and help me reproduce please ?

**Comment by arafesthain** [comment]
I found that sfdx project.json was malformed (missing ",") somewhere due to a bad merge conflict resolution
