### ISSUE TITLE
Deleting one file from LWC bundle puts entire component to destructiveChanges

### ISSUE THREAD

**Issue by nikitakarpenkov** [scolladon/sfdx-git-delta#481]
Issue verification check:

- [x] is the current repository fully deployable at the commit SHA provided with the 'from' parameter of the command?

## What is the problem?

---

Deleting only one of the files in the LWC bundle (for example css file) leads to entire component being added to the destructiveChanges.xml

### What is the parameter and the value you used with it?

```
sfdx sgd:source:delta --to HEAD --from HEAD~1 --source="force-app/" --generate-delta --output __diff/ --ignore .forceignore
```

### What is the expected result?

LWC component is added to the package.xml and diff sources folder.

### What is the actual result?

LWC is added to the destructiveChanges.xml

## Steps to reproduce

- Clone the playground: https://github.com/nikitakarpenkov/sfdx-git-delta-reproduction-playground
- Run `sfdx sgd:source:delta -d -f HEAD~1`

## Execution context

---

**Operating System:** Ubuntu 22.04 and Mac OS Monterey 12.3

**yarn version:** 1.22.19

**node version:** 16.17.1

**git version:** 2.39.2

**sfdx version:** 7.188.1

**sgd plugin version:** 5.13.2

## More information (optional)

---

```bash
$ git diff --name-status --no-renames HEAD~1 HEAD
```

```
D       sgd/reproduction/playground/lwc/testComponent/testComponent.css
```

**Comment by scolladon** [comment]
Hi @nikitakarpenkov !

Thanks for raising this issue and thanks for contributing in making this project better!

I can see that you have already debugged and found a fix for this issue
Thanks a lot for this hard work !
