### ISSUE TITLE
[JS problem introduced with ?.]

### ISSUE THREAD

**Issue by arafesthain** [scolladon/sfdx-git-delta#49]
Anything that I should have done in version 3.3.1 ?

```
$ sgd -d -t HEAD -f origin/master -o output/ -r .
C:\Users\alexis.rafesthain\AppData\Roaming\npm\node_modules\sfdx-git-delta\bin\cli:38
  if (jobResult?.warnings?.length) {
                ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:1063:16)
    at Module._compile (internal/modules/cjs/loader.js:1111:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
```

Execution context
Operating System: …
Windows 10
NPM version: …
6.14.5
Node version: …
v13.12.0
sgd version: …
3.3.1

**Comment by saakshig** [comment]
We are also running into the same issue. All the deployments till 4 hours ago were successful. After that, all have failed.

**Comment by scolladon** [comment]
Hello,

This is related to the node engine version required.
The [latest release](https://github.com/scolladon/sfdx-git-delta/releases/tag/v3.3.1) has introduced this.

Look the engines.node version in the [package.json](https://github.com/scolladon/sfdx-git-delta/blob/v3.3.1/package.json) it requires node version 14.6.0 or above to run.

@arafesthain @saakshig @engineerakki could you update node and see if you still have issue please ?

**Comment by arafesthain** [comment]
@scolladon alright from there 👍

**Comment by scolladon** [comment]
Maybe because you did an update instead of an install ?
Does upgrading nodes has fixed your environment ?

Would you be able to suggest a process for the next time ? So upgrading the engine to benefit from the new feature of the js will not make you lose time because of breaking in runtime.
What could be suitable for you ?

**Comment by arafesthain** [comment]
@scolladon true is my pipeline didn't break without updating node version :') but on my (wonderful) windows computer it did..

For this kind of stuff I will suggest a major release ? but not sure it fit in this scenario.

I did force the pipeline to stay on a chosen version so it will well fit in my case ^^
`sudo npm install sfdx-git-delta@^3.0.0 --global `

**Comment by scolladon** [comment]
Good advice thanks

We will definitly need to deal properly with this kind of situation @mehdisfdc 
We should define a simple process for that with the input from @arafesthain 

I was a little bit rough on this one :D
Sorry guys, I hope you will enjoyed the improvements though
