### ISSUE TITLE
3.3.1 is broken 

### ISSUE THREAD

**Issue by engineerakki** [scolladon/sfdx-git-delta#50]
We have a CI pipeline running using SGD,

with sgd upgraded to 3.3.1, our pipeline started failing with following issue:-

`/usr/local/lib/node_modules/sfdx-git-delta/bin/cli:38
  if (jobResult?.warnings?.length) {`

bug introduced in sgd version: 3.3.1
everything was working fine until 3.3.0

steps to reproduce:
install sgd 3.3.1
run  comand 
`sgd --to HEAD --from HEAD^ --repo . --output .`

**Comment by scolladon** [comment]
Duplicate with the #49
