### ISSUE TITLE
decisionTables metadata type missing from package.xml

### ISSUE THREAD

**Issue by rel5555** [scolladon/sfdx-git-delta#537]
Issue verification check:

- [x] is the current repository fully deployable at the commit SHA provided with the 'from' parameter of the command?

## What is the problem?

The following files which appear in our diff, are missing from the package.xml generated by SGD:

- force-app\main\default\decisionTableDatasetLinks\xyz.decisionTableDatasetLink-meta.xml
- force-app\main\default\decisionTables\xyz.decisionTable-meta.xml

### What is the parameter and the value you used with it?

`sfdx sgd:source:delta --to HEAD --from origin/qa --output .`

### What is the expected result?

The following lines in the package.xml:

```
	<types>
		<members>yyy</members>
		<name>DecisionTable</name>
	</types>
	<types>
		<members>xxx</members>
		<name>DecisionTableDatasetLink</name>
	</types>
```

### What is the actual result?

The components are missing from the package.xml

## Execution context

**Operating System:** Windows 10

**yarn version:** 1.22.19

**node version:** v18.15.0

**git version:** git version 2.40.0.windows.1

**sfdx version:** sfdx-cli/7.192.2 win32-x64 node-v18.14.2

**sgd plugin version:** sfdx-git-delta 5.13.3

**Comment by scolladon** [comment]
Hi @rel5555 !

Thanks for raising this issue and thanks for contributing in making this project better!

We will add those new metadata soon, thanks for requesting them.
Stay tuned !
