### ISSUE TITLE
Problems to extract workflows objects

### ISSUE THREAD

**Issue by alexandrececchin** [scolladon/sfdx-git-delta#54]
I'm getting trouble to extract the changes on my workflows objects custom or not, in some cases, the files are listed on the package.xml but are not copied into the forceapp folder.

`
C:\java_dev\Lightning\service>sgd --to "HEAD" --from 79f0af0f63 --repo . --output ./build -d .
{
  "error": null,
  "output": "./build",
  "success": true,
  "warnings": [
    "force-app\\main\\default\\workflows\\Case.workflow-meta.xml: metadataContent[subType].filter is not a function",
    "force-app\\main\\default\\workflows\\Task.workflow-meta.xml: metadataContent[subType].filter is not a function",
    "force-app\\main\\default\\workflows\\WorkOrder.workflow-meta.xml: metadataContent[subType].filter is not a function"
  ]
}
`
**Operating System:** …
Windows/Linux
**NPM version:** …
6.14.7
**Node version:** …
v14.8.0
**sgd version:** …
sfdx-git-delta@3.1.3

**Comment by scolladon** [comment]
Hi @alexandrececchin !

Thanks for raising this issue.

Does the workflow file itself is deployable ?

As I cannot reproduce locally, I would like to know if it is possible for you to provide a repository with the isolated suspect to reproduce the issue ?

When I cannot reproduce it is usually a specificity not yet handled by the tool or an issue with the xml structure in the file

Thanks in advance,
Seb

**Comment by alexandrececchin** [comment]
Hi @scolladon, 
I can't share the repository, but here are 2 examples of workflows objects with the problem that I mentioned before.

[workflows.zip](https://github.com/scolladon/sfdx-git-delta/files/5196642/workflows.zip)

**Comment by scolladon** [comment]
Hi @alexandrececchin 

Thanks for the files. They seem ok to me at first sight.

Does those file are deployable as is in your org ? Or they already have issues ?
Also, explain what modification I should commit on those files to reproduce your issue please ?

It will help a lot in the investigation process :)

**Comment by alexandrececchin** [comment]
Those files were extracted from a sandbox and added into a git branch. After that any even an empty space at the end of the files causing an issue.

**Comment by scolladon** [comment]
@alexandrececchin what is the result of the deploy command for those files on your side plz ? I would like to know if they are deployable without using sgd.
```
// <src-path> is the path to the metadata from your project folder (by default it is force-app/main/default/)
$ sfdx force:source:deploy -p <src-patch>/workflows/Task.workflow-meta.xml
```

**Comment by alexandrececchin** [comment]
@scolladon  I work around this problem manually copying the entire workflows to the deployed folder every time a new pipeline is triggered. Here  is the log from one of this deploy including the entire folder. 
[deploy_log.log](https://github.com/scolladon/sfdx-git-delta/files/5210312/deploy_log.log)

Inside the script deployment.ps1 I'm executing deploy using 

`sfdx force:source:deploy -p "./build/force-app/" -u $env:SFDX_USER --loglevel TRACE --wait 90`

**Comment by scolladon** [comment]
Ok so I guess the files are deployable with the full content.
Can you share the git diff related to those files please ?
`
git diff <from> <to>
`

**Comment by alexandrececchin** [comment]
[WorkOrder.zip](https://github.com/scolladon/sfdx-git-delta/files/5224740/WorkOrder.zip)
@scolladon heres the files, with e65c2f62 version being the old one and the 01c7f5d3 as the newest one.

**Comment by scolladon** [comment]
@alexandrececchin thank you very much for that, it helped a lot

I am able to reproduce locally and so I think I'll be able to ship a fix for that sooner or later.
I'll keep you posted here.
