### ISSUE TITLE
Metadata support request

### ISSUE THREAD

**Issue by jterrats** [scolladon/sfdx-git-delta#541]
Could it be possible to get support for AssessmentQuestion metadata type. This is from FSC

**Comment by scolladon** [comment]
There is something odd in the documentation about those types @jterrats 
It says the [suffix start with an uppercase](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_assessmentquestion.htm#:~:text=have%20the%20suffix%20.AssessmentQuestion) which is unusual => `.AssessmentQuestion`

Could let us know if it is really the case on your repository when fetching those metadata via sfdx ?
Same question for [AssessmentQuestionSet](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_assessmentquestionset.htm)

**Comment by scolladon** [comment]
I found the answer
- AssessmentQuestion suffix is `aq`
- AssessmentQuestionSet suffix is `aqs`
