### ISSUE TITLE
Unable to handle email templates

### ISSUE THREAD

**Issue by ciureanub** [scolladon/sfdx-git-delta#546]
Issue verification check:

- [ ] is the current repository fully deployable at the commit SHA provided with the 'from' parameter of the command?
- We're conducting delta-deployments for our project while parallelly retrieving prod metadata into branches to bring them closer to deployability-state.

## What is the problem?
We've noticed an incorrect sfdx-git-delta plugin behavior when it comes to email templates.

Using the plugin to get delta from PRs resulted in missing .email files (can be 0in size), which are required to deploy .email-meta.xml files. In other words any email template consists of two files:
email_template_developer_name.email
email_template_developer_name.email-meta.xml
The plugin generated delta only with .email-meta.xml files, skipping .email complementary files --> It's not possible to deploy only .email-meta.xml files. .email files have to be present to make it a deployable metadata delta.

It turned out that the last known working plugin version is 5.7.1. It could generate a delta of the pull request without issues (including .email). 
Many higher plugin versions (we checked above 7), including the newest one generated delta without .email files.

It seemed as a plugin fault at the very first sight however creating a new email template in a clean scratch org, retrieving it, committing and generating a delta resulted in correct outcome (both .email and .email-meta.xml files were present). I'm not sure if it's a bug in the plugin that has been hidden for so many releases.

We're in the middle of retrieving all email templates and email folders from production . Once that's done we should test the scenario once again and see if the plugin generates delta correctly. 

---

### What is the actual result?
No .email file is copied to delta folder

## Steps to reproduce
---

## Execution context
---

**Operating System:** Windows 
**node version:** node v19.0.1
**git version:** git version 2.39.2.windows.1
**sfdx version:** sfdx-cli/7.193.2 win32-x64 node-v18.14.2
**sgd plugin version:** sfdx-git-delta 5.13.3
## More information (optional)
---

GRPCL_AAL_EN
GRPCL_AAL_EN_333_program_step1.email-meta.xml
GRPCL_AAL_EN_333_program_step2.email-meta.xml
GRPCL_AAL_EN_333_program_step3.email-meta.xml
GRPCL_AAL_EN_Birthday.email-meta.xml
GRPCL_AAL_EN_Prospect_program_step1.email-meta.xml
GRPCL_AAL_EN_Prospect_program_step2.email-meta.xml
GRPCL_AAL_EN_Prospect_program_step3.email-meta.xml
GRPCL_AAL_EN_Share_a_product.email-meta.xml
GRPCL_AAL_EN_Win_back_program_step1.email-meta.xml
GRPCL_AAL_EN_Win_back_program_step2.email-meta.xml

**Comment by scolladon** [comment]
Hi @ciureanub !

Thanks for raising this issue and thanks for contributing in making this project better!

I'm able to reproduce locally when using empty email file, those are not copied alongside the `-meta.xml` related file...

I'll ship a fix soon
Stay tuned !

**Comment by ciureanub** [comment]
@scolladon that's correct; in our case the .email was 0 in size. 
Would be good to recheck the non-zero .email filesize. 
Thanks.
