### ISSUE TITLE
Ignore `.eslintrc.json` at project init

### ISSUE THREAD

**Issue by nvuillam** [scolladon/sfdx-git-delta#548]
When we do an [init of CI project](https://sfdx-hardis.cloudity.com/salesforce-ci-cd-setup-existing-org/) with sfdx-hardis, the first package.xml is computed using the great sfdx-git-delta :)

But it always adds .eslintrc.json in Aura and LWC types... so we have to update it manually

Would it be possible to always ignore them, as they won't never have any use being deployed to an org ? :)

**Comment by scolladon** [comment]
Hi @nvuillam!

Thanks for raising this issue and thanks for contributing in making this project better!

I think you could use the [`--ignore` parameter](https://github.com/scolladon/sfdx-git-delta#exclude-some-metadata-only-from-destructivechangesxml) of the plugin, it looks like to be exactly what you need.

Let us know if it is suited for your use case, if not let's talk about a new feature!

**Comment by nvuillam** [comment]
Thanks for the reply, but I really think it should be ignored by default because such behaviour is corresponding to 150% of sfdx-git-delta use cases, and these files must be committed anyway (and they are already in .forceignore by default)

**Comment by scolladon** [comment]
Hi @nvuillam, thanks for taking some times discussing this together in dm, really appreciated
From a pure product standpoint we aim to provide a flexible and simple plugin, we do not know better than our customers and do not pretend we could foresee every use cases 😅.
This is why we provide optional parameters to help customer drive the plugin to achieve their particular goals.

### Framing the requirement
In this situation the need as I understand it is to not add in the package.xml the elements that are not metadata (indeed makes sense...).
Question can be asked as well for the output folder containing incremental changes. Maybe there are uses cases where we want them to be copied anyway (splitting/revamping project per example), so let's consider this only at the package.xml level
it seems to be possible to consider using `--ignore` parameter as a workaround to not include those files.
And it seems not necessary to use sgd at the init as the whole repository content will be deployed anyway, unless we want to use sgd to generate the init package.xml (which is smart).

### Solution space
Here are the solution I can imagine for now (by order of preferences):
1. improve the plugin to not add in the package.xml element that are not metadata compliant (generic solution)
2. have a default `.sgdignore` used by the plugin when `-i` is not used (use it instead when filled) (configurable solution that would require maintenance to black list new elements)

Let's think/spike on that, maybe more solution will raises and maybe more people will need it or explain something similar which will help us shape another solution !

**Comment by mehdisfdc** [comment]
@scolladon My 2 cents:
IMO it's a minor issue since there is a workaround (`--ignore`), and it does not happen often (only once, when you initiate the repo). Still, in my view, it's an issue, as it not expected to have element that are not metadata compliant. 
So I would vote **solution #1**!

**Comment by nvuillam** [comment]
@scolladon as discussed, I also vote Solution 1 : avoid items that are not metadata in package.xml, without having to add extra parameters to the command :)

**Comment by AllanOricil** [comment]
I couldn't reproduce this. I ran sgd without passing a .sgdignore in a brand new sfdx project, and nothing was added in the package.xml. Then I created a dummy lwc, added a new commit, ran sgd again, and finally verified that only the lwc was included. Then I deleted .forceignore, repeated the previous steps, and again verified only the lwc was included in the package.xml.

**Comment by AllanOricil** [comment]
The same for aura. No `.eslintrc.` was inlcuded in the package.xml that sgd created

**Comment by AllanOricil** [comment]
I tested with `5.13.3` and `5.15.0`

**Comment by AllanOricil** [comment]
more or less related https://github.com/scolladon/sfdx-git-delta/issues/552

**Comment by scolladon** [comment]
Hi @nvuillam 

I just finalized a first draft of a PR (#554) to implement the solution 1.
If you could have a look at it and do the QA on your end and let us know your result (here or in the PR) it would be greatly appreciated!
Here are [high level steps](https://github.com/scolladon/sfdx-git-delta/blob/main/CONTRIBUTING.md#testing-the-plugin-from-a-pull-request) to do it.
_(do not hesitate to contact me if those steps are not clear enough or if you have any blockers while doing those)_

**Comment by nvuillam** [comment]
@scolladon of course :)
I'll just clone locally your branch, sfdx plugins:link and check with one of my use cases :)

**Comment by AllanOricil** [comment]
Somehow my previous tests were all wrong. Now that I have a test workbench repo in Github, I can see this problem. But for me it happens with workflows only

<img width="728" alt="image" src="https://user-images.githubusercontent.com/55927613/229589298-a87b6a83-89dd-49f8-8ac6-6eae371c4772.png">


<img width="625" alt="image" src="https://user-images.githubusercontent.com/55927613/229589106-58e6510a-b05b-4772-8860-8c9b7e4b8029.png">

**Comment by scolladon** [comment]
Hi @AllanOricil 

What is the SGD version running ?
Could you let me know how I can reproduce it locally ?
Can I access the repo you are mentioning and what command should I run to reproduce ?

What is the output of this command: 
```sh
$ git diff --name-status --no-renames <from> <to>
```

**Comment by AllanOricil** [comment]
@scolladon 

Im using sgd 5.16.0, but the issue also happens with 5.14.0.

This is the commit history of this repository

<img width="547" alt="image" src="https://user-images.githubusercontent.com/55927613/229636214-6b736af3-4714-46d4-95f2-8b0903e99617.png">


This is the output of `git diff --name-status --no-renames ${{ inputs.FROM }} HEAD`

<img width="688" alt="image" src="https://user-images.githubusercontent.com/55927613/229635923-67606f96-ac10-41ab-8d96-c786f3881192.png">

**Comment by scolladon** [comment]
Thanks for those information @AllanOricil.

According to the output of the `diff` command the result is consistent with the actual behavior of the plugin.
We can see it reproduced by the github workflows file present in the package.xml.
As there is no changes detected by git related to `.eslintrc.json` file it is not processed by the plugin and does not appear in the package.xml.
It is the result of the same behavior internally, the fix shipped will fix both.

It is expected to have the issue with any previous version.
The fix (#554) is going to be shipped in the next release (available first in the `latest-rc` release channel).
Stay tuned!

**Comment by nvuillam** [comment]
@scolladon sorry, just tested with @latest-rc and I still have .eslintrc.json :/

(but it's ok for the github workflow not appearing ^^ )

![image](https://user-images.githubusercontent.com/17500430/229748990-d4961a6b-a597-4f4d-9abe-31b43373fc04.png)

**Comment by scolladon** [comment]
Hi @nvuillam 

Thanks for the feedback and for your time testing it.

I'm not able to reproduce it locally
I have a created a dedicated [branch](https://github.com/scolladon/sfdx-git-delta-reproduction-playground/tree/issue/548) in our reproduction playground.

When you check it out:
```sh
$ git diff --name-status HEAD~3
A       .forceignore
A       .github/CODEOWNERS
A       .github/workflows/pull-request.yml
A       README.md
A       output/.keep
A       package.json
A       sfdx-project.json
A       sgd/reproduction/playground/aura/.eslintrc.json
A       sgd/reproduction/playground/classes/Test.cls
A       sgd/reproduction/playground/classes/Test.cls-meta.xml
A       sgd/reproduction/playground/lwc/.eslintrc.json
```
Which is what we want to reproduce

When it execute using `v5.17.0``
```sh
$ sfdx sgd:source:delta -f HEAD~3 -d
$ cat output/package/package.xml
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>Test</members>
        <name>ApexClass</name>
    </types>
    <version>57.0</version>
</Package>
$tree output
output
├── destructiveChanges
│   ├── destructiveChanges.xml
│   └── package.xml
├── package
│   └── package.xml
└── sgd
    └── reproduction
        └── playground
            └── classes
                ├── Test.cls
                └── Test.cls-meta.xml
```

**Comment by nvuillam** [comment]
@scolladon everything you need is here :)

I also just noticed that the files are `.eslintrc` and not `eslintrc.json`, I don't know if it matters ^^

**Comment by scolladon** [comment]
Thank you very much @nvuillam 

I cannot reproduce even using the repository provided. 
Using `v5.16.0` I can see the issue
Using `v5.17.0` the issue is fixed

Here is the protocol used:
```
$ git clone https://github.com/nvuillam/git-delta-test.git
$ cd git-delta-test
$ git fetch -pPt
$ mkdir output
$ sfdx sgd:source:delta --from 59a9d219d7f0b9a89f75bcadb8ea6ca078d6e106 --to 51800a3ff84d52568bb43740c1fa4b39aba65c3d -d
$ cat output/package/package.xml
$ tree output
```

I suspect the issue is related to the environment (mac vs windows)
I'll try tonight with a Windows VM with git bash and let you

**Comment by scolladon** [comment]
I've been able to reproduce on Windows.
Thanks @nvuillam for your help here.
I'll ship a fix tonight.

Stay tuned !

**Comment by nvuillam** [comment]
No more .eslintrc , I confirm this is ok with latest-rc, many thanks @scolladon :)

![image](https://user-images.githubusercontent.com/17500430/230027262-2855de0a-fab2-4dec-bdda-558e7c869acd.png)
