### ISSUE TITLE
new lwc isn't included

### ISSUE THREAD

**Issue by AllanOricil** [scolladon/sfdx-git-delta#565]
## What is the problem?

All the steps are shown below

repo: https://github.com/AllanOricil/sgd-issue

<img width="840" alt="image" src="https://user-images.githubusercontent.com/55927613/230612853-688fe7f7-184b-4156-be21-da6ea9ef02ff.png">

**Comment by AllanOricil** [comment]
@scolladon I published the test [repo](https://github.com/AllanOricil/sgd-issue) so that you can take a look

**Comment by AllanOricil** [comment]
never mind. I understood that if it is not on a package dir, sgd won't consider the metadata.

**Comment by scolladon** [comment]
Hi @AllanOricil,

I think it is related to [this enhancement request](https://github.com/scolladon/sfdx-git-delta/issues/316).
If there is traction from the community we will consider it.
But not much for now, and the workaround is the nominal use case of the plugin.
