### ISSUE TITLE
Is it possible to feed `--to` parameter with `"*"` ?

### ISSUE THREAD

**Issue by nvuillam** [scolladon/sfdx-git-delta#567]
I'm in a rush, can't detail more for now , currently I had to downgrade to sfdx-git-delta 5.13.3

sfdx sgd:source:delta --from "HEAD" --to "*" --output /tmp/sfdx-hardis-dag5kg --ignore-whitespace --json
{"status":1,"errorMessage":"[sfdx-hardis][ERROR] Error processing command\n${\n  \"status\": 1,\n  \"result\": null\n}\n\n","error":{"code":1,"killed":false,"signal":null,"cmd":"sfdx sgd:source:delta --from \"HEAD\" --to \"*\" --output /tmp/sfdx-hardis-dag5kg --ignore-whitespace --json","stdout":"{\n  \"status\": 1,\n  \"result\": null\n}\n","stderr":""}}

Anyone here having issues , that could detail more ?

**Comment by nvuillam** [comment]
I tested on another PR, the problem is probably coming from the XML
Would it be possible to have details on the crash when that happens ?

**Comment by scolladon** [comment]
Hi @nvuillam !

Thanks for raising this issue and thanks for contributing in making this project better!

During the duration of the investigation you can fallback to the `@stable` channel (linked to version `v5.13.3`)

You cannot have details on the crash via a debug parameter or a trace level parameter. We have plans to integrate it, but it is middle priority in our roadmap.

What I can see from the parameters is the `--from` parameter is referring to `HEAD` and `--to` is empty.
As `--to` is empty it is defaulted to `HEAD` as well.
It means the command executed will compare `HEAD` with `HEAD` ? This is the intent here ?

I need to reproduce the issue locally, there could be related to a Workflow file or a SharingRule file or a CustomLabels file.
If you are able to isolate the issue, let us know the steps.
If you are able to put everything in the [reproduction playground](https://github.com/scolladon/sfdx-git-delta-reproduction-playground) (branch `issue/567`) it could even more convenient

**Comment by nvuillam** [comment]
@scolladon does `fatal: Not a valid object name *\n` rings a bell for you ? :/

**Comment by scolladon** [comment]
Yep @nvuillam 

What should I do to reproduce in your context ?

**Comment by nvuillam** [comment]
It's on a client project, too complicated to reproduce publicly for now :/

Several month ago, `sfdx sgd:source:delta --from "HEAD" --to "*" --output /tmp/sfdx-hardis-dag5kg --ignore-whitespace --json` used to work, it does not anymore (even with not newest sfdx-git-delta)

I'll update sfdx-hardis to find a commit hash instead of the wildcard to build the command

**Comment by scolladon** [comment]
I am able to reproduce it locally using `--to` `"*"`.

I think the issue here is we try to interpret the `"*"` as a git pointer where it is not.
Not like HEAD or any other git formula, `"*"` is not translatable to a git sha.

What is the intent here of using `"*"` for `--to` parameter ? (if you could share docs about how it works it would be great)

Depending on what is the usage of `"*"` in git diff world and if there are (or not) suitable workaround, I'll consider whitelisting this input.

**Comment by nvuillam** [comment]
@scolladon any chance to have the "*" automatically converted to the appropriate value, or in some allowList ? :)
It would save me rework on sfdx-hardis ^^

**Comment by scolladon** [comment]
Issue closed on sfdx-hardis side

Answer to the question is it possible to feed `--to` parameter with `"*"`:
No, this is not a git sha pointer.

**Comment by nvuillam** [comment]
Thanks a lot @scolladon for the help in https://github.com/hardisgroupcom/sfdx-hardis/pull/360 :)
