### ISSUE TITLE
[DestructiveChanges] CustomObjectTranslations

### ISSUE THREAD

**Issue by alexmodis** [scolladon/sfdx-git-delta#57]
Issue verification check :

[x] does the current repository is fully deployable at the commit sha given to the from parameter of the command ?

## What is the problem
```
   "fullName": "DWIN2_WorkOrderTeammate__c-fr",
    "problem": "The CustomObjectTranslation called '\''DWIN2_WorkOrderTeammate__c-fr'\'' is standard and cannot be deleted",
    "problemType": "Error",

```
**but here is the destructive package.xml :**

```
<?xml version="1.0" encoding="UTF-8"?>
 <Package xmlns="http://soap.sforce.com/2006/04/metadata">
     <types>
         <members>DWIN2_AccountHandler</members>
         <members>DWIN2_AccountHelper</members>
         <members>DWIN2_ChatterPost_Utils</members>
         <name>ApexClass</name>
     </types>
     <types>
         <members>DWIN2_Operation_Dashboard/XRZpwoJeQSKZMYuycopSwAPYZPfLYU2</members>
         <name>Dashboard</name>
     </types>
     <types>
         <members>DWIN2_Account_AccountWithoutPriceBook</members>
         <members>DWIN2_Alert_Opportunity_VQ_Won_Relaunch24h</members>
         <members>DWIN2_ContractedPrice_CantUseProduct</members>
         <members>DWIN2_ContractedPrice_NoPricebook</members>
         <members>DWIN2_Error_DeleteWoliStageQuotation</members>
         <members>DWIN2_Error_DeleteWoliWorkOrderStatus</members>
         <members>DWIN2_Error_InsertWoliStageQuotation</members>
         <members>DWIN2_Error_InsertWoliWorkOrderStatus</members>
         <members>DWIN2_Error_OpportunitySendToCustomer</members>
         <members>DWIN2_Error_UpdateWoliStageQuotation</members>
         <members>DWIN2_Error_UpdateWoliWorkOrderStatus</members>
         <members>DWIN2_General_SourceRecordWasntFind</members>
         <members>DWIN2_Lead_LeadWithoutPricebook</members>
         <members>DWIN2_Lead_NoOpportunityWhileConversion</members>
         <members>DWIN2_OpportunityProduct_CantUseProduct</members>
         <members>DWIN2_OpportunityProduct_CantUseProductCauseOfLocation</members>
         <members>DWIN2_OpportunityProduct_NoPriceBookOnAccount</members>
         <members>DWIN2_OpportunityProduct_VehicleNotFound</members>
         <members>DWIN2_Opportunity_OpportunityWithoutProducts</members>
         <members>DWIN2_PriceBookEntry_ProductNotConfigured</members>
         <members>DWIN2_ProductLocationVehicle_ProductAndLocationVehicleMismatch</members>
         <name>CustomLabel</name>
     </types>
     <types>
         <members>Account-DWIN2_ProfessionalAccount</members>
         <members>Contact-DWIN2_Contact</members>
         <name>Layout</name>
     </types>
     <types>
         <members>DWIN2_Vehicle__c-en_US</members>
         <members>DWIN2_Vehicle__c-fr</members>
         <name>CustomObjectTranslation</name>
     </types>
     <types>
         <members>Account.DWIN2_AccountingGroup__c</members>
         <name>CustomField</name>
     </types>
     <types>
         <members>Contact.DWIN2_Contact_Compact</members>
         <name>CompactLayout</name>
     </types>
     <types>
         <members>default.DWIN2_AnalyticSectorsWithLead</members>
         <name>ReportType</name>
     </types>
     <types>
         <members>DWIN2_ADV_Reports/rapport_Comptes_par_dfaut_5WP</members>
         <members>DWIN2_Sales/DWIN2_Opportunity_VehicleQuote/DWIN2_LeadByMySector</members>
         <name>Report</name>
     </types>
     <types>
         <members>en_US</members>
         <members>fr</members>
         <name>Translations</name>
     </types>
     <version>49.0</version>
 </Package>
```

---

When trying to deploy destructive changes Salesforce send back an error that we cannot delete standard customobjecttranslation. 

### What is the expected result

Don't really know in this case as destructive package reference the whole translation fr/en_US but do not specifically reference the field in error...

### What is the actual result

```"problem": "The CustomObjectTranslation called '\''DWIN2_WorkOrderTeammate__c-fr'\'' is standard and cannot be deleted",```|

**Comment by alexmodis** [comment]
#40 we already talk about this subjet here but I think the situation is a bit different

**Comment by scolladon** [comment]
Hi @alexmodis !

Thanks for this, effectively it look like the other topics.
What commands (with parameters) did you use to deploy the destructiveChanges.xml ?

**Comment by alexmodis** [comment]
`sfdx force:mdapi:deploy --json --ignorewarnings --ignoreerrors -d ./output/destructiveChanges -u INTEG -w 60`

**Comment by scolladon** [comment]
Ok, so this is not handled by the ignorewarnings neither ignoreerrors.
Which I can understand because it is not going to be handled by the command line as it is not possible to do it.

So I guess you would like it to be handled by sgd.
Which I am not sure it is a good idea because it may requires a lot of work and maintenance for a use case which should not happen (deletion of standard translation). 

I guess it happened to you because you wanted to remove it from the repo, not from the org right ?

**Comment by alexmodis** [comment]
Yep the metadata doesn't exist anymore in the org.

I just don't understand why Salesforce understand that I want this field translation to be destruct as I do not see it in the output package xml. Any idea ?

**Comment by scolladon** [comment]
I think they are in the destructiveChanges in one of the past comment.
This is not this destructiveChanges you are deploying ?

**Comment by alexmodis** [comment]
Don't see it :

Below the interesting part of the destructive :
```
     <types>
         <members>DWIN2_Vehicle__c-en_US</members>
         <members>DWIN2_Vehicle__c-fr</members>
         <name>CustomObjectTranslation</name>
     </types>
```
```

     <types>
         <members>en_US</members>
         <members>fr</members>
         <name>Translations</name>
     </types>
```

And below the error : "problem": "The CustomObjectTranslation called '\''**DWIN2_WorkOrderTeammate__c-fr**'\'' is standard and cannot be deleted",|

I really don't get the point here as DWIN2_WorkOrderTeammate__c-fr is not part of the xml.

**Comment by scolladon** [comment]
I see, you're right.

Could be an issue with sfdx cli itself ?
Could you create an issue on the sfdx-cli repository also ?

**Comment by alexmodis** [comment]
Could be yes...
Yep I can 👍

**Comment by mehdisfdc** [comment]
@alexmodis To make sure that it's not directly an issue with SGD, would you be able to provide us with detailed repro steps leading to a `destructiveChanges xml.`that contains the `CustomObjectTranslation` and `Translations ` types? 
(assuming you did not delete all translations from the repo in one of your commit)

**Comment by alexmodis** [comment]
Issue is not with sgd as I'ld have write the same destructiveChange xml by hand.
