### ISSUE TITLE
Is it possible to create a required version of package.xml while triggering the Build ?

### ISSUE THREAD

**Issue by sairohith1009** [scolladon/sfdx-git-delta#582]
## What is the problem?
I want package.xml version as 52 
But i'm getting 56.

The below are the commands that i'm executing for generating the delta folder and package.xml
                        sh 'npm install sfdx-cli --global --force'
                        sh 'sfdx --version'
                        sh 'sfdx update'
                        sh 'sfdx plugins'
                        sh 'echo y | sfdx plugins:install sfdx-git-delta@v5.11.3'
                        sh 'mkdir -p Delta_pkg/'
                        if (env.GIT_BRANCH == 'develop' || env.CHANGE_TARGET == 'develop'){
                            sh 'sfdx sgd:source:delta -t HEAD -f b71f5d1aafa97cd2b95c914c345b730ab4818829 --output "Delta_pkg/" --generate-delta'
                        }
---

### What is the expected result?
i was expecting to have generate the package.xml with the specified version

## Steps to reproduce

---

## Execution context

---

**Operating System:** …

**yarn version:** …

**node version:** …

**git version:** …

**sfdx version:** …

**sgd plugin version:** …

## More information (optional)

---

**Comment by scolladon** [comment]
Hi @sairohith1009 !

You definitely can ! Just use the [`-a`](https://github.com/scolladon/sfdx-git-delta#:~:text=%2Da%2C%20%2D%2Dapi%2Dversion%3Dapi%2Dversion) parameter !

**Comment by sairohith1009** [comment]
Thank you so much for the quick reply @scolladon.
 is this the correct command to execute ?

sfdx sgd:source:delta -t HEAD -f b71f5d1aafa97cd2b95c914c345b730ab4818829 --output "Delta_pkg/" --generate-delta -a "52.0 "

If not, could you please paste any example command here.

**Comment by scolladon** [comment]
Sure,
I think what you wrote will work.
You could also pass it like that: `-a 52`
It is enough
