### ISSUE TITLE
Unable to Deploy Keyword List Component Type

### ISSUE THREAD

**Issue by Mars-PrakashSaini** [scolladon/sfdx-git-delta#593]
## What is the problem?

When I'm trying to retrieve keyword list and moderation rules using org browser, all the retrieved files goes into moderation folder. 
and the type of file is .keyword-meta.xml and .rule-meta.xml  for keyword list and moderation rules respectively. 
and while running the CI/CD, it creates package only for moderation rules not for Keyword List.

Also when I'm creating the package manually on my local machine using git-delta, it's not capturing the keyword list (The behavior is same as above).

The git delta is unable to differnetiate between file .keyword-meta.xml and .rule-meta.xml and reading only .rule-meta.xml file type.

### What is the parameter and the value you used with it?

sfdx sgd:source:delta --to HEAD --from $(previous_successfull_build_commit_id) --output . --ignore .packageignore

### What is the expected result?

The generated package.xml should include below component type 
    <types>
        <members>Test.Banned</members>
        <name>KeywordList</name>
    </types>
    <types>
        <members>test.Replace_banned</members>
        <members>test.Block_banned_keywords</members>
        <members>test.Freeze_for_frequent_posting</members>
        <members>test.Flag_banned</members>
        <members>test.Review_the_first_post</members>
        <name>ModerationRule</name>
    </types>

### What is the actual result?
The delta command only picking up moderation rules and creating the package.xml with below only 
    <types>
        <members>test.Replace_banned</members>
        <members>test.Block_banned_keywords</members>
        <members>test.Freeze_for_frequent_posting</members>
        <members>test.Flag_banned</members>
        <members>test.Review_the_first_post</members>
        <name>ModerationRule</name>
    </types>

## Steps to reproduce

All Site > Open Workspace > Moderation Rules > Content Criteria > New > give name and unique name > Save. > Click on add and add the keywords whatever you want.

click on Moderation Rules > Create a new rule > Provide the values accordingly and Save.
NOw retrive the newly created keyword list and moderation rule and try to create the package using sgd-deta commands 

sfdx sgd:source:delta --to HEAD --from $(previous_successfull_build_commit_id) --output . --ignore .packageignore

**Operating System:** … Windows

**node version:** … 18.0.0

**git version:** … 2.39.2.windows.1

**sfdx version:** … sfdx-cli/7.197.8

**sgd plugin version:** … v5.18.0

**Comment by scolladon** [comment]
Hi @Mars-PrakashSaini !

Thanks for raising this issue and thanks for contributing in making this project better!

I can reproduce the issue, thanks to your very detailed steps.
We'll fix it asap and let you know when it is shipped.

Stay tuned !

**Comment by scolladon** [comment]
Hi @Mars-PrakashSaini !

Thanks to you ! I'm sure it will help others as well !

Next week it will be integrated in the latest version (thanks for your feedback)

Happy incremental deployment !
