### ISSUE TITLE
Wave folder is not included in the diff

### ISSUE THREAD

**Issue by kaiserchiese** [scolladon/sfdx-git-delta#60]
## What is the problem

When running the usual command 'sgd --to myrepolastcommit --from myrepopreviouscommit --repo . --output .'

I've seen that Wave components are not included if they are commits related to changes on them.

We added some dashboards and components to the branch and we get nothing on the diff. 

The tool is currently working for us for everything but this Wave Analytics metadata.

We are running sgd v3.3.1

**Comment by scolladon** [comment]
Hi @kaiserchiese 

Thanks for this !
I try to reproduce locally and come back here
I think

1. We need to add the metadata definition for this in the metadata files
2. We need to map an handler with this kind of metadata (folder I guess)`

**Comment by kaiserchiese** [comment]
> Hi @kaiserchiese
> 
> Thanks for this !
> I try to reproduce locally and come back here
> I think
> 
> 1. We need to add the metadata definition for this in the metadata files
> 2. We need to map an handler with this kind of metadata (folder I guess)`

Yeah, if it is from some help 
![image](https://user-images.githubusercontent.com/37119471/93601846-19338580-f9c2-11ea-9b03-bccfa4d1dcc4.png)

That is the wave metadata that SF Org Browser on VS identifies in my Org. All the metadata of every kind is retrieved and deployed from the wave folder in force-app/main/default but each one has a different file termination.

**Comment by scolladon** [comment]
Hi @kaiserchiese !

Could you test the current master version locally ?
And let us know if it includes the Wave* elements
