### ISSUE TITLE
Missing LoyaltyProgramSetup metadata

### ISSUE THREAD

**Issue by gavignon** [scolladon/sfdx-git-delta#604]
Issue verification check:

- [x] is the current repository fully deployable at the commit SHA provided with the 'from' parameter of the command? 

## What is the problem?

Metadata "LoyaltyProgramSetup" is not part of the generated package.xml

---

### What is the parameter and the value you used with it?
We are using this plugin as part of the CI/CD

`sfdx sgd:source:delta -s force-app -f LAST_CI_DEPLOY -t HEAD -a 57.0 --output .`

## Steps to reproduce
Run the command in a repository with LoyaltyProgramSetup metadata

**Comment by scolladon** [comment]
Hi @gavignon!

Thanks for raising this issue and thanks for contributing in making this project better!

I'll add this metadata soon.
Stay tuned
