### ISSUE TITLE
Add `ActionLauncherItemDef` metadata support

### ISSUE THREAD

**Issue by bcawrse-SF** [scolladon/sfdx-git-delta#616]
Issue verification check:

- [X] is the current repository fully deployable at the commit SHA provided with the 'from' parameter of the command?

## What is the problem?

---

The following metadata type is omitted from the results of SGD:
ActionLauncherItemDef

      sfdx sgd:source:delta --to "HEAD" --from "$COMMIT_FROM" --output changed-sources/ --generate-delta --source force-app/ --ignore-destructive .destructiveignore --ignore .deltaignore

### What is the expected result?

Output should include the folder /ActionLaunchercherItemDef/ with the new Action Items; e.g. ComplaintCaptureEnglish_14t7f0l5jnkvp1edzzyd4ed3l7.actionLauncherItemDef-meta.xml

### What is the actual result?

Delta includes all changed files except those contained in /ActionLaunchercherItemDef/

Tried on both v57.0 and v58.0 of API

## Steps to reproduce

As above

## Execution context

---

**Operating System:** …

**yarn version:** …

**node version:** …

**git version:** …

**sfdx version:** …

**sgd plugin version:** …

**Comment by scolladon** [comment]
Hi @bcawrse-SF !

Thanks for raising this issue and thanks for contributing in making this project better!

I'm trying to find metadata definition but I'm a bit struggling... The [links](https://developer.salesforce.com/docs/metadata-coverage/57/ActionLauncherItemDef/details) seems broken.
If you have a link to share please let me know and I'll add this metadata support

**Comment by scolladon** [comment]
I found [this](https://github.com/forcedotcom/source-deploy-retrieve/blob/592f4c16fabd80a9d3bcdfc67e6d30040eaf1624/src/registry/metadataRegistry.json#LL3361C1-L3368C7) in the salesforce metadata repository.

It is enough for me to start, I'll ship this soon
