### ISSUE TITLE
Support for Apex SDK for Slack

### ISSUE THREAD

**Issue by legetz** [scolladon/sfdx-git-delta#621]
Salesforce has beta support for Apex SDK for Slack. This feature adds two new folders under force-app/main/default folder.

Folder "slackapps":
- Contains *.slackapp files where the content is YAML
- Contains *.slackapp-meta.xml files where XML file contains some sensitive values such as appToken/clientKey/clientSecret/signingSecret

Folder "viewdefinitions":
- Contains *.view files where the content is YAML
- Contains *.view-meta.xml files where XML file do not contain any sensitive data

https://developer.salesforce.com/docs/platform/salesforce-slack-sdk/guide/overview.html

It would be good if delta plugin would detect the changes in these folders as well

**Comment by AllanOricil** [comment]
cool feature
