### ISSUE TITLE
Issue creating package.xml from sgd:source:delta command

### ISSUE THREAD

**Issue by ikounalak** [scolladon/sfdx-git-delta#625]
Issue verification check:

- [ ] is the current repository fully deployable at the commit SHA provided with the 'from' parameter of the command?

## What is the problem?

Error when trying to generate the delta package.

### What is the parameter and the value you used with it?

sfdx sgd:source:delta --to "HEAD" --from "HEAD~1" --output "."

### What is the expected result?

Package.xml should have been update it with the delta componennts

### What is the actual result?

I get this: Warning: Deprecated config name: apiVersion. Please use org-api-version instead.

**Operating System:** Windows (VS Code)

**yarn version:** …

**node version:** v14.17.0

**git version:** 2.31.1.windows.1

**sfdx version:** sfdx-cli/7.203.6 win32-x64 node-v18.15.0

**sgd plugin version:** v5.19.0

**Comment by scolladon** [comment]
Hi @ikounalak !

Thanks for raising this issue and thanks for contributing in making this project better!

It seems related to #619 

If I understand properly, there are changes (new or changed metadata) in the codebase between the correct and the previous commit.
When executing the command sgd does not populate those changes in the package.xml right ?

Could you give me the exact step to reproduce this please (what is the content of the last commit) ?

**Comment by ikounalak** [comment]
Hello @scolladon ,

Thank you for your fast reply and help! It is related to #619 indeed, I will have a look in the config.

![image](https://github.com/scolladon/sfdx-git-delta/assets/30520125/acf6e7dd-b428-4a46-a6bd-fc8d3e925a1d)
