### ISSUE TITLE
Deleting any custom label from the source folder creates Custom Label file in the delta directory.

### ISSUE THREAD

**Issue by RohitGagan16** [scolladon/sfdx-git-delta#665]
Issue verification check:

- [ ] is the current repository fully deployable at the commit SHA provided with the 'from' parameter of the command?

## What is the problem?

Deleting the custom label from the source folder and not adding anything new, creates file in the delta directory while creating the delta with output directory. Since the file is added in the custom label without any label tag, this also makes an entry in the package.xml file.

Now while doing the deployment using this package xml will result in the error 

fileName:labels/CustomLabels.labels, fullName:CustomLabels, problem:Error parsing file: Premature end of file., problemType:Error, success:false]

Here is how I have created the delta folder

sudo sfdx sgd:source:delta --to<commitid> --from <commit id> --output sfdx-delta --generate-delta

and the command to deploy the source
sfdx force:source:deploy -x src-package.xml -u <userame> -g -w 0 --predestructivechanges src-destructiveChangesPre.xml --postdestructivechanges src-destructiveChangesPost.xml -l RunSpecifiedTests -r <tests> --json

---

### What is the expected result?
Ideally, if the custom label on translation file is modified with only deletion of labels and no new label is added, it should not generate any custom label file in the delta directory. If the file is not there in the delta directory, it will not be part of the generated package.xml file and hence error might not be there

### What is the actual result?

fileName:labels/CustomLabels.labels, fullName:CustomLabels, problem:Error parsing file: Premature end of file., problemType:Error, success:false]

## Steps to reproduce

1. Delete any custom label from the custom label file
2. run the sgd git delta tool. ex <sudo sfdx sgd:source:delta --to<commitid> --from <commit id> --output sfdx-delta --generate-delta>
4. Now check the generated package and package.xml file. this contains the custom label file with no label tag
6. trigger the deploy by providing the manifest file generated in step 3. ex 
sfdx force:source:deploy -x src-package.xml -u <userame> -g -w 0 --predestructivechanges src-destructiveChangesPre.xml --postdestructivechanges src-destructiveChangesPost.xml -l RunSpecifiedTests -r <tests> --json
---

-->

**Operating System:** … Linux

sfdx-cli/7.205.6 linux-x64 node-v18.16.0

**Comment by scolladon** [comment]
Hi @RohitGagan16 !

Thanks for raising this issue and thanks for contributing in making this project better!

I'll debug this issue very soon.
Thanks for catching this 👏 

Stay tuned, I'll try to ship a fix soon
