### ISSUE TITLE
@salesforce/cli compatibility

### ISSUE THREAD

**Issue by hungrypipo** [scolladon/sfdx-git-delta#673]
With sfdx-cli being now deprecated will this component be compatible as a plugin to the replacement cli @salesforce/cli?

This is the message on sfdx-cli in npm:
sfdx-cli is deprecated, and no updates are planned. Use @salesforce/cli instead. See https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_move_to_sf_v2.htm

If I install the latest @salesforce/cli and try to install this plugin I get the error 

pip@pip:~$ sfdx plugins:install sfdx-git-delta

    NpmError: Failed to find @salesforce/plugin-sfdx-git-delta@latest in the 

    registry

    Code: NpmError

My steps were:
Get NodeJS 18

sudo npm install -g @salesforce/cli

sfdx plugins:install sfdx-git-delta

**Comment by scolladon** [comment]
Hi @hungrypipo !

Thanks for raising this issue and thanks for contributing in making this project better!

We are aware that there may be [some compatibility quirks](https://github.com/scolladon/sfdx-git-delta/issues/619#issuecomment-1676123183) with `sf`.

We are planning doing the migration but we don't know yet **when** nor **how** it will be released (which tag / version).
We don't have yet automation to make sure it works and we barely tested it with various result.

Stay tuned, we plan to work on this subject at the earliest in September.

**Comment by hungrypipo** [comment]
Awesome thanks, I was hoping it was on your radar
