### ISSUE TITLE
Not picking up Custom Labels with --include param

### ISSUE THREAD

**Issue by hungrypipo** [scolladon/sfdx-git-delta#677]
Issue verification check:

- [x] is the current repository fully deployable at the commit SHA provided with the 'from' parameter of the command?

## What is the problem?

---

I'm trying to always include 3 directories in the diff and I'm using a .includeDeltaDeploy and contents are

force-app/main/default/labels/**
force-app/main/default/namedCredentials/**
force-app/main/default/remoteSiteSettings/**

It's working for namedCredentials and remoteSiteSettings but not Custom Labels
It's also weird I had to do the trailing ** otherwise I didn't get any files even for namedCredentials and remoteSiteSettings

### What is the parameter and the value you used with it?

  sfdx sgd:source:delta --to 07f98ffa652 --from 183aba061b9 --output . --include .includeDeltaDeploy

### What is the expected result?

(node:23168) Warning: Deprecated environment variable: SFDX_AUTOUPDATE_DISABLE. Please use SF_AUTOUPDATE_DISABLE instead.
(Use `node --trace-warnings ...` to show where the warning was created)
(node:23168) Warning: Deprecated environment variable: SFDX_DISABLE_AUTOUPDATE. Please use SF_DISABLE_AUTOUPDATE instead.
(node:23168) Warning: Deprecated environment variable: SFDX_LAZY_LOAD_MODULES. Please use SF_LAZY_LOAD_MODULES instead.
(node:23168) Warning: Deprecated config name: apiVersion. Please use org-api-version instead.
{
  "error": null,
  "output": ".",
  "success": true,
  "warnings": []
}

  Provide the expected content of the output folder
The output package.xml should list the 	<name>CustomLabel</name> types

### What is the actual result?

(node:23168) Warning: Deprecated environment variable: SFDX_AUTOUPDATE_DISABLE. Please use SF_AUTOUPDATE_DISABLE instead.
(Use `node --trace-warnings ...` to show where the warning was created)
(node:23168) Warning: Deprecated environment variable: SFDX_DISABLE_AUTOUPDATE. Please use SF_DISABLE_AUTOUPDATE instead.
(node:23168) Warning: Deprecated environment variable: SFDX_LAZY_LOAD_MODULES. Please use SF_LAZY_LOAD_MODULES instead.
(node:23168) Warning: Deprecated config name: apiVersion. Please use org-api-version instead.
{
  "error": null,
  "output": ".",
  "success": true,
  "warnings": []
}

  Provide the actual content of the output folder
The output package.xml does not list the <name>CustomLabel</name> types

## Execution context

---
**Operating System:** …
Windows 10

**node version:** …
18.17.1

**git version:** …
2.41.0.windows.1

**sfdx version:** …
7.161

**sgd plugin version:** …
5.24.2

## More information (optional)

---

$ git diff --name-status --no-renames 183aba061b9 07f98ffa652
M       .includeDeltaDeploy

  And for each SharingRule, WorkflowRule and CustomLabel files:
  $ git diff --no-prefix 183aba061b9 07f98ffa652 -- I:\source\files
diff --git .includeDeltaDeploy .includeDeltaDeploy
index e69de29bb..8b7a1490f 100644
--- .includeDeltaDeploy
+++ .includeDeltaDeploy
@@ -0,0 +1,4 @@
+# List files or directories below to include them when running sfdx-git-delta
+force-app/main/default/labels
+force-app/main/default/namedCredentials
+force-app/main/default/remoteSiteSettings
\ No newline at end of file

**Comment by scolladon** [comment]
Hi @hungrypipo !

Thanks for raising this issue and thanks for contributing in making this project better!

I'll have a look in the coming days.

Is there a custom label file at the `07f98ffa652` commit (`<to>`) ?
Do you have a way to isolate the issue by forking our [reproduction playground](https://github.com/scolladon/sfdx-git-delta-reproduction-playground) ? It will help us with the understanding of the issue from your point of view

**Comment by hungrypipo** [comment]
No I'm not committing changes to the custom label file but I'm trying to always have it in the delta output.   The reason is we have environment specific folders for the labels, namedCredentials, and remoteSiteSettings which we copy into the force-app/main/default/ directory structure and it's easier to always deploy them then figure out if they changed and include in delta.

The same thing with namedCredentials, and remoteSiteSettings is happening(I'm not committing changes to those) but the -n is working for those two and I get them in the package.xml as expected.

My understanding is the -n will always output those elements even if there's no changes in git

**Comment by scolladon** [comment]
Ok that's good information.
This way, I'm sure the case tested here concern only included file and not included file but also modified.
I'll check for both use case with the fix.

I think the best in this case is for the file to be erased by the modified. So for CustomLabel it will contains only what as changed when: `-n` is set **and** the CustomLabel file is modified.

Else it will contain the full CustomLabel file when: `-n` is set **and** the CustomLabel file is not modified.

**Comment by hungrypipo** [comment]
Confirmed the fix in v5.25.2
