### ISSUE TITLE
SGD command not generating delta on profile files

### ISSUE THREAD

**Issue by sameerseekala1** [scolladon/sfdx-git-delta#679]
Issue verification check:

- [x] is the current repository fully deployable at the commit SHA provided with the 'from' parameter of the command?
Yes
## What is the problem?

When committing changes to profiles in git, 'sgd:source:delta' command is creating package.xml with all profile names which are modified but it is not creating profiles folder under 'force-app/main/default' directory. SGD command is working fine with all the metadata files except profiles, it worked fine before but now seeing this issue. Did something change recently?

### What is the expected result?

Command should generate delta changes on the profile files and create 'profiles' folder under 'changed-sources/force-app/main/default' directory.

### What is the actual result?

No 'profiles' folder under 'changed-sources/force-app/main/default' directory though package.xml has the list of all changed profiles.

## Steps to reproduce

1. Clone feature branch from master.
2. Update and commit the change on any profile file by adding/removing a permission or page layout assignment under 'force-app/main/default' directory.
3. On commit git should trigger a validate/deployment job which generates delta changes between head commit and merge-base commit and store the delta changes under 'changed-sources' folder .
4. Upload the delta changes using github actions "actions/upload-artifact@v3.1.2".
5. Download the delta artifact and verify if 'profiles' folder exists under 'changed-sources/force-app/main/default' directory.

Since there is a change on the profile it should create delta artifact with profiles folder.

## Execution context

---

**Operating System:** …

**yarn version:** …

**node version:** …

**git version:** …

**sfdx version:** …

**sgd plugin version:** …

## More information (optional)

---

**Comment by scolladon** [comment]
Hi @sameerseekala1 !

Thanks for raising this issue and thanks for contributing in making this project better!

I need more information because I do not reproduce this behavior locally (cf branch [issue/679](https://github.com/scolladon/sfdx-git-delta-reproduction-playground/tree/issue/679) of the reproduction playground).
What is your context of execution ? (os, yarn version, node version, git version, sfdx version, sgd plugin version) =>
```sh
$ uname -v ; yarn -v ; node -v ; git --version ; sfdx --version ; sfdx plugins
```

Is there any specificity in the commit containing changes for the `profiles` ?
Is there any warnings in the output of sgd execution (it could come from the profile being malformatted per example)

**Comment by scolladon** [comment]
Thanks @sameerseekala1 I am able to reproduce locally now.
Nice catch

I work on it, stay tuned.

**Comment by sameerseekala1** [comment]
Plz let me know as soon as you have a fix for this.

**Comment by scolladon** [comment]
@sameerseekala1 if you have time to QA this PR it would be very helpful.
I think it fixes this issue.

You can follow those [steps](https://github.com/scolladon/sfdx-git-delta/blob/main/CONTRIBUTING.md#testing-the-plugin-from-a-pull-request) in order to test a PR locally
Let me know!

**Comment by sameerseekala1** [comment]
@scolladon Do i need to clone your repo and test it locally? I actually tried it but getting below error

<img width="449" alt="image" src="https://github.com/scolladon/sfdx-git-delta/assets/89123201/a55374a4-3fcd-4d1d-88df-c905a2085cb6">

**Comment by scolladon** [comment]
Yes @sameerseekala1  you need to clone or download the repository, you need it to build the plugin from the sources to test not yet released revision

**Comment by sameerseekala1** [comment]
@scolladon I tried to clone but getting below, am i doing something wrong here plz suggest
<img width="449" alt="image" src="https://github.com/scolladon/sfdx-git-delta/assets/89123201/071abd1d-5679-49d4-8249-e5eec67f89c9">

**Comment by scolladon** [comment]
@sameerseekala1 have you tried to clone it using the https url ?
```
$ git clone https://github.com/scolladon/sfdx-git-delta.git
```

**Comment by sameerseekala1** [comment]
@scolladon Thanks for quick fix.

**Comment by bct8925** [comment]
@scolladon I'm getting a similar issue even on v5.40.0 where it's not detecting the delta in the profiles, but it only happens when called via Node. Here is the git diff:
```
diff --git force-app/main/default/profiles/Admin.profile-meta.xml force-app/main/default/profiles/Admin.profile-meta.xml
index 0b328ec5..e2dbc09c 100644
--- force-app/main/default/profiles/Admin.profile-meta.xml
+++ force-app/main/default/profiles/Admin.profile-meta.xml
@@ -383,10 +383,6 @@
         <apexClass>LockSelector</apexClass>
         <enabled>true</enabled>
     </classAccesses>
-    <classAccesses>
-        <apexClass>LogCreatorEmailAction</apexClass>
-        <enabled>true</enabled>
-    </classAccesses>
     <classAccesses>
         <apexClass>LogPublisher</apexClass>
         <enabled>true</enabled>

```

**Comment by scolladon** [comment]
Hi @bct8925 

Sorry to hear you still have the issue.

What do you mean by "it only happens when called via Node" ?
Could you help me reproduce it with the minimal steps please ?

**Comment by bct8925** [comment]
We have a github workflow action running NodeJS that runs a validation deployment for PRs. We generate the diff and 
 package.xml using SGD to make the deployment zip. Here is a snippet of the code we run:
```js
const sgd = require('sfdx-git-delta');
let result = await sgd({
                to: HEAD_SHA,
                from: mergeBase,
                output: './output',
                apiVersion: `${sourceApiVersion}`,
                repo: './',
                source: './',
                ignore: IGNORE_PATH,
                ignoreDestructive: IGNORE_PATH,
            });
```
which stringified becomes this:
```json
{"config":{"to":"7e0f6ed34154aa21c3b6a7a99bd9d3c665801057","from":"3451c5b2cfad8ede63f2bfc41550afe105299a29","output":"output","apiVersion":59,"repo":"./","source":"./","ignore":".github/validator/resources/sgd-ignore","ignoreDestructive":".github/validator/resources/sgd-ignore"},"diffs":{"package":{},"destructiveChanges":{}},"warnings":[{},{},{},{}]}
```
The package.xml it generates seems to only be missing the profiles, but not permission sets, which makes sense considering how complicated profile metadata is. Here is the CLI command I ran which does generate the proper package.xml:
```bash
sf sgd source delta -f 3451c5b2cfad8ede63f2bfc41550afe105299a29 -t 7e0f6ed34154aa21c3b6a7a99bd9d3c665801057 -o output -i sgd-ignore -D sgd-ignore -a 59 --repo=./ --source=./
```

Thank you, any help is greatly appreciated!

**Comment by scolladon** [comment]
Sure @bct8925 !

What is the version of sgd you are using please ?
Both in the cli and locally in the `package.json` of the app you use to execute `sgd` as a node module

**Comment by bct8925** [comment]
@scolladon The CLI version is installed as an SF plugin and is on v5.40.0:
```
sfdx-git-delta
   ├─ version 5.40.0
   ├─ tag latest
   ├─ homepage https://github.com/scolladon/sfdx-git-delta#readme
   ├─ location /Users/bct8925/.local/share/sf/node_modules/sfdx-git-delta
   ├─ commands
   │  └─ sgd:source:delta
   └─ dependencies
      ├─ @salesforce/command ^5.3.9 => 5.3.9
      ├─ @salesforce/core ^7.3.6 => 7.3.8
      ├─ async ^3.2.5 => 3.2.5
      ├─ fast-xml-parser ^4.3.6 => 4.3.6
      ├─ fs-extra ^11.2.0 => 11.2.0
      ├─ ignore ^5.3.1 => 5.3.1
      ├─ isomorphic-git ^1.25.10 => 1.25.10
      ├─ lodash ^4.17.21 => 4.17.21
      ├─ simple-git ^3.24.0 => 3.24.0
      └─ xmlbuilder2 ^3.1.1 => 3.1.1
```

The node app's version is installing latest via bun, and the listed version is also v5.40.0:
```bash
> bun add --dev sfdx-git-delta @actions/cache @actions/artifact
"installed sfdx-git-delta@5.40.0"
```

**Comment by scolladon** [comment]
Could you help me to reproduce please ?
Could you create the minimum metadata and commit required to have the reproduction condition ? You can use our [reproduction playground](https://github.com/scolladon/sfdx-git-delta-reproduction-playground), just fork it and give me access to the fork.
And also provide the node application using the sgd module with the instruction to execute it using bun please ?

It will greatly help me reproduce exactly the issue in your condition and start troubleshooting

**Comment by bct8925** [comment]
@scolladon Will do!

**Comment by bct8925** [comment]
@scolladon I added you to my fork, but I'm unable to replicate the issue happening in our github action. At first I thought the issue was the node version, but it still happens in github on v20.13.1 but not locally. I made this [script](https://github.com/bct8925/sfdx-git-delta-reproduction-playground/blob/test-remove/test.js) to test but still no luck in replicating it locally. I'll keep playing around since at this point it must be something with our action.

**Comment by scolladon** [comment]
Ok @bct8925, thanks for keeping me posted.
I would like into the node cache first if I were you.
Let me know if I can help

**Comment by bct8925** [comment]
@scolladon  I did figure it out! I had to update our workflows and actions to use Node v20 instead of v16, which we needed to do anyway since they EOL'd v16. Thanks for all your help!

**Comment by scolladon** [comment]
Happy to hear you find it out @bct8925 !
We are compliant with the same requirement as sfdx cli for node versions.

Happy incremental deployment !
