### ISSUE TITLE
Install sfdx plugin on windows

### ISSUE THREAD

**Issue by alexmodis** [scolladon/sfdx-git-delta#68]
Unable to install the plugin sgd on windows as sfdx is running on node v12.8.3 and sgd need >14.6.0

```
alexis.rafesthain@LYN-L083 MINGW64 ~/Documents/projets/DentMaster/Repo/azureRepo (feature/713)
$ sfdx plugins:install sfdx-git-delta
This plugin is not digitally signed and its authenticity cannot be verified. Continue installation y/n?: y
Finished digital signature check.
error sfdx-git-delta@4.0.2: The engine "node" is incompatible with this module. Expected version ">=14.6.0". Got "12.18.3"
error Found incompatible module.
Installing plugin sfdx-git-delta... !

alexis.rafesthain@LYN-L083 MINGW64 ~/Documents/projets/DentMaster/Repo/azureRepo (feature/713)
$ node --version
v15.0.1

alexis.rafesthain@LYN-L083 MINGW64 ~/Documents/projets/DentMaster/Repo/azureRepo (feature/713)
$ sfdx -v
sfdx-cli/7.77.0-112dd7d412 win32-x64 node-v12.18.3
```

**Comment by mehdisfdc** [comment]
@alexmodis You should be able to run sfdx with higher versions of node than v12.8.3 
For example, I've installed node v14.14.0 on my machine (before installing Salesforce CLI with npm), and here the the output I get when I execute `sfdx -v`:
`sfdx-cli/7.77.0 darwin-x64 node-v14.14.0`

In fact I've had the `Expected version ">=14.6.0"` issue myself when I first tried to installed to the new version of SGD. 
I managed to solve it by removing any previous installation of node / yarn / Salesforce CLI on my machine, and then making sure that node v14.14.0 was properly installed before installing Salesforce CLI (via npm) and SGD.

**Comment by alexmodis** [comment]
alright thanks @mehdisfdc 
problem was with sfdx windows installer -> go in programe files -> Salesforce CLI --> uninstall.exe
Then install sfdx with npm instead of windows installer
