### ISSUE TITLE
Install fails with unable to obtain lock

### ISSUE THREAD

**Issue by raghavthakur1** [scolladon/sfdx-git-delta#692]
Issue verification check:

- [ ] is the current repository fully deployable at the commit SHA provided with the 'from' parameter of the command?

## What is the problem?

Install fails with unable to obtain lock for sfdx-git- delta

![image](https://github.com/scolladon/sfdx-git-delta/assets/10909369/6425a767-2655-489a-9fb2-4455a89a39ea)

## Steps to reproduce

---

## Execution context

---

**Operating System:** …

**yarn version:** …

**node version:** …

**git version:** …

**sfdx version:** …

**sgd plugin version:** …

## More information (optional)

---

**Comment by scolladon** [comment]
Hi @raghavthakur1 !

Thanks for raising this issue and thanks for contributing in making this project better!

It seems the installation tries to install the `v5.17.0`
Could you try with the `latest` channel ?

And also, could you give us more information about the Execution context (this is important) please?

**Comment by scolladon** [comment]
Hi @raghavthakur1 

We close this issue because we do not have enough information to pursue.

Feel free to reopen it with the information asked so we can move forward on it.
