### ISSUE TITLE
sf plugins

### ISSUE THREAD

**Issue by JulienDryepondt** [scolladon/sfdx-git-delta#694]
Hello,

It's more a quick question than an issue.
I'm moving my old sfdx commands to sf commands in yaml pipeline.
I'm wondering how sgd works with the new sf commands ? Can i still use "sfdx sgd" ? Have you planned to migrate the plugin to "sf sgd" ?

Thanks
Julien

**Comment by JulienDryepondt** [comment]
I read a closed issue what answers my question : https://github.com/scolladon/sfdx-git-delta/discussions/686#discussioncomment-6925644

**Comment by scolladon** [comment]
Hi @JulienDryepondt 

Thanks for this question, nice plan to migrate to `sf-v2`

We are planning on migrating our current plugin to the `sf-v2` plugin architecture.

In the meantime we tested the actual plugin with `sf-v2` and it works.

More details [here](https://github.com/scolladon/sfdx-git-delta/discussions/686#discussioncomment-6925644)
