### ISSUE TITLE
.include does not pull CustomLabel or ValueSet into package.xml

### ISSUE THREAD

**Issue by rravisaheb** [scolladon/sfdx-git-delta#695]
Issue verification check:

- [x] is the current repository fully deployable at the commit SHA provided with the 'from' parameter of the command?

## What is the problem?

Our CI/CD is set to validate builds and merge them to GitHub, however we push the changes to Production only once a week. Due to this setup, sometimes there are changes that were merged to GitHub but they are not pushed to Production yet. If there are dependencies between the changes, we rely on the `.include` parameter to pull the additional changes while generating package.xml.

It seems for the CustomLabel or ValueSet, even after it is listed in the `.include` file, the package.xml does not list them.

### What is the parameter and the value you used with it?

Example of .include file,
```
$ pwd
/Users/my_user/my_git_repo

$ cat .include
./force-app/main/default/labels/CustomLabels.labels-meta.xml
```

We run the following command to generate package.xml
```
sfdx sgd:source:delta --to HEAD --from "origin/release/remote_base_branch" --output "./manifest" --api-version 57.0 --include .include
```

### What is the expected result?

Here's the package.xml I'd expect,
```
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>Object__c.Field__c</members>
        <name>CustomField</name>
    </types>
    <types>
        <members>*</members>
        <name>CustomLabel</name>
    </types>
    <types>
        <members>Case.VR_on_Case</members>
        <name>ValidationRule</name>
    </types>
    <version>57.0</version>
</Package>
``` 

### What is the actual result?

```
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>Object__c.Field__c</members>
        <name>CustomField</name>
    </types>
    <types>
        <members>Case.VR_on_Case</members>
        <name>ValidationRule</name>
    </types>
    <version>57.0</version>
</Package>
``` 

## Steps to reproduce

1. Generate the `.include` file at the root of the project directory
2. Add `CustomLabels` to the .include file (see parameter above)
3. Generate `package.xml` using `sgd:source:delta`

## Execution context

**Operating System:** Mac/Linux

**node version:** 20.6.1

**git version:** 2.42.0

**sfdx version:** salesforce/cli/2.7.11 darwin-x64 node-v18.15.0

**sgd plugin version:** 5.25.2

## More information (optional)

---

**Comment by scolladon** [comment]
Hi @rravisaheb !

Thanks for raising this issue and thanks for contributing in making this project better!

I'll have a look very soon and keep you updated.

**Comment by scolladon** [comment]
Hi @rravisaheb 

I was able to reproduce locally.
And I was able to fix it by changing the content of the `.include` file.
With this content I got it working on my local: 

```
force-app/main/default/labels/CustomLabels.labels-meta.xml
```

Could you try on your end and me know ?
If it works I'll close the issue then
