### ISSUE TITLE
Error - "API version not found or not supported, using '58' instead"

### ISSUE THREAD

**Issue by AnantSahTeli** [scolladon/sfdx-git-delta#696]
Issue verification check:

- [ ] is the current repository fully deployable at the commit SHA provided with the 'from' parameter of the command?

## What is the problem?

Not able to convert metadata with api version 59

  When running delts sgd, throwing error, if the api version is greater than 58

### What is the parameter and the value you used with it?

PS C:\Users\dkaste\codebranch\coloplast-salesforce-repository> sfdx sgd:source:delta --from "HEAD^" --to "HEAD"  --repo . --output . --api-version "59.0"
(node:21236) Warning: Deprecated config name: apiVersion. Please use org-api-version instead.
(Use `node --trace-warnings ...` to show where the warning was created)
{
  "error": null,
  "output": ".",
  "success": true,
  "warnings": [
    "API version not found or not supported, using '58' instead"
  ]
}

### What is the expected result?

metadata should be convered with api version 59

### What is the actual result?

PS C:\Users\dkaste\codebranch\coloplast-salesforce-repository> sfdx sgd:source:delta --from "HEAD^" --to "HEAD"  --repo . --output . --api-version "59.0"
(node:21236) Warning: Deprecated config name: apiVersion. Please use org-api-version instead.
(Use `node --trace-warnings ...` to show where the warning was created)
{
  "error": null,
  "output": ".",
  "success": true,
  "warnings": [
    "API version not found or not supported, using '58' instead"
  ]
}

## Steps to reproduce

---

Update sfdx-project.json file with "sourceApiVersion": "59.0" and run a sgd command for delta

## Execution context

---

$ uname -v ; yarn -v ; node -v ; git --version ; sfdx --version ; sfdx plugins

**Operating System:** …Linux-x64

**yarn version:** …

**node version:** …node-v17.6.0

**git version:** …@salesforce/cli/2.9.8 linux-x64 

**sfdx version:** …sfdx-cli/7.209.6

**sgd plugin version:** … 5.25.2

## More information (optional)

---

PS C:\Users\dkaste\codebranch\coloplast-salesforce-repository> sfdx sgd:source:delta --from "HEAD^" --to "HEAD"  --repo . --output . --api-version "59.0"
(node:21236) Warning: Deprecated config name: apiVersion. Please use org-api-version instead.
(Use `node --trace-warnings ...` to show where the warning was created)
{
  "error": null,
  "output": ".",
  "success": true,
  "warnings": [
    "API version not found or not supported, using '58' instead"
  ]
}

**Comment by scolladon** [comment]
Hi @AnantSahTeli !

Thanks for raising this issue and thanks for contributing in making this project better!

We planned to release the v59 support when the winter 24 will be fully generally available (13 of October 2023)

Stay tuned !

#closes 641

**Comment by AnantSahTeli** [comment]
Thanks @scolladon

**Comment by mehdisfdc** [comment]
Thank you @scolladon for the enhancement!

@AnantSahTeli With the latest version of the plugin (from today), you should now be able to use API v59.

Let us now if this works as expected from your end 😃

**Comment by AnantSahTeli** [comment]
Thanks a lot @scollsdon.

Regards,
Anant Sah Teli
