### ISSUE TITLE
Add Git LFS Support

### ISSUE THREAD

**Issue by Russman12** [scolladon/sfdx-git-delta#704]
### Is your proposal related to a problem?

---

It seems git LFS is not fully supported. We would like to add git LFS to our project. We have a pipeline which handles deployment automatically based on the diff generated by this plugin. Unfortunately, when the diff encounters files that are LFS files, they don't get resolved and the pointer files are added to the output directory instead of the actual file. This is an example of the command which is being executed:
`sfdx sgd:source:delta --from "7ead58d37b9" --to "HEAD" --output deployment -d`
In the resulting deployment directory, the LFS file contents are the LFS pointers.

### Describe a solution you propose

---

Add the ability to properly diff git LFS files. There could be a new flag added to the command `--lfs` or maybe it could be something that's automatically detected.

### Describe alternatives you've considered

---

I've tried setting the lfs diff in my project git config with the following command: `git config diff.lfs.textconv cat`. This made no difference. Is there perhaps a different git config I can set that might resolve the issue?

**Comment by scolladon** [comment]
Hi @Russman12 !

Thanks for raising this issue and thanks for contributing in making this project better!

That is very interesting.
It seems to be [supported](https://github.com/git-lfs/git-lfs/blob/main/docs/man/git-lfs-faq.adoc#:~:text=How%20do%20I%20enable%20git%20diff%20to%20work%20on%20LFS%20files%3F) and what you did would do the trick

Where do you experience the issue? Locally or in the pipeline?
If it is in the pipeline, does `lfs` is [installed](https://github.com/git-lfs/git-lfs/blob/main/docs/man/git-lfs-faq.adoc#:~:text=I%E2%80%99m%20using%20Jenkins%20and%20git%20lfs%20install%20fails%20due%20to%20an%20invalid%20hook%20path.%20What%20do%20I%20do%3F) when the pipeline execute?
Do you have `.gitattributes`? If yes, what are those?

I'll try to reproduce it soon, (maybe early next week)
