### ISSUE TITLE
Push to scratch org

### ISSUE THREAD

**Issue by yaniv3109** [scolladon/sfdx-git-delta#716]
## Description

Hi,
As everyone knows, the delta allows some components to be pushed instead of all.
This is true and good for non-temporary environments like Dev, Qa and Prod.
What about the scratch org? The push must include all Metadata and then we will lose the advantage of a partial push.
In our organization, we want to use Delta to unite projects that have dependencies between them so that the project package will be significantly larger. Using Delta may help us in this case but there is still the problem of pushing to Scratch org because the push will take a long time.
Do you have a solution/idea for this case?
Thanks,
Yaniv

## Steps to reproduce
1. Create SO
2. Push to SO

**Operating System:** …

node version: 18.15.0

git version: 2.28

sfdx version: 7.209.6

---

**Comment by scolladon** [comment]
Hi @yaniv3109

I think you could be interested in the [org snapshot](https://developer.salesforce.com/docs/atlas.en-us.sfdx_cli_reference.meta/sfdx_cli_reference/cli_reference_org_commands_unified.htm#cli_reference_org_create_snapshot_unified) pilot.
I may help you having scratch org created with a base set of metadata, on top of which you could easily apply delta deployment.

**Comment by yaniv3109** [comment]
Hi @scolladon,
Thank you very much for the quick response and the desire to help!
I will contact Salesforce to open the possibility for me and I will examine it.
Is it ok for you not to close the case for now?
I will be in touch with you later..

**Comment by scolladon** [comment]
Yes sure !  We can keep it open, or we can close it and you can reopen it when you want.
Let me know what suits you best

**Comment by yaniv3109** [comment]
Thanks!! it's not taken for granted.
I'm just testing the sfdx for a few weeks and want to start using it later.
I came across several questions, including the question I asked here.
I would be happy if we could later hold a meeting about the tool - about its capabilities and limitations..
Is this possible for you?
If so, the case can be closed and I will contact you later as you determine.

**Comment by scolladon** [comment]
Sure, we can hold a meeting later, no problems

**Comment by yaniv3109** [comment]
Hi @scolladon,
How can I make an appointment with you? On which platform can we talk?
Thanks!

**Comment by scolladon** [comment]
Hi @yaniv3109 !

You can contact me on my email (in my github [profile](https://github.com/scolladon)).
