### ISSUE TITLE
Request for `OmniSupervisorConfig` metadata support

### ISSUE THREAD

**Issue by vstsjlp** [scolladon/sfdx-git-delta#722]
Issue verification check:

- [x] is the current repository fully deployable at the commit SHA provided with the 'from' parameter of the command?

## What is the problem?

After create or modificate a OmniChannelSettings metadata type and commited to the repo, no reference appears at package.xml

### What is the parameter and the value you used with it?

 sfdx sgd:source:delta --output /tmp/delta-deployment --to HEAD --from HEAD~3

### What is the expected result?
package.xml:

```
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>Incentive__c</members>
        <name>CustomObject</name>
    </types>
    <types>
        <members>OCS_1</members>
        <members>OCS_2</members>
        <name>OmniChannelSettings</name>
    </types
    <version>58.0</version>
</Package>
```

### What is the actual result?
package.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>Incentive__c</members>
        <name>CustomObject</name>
    </types>
    <version>58.0</version>
</Package>
```

## Steps to reproduce

---
1. Create or modificate som OmniChannelSettings metadata type. Push it to repository.
2. run 
$ sfdx sgd:source:delta --output /tmp/delta-deployment --to HEAD --from HEAD~3

## Execution context

---

[jenkins@jnk-salesforce]$ uname -v ; yarn -v ; node -v ; git --version ; sfdx --version ; sfdx plugins
#1 SMP Sun Oct 22 17:17:17 UTC 2023
-bash: yarn: command not found
v16.20.1
git version 2.40.1
 ›   Warning: sfdx-cli update available from 7.208.10 to 7.209.6.
sfdx-cli/7.208.10 linux-x64 node-v16.20.1
 ›   Warning: sfdx-cli update available from 7.208.10 to 7.209.6.
sfdmu 4.28.0
sfdx-git-delta 5.22.0

---

  Provide the output of these commands:
  $ git diff --name-status --no-renames HEAD~3 HEAD
  
  M       force-app/main/default/omniSupervisorConfigs/OCS_1.omniSupervisorConfig-meta.xml
  M       force-app/main/default/omniSupervisorConfigs/OCS_1.omniSupervisorConfig-meta.xml
  M       force-app/main/default/objects/Incentive__c/Incentive__c.object-meta.xml

**Comment by scolladon** [comment]
Hi @vstsjlp !

Thanks for raising this enhancement request and thanks for contributing in making this project better!

From what I see in the feature request, what you want is to add the [OmniSupervisorConfig](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta.%20%20/api_meta/meta_omnisupervisorconfig.htm) metadata support, right ? Not the [OmniChannelSettings](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_omnichannelsettings.htm) right ?
I think it is different but I want you to confirm.

**Comment by vstsjlp** [comment]
You're right, it's OmniSupervisorConfig.
