### ISSUE TITLE
Request support for `EventRelayConfig` metadata

### ISSUE THREAD

**Issue by szymon-halik** [scolladon/sfdx-git-delta#725]
### Is your proposal related to a problem?

 Metadata is not being picked up in the delta generation

---

### Describe a solution you propose

---
Please add `EventRelayConfig` metadata description for API version 56.0 and later

**Comment by szymon-halik** [comment]
Just to help a bit the folder name is `eventRelays`, so that you don't need to go via the config process
<img width="308" alt="Screenshot 2023-11-17 at 16 35 38" src="https://github.com/scolladon/sfdx-git-delta/assets/35228022/7aae2882-030a-4487-9829-90e9b76dcacd">

**Comment by scolladon** [comment]
Hi @szymon-halik !

Thanks for raising this feature request and thanks for contributing in making this project better!

I'll add it to the metadata the plugin support very soon
Stay tuned

**Comment by scolladon** [comment]
I cannot find any documentation related to `EventRelayConfig` metadata.
I find something with the [tooling API](https://developer.salesforce.com/docs/atlas.en-us.object_reference.meta/object_reference/sforce_api_objects_eventrelayconfig.htm) but I do not find anything with the metadata API and it does not seems to be displayed in the [Metadata coverage app](https://developer.salesforce.com/docs/metadata-coverage/59)

@szymon-halik how can I create this metadata and how can I retrieve it (what package.xml retrieve this kind of metadata) please ?

**Comment by szymon-halik** [comment]
I just saw it was released @scolladon. Thanks for the very quick fix for that! I will leave the short explanation for the successors the shed some light into this metadata type:

1. It's used to control the configuration with Amazon Event Bridge using events - [docs](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_eventrelayconfig.htm)
2. to be able to successfully deploy it you need to configure three other types of metadata:
    - `NamedCredential` - linking to your AWS account
    - `PlatformEventChannel`- channel placeholder for events either `data` or `event`
    - `PlatformEventChannelMember`- member with a subscription to Platform Event or ChangeDataCapture

3. The last two ones must be created using Tooling API 
4. The `Run` status can be changed manually depending on the needs so the metadata in repo will not always reflect what is in the org
