### ISSUE TITLE
Unable to install the plugin using new sf style command

### ISSUE THREAD

**Issue by shabnamnasreen** [scolladon/sfdx-git-delta#730]
I am using the new sf cli v2.15.9. The sdg plugin was working fine till last week, starting this week my jobs are failing with this error: 

Error: Could not run npm show for @salesforce/plugin-sfdx-git-delta

My node version is v21.3.0

This is my piece of code, which was working just fine till last week:

    node --version
    npm cache clean --force
    mkdir ~/.npm-global
    npm config set prefix '~/.npm-global'
    export PATH=~/.npm-global/bin:$PATH
    source ~/.profile
    npm install @salesforce/cli@2.15.9 --global

    # Output CLI version and plug-in information
    sf --version
    echo "y" | sf plugins install sfdx-git-delta
    sf plugins --core
    
    And below is the error I am getting:
    Error: Could not run npm show for @salesforce/plugin-sfdx-git-delta

**Comment by shabnamnasreen** [comment]
Thanks a ton @batruongnguyen . It worked.

**Comment by scolladon** [comment]
Thank you guys, feel free to reopen this issue if something similar occurs again.
