### ISSUE TITLE
Support `MarketingAppExtension` metadata

### ISSUE THREAD

**Issue by mollyellwick** [scolladon/sfdx-git-delta#732]
### Is your proposal related to a problem?

---

I am trying to deploy a MarketingAppExtension using sfdx-git-delta but it's not adding my metadata to the package.xml. I checked the plugin metadata files and noticed it wasn't listed.

### Describe a solution you propose

---
Adding support to plugin for `MarketingAppExtension` metadata type as outlined in this documentation:
https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_marketingappextension.htm

**Comment by scolladon** [comment]
Hi @mollyellwick !

Thanks for raising this feature request and thanks for contributing in making this project better!

I'll have a look at it in the week (probably) and I'll try to create a PR to include them if possible.
Stay tuned

**Comment by scolladon** [comment]
Hi @mollyellwick could you help us with the testing please ?
We have created a [PR](https://github.com/scolladon/sfdx-git-delta/pull/735), you can install it locally to test with your own metadata following those [steps](https://github.com/scolladon/sfdx-git-delta/blob/main/CONTRIBUTING.md#testing-the-plugin-from-a-pull-request).
Let us know if it possible for you to contribute this way, if not we'll find another way to test it before merging it and ship it.

**Comment by mollyellwick** [comment]
Hi @scolladon we use your plugin in a Docker image so I don't have experience using it locally, if you could find another way to test that would probably be best. Sorry I can't be of more help, and thank you for jumping on this so quickly!

**Comment by scolladon** [comment]
No problem, thanks for your answer, we'll find a way to test it properly
