### ISSUE TITLE
 npm ERR! request to https://registry.npmjs.org/sfdx-git-delta failed, reason: self-signed certificate in certificate chain

### ISSUE THREAD

**Issue by A30016340** [scolladon/sfdx-git-delta#734]
Hi,

When I am trying to install sgd plugin I am getting the below error. Can you please suggest how can I go ahead:

![image](https://github.com/scolladon/sfdx-git-delta/assets/148831272/26f24d68-e4c6-4947-b6f9-69e08ba66373)

`C:\WINDOWS\system32>sfdx plugins:install sfdx-git-delta
    ShellExecError: npm ERR! code SELF_SIGNED_CERT_IN_CHAIN
    npm ERR! errno SELF_SIGNED_CERT_IN_CHAIN
    npm ERR! request to https://registry.npmjs.org/sfdx-git-delta failed, reason: self-signed certificate in
    certificate chain

    npm ERR! A complete log of this run can be found in:
    C:\Users\a30014740_euc\AppData\Local\npm-cache\_logs\2023-12-06T00_04_57_601Z-debug-0.log

    Code: ShellExecError`

Thanks,
Ata.

**Comment by A30016340** [comment]
`31 timing command:show Completed in 70206ms
32 verbose type system
33 verbose stack FetchError: request to https://registry.npmjs.org/@salesforce%2fplugin-sfdx-git-delta failed, reason: self-signed certificate in certificate chain
33 verbose stack     at ClientRequest.<anonymous> (C:\Program Files\sf\client\node_modules\@oclif\plugin-plugins\node_modules\npm\node_modules\minipass-fetch\lib\index.js:130:14)
33 verbose stack     at ClientRequest.emit (node:events:514:28)
33 verbose stack     at TLSSocket.socketErrorListener (node:_http_client:495:9)
33 verbose stack     at TLSSocket.emit (node:events:526:35)
33 verbose stack     at emitErrorNT (node:internal/streams/destroy:151:8)
33 verbose stack     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
33 verbose stack     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
34 verbose cwd C:\Users\A30016340
35 verbose Windows_NT 10.0.19044
36 verbose node v20.9.0
37 verbose npm  v9.9.1
38 error code SELF_SIGNED_CERT_IN_CHAIN
39 error errno SELF_SIGNED_CERT_IN_CHAIN
40 error request to https://registry.npmjs.org/@salesforce%2fplugin-sfdx-git-delta failed, reason: self-signed certificate in certificate chain`

**Comment by scolladon** [comment]
Hi @A30016340 !

Thanks for raising this issue and thanks for contributing in making this project better!

Could you give us more information about your context please ?
```sh
$ uname -v ; yarn -v ; node -v ; git --version ; sfdx --version ; sfdx plugins
```
