### ISSUE TITLE
Translation Files not correctly created via --generate-delta

### ISSUE THREAD

**Issue by joernflath** [scolladon/sfdx-git-delta#737]
Issue verification check:

- [ ] is the current repository fully deployable at the commit SHA provided with the 'from' parameter of the command?

## What is the problem?

---

Translation files copied over via `sf sgd source delta --from develop --to HEAD --output ./deployment/tmp --generate-delta --source force-app` loose a parameter.
The original file looks like this:
<img width="854" alt="Greenshot 2023-12-11 17 25 32" src="https://github.com/scolladon/sfdx-git-delta/assets/2586710/be694f65-3a84-4c5d-b57e-3c923c2139d1">

And the copied over file looks like this:
<img width="861" alt="Greenshot 2023-12-11 17 25 47" src="https://github.com/scolladon/sfdx-git-delta/assets/2586710/ad5306ab-1ac3-4f5b-a7ce-054fcb318e80">

As you can see, the `xsi:nil=true` gets lost in the generation.

### What is the parameter and the value you used with it?

f sgd source delta --from develop --to HEAD --output ./deployment/tmp --generate-delta --source force-app

### What is the expected result?

The two files look exactly the same

### What is the actual result?

See description above

## Steps to reproduce

---

https://github.com/joernflath/sfdx-git-delta-reproduction-playground/tree/issue/737

## Execution context

---

Darwin Kernel Version 23.1.0: Mon Oct  9 21:28:12 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T8103
zsh: command not found: yarn
v18.6.0
git version 2.41.0
@salesforce/cli/2.20.6 darwin-arm64 node-v18.6.0
@salesforce/sfdx-scanner 3.18.0
devops-center 1.2.0
lightning-flow-scanner 2.5.0
packaging 1.27.7
sf-orgdevmode-builds 1.1.0
sfdmu 4.32.2
sfdx-essentials 2.12.0
sfdx-git-delta 5.30.0
sfdx-hardis 4.6.0
sfpowerkit 6.1.0
signups 1.4.28 (1.4.22)
texei-sfdx-plugin 1.17.3

**Operating System:** MacOs 

**yarn version:** N/A

**node version:** 18.6.0

**git version:** 2.41.0

**sfdx version:** 2.20.6

**sgd plugin version:** 5.30.0

## More information (optional)

---

**Comment by scolladon** [comment]
Hi @joernflath !

Thanks for raising this issue and thanks for contributing in making this project better!

Thank you very much for the level of detail provided here.
It is very comfortable, I think I have everything I need to look at this issue.

I'll try to provide a fix asap, stay tuned !

**Comment by scolladon** [comment]
Quick question @joernflath, does this change to the metadata makes it not deployable ?

**Comment by scolladon** [comment]
@joernflath would you be ok to help us doing the QA please ?

We have created a [PR](https://github.com/scolladon/sfdx-git-delta/pull/738), you can test it locally following those [steps](https://github.com/scolladon/sfdx-git-delta/blob/main/CONTRIBUTING.md#testing-the-plugin-from-a-pull-request).

**Comment by joernflath** [comment]
> Quick question @joernflath, does this change to the file content makes it not deployable ?

@scolladon - Yes, this makes the file not deployable:
`| Error de    Error parsing file: Attribute name "xsi:nil" associated with an element type "description" must be followed by the ' = ' character. (4:29) 4:29`

**Comment by joernflath** [comment]
@scolladon - Sorry, I tried to but complete these [steps](https://github.com/scolladon/sfdx-git-delta/blob/main/CONTRIBUTING.md#testing-the-plugin-from-a-pull-request), but I'm not able to link the plugin version with `sfdx plugins:link`
I get the following error:
`sfdx plugins:link
@salesforce/cli: linking plugin sfdx-git-delta... !
    Error: /Users/joernflath/.nvm/versions/node/v18.6.0/lib/node_modules/@salesforce/cli/node_modules/yarn/bin/yarn.js --non-interactive --mutex=file:/Users/joernflath/VS Code 
    Projects/SGD Playground/sfdx-git-delta/yarn.lock --preferred-cache-folder=/Users/joernflath/Library/Caches/sf/yarn --check-files --silent exited with code 1`

**Comment by scolladon** [comment]
Thank you very much for your help on this one @joernflath 
Great contribution, we'll ship a release soon.
Stay tuned!
