### ISSUE TITLE
Add Support for RecordAlertCategory

### ISSUE THREAD

**Issue by rel5555** [scolladon/sfdx-git-delta#751]
### Is your proposal related to a problem?

---

RecordAlertCategory isn't added to the package.xml generated by SGD.

### Describe a solution you propose

---

Add RecordAlertCategory

### Describe alternatives you've considered

---

N/A

### Additional context

---

**Comment by scolladon** [comment]
Hi @rel5555 !

Thanks for raising this issue and thanks for contributing in making this project better!

I'll have a look and try to include this in the next release
Stay tuned !
