### ISSUE TITLE
Missing MessagingChannel metadata

### ISSUE THREAD

**Issue by mhamdaouiSFDC** [scolladon/sfdx-git-delta#753]
Issue verification check:

- [x] is the current repository fully deployable at the commit SHA provided with the 'from' parameter of the command?

## What is the problem?

---

Metadata "MessagingChannel" is not part of the generated package.xml (it is supported by salesforce cli): https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_messagingchannel.htm

### What is the parameter and the value you used with it?

We are using this plugin as part of the CI/CD
`sf sgd source delta --to "HEAD" --from "HEAD^" --output changed-sources/ --generate-delta --source force-app/ 
`
## Steps to reproduce
Run the command in a repository with MessagingChannel metadata

**Comment by scolladon** [comment]
Hi @mhamdaouiSFDC !

Thanks for raising this issue and thanks for contributing in making this project better!

I'll add this metadata support in the next days.
Stay tuned!
