### ISSUE TITLE
I am getting Warning like in both  sfdx-cli and  Salesforce/CLI 

### ISSUE THREAD

**Issue by vivelan** [scolladon/sfdx-git-delta#761]
Hi,

I am getting Warning like in both  sfdx-cli and  Salesforce/CLI - like '(node:33036) Warning: Deprecated config name: apiVersion. Please use org-api-version instead.'

Thanks

**Comment by scolladon** [comment]
Hi @vivelan

This issue is already tracked.

Duplicate of #619 

**TL;DR**: You can ignore this warning, it will be fixed when we migrate on the new sf v2 plugin architecture
