### ISSUE TITLE
Getting warning while installing SFDX GIT Delta plugin

### ISSUE THREAD

**Issue by vivelan** [scolladon/sfdx-git-delta#772]
Hi,

I am converting my GitHub action(pipeline) from SFDX CLI to Salesforce@CLI latest version and I am using (echo y | sfdx plugins:install sfdx-git-delta and sfdx plugins:install @salesforce/sfdx-scanner) before also I use the same plugin with OLD SFDX CLI I have not received any warning but after update happen in CLI its throwing warning given below, Kindly help me to resolve this.

**For Git delta :**

its creator. Do you want to continue the installation?, (y/N)? This plugin isn't signed by Salesforce. Only install the plugin if you trust
its creator. Do you want to continue the installation?, (y/N) y? This plugin isn't signed by Salesforce. Only install the plugin if you trust
its creator. Do you want to continue the installation?, yes
25hBecause you approved this plugin, you can avoid future installation confirmations by adding the plugin to the unsignedPluginAllowList.json file. For details, see https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_allowlist.htm.
Finished digital signature check.
Installing plugin sfdx-git-delta@latest... yarn add v1.22.21
Installing plugin sfdx-git-delta@latest... info No lockfile found.Installing plugin sfdx-git-delta@latest... [1/4] Resolving packages...Installing plugin sfdx-git-delta@latest... [2/4] Fetching packages...Installing plugin sfdx-git-delta@latest... [3/4] Linking dependencies...Installing plugin sfdx-git-delta@latest... [4/4] Building fresh packages...Installing plugin sfdx-git-delta@latest... success Saved lockfile.Installing plugin sfdx-git-delta@latest... success Saved 234 new dependencies.Installing plugin sfdx-git-delta@latest... info Direct dependenciesInstalling plugin sfdx-git-delta@latest... └─ sfdx-git-delta@5.34.0Installing plugin sfdx-git-delta@latest... info All dependenciesInstalling plugin sfdx-git-delta@latest... ├─ @jridgewell/resolve-uri@3.1.1Installing plugin sfdx-git-delta@latest... ├─ @oclif/linewrap@1.0.0Installing plugin sfdx-git-delta@latest... ├─ @oclif/screen@3.0.8Installing plugin sfdx-git-delta@latest... ├─ @oozcitak/dom@1.15.10Installing plugin sfdx-git-delta@latest... ├─ arg@4.1.3Installing plugin sfdx-git-delta@latest... ├─ chalk@4.1.2Installing plugin sfdx-git-delta@latest... ├─ constant-case@3.0.4Installing plugin sfdx-git-delta@latest... ├─ csv-stringify@5.6.5Installing plugin sfdx-git-delta@latest... ├─ emoji-regex@8.0.0Installing plugin sfdx-git-delta@latest... ├─ ignore@5.3.0Installing plugin sfdx-git-delta@latest... ├─ jws@3.2.2Installing plugin sfdx-git-delta@latest... ├─ mock-stdin@1.0.0Installing plugin sfdx-git-delta@latest... ├─ os-tmpdir@1.0.2Installing plugin sfdx-git-delta@latest... ├─ propagate@2.0.1Installing plugin sfdx-git-delta@latest... ├─ reusify@1.0.4Installing plugin sfdx-git-delta@latest... ├─ sentence-case@3.0.4Installing plugin sfdx-git-delta@latest... ├─ slice-ansi@4.0.0Installing plugin sfdx-git-delta@latest... ├─ through@2.3.8Installing plugin sfdx-git-delta@latest... ├─ type-fest@0.21.3Installing plugin sfdx-git-delta@latest... ├─ v8-compile-cache-lib@3.0.1Installing plugin sfdx-git-delta@latest... ├─ xmlbuilder@11.0.1Installing plugin sfdx-git-delta@latest... └─ zip-stream@4.1.1Installing plugin sfdx-git-delta@latest... Done in 12.35s.Installing plugin sfdx-git-delta@latest... Refreshing user plugins...Installing plugin sfdx-git-delta@latest... installed v5.34.0
 ›   Warning: sfdx-git-delta > @salesforce/command@5.3.9: Package no longer 
 ›   supported. Contact Support at https://www.npmjs.com/support for more info.
 ›   Warning: "sfdx-git-delta > @salesforce/command > @oclif/test > @oclif/core
 ›    > ts-node@10.9.2" has unmet peer dependency "@types/node@*".
 ›   Warning: "sfdx-git-delta > @salesforce/command > @oclif/test > @oclif/core
 ›    > ts-node@10.9.2" has unmet peer dependency "typescript@>=2.[7](https://github.com/vivelan/CRMIT/actions/runs/7693454917/job/20962244676#step:5:8)".

These warnings can only be addressed by the owner(s) of sfdx-git-delta.
We suggest that you create an issue at https://github.com/scolladon/sfdx-git-delta/issues and ask the plugin owners to address them.

Successfully installed sfdx-git-delta v5.34.0
sfdx-git-delta 5.34.0

Uninstalled JIT Plugins:
community 3.0.13
custom-metadata 3.1.4
dev 2.1.6
devops-center 1.2.5
env 3.0.15
functions 1.22.[11](https://github.com/vivelan/CRMIT/actions/runs/7693454917/job/20962244676#step:5:12)
signups 2.0.[17](https://github.com/vivelan/CRMIT/actions/runs/7693454917/job/20962244676#step:5:18)
@salesforce/sfdx-plugin-lwc-test 1.1.1
@salesforce/sfdx-scanner 3.[20](https://github.com/vivelan/CRMIT/actions/runs/7693454917/job/20962244676#step:5:21).0

Thanks

**Comment by scolladon** [comment]
Hi @vivelan !

Thanks for raising this issue and thanks for contributing in making this project better!

We will address this issue when we will migrate the plugin to `sf v2` plugin architecture.
Currently we are still using the old architecture because our user base has not yet migrated to the new `sf` cli and we do not want to break their CI/CD.

We are currently thinking about how we would ship a new version on the new `sf v2` while still allowing legacy users to use the legacy cli without breaking their installation and without having to touch their setup.

This is issue is linked to this one #619 because the fix will close both of them.

**Comment by vivelan** [comment]
Thanks! for the quick response.

As per my understanding... The issue linked above which says people faces issues with sgd command but in my case I am facing warning at the stage of installing SFDX git delta and scanner it self.

Or Is this warning will not make any impact on my pipeline run ? so I can ignore for now and wait for your fix in future ?

**Comment by scolladon** [comment]
Yes @vivelan, you can ignore it, the plugin is installed and is working.
We have pipelines that ensure the latest version runs on all os, maintenance and active lts node version, and both sfdx and sf cli.

**Comment by vivelan** [comment]
Thanks and appreciate for the quick response.
