### ISSUE TITLE
Support the WebStoreTemplate metadata type

### ISSUE THREAD

**Issue by scolladon** [scolladon/sfdx-git-delta#776]
### Discussed in https://github.com/scolladon/sfdx-git-delta/discussions/774

<div type='discussions-op-text'>

<sup>Originally posted by **marcoalmodova** January 30, 2024</sup>
Hi, I was checking the files with the API versions and I could not find it there, but can the WebStoreTemplate metadata type be supported? 
We are using the plugin in a project and it does not detect the changes to this type of metadata.

There is the SF doc about it: https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_webstoretemplate.htm

Thanks!</div>

**Comment by marcoalmodova** [comment]
Thanks for the quick response and action, @scolladon ! ❤️

**Comment by marcoalmodova** [comment]
Thanks again, @scolladon ! Buying you a beer ;)

**Comment by marcoalmodova** [comment]
Hey @scolladon , I updated the plugin and tested, but it's not picking up the changes. I tested with a commit right before and the one adding a webStoreTemplate file. Can you have a second look at it, please?

**Comment by scolladon** [comment]
Hi @marcoalmodova, the plugin is updated but only the channel `latest-rc` has the new change.

Could you check the version you have ? (`sfdx plugins`)

**Comment by marcoalmodova** [comment]
Maybe because the folder name is camel-cased? Not sure if that will make a difference in the way the plugin parses the files.

![image](https://github.com/scolladon/sfdx-git-delta/assets/47369966/a9eda326-2e82-4a4f-8aa6-3a604c2950a7)

**Comment by scolladon** [comment]
That's it @marcoalmodova, the [documentation](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_webstoretemplate.htm) says the file extension and the folder name is lower case.
The plugin cannot match on either as in your exemple it is camel case and the plugin is case sensitive.
If you could make both the folder and the file extension lower case it would match.
Also the folder is `webstoretemplate` without an "s" in the end according to the doc.

**Comment by marcoalmodova** [comment]
But that's how the file is pulled from the scratch orgs, I didn't rename anything (the same about the folder).
So maybe the SF docs are wrong, but in any case the plugin should expect it to be camel cased. 
What do you think?

**Comment by scolladon** [comment]
We already had this kind of situation in the past. We prefer to use the documentation as the source of truth. 

Just to be sure, you could create an issue in sf cli and see how they propose to fix it (the doc or the way the cli retrieve). You could link this issue to the one in the cli.

In the meantime, you can change the folder name to be lower case, next retrieve will not change the folder.

**Comment by marcoalmodova** [comment]
@scolladon I tried like this and it also did not work:
<img width="304" alt="image" src="https://github.com/scolladon/sfdx-git-delta/assets/47369966/2154bcfa-33bc-462d-823a-7d18b7566bb5">

**Comment by marcoalmodova** [comment]
Renaming worked just fine, thanks.
I will also open an issue on the sf cli repository.
