### ISSUE TITLE
Profile file random behavior on generating Delta changes

### ISSUE THREAD

**Issue by vivelan** [scolladon/sfdx-git-delta#787]
Hi,

I am using Git Delta deployment on my pipeline and I am not sure about the file generating Delta changes on Profile.

I am having Profile file called admin.profile and it has almost all permission like (fieldpermission, classpermission, layout, object etc...) its around 3343 lines, Now I am creating new field under Account object and I am trying to add permission for Field in Admin profile, so i am adding only the new fields permission tag in profile, but while I am going for Delta deployment it creating profile file in Delta but inside the file I can see my changes are coming but along with few extra fields, layout permission also coming.

I am not able to understand, usually it should take the entire profile file 3343 lines or it should take only my changes.

My question is why its taking my changes and some few extra fields sometimes layout or sometimes objects ?

Thanks

**Comment by vivelan** [comment]
Thanks for the Quick response!

So on to your answer I understand that this random behavior in generating Profile file is usual! its not issue in my pipeline?

**Comment by scolladon** [comment]
Yes, this is usual and wanted
