### ISSUE TITLE
sfdx git delta is unable to generate package.xml for the omni supervisor configuration

### ISSUE THREAD

**Issue by narmadakankuri9** [scolladon/sfdx-git-delta#789]
Issue verification check:

- [x] is the current repository fully deployable at the commit SHA provided with the 'from' parameter of the command?

## What is the problem?

1. We have code change which consist of omni supervisor configuration in my code base. When I generate the package.xml using sfdx git delta. I was not able to se any members in the package.xml

### What is the parameter and the value you used with it?

sfdx sgd:source:delta --from <source branch> <Target branch> --output ./git-delta-diff

### What is the actual result?
command is generated the pakage.xml but it is without omni supervisor configuration changes

## Steps to reproduce

1. do some code base changes with omni supervisor configuration

folder structure : force-app/main/default/omniSupervisorConfigs

## Execution context

sfdx sgd:source:delta --from <source branch> <Target branch> --output ./git-delta-diff

**Operating System:** … windows 

**sfdx version:** … 7.144.2

**sgd plugin version:** … 5.2.0

**Comment by scolladon** [comment]
Hi @narmadakankuri9 !

Thanks for raising this issue and thanks for contributing in making this project better!

I see you are using the version `v5.2.0` of sgd.
`omniSupervisorConfigs` metadata support has been introduce in `v5.29.0`.

Could you update the plugin (using `latest-rc` channel would be best) and try again please ?
```sh
$ sfdx plugins:update
# or
$ sfdx plugins:install sfdx-git-delta@latest-rc
```

**Comment by narmadakankuri9** [comment]
Hello @scolladon - I have update the git-delta to sfdx-git-delta 5.34.0 version and tried to generate the package.xml. Still I see empty package.xml.

**Comment by scolladon** [comment]
Could you send the result of this command please :
```sh
$ git diff --name-status --no-renames <from> HEAD
# where <from> is the commit sha or git shortcut used with the `--from` parameter of sgd
```

**Comment by scolladon** [comment]
I think the omni supervisor config should be in the `destructiveChanges.xml` file as git tells it is deleted (D) @narmadakankuri9

**Comment by narmadakankuri9** [comment]
Sorry my bad! It's typo mistake. After upgrading the sfdx-git-delta to latest version I can see omni configurations in package.xml and as a source files. Thank you for the inputs!
