### ISSUE TITLE
UserAccessPolicy missing

### ISSUE THREAD

**Issue by jeldwendean** [scolladon/sfdx-git-delta#792]
Issue verification check:

- [X] is the current repository fully deployable at the commit SHA provided with the 'from' parameter of the command?

## What is the problem?

---

UserAccessPolicy isn't being picked up as a change

e.g. if I have a file called Admin.useraccesspolicy-meta.xml in the useraccesspolicies folder, when sfdx sgd:source:delta runs, it doesn't pick up these files.

### What is the parameter and the value you used with it?

N/A

### What is the expected result?

User Access Policies should be picked up

### What is the actual result?

User Access Policies are not picked up (delta folder is empty)

## Steps to reproduce

---

Create a User Access Policy, retrieve the metadata, commit metadata to branch, push branch, create PR, run pipeline with sfdx sgd:source:delta command

## Execution context

---

N/A - latest version of sfdx-git-delta

From searching the repo, I couldn't find UserAccessPolicy in any of the metadata version files

https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_useraccesspolicy.htm

**Comment by jeldwendean** [comment]
This should be as easy as adding:

`{
    "directoryName": "useraccesspolicies",
    "inFolder": false,
    "metaFile": false,
    "xmlName": "UserAccessPolicy"
  }`

to v57+

**Comment by scolladon** [comment]
I'll give it a shot soon, it will be available next week if everything goes fine
