### ISSUE TITLE
Data Wave scripts is not added to the delta

### ISSUE THREAD

**Issue by olektymchenko** [scolladon/sfdx-git-delta#800]
Issue verification check:

- [ ] is the current repository fully deployable at the commit SHA provided with the 'from' parameter of the command?

## Steps to reproduce

---

Add DataWeave script to the "force-app/main/dw" folder

**Comment by scolladon** [comment]
Hi @olektymchenko !

Thanks for raising this issue and thanks for contributing in making this project better!

Could you tell me more about this metadata type ?
I found something that could match in the documentation as [DataWaveResource](https://developer.salesforce.com/docs/atlas.en-us.248.0.api_meta.meta/api_meta/meta_dataweaveresource.htm), is it what you are thinking of ?

**Comment by olektymchenko** [comment]
Hello,
Yes, it is
Also other documentation
https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/DataWeaveInApex.htm



Пт, 8.03.2024 в 17:53, Sebastien ***@***.***>:
