### ISSUE TITLE
[LATEST-RC/5.38.1] [Error folder does not exist]

### ISSUE THREAD

**Issue by arafesthain** [scolladon/sfdx-git-delta#814]
Issue verification check:

- [x] is the current repository fully deployable at the commit SHA provided with the 'from' parameter of the command?

## What is the problem?

Unable to run the sgd delta command with success

### What is the parameter and the value you used with it?

`sfdx sgd:source:delta -d -t HEAD -f 2024_GR02.1_stopclock -r /home/vsts/work/1/salesforce_repo -i /home/vsts/work/1/salesforce_repo/.forceignore -o output`

### What is the expected result?

Command run without error (SGD version 5.34.0)

### What is the actual result?
`''\''home/vsts/work/1/salesforce_repo'\'' folder does not exist, '\''home/vsts/work/1/salesforce_repo/.forceignore'\'' file does not exist, '\''home/vsts/work/1/salesforce_repo'\'' is not a git repository'`

## Steps to reproduce

Go on develop24GR03 branch and try to compare with 2024_GR02.1_stopclock tag with the same folder structure as on the command line

## Execution context

Node:
v18.19.1
Npm version :
10.2.4
@salesforce/cli/2.32.8 linux-x64 node-v18.19.1
system: Ubuntu 22.04.4 LTS

sfdx-git-delta 5.38.1

yarn v1.22.21

**Comment by scolladon** [comment]
Hi @arafesthain !

Thanks for raising this issue and thanks for contributing in making this project better!

The issue is because of the absolute path IMHO...
It works well with relative path
I'll fix it very soon (I hope today).

Stay tuned !

**Comment by arafesthain** [comment]
Ahaha yep could be the root cause :)
As I'm on a virtual machine with fixed environment variables, I have to stick to the absolute path for my own sake :D

**Comment by arafesthain** [comment]
@scolladon alright from here! thx :)
