### ISSUE TITLE
Looking for an information

### ISSUE THREAD

**Issue by narmadakankuri9** [scolladon/sfdx-git-delta#824]
Hello! 

This is not an issue/bug/enhancement.

I'm looking for an info.

We are trying to create pachage.xml for custom applications and flexi pages but plugin is not able to generate. We are using sfdx-git-delts 5.2.0 version.

in which version of sfdx-git-delta , are you supporting the custom applications and flexi pages?

Thank you.!

I'm unable to find them in the product release.

**Comment by scolladon** [comment]
Hi !

I don't know why flexi pages and custom applications does not generate for you, both type are handled since the beginning of the project.

I think you should try with the `latest-rc` or `latest` or `stable` version of the plugin.
If you still have the issue then we should investigate

**Comment by scolladon** [comment]
Closing this issue as it needs more information, it seems to be related to an old version and it does not seems to be critical/urgent
Feel free to reopen it with more information
