### ISSUE TITLE
Not picking up on changes to omniDataTransforms, omniIntegrationProcedures and omniScripts

### ISSUE THREAD

**Issue by pcjones10** [scolladon/sfdx-git-delta#827]
Issue verification check:

- [x] is the current repository fully deployable at the commit SHA provided with the 'from' parameter of the command? Yes

## What is the problem?
---
We committed omniDataTransform, omniIntegrationProcedure and omniScript components to our code base but we are not seeing the newly added components picked up in the diff and manifest.

### What is the parameter and the value you used with it?
---
sfdx sgd:source:delta -f HEAD^ -o changed-sources/ -d

### What is the expected result?
---
We expect to see a package.xml created with the new components and types
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>PhilTest_1</members>
        <name>OmniDataTransform</name>
    </types>
    <version>52.0</version>
</Package> 
<img width="424" alt="image" src="https://github.com/scolladon/sfdx-git-delta/assets/1703223/2d7a20bc-7e36-42ed-bccb-5acafe97ed85">

### What is the actual result?
---
Instead we get an empty package.xml
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <version>52.0</version>
</Package>
<img width="442" alt="image" src="https://github.com/scolladon/sfdx-git-delta/assets/1703223/78e71d3f-551d-4165-b134-50c3a17f6b49">

## Steps to reproduce
---
Try adding OmniDataTransform components with a new commit.
Then run sfdx sgd:source:delta -f HEAD^ --output "."

## Execution context
---

---

**Operating System:** Ubuntu latest

**yarn version:** NA

**node version:** v18.12.0

**git version:** 2.25.1

**sfdx version:** 7.187.1

**sgd plugin version:** 5.11.4

<img width="1728" alt="99B3B1B1-E026-4FE0-9158-6FC0E2F12280" src="https://github.com/scolladon/sfdx-git-delta/assets/1703223/24da61c1-9c42-4187-84bf-f9346ed1e0f1">

**Comment by pcjones10** [comment]
I have tried increasing the API version with -a and in the sfdx config as well but that does not seem to produce a new result.

**Comment by scolladon** [comment]
Hi @pcjones10!

Thanks for raising this issue and thanks for contributing in making this project better!

From what I see you should try upgrading the plugin version you are using (`latest-rc` should work) 
Those metadata have been included with the version 5.29.0
