### ISSUE TITLE
Consider file with extension ".md" as CustomMetadata 

### ISSUE THREAD

**Issue by camillerev** [scolladon/sfdx-git-delta#853]
Issue verification check:

- [ ] is the current repository fully deployable at the commit SHA provided with the 'from' parameter of the command?

## What is the problem?

The files with the extension ".md" are considered as CustomMetadata components. After we run the sgd command with new .md files, we find it in the package.xml as below: 
![image](https://github.com/scolladon/sfdx-git-delta/assets/62376486/32fe7fda-89fe-4700-ada2-6e12424074f0)

### What is the parameter and the value you used with it?

Here is the command ran:
sf sgd:source:delta --to HEAD --from origin/main --repo . --output . --api-version 60.0

### What is the expected result?

Not having the files with the extension ".md" in the package.xml when we run the sgd command.

### What is the actual result?

The files with the extension ".md" are considered as CustomMetadata components in the package.xml. Here is an example:
![image](https://github.com/scolladon/sfdx-git-delta/assets/62376486/e63d2d63-dce6-4420-b3bb-0f4451044121)

## Steps to reproduce

1. Use the repo : https://github.com/camillerev/sfdx-delta-error-reproduction
2. Run : 
git checkout feature/testCustomMetadataPackage
sf plugins install sfdx-git-delta
sf sgd:source:delta --to HEAD --from origin/main --repo . --output . --api-version 60.0
3. Check the new file: package.xml
The file should not contain README and TEST. (Those are corresponding to ./TESTMD/README.md and ./TEST.md files that I created on the branch to test)

Result:
The package.xml contains:
![image](https://github.com/scolladon/sfdx-git-delta/assets/62376486/f8241046-ed85-461a-90b2-cd62c15f5d8c)

## Execution context

---

**Operating System:** MacOs 14.4.1

**yarn version:** …

**node version:** v21.6.1

**git version:** git version 2.30.2

**sfdx version:** salesforce/cli/2.25.7

**sgd plugin version:** v5.38.4

**Comment by scolladon** [comment]
You're welcome !

Happy incremental deployment 🚀
