### ISSUE TITLE
Package XML is empty.

### ISSUE THREAD

**Issue by jfaderanga** [scolladon/sfdx-git-delta#857]
Issue verification check:

## What is the problem?
- package.xml is empty when delta command is executed.
- tried with version v5.39.0 and v5.39.1, same result.

### What is the parameter and the value you used with it?
`--to "HEAD" --from "origin/develop" --output delta/ `

### What is the expected result?
Command output - Success
```
{
  "error": null,
  "output": "delta/",
  "success": true,
  "warnings": []
}
```

Package XML - Contains components
```
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <version>59.0</version>
    <types>
        <members>ClassName</members>
        <name>ApexClass</name>
    </types>
</Package>
```

### What is the actual result?
Command output - Success
```
{
  "error": null,
  "output": "delta/",
  "success": true,
  "warnings": []
}
```

Package XML - Empty
```
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <version>59.0</version>
</Package>
```
## Other Info
Rolled back to version 5.32.0 and works fine. Haven't tried other versions.

**Comment by scolladon** [comment]
Hi @jfaderanga !

Thanks for raising this issue and thanks for contributing in making this project better!

I think you can try the `stable` channel (it is linked to the version `5.34.0`) if you don't want to use a hard coded version.

Could you give me the result of those commands please ?
```sh
$ uname -v ; yarn -v ; node -v ; git --version ; sfdx --version ; sfdx plugins
$ git diff --name-status --no-renames <from> <to>
```

Also if you could provide reproduction steps it would be awesome and would really help me isolate the issue fast.

**Comment by scolladon** [comment]
That's great @jfaderanga, I have enough information to start troubleshooting on my side.
Thanks !

**Comment by scolladon** [comment]
I suspect the changes are white changes in the profiles @jfaderanga 
Meaning they are either formatting change or information moved resulting in nothing change as metadata in the file.

Could you send the result of this command for all profiles listed in your previous comment please ?
```sh
$ git diff --no-prefix <from> <to> -- <file-path>
```

**Comment by scolladon** [comment]
Good news @jfaderanga, I'm able to reproduce
I reopen the issue and work on it.
Thanks for all your help here

**Comment by bct8925** [comment]
@scolladon I'm getting a similar issue even on v5.40.0 where it's also never picking up profiles, but only when called via Node.
