### ISSUE TITLE
GenAiPromptTemplate and other new metadata types are not detected - please add.

### ISSUE THREAD

**Issue by prakashpurswani-sanofi** [scolladon/sfdx-git-delta#863]
### Is your proposal related to a problem?

---

### Describe a solution you propose

---

### Describe alternatives you've considered

---

### Additional context

---

**Comment by prakashpurswani-sanofi** [comment]
Thanks @scolladon for prompt reply. One more we can add in the same build is https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_genaiprompttemplateactv.htm

These two are related to "Prompt Templates" and it would be a great help if we can release a build soon with this. I will raise separate issue for the other GenAI / Einstein / GPT metadata types as per the needs.

**Comment by scolladon** [comment]
You got it @prakashpurswani-sanofi !

In the mean time we will create the preview version (61) support
