### ISSUE TITLE
[Ability to add file that has no modifications in git]

### ISSUE THREAD

**Issue by alexmodis** [scolladon/sfdx-git-delta#87]
### Is your proposal related to a problem?

---

I got an error during the deployment of an object : Cannot set sharingModel to ControlledByParent on a CustomObject without a MasterDetail relationship field

So I had to make modifications in master/details field of this object in order for the deploy to work.

### Describe the solution you'd like

---

Add something like a .XXXignore file, ".filestoadd" ? to be able to add file on the fly without making git modifications.

### Describe alternatives you've considered

---

Crate a fake/non-useful diff just for delta to add it.

Use sfdx option to deploy via package.xml/manifest only (-x)

**Comment by mehdisfdc** [comment]
I'm not sure about the ways the ".filestoadd" file would be maintained? (If you need to edit it manually to add **and** to remove the files once they are deployed, it would be a little cumbersome).
I would recommend dealing with this issue with a deployment using the package.xml option (`sfdx force:source:deploy -x`)

**Comment by alexmodis** [comment]
@mehdisfdc less cumbersome/error prone than adding blank space to a metadata file INMHO.
For manifest option, that I think too is the best one (even if I do not like Salesforce to add all that automatic files to my deploy without my consent ^^), it means udpate the pipeline to be possible to deploy as usual with -p option or with -x option.

**Comment by scolladon** [comment]
Hello,

I think you could use the idea from @mehdisfdc and have another static package.xml.
Then in your pipeline you can merge the generated package.xml with the static using [another tool](https://github.com/scolladon/sfdc-merge-package).
And then deploy using the package.xml to have both in one shot

**Comment by alexmodis** [comment]
@scolladon @mehdisfdc Thanks guys, I'm closing this one
