### ISSUE TITLE
Enable 'UserAccessPolicy' metadata

### ISSUE THREAD

**Issue by awesomeandrey** [scolladon/sfdx-git-delta#886]
### Is your proposal related to a problem?

---

[User Access Policy (UAP) settings](https://help.salesforce.com/s/articleView?id=sf.perm_user_access_policies.htm&type=5) are useful in the context of managing/setting up users with permission sets & PSGs.
IMHO it makes sense to enhance SGD plugin to support underlying metadata for UAP.

### Describe a solution you propose

---

When running `sf sgd:source:delta` command I would like SGD plugin to capture changes to `***.useraccesspolicy-meta.xml` files too.

### Describe alternatives you've considered

---

So far the only option is to deploy UAP metadata manually bypassing automated CI/CD flow.

### Additional context

---

- SGD plugin installation command: `sf plugins:install "sfdx-git-delta@stable"`
- Salesforce API version used on the project: `60.0`

**Comment by scolladon** [comment]
Hi @awesomeandrey !

Thanks for raising this issue and thanks for contributing in making this project better!

I think it has been released with the `v5.37.0`.

Could you try using the `latest` tag please ? `sf plugins:install "sfdx-git-delta@latest"`

**Comment by awesomeandrey** [comment]
@scolladon 

That worked, wonderful, thanks a ton!
