### ISSUE TITLE
Support `sf` CLI instead of `sfdx`

### ISSUE THREAD

**Issue by anand-sdocs** [scolladon/sfdx-git-delta#888]
Currently this plugin is a plugin to `sfdx`. Salesforce is moving towards `sf` cli as the supported command line. Having this plugin be `sf` CLI friendly would be awesome.

Don't know if this plugin in as is would work if i tried to do `sf plugin install` but putting this in your radar as salesforce isn't working on `sfdx` AFAIK.

**Comment by scolladon** [comment]
Hi @anand-sdocs!

Thanks for raising this issue and thanks for contributing in making this project better!

We are tracking this matter inside this [issue](https://github.com/scolladon/sfdx-git-delta/issues/619#issuecomment-2130037700). 
We documented our approach there to make sure no users are impacted badly by the upgrade.
duplicate #619

The plugin is compatible with `sf` cli, we have CI jobs ensuring it.
If it's ok for you we can close this issue and go on the discussion in the other issue if you feel the need to

**Comment by anand-sdocs** [comment]
Thanks @scolladon !!! Closing the issue.
