### ISSUE TITLE
Resource file changed does not copy the whole static resource

### ISSUE THREAD

**Issue by RohitGagan16** [scolladon/sfdx-git-delta#895]
Issue verification check:

- [ ] is the current repository fully deployable at the commit SHA provided with the 'from' parameter of the command?

## What is the problem?

sfdx git delta plugin is not picking the source file in the delta directory if the change is done in the meta xml of a static resource.

### What is the actual result?

Retrieve the static resource from the org in source format using the sf project retrieve start command
and then make a change to the -meta.xml file. Run the sfdx-git delta command to generate the delta folder.
Check the contents of the foler,it only has the -meta.xml file

@salesforce/cli/2.51.6 linux-x64 node-v18.17.1

@salesforce/cli: Installing plugin sfdx-git-delta@latest... installed v5.40.2

**Comment by scolladon** [comment]
Hi @RohitGagan16 !

Would you be able to help us with the UAT [here](https://github.com/scolladon/sfdx-git-delta/pull/896#issuecomment-2259240919) please ?

**Comment by RohitGagan16** [comment]
> Hi @RohitGagan16 !
> 
> Would you be able to help us with the UAT [here](https://github.com/scolladon/sfdx-git-delta/pull/896#issuecomment-2259240919) please ?

aah i am sorry, missed the message

**Comment by RohitGagan16** [comment]
Thanks @scolladon  for the quick fix. That is amazing
