### ISSUE TITLE
Consider generating test classes based on annotations in class files

### ISSUE THREAD

**Issue by renatoliveira** [scolladon/sfdx-git-delta#913]
### Is your proposal related to a problem?

My proposal relates to what has been reported back in December 2022 on #402 and two weeks ago in #902.

---

Currently the SGD plugin is unable to generate a list of test classes on its own because it does not connect to the Salesforce orgs to read the source from the Dependency API. I'm assuming the idea, if this connection was implemented, was to list classes that were modified and then verify which test classes depend on those, but that's not what I'm proposing here.

---

I propose the creation of an annotation for SGD to read the files that are being deployed to the org. A comment on the top level of the Apex class or trigger that mentions the test(s) that are used to cover that class. This could also be done with Flows if users are willing to add a snippet to the flow's description, or create a dummy variable within it that is not used by the Flow itself, but can be accessed by SGD by reading the XML directly.

For classes and triggers, the annotation could include either a) a single test, b) a list of tests, c) a test suite or d) a collection of suites (or a mixture of all). The annotation starts with the prefix `@SGD.[Tests,TestSuites]` and is followed by a list of API names of classes or test suites.

```apex
//@SGD.Tests: ThatThingTest
//@SGD.TestSuites: ThatTestSuite,OtherTestSuite
public class ThatThing {
  public static void doThat() { ... }
}
```

```apex
//@SGD.Tests: ThatThingTest,ThatIntegrationThingTest
//@SGD.TestSuites: ThatTestSuite
trigger ThatThing on Thing__c (before insert) {
  ... 
}
```

I think that it would be an option to use `@SuppressWarnings` too, which does nothing in Apex, but then SGD would have to read the entire class. Meanwhile, having a comment at the top level would be quicker to read because the tool can stop reading once it reaches a `public`, `private`, `global` or `trigger` keyword.

---

I believe this approach is non-invasive, it keeps SGD from having to connect to the org's APIs, and gives the developers full control of which tests are run for each deployment, because the information is sourced from the changed metadata.

For failed pipelines when the developer forgets to add the notation (that is: a deployment fails because a certain test was not run) the fix is as simple as adding a line to the affected class(es).

---

**Comment by scolladon** [comment]
Hi @renatoliveira !

I really love the idea and I really love the work you've done with this spec, very clear, thanks.

I think there is no requirement to couple that with this plugin and I think it should be done in a dedicated plugin.
If you want I can contribute (read code, discuss architecture, build CI, build small feature, etc)

**Comment by scolladon** [comment]
> Can I @ you about it on this issue later? 🙏

Sure ! I'll contribute with pleasure 👍

**Comment by mcarvin8** [comment]
@renatoliveira  - To chime in here, I do like the idea of declaring tests to run against as annotations in the apex file itself. 

I did something similar in terms of developing a Salesforce CLI plugin designed to be paired with sfdx-git-delta for users wishing to execute the right tests during delta deployments. 

My approach is using the commit messages and a config that contains a regular expression developers would use to declare tests in the message. 

But declaring them in the files themselves might be a more Salesforce friendly solution. 

You can reference my plugin which was built from the "sf" plugin template from earlier this year. I recall issues directly with the template until I made adjustments to certain files. The sfdx-git-delta plugin is built from the previous sfdx architecture if I'm not mistaken. 

I also have made certain functions designed to validate provided test class names against the package directories, which is something I would recommend you doing so users are alerted to things like typos/etc. 

Up to you what you'd like to do. Just thought I'd share similar work I've done earlier this year. 

https://github.com/mcarvin8/apex-tests-git-delta

**Comment by renatoliveira** [comment]
> @renatoliveira - To chime in here, I do like the idea of declaring tests to run against as annotations in the apex file itself.
> 
> I did something similar in terms of developing a Salesforce CLI plugin designed to be paired with sfdx-git-delta for users wishing to execute the right tests during delta deployments.
> 
> My approach is using the commit messages and a config that contains a regular expression developers would use to declare tests in the message.
> 
> But declaring them in the files themselves might be a more Salesforce friendly solution.
> 
> You can reference my plugin which was built from the "sf" plugin template from earlier this year. I recall issues directly with the template until I made adjustments to certain files. The sfdx-git-delta plugin is built from the previous sfdx architecture if I'm not mistaken.
> 
> I also have made certain functions designed to validate provided test class names against the package directories, which is something I would recommend you doing so users are alerted to things like typos/etc.
> 
> Up to you what you'd like to do. Just thought I'd share similar work I've done earlier this year.
> 
> https://github.com/mcarvin8/apex-tests-git-delta

Really appreciate the comment! Interesting to see your plugin, but the direction I'm going with my idea is unrelated to the version control itself (at least for now!).

I started some work on this repository of mine, and would love some input from you and @scolladon on this. Currently I implemented the list feature only to read the Apex files in a directory, and provided two output formats (CSV and the Salesforce CLI command format).

https://github.com/renatoliveira/apex-test-list

I have yet to check on how to publish this. I don't recall seeing on the official guide if publishing to NPM is a must so others can install. Is this the case?

The next feature to work on is to read all Apex files listed in a XML manifest and then try to read those files to do the same thing as the current command does - except it will read only specific files. :)

**Comment by mcarvin8** [comment]
I think publishing to NPM is usually the recommended method for all Salesforce CLI plugins. I see the salesforcecli github templates has a template for publishing to NPM which you use. I don't use this, I use Google's Release Please github actions to publish to NPM following conventional commit messages, which I would recommend. SFDX Git Delta follows this as well.

@scolladon - I think it's safe to close this issue here since I concur this task is better fit for @renatoliveira 's apex-test-list plugin. Think the only thing you could do is maybe link his plugin in your's README if you want to suggest people using your plugin to check his out.

**Comment by scolladon** [comment]
I really like your idea @mcarvin8 to reference @renatoliveira plugin in sgd readme.
I think you should do that as well.

Maybe you could create a PR to reference your plugins inside a "Complementary plugin" section in SGD README ?
(Closing this issue, but we can still discuss on it)
