### ISSUE TITLE
ADD SearchCustomization metadata in your list of mdapi components

### ISSUE THREAD

**Issue by pjha06** [scolladon/sfdx-git-delta#920]
Hello There,
i see SGD is not creating a package.xml for SearchCustomization metadata api and i tried even with your latest version and its metadata api support started from 61.0 apiversion ,maybe this is not tracked yet by this plugin.

Please add this support in your good plugin.

Regards,
Prabhat Jha

**Comment by scolladon** [comment]
Hi @pjha06 !

Thanks for raising this issue and thanks for contributing in making this project better!

I'll ship a new version soon to
