### ISSUE TITLE
BriefcaseDefinitions metadata not handled by plugin

### ISSUE THREAD

**Issue by camillerev** [scolladon/sfdx-git-delta#925]
Issue verification check:

- [ ] is the current repository fully deployable at the commit SHA provided with the 'from' parameter of the command?

## What is the problem?

The metadata briefcaseDefinitions doesn't seem to be handled. After we run the sgd command with new briefcaseDefinition, we don't find it in the package.xml:

<img width="399" alt="image" src="https://github.com/user-attachments/assets/e3d7fc9b-84f0-41ef-bfea-ebb7ea84c49b">
<img width="390" alt="image" src="https://github.com/user-attachments/assets/d7452db3-9694-4b09-a655-716c684f1a93">

### What is the parameter and the value you used with it?

Here is the command ran:
sf sgd:source:delta --to HEAD --from origin/main --repo . --output . --api-version 61.0

### What is the expected result?

The briefcaseDefinitions should be in the package.xml
<img width="384" alt="image" src="https://github.com/user-attachments/assets/7e5dc8c2-31fa-42d2-a7f3-6f2e6d14f5b9">

### What is the actual result?

The briefcaseDefinitions is not in the package.xml

## Steps to reproduce

---

Use the repo : https://github.com/camillerev/sfdx-delta-error-reproduction
Run :
git checkout test/briefcaseInDelta 
sf plugins install sfdx-git-delta
sf sgd:source:delta --to HEAD --from origin/main --repo . --output . --api-version 61.0
Check the new file: package.xml
The briefcaseDefinitions should be in the package.xml

Result:
The package.xml contains:
<img width="381" alt="image" src="https://github.com/user-attachments/assets/9b84f4c2-2861-467d-941e-c015b5d44c06">

## Execution context

---

**Operating System:** 14.6.1

**yarn version:** …

**node version:** v21.6.1

**git version:** git version 2.30.2

**sfdx version:** @salesforce/cli/2.42.6 darwin-x64 node-v20.12.2

**sgd plugin version:** v5.45.0

**Comment by scolladon** [comment]
Hi @camillerev !

Thanks for raising this issue and thanks for contributing in making this project better!

I'll ship it soon, stay tune !
