### ISSUE TITLE
Unable to Generate the delta for all the folders/directories in the repo.

### ISSUE THREAD

**Issue by shivamgarg0641** [scolladon/sfdx-git-delta#928]
Issue verification check:

- [ ] is the current repository fully deployable at the commit SHA provided with the 'from' parameter of the command?

## What is the problem?

<img width="239" alt="image" src="https://github.com/user-attachments/assets/ccbb0c5b-89da-44ad-890b-c219112295c0">
We have the above directory structure and git delta can only generate the delta for the force-app folder and skip others somehow.
---

## Steps to reproduce

---

## Execution context

---

**Operating System:** …

**yarn version:** …

**node version:** …

**git version:** …

**sfdx version:** …

**sgd plugin version:** …

## More information (optional)

---

**Comment by shivamgarg0641** [comment]
Seems like some details are not saved. Please find more details below:

Command Used:
sfdx sgd:source:delta --from origin/develop --to origin/feature/testbuild --output .

Delta from Bitbucket:
![image](https://github.com/user-attachments/assets/f94bb65f-a8db-4364-af12-a035a7f3a0c7)

Expected Delta:
Same as bitbucket

Actual Delta:
Diff from force-app only.

**Comment by shivamgarg0641** [comment]
@scolladon Here is the PR details https://github.com/shivamgarg0641/sfdx-git-delta-reproduction-playground/pull/2 and below is the command:
sfdx sgd:source:delta --from origin/develop --to origin/feature/test1 --output .

**Comment by scolladon** [comment]
@shivamgarg0641 does the issue is encountered when having trailing whitespace ?
I'm not sure it is possible with Salesforce though... I think the API trim trailing and leading white space when deploying and retrieving

**Comment by scolladon** [comment]
Any update @shivamgarg0641 ?
Did you manage to reproduce the issue without whitespace ?
Could you upgrade the repro playground ?

**Comment by shivamgarg0641** [comment]
@scolladon - I verified it without white spaces and it worked. Thanks for your help :)
