### ISSUE TITLE
Missing genAI Metadata Types

### ISSUE THREAD

**Issue by gavignon** [scolladon/sfdx-git-delta#929]
## What is the problem?

---

GenAI Metadata types are missing, they were added by Salesforce since 60.0:

- genAiFunctions
- genAiPlanners
- genAiPlugins

### What is the expected result?

These metadata types should be in the delta package.

### What is the actual result?

They are not included in the delta package.

## Steps to reproduce

---

sf sgd source delta -f {FROM} -t HEAD -a 61.0

**Comment by scolladon** [comment]
Hi @gavignon!

Thanks for raising this issue and thanks for contributing in making this project better!

I'll make a new version including those soon !
