### ISSUE TITLE
delta process taking none force-app (or src) files into a package.xml

### ISSUE THREAD

**Issue by niv-goldenberg** [scolladon/sfdx-git-delta#94]
## What is the problem

Changing my .github actions folder yml files is been identified as changed by the sfdx-git-delta process, meaning I get a package.xml files with the yml files.

### What is parameter and their value you used

sgd -t HEAD -f HEAD^  -r . -o .

### What is the expected result

```
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <version>50.0</version>
</Package>
```

### What is the actual result

```
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>.eslintrc</members>
        <name>LightningComponentBundle</name>
    </types>
    <types>
        <members>main.yml</members>
        <members>release.yml</members>
        <name>Workflow</name>
    </types>
    <version>50.0</version>
</Package>
```

## OS and Versions

Linux x64 Ubuntu 20.04
node v14.15.4
sgd 4.2.0

**Note:** I assume this is because the name of the github actions folder is workflows which is the same as the force-app/workflows floder? In addition, I see I have changed the eslintrc file in the lwc folder and it got picked up as well...

**Comment by scolladon** [comment]
Hello @niv-goldenberg !

That is a nice one !
You are totally correct, the issue occurs because of the workflows folder.

Currently you could use the ignore capability of the plugin to deal with that.
It will make sure it is not treated. You can reuse the .forceignore file, just add the folder you want the plugin to ignore and pass it as a parameter in the cli execution : 
```
$ sfdx sgd:source:delta --to HEAD --from HEAD^ --output . -i .forceignore
```

Does that help ?

Seb

**Comment by niv-goldenberg** [comment]
I'll give it a try on the next deployment and let you know. Note that since the package xml with this 'fake' source can't be converted it's seems like this been just skipped by the cli.

**Comment by scolladon** [comment]
We close the issue, feel free to reopen it
