### ISSUE TITLE
Translations are not detected during sgd diff commit 1 commit2

### ISSUE THREAD

**Issue by pjha06** [scolladon/sfdx-git-delta#940]
| Changed en_US Translations force-app\main\default\translations\en_US.translation-meta.xml
| Changed es    Translations force-app\main\default\translations\es.translation-meta.xml
| Changed fr    Translations force-app\main\default\translations\fr.translation-meta.xml

i have retrieved above files from my org but in package creation step it does not detect this changes and creates below package.xml <?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <version>62.0</version>
</Package>

**Comment by scolladon** [comment]
Hi @pjha06 !

Thanks for raising this issue and thanks for contributing in making this project better!

Could you help me reproduce on my machine please ?
We have a [reproduction playground](https://github.com/scolladon/sfdx-git-delta-reproduction-playground), you could fork it, create a branch, put in it the minimal information to reproduce the issue and share that with me if the instructions to reproduce it please ?

**Comment by pjha06** [comment]
Hi Sebastien ,
I created a fork
https://github.com/pjha06/sfdx-git-delta-reproduction-playground
Clone URl:
https://github.com/pjha06/sfdx-git-delta-reproduction-playground.git
and added few commits ,Please run below command to generate deltas:
sf sgd:source:delta --from d20854011af913defd507982d3e833dd26e3317b  --to
"HEAD" --output deltas --generate-delta --source force-app
and see the package.xml under deltas folder.
Regards,
Prabhat Jha

**Comment by scolladon** [comment]
Hi @pjha06,

I have done a few test (add, modify existing, modify by adding, modify by removing, deleting) on the [playground](https://github.com/scolladon/sfdx-git-delta-reproduction-playground/tree/issue/940) and it seems to be working on my side.
Could you check out the branch and run between each commit `sf sgd source delta -f HEAD~1 -d` and tell me the result ?

_I'm using mac
with node v18.20.4
with npm 10.9.0
with git 2.47.0
with salesforce/cli 2.42.6
with sfdx-git-delta 5.49.0_

**Comment by scolladon** [comment]
> sf sgd:source:delta --from d20854011af913defd507982d3e833dd26e3317b --to "HEAD" --output deltas --generate-delta --source force-app

I think the issue is because the Translations are empty.
As there is nothing to deploy it is not listed nor copied.

The plugin is able to trim the Translations file to contains only what as changed between 2 revisions.
This way it allows for faster deployment of only what as really changed.
There are a [few metadata type](https://github.com/scolladon/sfdx-git-delta/pull/533) for which the metadata API behaves like this.

**Comment by pjha06** [comment]
Hi Sebastien,
I understand its the issue with the retrieval as i added a file used by
you,its detected under package.xml.
Apology for your wasted time.
Regards,
Prabhat Jha

**Comment by scolladon** [comment]
No problem @pjha06 !
Happy to help.

Enjoy incremental deployment 🚀
