### ISSUE TITLE
SGD Doesn't Detect Changes to Decomposed Workflow Children

### ISSUE THREAD

**Issue by mcarvin8** [scolladon/sfdx-git-delta#941]
Issue verification check:

- [Y ] is the current repository fully deployable at the commit SHA provided with the 'from' parameter of the command?

## What is the problem?

---

Salesforce recently has provided several Beta decomposition services for metadata types such as labels and workflows.

I am testing the latest Workflow decomposed beta via this key in my `sfdx-project.json` file:

```
"sourceBehaviorOptions": ["decomposeWorkflowBeta"],
```

After you immediately decompose all of your existing workflows and run the standard SGD command (`sf sgd source delta --to "HEAD" --from "HEAD~1" --output "."`), the delta package will contain the workflows since each decomposed workflow will still have a file with the same file-name as the original un-decomposed workflow (for example: `force-app\main\default\workflows\Account\Account.workflow-meta.xml` is the decomposed workflow meta file).

After the initial decompose workflows commit is pushed and you make another commit to just 1 child workflow file (`force-app\main\default\workflows\Account\workflowRules\Activate Partner First Deal.workflowRule-meta.xml` for example), the SGD package with the default command (`sf sgd source delta --to "HEAD" --from "HEAD~1" --output "."`) will be an empty package.

### What is the parameter and the value you used with it?

`sf sgd source delta --to "HEAD" --from "HEAD~1" --output "."`

### What is the expected result?

SGD package.xml to contain the workflow child that was updated in the most recent commit.

### What is the actual result?

SGD package.xml is empty.

## Steps to reproduce

1. Install the latest SGD and `sf` CLI
2. Update the `sfdx-project.json` to use the workflow decomposed beta from SF:
```
"sourceBehaviorOptions": ["decomposeWorkflowBeta"],
```
3. Delete all original workflows in your repo and re-retrieve all workflows in order to decompose them.
4. Stage all changes and commit that to git.
5. Run SGD: `sf sgd source delta --to "HEAD" --from "HEAD~1" --output "."`
6. Confirm `package\package.xml` has workflows in them
7. Make a minor change to 1 of the decomposed workflow children meta files
8. Stage and commit that change to git.
9. Run SGD: `sf sgd source delta --to "HEAD" --from "HEAD~1" --output "."`
10. Confirm `package\package.xml` has the change for the 1 workflow

Step 5's SGD package.xml will have Workflows in them.
Step 9's SGD package.xml will be empty, but I was expecting the workflow child I updated (or just the parent workflow in general) to be in the package.

There are 2 potential solutions for this thing I see:
1. If workflow child is modified, SGD package.xml should just contain the workflow child modified.
2. If workflow child is modified, SGD package.xml should contain the parent workflow

**I remember there was a Salesforce CLI bug where you could retrieve individual workflow children but you were unable to deploy individual workflow children. I don't know if they fixed that or not.**

https://github.com/forcedotcom/cli/discussions/2356

## Execution context

---

**Operating System:** … Windows 11

**yarn version:** … 1.22.4

**node version:** …  v20.18.0

**git version:** … git version 2.47.0.windows.2

**sfdx version:** … @salesforce/cli/2.64.8 win32-x64 node-v20.17.0

**sgd plugin version:** … sfdx-git-delta 5.49.0

## More information (optional)

---

**Comment by scolladon** [comment]
Hi @mcarvin8 !

Thanks for raising this issue and thanks for contributing in making this project better!

I'll have a look very soon and also check if other decomposed metadata types are impacted as well.
I worked on this feature when it was alpha and it may have slightly chances since now it is beta.
Thanks for this really described issue, it really helps

Stay tuned
