### ISSUE TITLE
Delta generation takes long time if delta consists meta.xml files

### ISSUE THREAD

**Issue by anandsecured** [scolladon/sfdx-git-delta#948]
Issue verification check:

- [ ] is the current repository fully deployable at the commit SHA provided with the 'from' parameter of the command?

Yes
## What is the problem?

Delta Generation takes long time if modified files are with extension meta.xml. 

I have noticed that if we have lot of profile/layout/recordtype files which has file extension of -meta.xml, takes long time to generate the delta. In some scenarios it takes more than an hour for generating delta.

### What is the parameter and the value you used with it?

sfdx sgd:source:delta --to origin/feature/test1/US388015_388017 --from origin/test1 --output changes/

### What is the expected result?
Delta Generation and package creation

### What is the actual result?
Delta Generation and package gets created but takes long time

## Steps to reproduce

Try to generate delta with lot of profile/recordtype files 

**Operating System:** …

**yarn version:** …

**node version:** …

**git version:** 2.39.2

**sfdx version:** … 2.58.7

**sgd plugin version:** …

**Comment by scolladon** [comment]
Hi @anandsecured!

Thanks for raising this issue and thanks for contributing in making this project better!

Could you help me reproduce the issue locally ?
You can either describe what commit content I should create inside a repository, or you could also fork the [reproduction playground](https://github.com/scolladon/sfdx-git-delta-reproduction-playground), create a branch, write the necessary commit to reproduce and share that branch here.
And give me the commands to run with sgd to reproduce the issue.

Also I need more information about the context of execution (OS, node version, plugin version). If you could fill the missing information inside the issue description it would be perfect. Could you add information about the machine as well please ? (processor and ram)

**Comment by scolladon** [comment]
Hi @anandsecured !

Do you have any news following my previous comments about this issue ?

**Comment by scolladon** [comment]
Hi @anandsecured 

One more attempt to gather information from my side.
Have you tried using the current latest version (v5.49.4) ? 
Could you share a repository where I could reproduce ?
Could you share more information about the context of execution ? (OS, node version, plugin version, processor, ram, etc)
