### ISSUE TITLE
Strange behaviour with profiles 

### ISSUE THREAD

**Issue by Joselulr90** [scolladon/sfdx-git-delta#953]
Issue verification check:

If profile is added in the delta. not only deploy the corresponding permission, but also the LayoutAssignments and LoginIpRanges.

**Comment by scolladon** [comment]
Hi @Joselulr90 !

Thanks for raising this issue and thanks for contributing in making this project better!

If you are asking if it is expected to always have all the `layoutAssignments` and `loginIpRanges` (even those not momdified) when modifying a profile and running sgd then yes.
The plugin currently works this way.

There is someone else who raised the matter as well in [another closed issue](https://github.com/scolladon/sfdx-git-delta/issues/198#issuecomment-2502202637) (fyi @gvivo).

I'm currently working on this to ensure the plugin build profile with only modified `layoutAssignments` and `loginIpRanges` and not all.
Stay tuned!
