### ISSUE TITLE
Support for External Client Application Metadata

### ISSUE THREAD

**Issue by dmitrii-dronov** [scolladon/sfdx-git-delta#955]
**As a Salesforce Tech Lead**, I want the SFDX Delta plugin to support generating packages with the following new Salesforce metadata types:
	•	`ExternalClientApplication`
	•	`ExtlClntAppGlobalOauthSettings`
	•	`ExtlClntAppOauthConfigurablePolicies`
	•	`ExtlClntAppOauthSettings`

This will ensure the plugin remains compatible with Salesforce’s next-generation integration features.

**TODO**:
	1.	Investigate the metadata structure and retrieval methods for the new types.
	2.	Update the metadata type configuration in the plugin to include support for the new types.
	3.	Test package generation for projects containing these metadata types to ensure compatibility.

**Solution Hints**:
	•	Refer to the official documentation for External Client Applications: [Salesforce Help](https://help.salesforce.com/s/articleView?id=sf.retrieve_data_from_the_source_org.htm&type=5).
	•	For an overview and comparison with Connected Applications, review this article: [Salesforce Ben](https://www.salesforceben.com/external-client-vs-connected-apps-comparing-salesforces-next-gen-integration/).

**Comment by scolladon** [comment]
Hi @dmitrii-dronov!

Thanks for raising this issue and thanks for contributing in making this project better!

I'll ship it soon, stay tuned !

**Comment by tggagne** [comment]
New version works great.  Thanks!
