### ISSUE TITLE
Expression Set Version and Context Definitions metadata support

### ISSUE THREAD

**Issue by scolladon** [scolladon/sfdx-git-delta#959]
### Discussed in https://github.com/scolladon/sfdx-git-delta/discussions/958

<div type='discussions-op-text'>

<sup>Originally posted by **PythSomeone** December  9, 2024</sup>
Hi,

When a delta is generated, changes or creations of the Expression Set Version and Context Definition are not shown in the resulting delta.

Could you please add support for both types of metadata?</div>

**Comment by scolladon** [comment]
Support for : 

- [ExpressionSetDefinitionVersion](https://developer.salesforce.com/docs/atlas.en-us.industries_reference.meta/industries_reference/tooling_api_objects_expressionsetdefinitionversion.htm)
- [ContextDefinition](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_contextdefinition.htm?q=Context%20Definitions)

**Comment by scolladon** [comment]
Also add support for : 
- [ProductSpecificationType](https://developer.salesforce.com/docs/atlas.en-us.revenue_lifecycle_management_dev_guide.meta/revenue_lifecycle_management_dev_guide/sforce_api_objects_productspecificationtype.htm)
- [ProductSpecificationRecType](https://developer.salesforce.com/docs/atlas.en-us.revenue_lifecycle_management_dev_guide.meta/revenue_lifecycle_management_dev_guide/sforce_api_objects_productspecificationrectype.htm)

**Comment by eqtkram** [comment]
Hi!
We're also missing the [UiFormatSpecificationSet](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_uiformatspecificationset.htm) metadata type.

**Comment by PythSomeone** [comment]
I checked the ExpressionSetDefinitionVersion against the generated delta, but it looks like it produce errors once the actual validation launched the following error appeared : 
![image](https://github.com/user-attachments/assets/930c1cc5-44f4-43c6-87da-d538f6ac8285)

**Comment by PythSomeone** [comment]
Hi @scolladon 

I probably found the issue,.

Here is what delta has generated:
![image](https://github.com/user-attachments/assets/18b0d366-29e8-4309-bccb-fbdebb49f25f)
and here is what I included in the package in repo:
![image](https://github.com/user-attachments/assets/b64a5e96-1447-477e-a8bb-21824e2e8cab)
Could you please create a testing version of Delta, so it would generate `ExpressionSetDefinitionVersion` instead of `ExpressionSetVersion` so I can checkout it that would solve the error?

**Comment by scolladon** [comment]
Sure @PythSomeone !

That's a very good idea, I create this beta version and mention you on the related PR
