### ISSUE TITLE
No object FinclAcctPtyFinclAsset in plugin

### ISSUE THREAD

**Issue by KacperZawalskiCF** [scolladon/sfdx-git-delta#964]
I am using delta deployment on validation to XYZ org. I used the following step to install plugin:
```
     - name: Install SFDX Git Delta Plugin
        run: |
          printf y\\n | sf plugins install sfdx-git-delta 2> /dev/null
```
The following code inside validation github bash step: 
```
sf sgd source delta \
            --ignore .forceignore \
            --ignore .sandboxignore \
            --ignore-destructive .forceignoredestructive \
            --output . \
            --from "$(git merge-base "$BASE_SHA" "$HEAD_SHA")" \
            --to "$HEAD_SHA"
```
There no reference to this object inside --ignore files

Expected output of the command: create a `package/package.xml` with custom fields for automotive standard object 

Actual output of the command:
I get an `undefined` custom object name inside `package/package.xml` when I refer to custom field for [FinclAcctPtyFinclAsset](https://developer.salesforce.com/docs/atlas.en-us.automotive_cloud.meta/automotive_cloud/sforce_api_objects_finclacctptyfinclasset.htm) standard object from Automotive cloud, example for custom field developer wanted to add with PR:
      
      <types>
          <members>undefined.customFieldName__c</members>
          <name>CustomField</name>
      </types>

**Comment by scolladon** [comment]
Hi @KacperZawalskiCF !

Thanks for raising this issue and thanks for contributing in making this project better!

Could you help me reproduce the issue locally ?
You can either describe what commit content I should create inside a repository, or you could also fork the [reproduction playground](https://github.com/scolladon/sfdx-git-delta-reproduction-playground), create a branch, write the necessary commit to reproduce and share that branch here.
And give me the commands to run with sgd to reproduce the issue.

Could you also give he output of those command : 
```
uname -v; npm -v ; node -v ; git --version ; sf --version ; sf plugins
git diff --name-status --no-renames <from> <to>
```

**Comment by KacperZawalskiCF** [comment]
Hello @scolladon!

This was developer error, she put fields outside of `../objects/FinclAcctPtyFinclAsset/fields` folder - inside `../objects/FinclAcctPtyFinclAsset`. The problem was on our side, Thank you for your time!

**Comment by scolladon** [comment]
No problem, do not hesitate if I can help

Happy incremental deployment 🚀
